In [11]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder,OneHotEncoder, StandardScaler, MinMaxScaler
from sklearn.naive_bayes import GaussianNB, BernoulliNB
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer, make_column_selector
from sklearn.metrics import log_loss, accuracy_score, f1_score, confusion_matrix, precision_score, recall_score, classification_report,roc_auc_score,roc_curve,RocCurveDisplay
import os
from sklearn.impute import SimpleImputer
import matplotlib.pyplot as plt

In [3]:
irrigation = pd.read_csv("train.csv", index_col = 0)
irrigation

,Soil_Type,Soil_pH,Soil_Moisture,Organic_Carbon,Electrical_Conductivity,Temperature_C,Humidity,Rainfall_mm,Sunlight_Hours,Wind_Speed_kmh,Crop_Type,Crop_Growth_Stage,Season,Irrigation_Type,Water_Source,Field_Area_hectare,Mulching_Used,Previous_Irrigation_mm,Region,Irrigation_Need
id,,,,,,,,,,,,,,,,,,,,
0,Loamy,4.92,32.58,1.01,3.05,15.01,50.61,725.99,5.90,16.79,Sugarcane,Sowing,Zaid,Drip,Rainwater,0.82,No,112.16,East,Low
1,Clay,7.08,56.61,0.44,2.00,22.92,67.86,985.66,6.98,3.39,Wheat,Vegetative,Kharif,Rainfed,River,5.27,Yes,47.16,South,Low
2,Clay,5.69,27.71,0.81,2.83,26.97,92.22,2201.70,6.05,3.85,Rice,Vegetative,Kharif,Sprinkler,Reservoir,8.24,Yes,110.38,North,Low
3,Sandy,5.65,13.32,1.33,0.87,13.32,61.57,1357.33,9.12,2.31,Wheat,Flowering,Kharif,Canal,River,8.32,Yes,53.85,South,Medium
4,Clay,7.96,59.14,0.38,0.96,20.22,91.11,1538.20,6.95,13.94,Wheat,Sowing,Rabi,Canal,River,7.37,No,93.19,South,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
629995,Clay,6.54,13.45,1.15,1.86,26.65,26.86,1041.33,10.62,18.85,Rice,Sowing,Kharif,Sprinkler,River,4.35,No,118.36,South,Medium
629996,Clay,7.03,54.49,0.96,2.35,36.99,88.00,1419.57,9.93,17.99,Sugarcane,Vegetative,Kharif,Drip,Groundwater,12.97,Yes,40.75,Central,Medium
629997,Clay,6.52,11.98,0.93,0.38,37.82,70.98,88.45,8.19,17.25,Potato,Vegetative,Zaid,Canal,Reservoir,13.58,Yes,2.62,South,High
629998,Clay,5.93,42.86,0.33,3.39,34.99,94.58,2433.92,9.88,5.00,Sugarcane,Vegetative,Zaid,Sprinkler,Groundwater,0.79,Yes,90.00,East,Low
629999,Loamy,7.02,35.36,1.19,0.46,26.92,64.33,1269.55,7.91,2.72,Maize,Harvest,Kharif,Drip,Reservoir,3.80,No,112.93,West,Low

In [4]:
irrigation.info()

<class 'pandas.core.frame.DataFrame'>
Index: 630000 entries, 0 to 629999
Data columns (total 20 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   Soil_Type                630000 non-null  object
 1   Soil_pH                  630000 non-null  float64
 2   Soil_Moisture            630000 non-null  float64
 3   Organic_Carbon           630000 non-null  float64
 4   Electrical_Conductivity  630000 non-null  float64
 5   Temperature_C            630000 non-null  float64
 6   Humidity                 630000 non-null  float64
 7   Rainfall_mm              630000 non-null  float64
 8   Sunlight_Hours           630000 non-null  float64
 9   Wind_Speed_kmh           630000 non-null  float64
 10  Crop_Type                630000 non-null  object
 11  Crop_Growth_Stage        630000 non-null  object
 12  Season                   630000 non-null  object
 13  Irrigation_Type          630000 non-null  object
 14  Water_Source             630000 non-null  object
 15  Field_Area_hectare       630000 non-null  float64
 16  Mulching_Used            630000 non-null  object
 17  Previous_Irrigation_mm   630000 non-null  float64
 18  Region                   630000 non-null  object
 19  Irrigation_Need          630000 non-null  object
dtypes: float64(11), object(9)
memory usage: 100.9+ MB

In [6]:
irrigation.isna().sum().sum()

np.int64(0)

In [7]:
le = LabelEncoder()
irrigation["Irrigation_Need"] = le.fit_transform(irrigation["Irrigation_Need"])
irrigation

,Soil_Type,Soil_pH,Soil_Moisture,Organic_Carbon,Electrical_Conductivity,Temperature_C,Humidity,Rainfall_mm,Sunlight_Hours,Wind_Speed_kmh,Crop_Type,Crop_Growth_Stage,Season,Irrigation_Type,Water_Source,Field_Area_hectare,Mulching_Used,Previous_Irrigation_mm,Region,Irrigation_Need
id,,,,,,,,,,,,,,,,,,,,
0,Loamy,4.92,32.58,1.01,3.05,15.01,50.61,725.99,5.90,16.79,Sugarcane,Sowing,Zaid,Drip,Rainwater,0.82,No,112.16,East,1
1,Clay,7.08,56.61,0.44,2.00,22.92,67.86,985.66,6.98,3.39,Wheat,Vegetative,Kharif,Rainfed,River,5.27,Yes,47.16,South,1
2,Clay,5.69,27.71,0.81,2.83,26.97,92.22,2201.70,6.05,3.85,Rice,Vegetative,Kharif,Sprinkler,Reservoir,8.24,Yes,110.38,North,1
3,Sandy,5.65,13.32,1.33,0.87,13.32,61.57,1357.33,9.12,2.31,Wheat,Flowering,Kharif,Canal,River,8.32,Yes,53.85,South,2
4,Clay,7.96,59.14,0.38,0.96,20.22,91.11,1538.20,6.95,13.94,Wheat,Sowing,Rabi,Canal,River,7.37,No,93.19,South,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
629995,Clay,6.54,13.45,1.15,1.86,26.65,26.86,1041.33,10.62,18.85,Rice,Sowing,Kharif,Sprinkler,River,4.35,No,118.36,South,2
629996,Clay,7.03,54.49,0.96,2.35,36.99,88.00,1419.57,9.93,17.99,Sugarcane,Vegetative,Kharif,Drip,Groundwater,12.97,Yes,40.75,Central,2
629997,Clay,6.52,11.98,0.93,0.38,37.82,70.98,88.45,8.19,17.25,Potato,Vegetative,Zaid,Canal,Reservoir,13.58,Yes,2.62,South,0
629998,Clay,5.93,42.86,0.33,3.39,34.99,94.58,2433.92,9.88,5.00,Sugarcane,Vegetative,Zaid,Sprinkler,Groundwater,0.79,Yes,90.00,East,1
629999,Loamy,7.02,35.36,1.19,0.46,26.92,64.33,1269.55,7.91,2.72,Maize,Harvest,Kharif,Drip,Reservoir,3.80,No,112.93,West,1

In [8]:
X, y = irrigation.drop("Irrigation_Need", axis = 1), irrigation["Irrigation_Need"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 26,stratify=irrigation['Irrigation_Need'])

In [12]:
ohe = OneHotEncoder(sparse_output = False, drop = 'first').set_output(transform = 'pandas')
transformer = ColumnTransformer(transformers=[('OHE',ohe,make_column_selector(dtype_include=object)),
                                            ]
                               ,remainder='passthrough',
                               verbose_feature_names_out=False
                               ).set_output(transform='pandas')

In [13]:
X_train_ohe = transformer.fit_transform(X_train)
X_test_ohe = transformer.transform(X_test)

In [14]:
ss = StandardScaler()
X_train_scaled = ss.fit_transform(X_train_ohe)
X_test_scaled = ss.transform(X_test_ohe)

In [15]:
bm = GaussianNB()
bm.fit(X_train_scaled, y_train)
y_pred = bm.predict(X_test_scaled)
y_pred_proba = bm.predict_proba(X_test_scaled)

y_pred_labels = le.inverse_transform(y_pred)
y_pred_labels

array(['Medium', 'Low', 'Low', ..., 'Medium', 'Low', 'Medium'],
      dtype=object)

In [16]:
print(log_loss(y_test, y_pred_proba))

0.48752389106082267

In [17]:
print(accuracy_score(y_test, y_pred))

0.796037037037037

In [18]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.63      0.78      0.70      6303
           1       0.85      0.84      0.84    110975
           2       0.74      0.73      0.73     71722

    accuracy                           0.80    189000
   macro avg       0.74      0.78      0.76    189000
weighted avg       0.80      0.80      0.80    189000

In [19]:
tst = pd.read_csv("test.csv", index_col = 0)
tst_ohe = transformer.transform(tst)
tst_scaled = ss.transform(tst_ohe)
tst_pred = bm.predict(tst_scaled)
tst_pred

array([1, 1, 1, ..., 2, 1, 1])

In [20]:
submission = pd.read_csv("sample_submission.csv")
submission

            id Irrigation_Need
0       630000             Low
1       630001             Low
2       630002             Low
3       630003             Low
4       630004             Low
...        ...             ...
269995  899995             Low
269996  899996             Low
269997  899997             Low
269998  899998             Low
269999  899999             Low

[270000 rows x 2 columns]

In [21]:
submission["Irrigation_Need"] = le.inverse_transform(tst_pred)
submission

            id Irrigation_Need
0       630000             Low
1       630001             Low
2       630002             Low
3       630003             Low
4       630004             Low
...        ...             ...
269995  899995          Medium
269996  899996          Medium
269997  899997          Medium
269998  899998             Low
269999  899999             Low

[270000 rows x 2 columns]

In [22]:
submission.to_csv("KaggleSubmissionGaussianNB.csv", index = False)