In [12]:
import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import r2_score,mean_squared_error
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, StandardScaler, MinMaxScaler
from sklearn.compose import ColumnTransformer, make_column_selector
import os
os.chdir('/home/pgcp-ai/MachineLearning/Cases/Concrete_Strength/')

In [13]:
conc = pd.read_csv("Concrete_Data.csv")

In [14]:
conc.dtypes

Cement              float64
Blast               float64
Fly                 float64
Water               float64
Superplasticizer    float64
Coarse              float64
Fine                float64
Age                   int64
Strength            float64
dtype: object

In [4]:
X, y = conc.drop('Strength', axis = 1), conc['Strength']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 26)

In [5]:
scores=[]
k=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
for i in k:
    knn = KNeighborsRegressor(n_neighbors=i)
    knn.fit(X_train,y_train)
    y_pred = knn.predict(X_test)
    score = r2_score(y_test,y_pred)
    scores.append([i,score])
df_scores = pd.DataFrame(scores,columns=['k','scores'])
df_scores.sort_values('scores',ascending=False)

     k    scores
3    4  0.686300
4    5  0.677831
2    3  0.670531
5    6  0.665381
6    7  0.655423
7    8  0.654509
8    9  0.653360
9   10  0.650692
10  11  0.644692
11  12  0.638007
12  13  0.630372
13  14  0.617334
0    1  0.600732
14  15  0.597249
1    2  0.585802

In [6]:
ss = StandardScaler()

In [7]:
X_train_stand_scaled = ss.fit_transform(X_train)
X_test_stand_scaled = ss.transform(X_test)

In [8]:
scores=[]
k=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
for i in k:
    knn = KNeighborsRegressor(n_neighbors=i)
    knn.fit(X_train_stand_scaled,y_train)
    y_pred = knn.predict(X_test_stand_scaled)
    score = r2_score(y_test,y_pred)
    scores.append([i,score])
df_scores = pd.DataFrame(scores,columns=['k','scores'])
df_scores.sort_values('scores',ascending=False)

     k    scores
4    5  0.709654
7    8  0.698692
5    6  0.695497
6    7  0.692776
2    3  0.692324
8    9  0.691358
3    4  0.687532
9   10  0.684627
10  11  0.679389
11  12  0.669188
13  14  0.653004
12  13  0.652451
1    2  0.649537
14  15  0.641319
0    1  0.618293

In [9]:
minmax = MinMaxScaler()

In [10]:
X_train_mm_scaled = minmax.fit_transform(X_train)
X_test_mm_scaled = minmax.transform(X_test)

In [11]:
scores=[]
k=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
for i in k:
    knn = KNeighborsRegressor(n_neighbors=i)
    knn.fit(X_train_mm_scaled,y_train)
    y_pred = knn.predict(X_test_mm_scaled)
    score = r2_score(y_test,y_pred)
    scores.append([i,score])
df_scores = pd.DataFrame(scores,columns=['k','scores'])
df_scores.sort_values('scores',ascending=False)

     k    scores
5    6  0.686359
6    7  0.681397
4    5  0.678060
7    8  0.677690
8    9  0.674605
9   10  0.671331
2    3  0.661179
10  11  0.658750
3    4  0.654668
11  12  0.652859
12  13  0.636865
13  14  0.625703
14  15  0.611317
1    2  0.595086
0    1  0.562804