In [1]:
import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import r2_score,mean_squared_error
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, StandardScaler, MinMaxScaler
from sklearn.compose import ColumnTransformer, make_column_selector
import os
os.chdir('/home/pgcp-ai/MachineLearning/Datasets/')

In [2]:
housing = pd.read_csv("Housing.csv")

In [3]:
housing.dtypes

price       float64
lotsize       int64
bedrooms      int64
bathrms       int64
stories       int64
driveway     object
recroom      object
fullbase     object
gashw        object
airco        object
garagepl      int64
prefarea     object
dtype: object

In [4]:
X, y = housing.drop('price', axis = 1), housing['price']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 26)

ohe = OneHotEncoder(sparse_output = False, drop = 'first').set_output(transform = 'pandas')
transformer = ColumnTransformer(transformers=[('OHE',ohe,make_column_selector(dtype_include=object)),
                                            ]
                               ,remainder='passthrough',
                               verbose_feature_names_out=False
                               ).set_output(transform='pandas')

X_train_trans = transformer.fit_transform(X_train)
X_test_trans = transformer.transform(X_test)

In [5]:
knn = KNeighborsRegressor(n_neighbors=3)
knn.fit(X_train_trans,y_train)
y_pred = knn.predict(X_test_trans)
score = r2_score(y_test,y_pred)
score

0.2107443983070001

In [6]:
scores=[]
k=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
for i in k:
    knn = KNeighborsRegressor(n_neighbors=i)
    knn.fit(X_train_trans,y_train)
    y_pred = knn.predict(X_test_trans)
    score = r2_score(y_test,y_pred)
    scores.append([i,score])
df_scores = pd.DataFrame(scores,columns=['k','scores'])
df_scores.sort_values('scores',ascending=False)

     k    scores
10  11  0.398495
11  12  0.386896
12  13  0.382631
13  14  0.381488
9   10  0.379393
7    8  0.376241
8    9  0.376235
14  15  0.372916
5    6  0.370866
6    7  0.351990
4    5  0.326251
3    4  0.274102
2    3  0.210744
1    2  0.042913
0    1 -0.031039

In [7]:
housing = pd.read_csv("Housing.csv")

In [8]:
ss = StandardScaler()

In [9]:
X, y = housing.drop('price', axis = 1), housing['price']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 26)

ohe = OneHotEncoder(sparse_output = False, drop = 'first').set_output(transform = 'pandas')
transformer = ColumnTransformer(transformers=[('OHE',ohe,make_column_selector(dtype_include=object)),
                                              ('SS',ss,make_column_selector(dtype_include=[float,int]))
                                            ]
                               ,remainder='passthrough',
                               verbose_feature_names_out=False
                               ).set_output(transform='pandas')

X_train_trans = transformer.fit_transform(X_train)
X_test_trans = transformer.transform(X_test)

In [10]:
scores=[]
k=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
for i in k:
    knn = KNeighborsRegressor(n_neighbors=i)
    knn.fit(X_train_trans,y_train)
    y_pred = knn.predict(X_test_trans)
    score = r2_score(y_test,y_pred)
    scores.append([i,score])
df_scores = pd.DataFrame(scores,columns=['k','scores'])
df_scores.sort_values('scores',ascending=False)

     k    scores
13  14  0.635987
12  13  0.631634
14  15  0.630365
11  12  0.629461
10  11  0.626731
8    9  0.622583
9   10  0.622155
7    8  0.609923
5    6  0.589854
6    7  0.587524
4    5  0.584683
3    4  0.572149
2    3  0.545986
1    2  0.469649
0    1  0.442144

In [11]:
minmax = MinMaxScaler()

In [17]:
X, y = housing.drop('price', axis = 1), housing['price']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 26)

ohe = OneHotEncoder(sparse_output = False, drop = 'first').set_output(transform = 'pandas')
transformer = ColumnTransformer(transformers=[('OHE',ohe,make_column_selector(dtype_include=object)),
                                              ('MM',minmax,make_column_selector(dtype_include=[float,int]))
                                            ]
                               ,remainder='passthrough',
                               verbose_feature_names_out=False
                               ).set_output(transform='pandas')

X_train_trans = transformer.fit_transform(X_train)
X_test_trans = transformer.transform(X_test)

In [18]:
scores=[]
k=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
for i in k:
    knn = KNeighborsRegressor(n_neighbors=i)
    knn.fit(X_train_trans,y_train)
    y_pred = knn.predict(X_test_trans)
    score = r2_score(y_test,y_pred)
    scores.append([i,score])
df_scores = pd.DataFrame(scores,columns=['k','scores'])
df_scores.sort_values('scores',ascending=False)

     k    scores
3    4  0.648484
5    6  0.634816
4    5  0.628915
2    3  0.618242
6    7  0.615586
8    9  0.611275
9   10  0.609886
7    8  0.609309
10  11  0.600014
14  15  0.587456
11  12  0.585337
13  14  0.581295
12  13  0.577580
1    2  0.525986
0    1  0.333553

In [19]:
tst = pd.read_csv("tst_Housing.csv")
X_trans = transformer.fit_transform(X)
tst_trans = transformer.transform(tst)
bm = KNeighborsRegressor(n_neighbors=4)
bm.fit(X_trans,y)
y_pred_new = bm.predict(tst_trans)
tst['Predicted Price'] = y_pred_new
tst

,lotsize,bedrooms,bathrms,stories,driveway,recroom,fullbase,gashw,airco,garagepl,prefarea,Predicted Price
0,5600,3,1,2,yes,no,yes,no,no,1,no,51500.0
1,4355,2,1,1,yes,no,no,no,no,0,no,46625.0
2,3412,3,1,1,yes,no,no,no,no,0,no,46625.0
3,6666,2,2,2,yes,yes,no,no,no,0,no,68125.0