In [25]:
import os
import pandas as pd
import numpy as np
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

from sklearn.ensemble import VotingRegressor,RandomForestRegressor, BaggingRegressor,StackingRegressor
from sklearn.linear_model import LinearRegression
from xgboost import XGBRegressor
from catboost import CatBoostRegressor
from lightgbm import LGBMRegressor
from sklearn.model_selection import KFold, GridSearchCV, RandomizedSearchCV
from sklearn.pipeline import Pipeline
from sklearn.compose import make_column_transformer,make_column_selector
from sklearn.impute import SimpleImputer
os.chdir('/home/pgcp-ai/MachineLearning/Datasets/BigMarketSale/')

In [26]:
train = pd.read_csv("train_v9rqX0R.csv")
test = pd.read_csv("test_AbJTz2l.csv")

In [27]:
train

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.300,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.920,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.500,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,FDX07,19.200,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800
4,NCD19,8.930,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052
...,...,...,...,...,...,...,...,...,...,...,...,...
8518,FDF22,6.865,Low Fat,0.056783,Snack Foods,214.5218,OUT013,1987,High,Tier 3,Supermarket Type1,2778.3834
8519,FDS36,8.380,Regular,0.046982,Baking Goods,108.1570,OUT045,2002,NaN,Tier 2,Supermarket Type1,549.2850
8520,NCJ29,10.600,Low Fat,0.035186,Health and Hygiene,85.1224,OUT035,2004,Small,Tier 2,Supermarket Type1,1193.1136
8521,FDN46,7.210,Regular,0.145221,Snack Foods,103.1332,OUT018,2009,Medium,Tier 3,Supermarket Type2,1845.5976
8522,DRG01,14.800,Low Fat,0.044878,Soft Drinks,75.4670,OUT046,1997,Small,Tier 1,Supermarket Type1,765.6700

In [ ]:
train.groupby['Item_Identifier']['Item_Weight'] = train.groupby['Item_Identifier']['Item_Weight'].mode()

In [28]:
train.isnull().sum()

Item_Identifier                 0
Item_Weight                  1463
Item_Fat_Content                0
Item_Visibility                 0
Item_Type                       0
Item_MRP                        0
Outlet_Identifier               0
Outlet_Establishment_Year       0
Outlet_Size                  2410
Outlet_Location_Type            0
Outlet_Type                     0
Item_Outlet_Sales               0
dtype: int64

In [29]:
ohe = OneHotEncoder(sparse_output=False,drop='first',handle_unknown='ignore').set_output(transform='pandas')
SI = SimpleImputer(strategy='mean').set_output(transform='pandas')
SI_F = SimpleImputer(strategy='most_frequent').set_output(transform='pandas')
data_pipe = Pipeline([('SI_F',SI_F),('OHE',ohe)])

In [30]:
transformer = ColumnTransformer([('SI',SI,['Item_Weight']),
                                ('PIPE',data_pipe,make_column_selector(dtype_include=object))
                                 ],
                               verbose_feature_names_out=False,remainder='passthrough')

In [31]:
X, y = train.drop('Item_Outlet_Sales', axis = 1), train['Item_Outlet_Sales']

In [37]:
xgbm = XGBRegressor(random_state = 26)
lgbm = LGBMRegressor(random_state = 26)
cat = CatBoostRegressor(random_state = 26)
rf = RandomForestRegressor(random_state=26)
stack = StackingRegressor([('XGB',xgbm),('LGBM',lgbm),('CAT',cat)],final_estimator=rf)

In [39]:
kfolds = KFold(n_splits = 5, shuffle = True, random_state = 26)
pipe_stack = Pipeline([('OHE', transformer), ('stack',stack)])

params = {'stack__XGB__max_depth': [4, 6,10],
          'stack__XGB__learning_rate': [0.05, 0.2,0.3],
          'stack__XGB__n_estimators': [100, 150,200],
         
          'stack__LGBM__max_depth': [4,6,10],
          'stack__LGBM__learning_rate': [0.05, 0.1,0.3],
          'stack__LGBM__n_estimators': [75, 150,200],
          
          'stack__CAT__max_depth': [6,8,10],
          'stack__CAT__learning_rate': [0.05, 0.1, 0.2],
          'stack__CAT__n_estimators': [75,100,200],
          
          'stack__final_estimator__max_depth' : [4,6],
          'stack__final_estimator__n_estimators' : [75,100,150]
         }

gcv = RandomizedSearchCV(estimator= pipe_stack, cv = kfolds, n_jobs = -1, param_distributions=params, verbose = 2,scoring='neg_root_mean_squared_error')
gcv.fit(X, y)

Fitting 5 folds for each of 10 candidates, totalling 50 fits
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.099025 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 815
[LightGBM] [Info] Number of data points in the train set: 6818, number of used features: 39
[LightGBM] [Info] Start training from score 2183.057911
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
0:	learn: 1648.7702054	total: 127ms	remaining: 9.38s
1:	learn: 1606.7091601	total: 237ms	remaining: 8.65s
2:	learn: 1564.8105123	total: 400ms	remaining: 9.61s
3:	learn: 1528.1116075	total: 485ms	remaining: 8.6s
4:	learn: 1493.7558434	total: 560ms	remaining: 7.83s
5:	learn: 1459.9544326	total: 668ms	remaining: 7.68s
6:	learn: 1433.5455273	total: 756ms	remaining: 7.34s
7:	learn: 1405.1725444	total: 834ms	remaining: 6.99s
8:	learn: 1381.8854620	total: 841ms	remaining: 6.17s
9:	learn: 1359.0611775	total: 852ms	remaining: 5.54s
10:	learn: 1336.0269234	total: 859ms	remaining: 5s
11:	learn: 1315.9754354	total: 869ms	remaining: 4.56s
12:	learn: 1299.0141138	total: 907ms	remaining: 4.32s
13:	learn: 1280.6818272	total: 928ms	remaining: 4.04s
14:	learn: 1264.1214070	total: 999ms	remaining: 4s
15:	learn: 1248.9573637	total: 1.01s	remaining: 3.72s
16:	learn: 1233.7733784	total: 1.12s	remaining: 3.82s
17:	learn: 1220.6589001	total: 1.14s	remaining: 3.61s
18:	learn: 1208.4817071	total: 1.16s	remaining: 3.41s
19:	learn: 1196.8979046	total: 1.18s	remaining: 3.25s
20:	learn: 1186.3680710	total: 1.19s	remaining: 3.06s
21:	learn: 1176.3159246	total: 1.22s	remaining: 2.95s
22:	learn: 1166.9051270	total: 1.23s	remaining: 2.79s
23:	learn: 1159.1507801	total: 1.24s	remaining: 2.64s
24:	learn: 1151.9823993	total: 1.25s	remaining: 2.5s
25:	learn: 1145.6352721	total: 1.26s	remaining: 2.37s
26:	learn: 1139.3786644	total: 1.28s	remaining: 2.27s
27:	learn: 1134.2396943	total: 1.34s	remaining: 2.26s
28:	learn: 1128.7643814	total: 1.46s	remaining: 2.32s
29:	learn: 1123.7157548	total: 1.48s	remaining: 2.22s
30:	learn: 1119.0055605	total: 1.65s	remaining: 2.34s
31:	learn: 1115.3827771	total: 1.66s	remaining: 2.23s
32:	learn: 1111.4308002	total: 1.75s	remaining: 2.23s
33:	learn: 1107.2774218	total: 1.82s	remaining: 2.19s
34:	learn: 1104.2657055	total: 1.92s	remaining: 2.19s
35:	learn: 1101.6148302	total: 1.98s	remaining: 2.15s
36:	learn: 1098.6524987	total: 2.03s	remaining: 2.08s
37:	learn: 1096.2755801	total: 2.12s	remaining: 2.06s
38:	learn: 1094.6071223	total: 2.13s	remaining: 1.97s
39:	learn: 1093.2129545	total: 2.14s	remaining: 1.87s
40:	learn: 1091.1344910	total: 2.22s	remaining: 1.84s

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.272432 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 820
[LightGBM] [Info] Number of data points in the train set: 6819, number of used features: 39
[LightGBM] [Info] Start training from score 2189.804680
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.288301 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 816
[LightGBM] [Info] Number of data points in the train set: 6818, number of used features: 39
[LightGBM] [Info] Start training from score 2159.816823
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.247659 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 819
[LightGBM] [Info] Number of data points in the train set: 6818, number of used features: 39
[LightGBM] [Info] Start training from score 2180.679468
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.287646 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 817
[LightGBM] [Info] Number of data points in the train set: 6819, number of used features: 39
[LightGBM] [Info] Start training from score 2193.082712
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.239904 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 815
[LightGBM] [Info] Number of data points in the train set: 6818, number of used features: 39
[LightGBM] [Info] Start training from score 2183.057911
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
0:	learn: 1537.1871568	total: 121ms	remaining: 8.94s
1:	learn: 1397.6086431	total: 216ms	remaining: 7.88s
2:	learn: 1299.7101166	total: 391ms	remaining: 9.38s
3:	learn: 1238.5813988	total: 525ms	remaining: 9.32s
4:	learn: 1186.2326325	total: 727ms	remaining: 10.2s
5:	learn: 1155.4610966	total: 1.01s	remaining: 11.6s
6:	learn: 1127.6112328	total: 1.12s	remaining: 10.9s
7:	learn: 1108.5776751	total: 1.39s	remaining: 11.7s
8:	learn: 1100.8459820	total: 1.4s	remaining: 10.3s
9:	learn: 1090.8938700	total: 1.56s	remaining: 10.2s
10:	learn: 1085.3780302	total: 1.71s	remaining: 9.93s
11:	learn: 1079.9561222	total: 1.89s	remaining: 9.91s
12:	learn: 1074.5316659	total: 2.03s	remaining: 9.66s
13:	learn: 1072.1168268	total: 2.15s	remaining: 9.37s
14:	learn: 1067.8176652	total: 2.32s	remaining: 9.27s
15:	learn: 1065.2356379	total: 2.44s	remaining: 9.01s
16:	learn: 1060.7849467	total: 2.6s	remaining: 8.88s
17:	learn: 1056.7858611	total: 2.84s	remaining: 8.98s
18:	learn: 1055.4421857	total: 2.9s	remaining: 8.54s
19:	learn: 1052.7472759	total: 3.11s	remaining: 8.54s
20:	learn: 1051.4449830	total: 3.19s	remaining: 8.21s
21:	learn: 1049.8880695	total: 3.32s	remaining: 8s
22:	learn: 1048.7484404	total: 3.52s	remaining: 7.97s
23:	learn: 1048.1006926	total: 3.54s	remaining: 7.51s
24:	learn: 1046.9663275	total: 3.67s	remaining: 7.33s
25:	learn: 1046.3053013	total: 3.8s	remaining: 7.17s
26:	learn: 1045.4813354	total: 3.82s	remaining: 6.8s
27:	learn: 1044.7765430	total: 3.98s	remaining: 6.69s
28:	learn: 1044.0579536	total: 4.02s	remaining: 6.38s
29:	learn: 1043.6199645	total: 4.31s	remaining: 6.46s
30:	learn: 1042.8650569	total: 4.39s	remaining: 6.23s
31:	learn: 1042.1978744	total: 4.51s	remaining: 6.06s
32:	learn: 1041.1397593	total: 4.57s	remaining: 5.82s
33:	learn: 1040.5718311	total: 4.59s	remaining: 5.54s
34:	learn: 1038.0108709	total: 4.66s	remaining: 5.32s
35:	learn: 1037.2245360	total: 4.69s	remaining: 5.08s
36:	learn: 1036.5071543	total: 4.8s	remaining: 4.93s
37:	learn: 1035.6625613	total: 4.84s	remaining: 4.71s
38:	learn: 1035.2025293	total: 5.06s	remaining: 4.67s
39:	learn: 1033.9169559	total: 5.17s	remaining: 4.52s
40:	learn: 1033.4459713	total: 5.36s	remaining: 4.44s
41:	learn: 1032.7208051	total: 5.49s	remaining: 4.31s
42:	learn: 1032.1424554	total: 5.6s	remaining: 4.17s
43:	learn: 1031.3006272	total: 5.75s	remaining: 4.05s
44:	learn: 1030.2537497	total: 5.85s	remaining: 3.9s
45:	learn: 1029.4296668	total: 5.97s	remaining: 3.77s
46:	learn: 1028.5651759	total: 6.12s	remaining: 3.65s
47:	learn: 1027.7074086	total: 6.33s	remaining: 3.56s
48:	learn: 1026.8327884	total: 6.46s	remaining: 3.43s
49:	learn: 1026.0545514	total: 6.8s	remaining: 3.4s
50:	learn: 1025.2642192	total: 6.95s	remaining: 3.27s
51:	learn: 1024.5879910	total: 7.09s	remaining: 3.13s
52:	learn: 1023.7108867	total: 7.2s	remaining: 2.99s
53:	learn: 1022.8973762	total: 7.3s	remaining: 2.84s
54:	learn: 1021.6842274	total: 7.45s	remaining: 2.71s
55:	learn: 1020.8198772	total: 7.65s	remaining: 2.6s
56:	learn: 1020.1151115	total: 7.8s	remaining: 2.46s
57:	learn: 1019.0087506	total: 7.92s	remaining: 2.32s
58:	learn: 1017.8096374	total: 8.1s	remaining: 2.2s
59:	learn: 1016.8468382	total: 8.38s	remaining: 2.1s
60:	learn: 1016.0066304	total: 8.7s	remaining: 2s
61:	learn: 1015.1607267	total: 8.83s	remaining: 1.85s
62:	learn: 1014.5268279	total: 9.1s	remaining: 1.73s
63:	learn: 1013.7911396	total: 9.36s	remaining: 1.61s
64:	learn: 1013.1901460	total: 9.54s	remaining: 1.47s
65:	learn: 1012.6321041	total: 9.84s	remaining: 1.34s
66:	learn: 1011.8127496	total: 10s	remaining: 1.2s
67:	learn: 1010.8683591	total: 10.1s	remaining: 1.04s
68:	learn: 1010.2409777	total: 10.2s	remaining: 890ms
69:	learn: 1009.0013235	total: 10.4s	remaining: 746ms
70:	learn: 1008.0894168	total: 10.5s	remaining: 592ms
71:	learn: 1007.1203873	total: 10.6s	remaining: 443ms
72:	learn: 1006.7035923	total: 10.9s	remaining: 299ms
73:	learn: 1006.2095756	total: 11s	remaining: 149ms
74:	learn: 1005.4233404	total: 11.1s	remaining: 0us
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.355606 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 817
[LightGBM] [Info] Number of data points in the train set: 5454, number of used features: 39
[LightGBM] [Info] Start training from score 2173.066949
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
0:	learn: 1535.7740899	total: 207ms	remaining: 15.3s
1:	learn: 1396.2743318	total: 296ms	remaining: 10.8s
2:	learn: 1297.0224680	total: 535ms	remaining: 12.8s
3:	learn: 1235.5193222	total: 749ms	remaining: 13.3s
4:	learn: 1180.3421262	total: 903ms	remaining: 12.6s
5:	learn: 1151.6597971	total: 1.02s	remaining: 11.8s
6:	learn: 1124.4234752	total: 1.15s	remaining: 11.2s
7:	learn: 1105.2506394	total: 1.24s	remaining: 10.4s
8:	learn: 1097.6551769	total: 1.34s	remaining: 9.83s
9:	learn: 1086.8669350	total: 1.5s	remaining: 9.73s
10:	learn: 1080.1787414	total: 1.66s	remaining: 9.63s
11:	learn: 1074.7521233	total: 1.83s	remaining: 9.6s
12:	learn: 1070.0253185	total: 2.03s	remaining: 9.67s
13:	learn: 1067.8346926	total: 2.43s	remaining: 10.6s
14:	learn: 1063.9469290	total: 2.55s	remaining: 10.2s
15:	learn: 1061.7962914	total: 2.87s	remaining: 10.6s
16:	learn: 1058.7257889	total: 3.07s	remaining: 10.5s
17:	learn: 1057.6850690	total: 3.18s	remaining: 10.1s
18:	learn: 1056.1253493	total: 3.27s	remaining: 9.64s
19:	learn: 1054.5663755	total: 3.29s	remaining: 9.05s
20:	learn: 1053.8629147	total: 3.37s	remaining: 8.66s
21:	learn: 1052.3353610	total: 3.41s	remaining: 8.22s
22:	learn: 1051.9692777	total: 3.47s	remaining: 7.84s
23:	learn: 1050.1503949	total: 3.84s	remaining: 8.16s
24:	learn: 1048.7454138	total: 4.07s	remaining: 8.15s
25:	learn: 1047.8167385	total: 4.23s	remaining: 7.97s
26:	learn: 1045.8342185	total: 4.43s	remaining: 7.87s
27:	learn: 1045.1373753	total: 4.61s	remaining: 7.73s
28:	learn: 1044.2407973	total: 4.8s	remaining: 7.62s
29:	learn: 1043.7749413	total: 4.89s	remaining: 7.33s
30:	learn: 1043.0715900	total: 5.11s	remaining: 7.26s
31:	learn: 1041.9894334	total: 5.22s	remaining: 7.01s
32:	learn: 1040.6140215	total: 5.33s	remaining: 6.78s
33:	learn: 1039.3759569	total: 5.41s	remaining: 6.53s
34:	learn: 1038.6711662	total: 5.47s	remaining: 6.25s
35:	learn: 1037.5224117	total: 5.57s	remaining: 6.04s
36:	learn: 1036.9695197	total: 5.69s	remaining: 5.84s
37:	learn: 1036.0954046	total: 5.83s	remaining: 5.68s
38:	learn: 1034.5306584	total: 6.11s	remaining: 5.64s
39:	learn: 1033.8279998	total: 6.3s	remaining: 5.52s
40:	learn: 1033.3510038	total: 6.42s	remaining: 5.33s
41:	learn: 1032.2060505	total: 6.57s	remaining: 5.16s
42:	learn: 1031.3411055	total: 6.97s	remaining: 5.19s
43:	learn: 1029.6906156	total: 7.18s	remaining: 5.06s
44:	learn: 1028.8211710	total: 7.47s	remaining: 4.98s
45:	learn: 1028.3441038	total: 7.57s	remaining: 4.77s
46:	learn: 1027.2982396	total: 7.71s	remaining: 4.59s
47:	learn: 1026.5349447	total: 7.78s	remaining: 4.37s
48:	learn: 1025.8631349	total: 7.84s	remaining: 4.16s
49:	learn: 1025.1727471	total: 8.01s	remaining: 4.01s
50:	learn: 1024.2352450	total: 8.14s	remaining: 3.83s
51:	learn: 1023.2673941	total: 8.28s	remaining: 3.66s
52:	learn: 1022.6744430	total: 8.5s	remaining: 3.53s
53:	learn: 1022.0730324	total: 8.6s	remaining: 3.34s
54:	learn: 1021.1026621	total: 8.78s	remaining: 3.19s
55:	learn: 1020.4471333	total: 9.01s	remaining: 3.06s
56:	learn: 1019.4555457	total: 9.19s	remaining: 2.9s
57:	learn: 1018.4025598	total: 9.3s	remaining: 2.73s
58:	learn: 1017.8253398	total: 9.57s	remaining: 2.6s
59:	learn: 1016.7441290	total: 9.75s	remaining: 2.44s
60:	learn: 1015.9078334	total: 9.85s	remaining: 2.26s
61:	learn: 1015.4090921	total: 9.87s	remaining: 2.07s
62:	learn: 1014.7242272	total: 9.94s	remaining: 1.89s
63:	learn: 1013.8686215	total: 10s	remaining: 1.73s
64:	learn: 1013.5229980	total: 10.2s	remaining: 1.56s
65:	learn: 1012.8857783	total: 10.3s	remaining: 1.41s
66:	learn: 1012.1673880	total: 10.4s	remaining: 1.24s
67:	learn: 1011.4495851	total: 10.5s	remaining: 1.08s
68:	learn: 1010.5826145	total: 10.6s	remaining: 925ms
69:	learn: 1009.6283043	total: 10.8s	remaining: 775ms
70:	learn: 1008.7403241	total: 11.2s	remaining: 631ms
71:	learn: 1007.9026713	total: 11.4s	remaining: 474ms
72:	learn: 1007.6205646	total: 11.5s	remaining: 315ms
73:	learn: 1007.1659561	total: 11.6s	remaining: 157ms
74:	learn: 1006.8537932	total: 11.8s	remaining: 0us
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.346497 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 817
[LightGBM] [Info] Number of data points in the train set: 5455, number of used features: 39
[LightGBM] [Info] Start training from score 2184.653597
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
0:	learn: 1528.5835446	total: 351ms	remaining: 26s
1:	learn: 1391.2901665	total: 460ms	remaining: 16.8s
2:	learn: 1295.1466657	total: 668ms	remaining: 16s
3:	learn: 1223.7055803	total: 867ms	remaining: 15.4s
4:	learn: 1171.9567350	total: 1.03s	remaining: 14.4s
5:	learn: 1135.9214537	total: 1.2s	remaining: 13.8s
6:	learn: 1115.9686673	total: 1.42s	remaining: 13.8s
7:	learn: 1098.6903590	total: 1.49s	remaining: 12.5s
8:	learn: 1088.4569008	total: 1.71s	remaining: 12.5s
9:	learn: 1079.8883055	total: 1.98s	remaining: 12.9s
10:	learn: 1072.2701343	total: 2.32s	remaining: 13.5s
11:	learn: 1067.4695944	total: 2.6s	remaining: 13.7s
12:	learn: 1063.0853341	total: 2.7s	remaining: 12.9s
13:	learn: 1059.1261205	total: 2.74s	remaining: 11.9s
14:	learn: 1055.7137712	total: 2.76s	remaining: 11s
15:	learn: 1053.1918785	total: 2.95s	remaining: 10.9s
16:	learn: 1051.4502910	total: 3.08s	remaining: 10.5s
17:	learn: 1049.9850264	total: 3.24s	remaining: 10.3s
18:	learn: 1047.8728343	total: 3.34s	remaining: 9.85s
19:	learn: 1046.1425325	total: 3.47s	remaining: 9.55s
20:	learn: 1044.4301218	total: 3.5s	remaining: 9.01s
21:	learn: 1043.2602391	total: 3.75s	remaining: 9.03s
22:	learn: 1041.2001696	total: 4.03s	remaining: 9.12s
23:	learn: 1040.3588562	total: 4.22s	remaining: 8.97s
24:	learn: 1039.2458710	total: 4.42s	remaining: 8.83s
25:	learn: 1038.5435134	total: 4.52s	remaining: 8.52s
26:	learn: 1037.6920132	total: 4.63s	remaining: 8.22s
27:	learn: 1036.2183367	total: 4.65s	remaining: 7.81s
28:	learn: 1035.6403514	total: 4.76s	remaining: 7.55s
29:	learn: 1034.9163542	total: 4.83s	remaining: 7.25s
30:	learn: 1033.4922826	total: 4.88s	remaining: 6.93s
31:	learn: 1032.4791415	total: 4.94s	remaining: 6.64s
32:	learn: 1031.6985661	total: 5.07s	remaining: 6.46s
33:	learn: 1030.9206412	total: 5.18s	remaining: 6.25s
34:	learn: 1030.1104488	total: 5.3s	remaining: 6.06s
35:	learn: 1029.2095631	total: 5.38s	remaining: 5.83s
36:	learn: 1028.5281974	total: 5.54s	remaining: 5.69s
37:	learn: 1027.8195774	total: 5.64s	remaining: 5.5s
38:	learn: 1026.8138262	total: 5.74s	remaining: 5.29s
39:	learn: 1026.2148531	total: 5.76s	remaining: 5.04s
40:	learn: 1025.6208142	total: 5.95s	remaining: 4.94s
41:	learn: 1024.9969496	total: 6.15s	remaining: 4.83s
42:	learn: 1024.0151927	total: 6.25s	remaining: 4.65s
43:	learn: 1023.1979258	total: 6.31s	remaining: 4.44s
44:	learn: 1022.4636927	total: 6.49s	remaining: 4.32s
45:	learn: 1021.7925967	total: 6.58s	remaining: 4.15s
46:	learn: 1021.2062389	total: 6.75s	remaining: 4.02s
47:	learn: 1020.1983613	total: 6.84s	remaining: 3.85s
48:	learn: 1019.3195357	total: 6.95s	remaining: 3.69s
49:	learn: 1018.5036591	total: 7.07s	remaining: 3.53s
50:	learn: 1017.5839677	total: 7.24s	remaining: 3.41s
51:	learn: 1016.5565291	total: 7.43s	remaining: 3.29s
52:	learn: 1015.7412925	total: 7.54s	remaining: 3.13s
53:	learn: 1014.8514571	total: 7.66s	remaining: 2.98s
54:	learn: 1014.3661463	total: 7.74s	remaining: 2.81s
55:	learn: 1013.3177352	total: 7.8s	remaining: 2.65s
56:	learn: 1012.6039366	total: 7.96s	remaining: 2.52s
57:	learn: 1011.6432022	total: 8.04s	remaining: 2.36s
58:	learn: 1010.9503327	total: 8.14s	remaining: 2.21s
59:	learn: 1010.3189776	total: 8.34s	remaining: 2.08s
60:	learn: 1009.5536325	total: 8.37s	remaining: 1.92s
61:	learn: 1008.4606520	total: 8.46s	remaining: 1.77s
62:	learn: 1007.8205701	total: 8.49s	remaining: 1.62s
63:	learn: 1006.9360663	total: 8.51s	remaining: 1.46s
64:	learn: 1005.9347708	total: 8.59s	remaining: 1.32s
65:	learn: 1005.2083422	total: 8.61s	remaining: 1.17s
66:	learn: 1004.7008751	total: 8.63s	remaining: 1.03s
67:	learn: 1004.2881512	total: 8.68s	remaining: 893ms
68:	learn: 1003.9696523	total: 8.81s	remaining: 766ms
69:	learn: 1003.7055317	total: 9.05s	remaining: 646ms
70:	learn: 1002.7964706	total: 9.22s	remaining: 519ms
71:	learn: 1001.8474582	total: 9.38s	remaining: 391ms
72:	learn: 1000.9260327	total: 9.55s	remaining: 262ms
73:	learn: 999.9803446	total: 9.66s	remaining: 131ms
74:	learn: 998.8245309	total: 9.85s	remaining: 0us
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.192637 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 816
[LightGBM] [Info] Number of data points in the train set: 5454, number of used features: 39
[LightGBM] [Info] Start training from score 2147.784860
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

41:	learn: 1088.8319895	total: 2.25s	remaining: 1.76s
42:	learn: 1087.3629929	total: 2.35s	remaining: 1.75s
43:	learn: 1085.7624144	total: 2.42s	remaining: 1.7s
44:	learn: 1084.1731915	total: 2.5s	remaining: 1.67s
45:	learn: 1082.8810041	total: 2.63s	remaining: 1.66s
46:	learn: 1081.5717011	total: 2.63s	remaining: 1.57s
47:	learn: 1080.3890411	total: 2.75s	remaining: 1.55s
48:	learn: 1078.7818047	total: 2.83s	remaining: 1.5s
49:	learn: 1077.6499314	total: 2.9s	remaining: 1.45s
50:	learn: 1076.6643230	total: 2.97s	remaining: 1.4s
51:	learn: 1075.7437486	total: 3.04s	remaining: 1.34s
52:	learn: 1074.7490662	total: 3.12s	remaining: 1.3s
53:	learn: 1074.1478629	total: 3.18s	remaining: 1.24s
54:	learn: 1073.2936242	total: 3.2s	remaining: 1.16s
55:	learn: 1072.4464746	total: 3.24s	remaining: 1.1s
56:	learn: 1071.6010320	total: 3.25s	remaining: 1.02s
57:	learn: 1071.2259368	total: 3.26s	remaining: 955ms
58:	learn: 1070.7449546	total: 3.27s	remaining: 886ms
59:	learn: 1070.0859615	total: 3.27s	remaining: 819ms
60:	learn: 1069.6989954	total: 3.28s	remaining: 754ms
61:	learn: 1068.8697992	total: 3.29s	remaining: 690ms
62:	learn: 1068.3928120	total: 3.3s	remaining: 629ms
63:	learn: 1067.6116874	total: 3.31s	remaining: 568ms
64:	learn: 1067.1911396	total: 3.32s	remaining: 511ms
65:	learn: 1066.7483930	total: 3.33s	remaining: 455ms
66:	learn: 1066.3855718	total: 3.36s	remaining: 401ms
67:	learn: 1065.8431044	total: 3.37s	remaining: 347ms
68:	learn: 1065.4500414	total: 3.4s	remaining: 295ms
69:	learn: 1064.7649906	total: 3.4s	remaining: 243ms
70:	learn: 1064.5405600	total: 3.42s	remaining: 193ms
71:	learn: 1064.1806580	total: 3.43s	remaining: 143ms
72:	learn: 1063.9775357	total: 3.44s	remaining: 94.2ms
73:	learn: 1063.2470839	total: 3.45s	remaining: 46.6ms
74:	learn: 1062.8121144	total: 3.45s	remaining: 0us
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.284209 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 813
[LightGBM] [Info] Number of data points in the train set: 5454, number of used features: 39
[LightGBM] [Info] Start training from score 2171.037443
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.227342 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 813
[LightGBM] [Info] Number of data points in the train set: 5454, number of used features: 39
[LightGBM] [Info] Start training from score 2197.953391
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
0:	learn: 1526.5767613	total: 92.3ms	remaining: 6.83s
1:	learn: 1390.2010266	total: 274ms	remaining: 10s
2:	learn: 1293.5915664	total: 418ms	remaining: 10s
3:	learn: 1233.7314787	total: 469ms	remaining: 8.32s
4:	learn: 1185.7317805	total: 506ms	remaining: 7.08s
5:	learn: 1153.7782732	total: 710ms	remaining: 8.16s
6:	learn: 1128.7251813	total: 837ms	remaining: 8.13s
7:	learn: 1111.6907616	total: 905ms	remaining: 7.58s
8:	learn: 1098.9908946	total: 1.07s	remaining: 7.87s
9:	learn: 1091.8106908	total: 1.24s	remaining: 8.06s
10:	learn: 1085.4918352	total: 1.33s	remaining: 7.76s
11:	learn: 1077.8161243	total: 1.49s	remaining: 7.8s
12:	learn: 1072.8542561	total: 1.68s	remaining: 8.03s
13:	learn: 1069.0649715	total: 1.83s	remaining: 7.97s
14:	learn: 1067.5599905	total: 1.96s	remaining: 7.82s
15:	learn: 1064.2742304	total: 2.13s	remaining: 7.87s
16:	learn: 1061.1244016	total: 2.32s	remaining: 7.9s
17:	learn: 1060.2626388	total: 2.52s	remaining: 7.99s
18:	learn: 1058.7045549	total: 2.73s	remaining: 8.05s
19:	learn: 1057.4620640	total: 2.9s	remaining: 7.99s
20:	learn: 1056.6936105	total: 3.06s	remaining: 7.88s
21:	learn: 1055.5340965	total: 3.17s	remaining: 7.64s
22:	learn: 1054.2840336	total: 3.31s	remaining: 7.48s
23:	learn: 1053.6006929	total: 3.44s	remaining: 7.31s
24:	learn: 1053.0237610	total: 3.48s	remaining: 6.96s
25:	learn: 1051.9089030	total: 3.61s	remaining: 6.8s
26:	learn: 1051.0141959	total: 3.73s	remaining: 6.63s
27:	learn: 1050.1443063	total: 3.86s	remaining: 6.48s
28:	learn: 1048.8532526	total: 3.97s	remaining: 6.3s
29:	learn: 1046.9453055	total: 4.08s	remaining: 6.11s
30:	learn: 1045.4469247	total: 4.19s	remaining: 5.95s
31:	learn: 1044.3343929	total: 4.34s	remaining: 5.83s
32:	learn: 1043.3624749	total: 4.39s	remaining: 5.59s
33:	learn: 1041.3797196	total: 4.42s	remaining: 5.33s
34:	learn: 1040.5836515	total: 4.45s	remaining: 5.09s
35:	learn: 1038.6129080	total: 4.62s	remaining: 5s
36:	learn: 1037.8438855	total: 4.8s	remaining: 4.93s
37:	learn: 1037.3503921	total: 5s	remaining: 4.87s
38:	learn: 1036.2663789	total: 5.21s	remaining: 4.81s
39:	learn: 1035.8327539	total: 5.37s	remaining: 4.7s
40:	learn: 1035.1409037	total: 5.61s	remaining: 4.65s
41:	learn: 1034.5123927	total: 5.77s	remaining: 4.53s
42:	learn: 1033.5733405	total: 5.89s	remaining: 4.38s
43:	learn: 1032.7932263	total: 5.97s	remaining: 4.2s
44:	learn: 1032.0026392	total: 6.18s	remaining: 4.12s
45:	learn: 1031.1643605	total: 6.37s	remaining: 4.01s
46:	learn: 1029.8507538	total: 6.43s	remaining: 3.83s
47:	learn: 1028.9974145	total: 6.64s	remaining: 3.73s
48:	learn: 1027.9958606	total: 6.8s	remaining: 3.61s
49:	learn: 1026.9617887	total: 6.83s	remaining: 3.41s
50:	learn: 1025.9047377	total: 6.88s	remaining: 3.24s
51:	learn: 1025.2305473	total: 6.9s	remaining: 3.05s
52:	learn: 1024.2909677	total: 6.92s	remaining: 2.87s
53:	learn: 1023.1778418	total: 7s	remaining: 2.72s
54:	learn: 1022.6024677	total: 7.11s	remaining: 2.58s
55:	learn: 1021.9276428	total: 7.18s	remaining: 2.44s
56:	learn: 1021.0692873	total: 7.29s	remaining: 2.3s
57:	learn: 1020.2169583	total: 7.43s	remaining: 2.18s
58:	learn: 1019.5999551	total: 7.62s	remaining: 2.07s
59:	learn: 1018.5204435	total: 7.72s	remaining: 1.93s
60:	learn: 1017.7917263	total: 7.86s	remaining: 1.8s
61:	learn: 1017.2293347	total: 7.98s	remaining: 1.67s
62:	learn: 1016.4993691	total: 8.07s	remaining: 1.54s
63:	learn: 1015.5695665	total: 8.17s	remaining: 1.4s
64:	learn: 1014.8963892	total: 8.26s	remaining: 1.27s
65:	learn: 1014.0821155	total: 8.35s	remaining: 1.14s
66:	learn: 1013.6025005	total: 8.42s	remaining: 1s
67:	learn: 1013.1731625	total: 8.47s	remaining: 872ms
68:	learn: 1012.8436195	total: 8.54s	remaining: 743ms
69:	learn: 1011.9774212	total: 8.62s	remaining: 616ms
70:	learn: 1011.3297832	total: 8.7s	remaining: 490ms
71:	learn: 1010.6266368	total: 8.79s	remaining: 366ms
72:	learn: 1009.8256735	total: 8.85s	remaining: 242ms
73:	learn: 1009.2103158	total: 8.89s	remaining: 120ms
74:	learn: 1008.5513527	total: 9.05s	remaining: 0us
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.330380 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 816
[LightGBM] [Info] Number of data points in the train set: 5455, number of used features: 39
[LightGBM] [Info] Start training from score 2186.946488
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
0:	learn: 1515.7762607	total: 167ms	remaining: 12.4s
1:	learn: 1381.9551530	total: 216ms	remaining: 7.9s
2:	learn: 1289.6671898	total: 354ms	remaining: 8.5s
3:	learn: 1221.8616661	total: 508ms	remaining: 9.02s
4:	learn: 1173.5144324	total: 636ms	remaining: 8.9s
5:	learn: 1136.1605580	total: 721ms	remaining: 8.3s
6:	learn: 1112.1257382	total: 791ms	remaining: 7.68s
7:	learn: 1096.8395597	total: 1.05s	remaining: 8.78s
8:	learn: 1086.9527569	total: 1.18s	remaining: 8.69s
9:	learn: 1079.6948851	total: 1.21s	remaining: 7.88s
10:	learn: 1072.0366946	total: 1.24s	remaining: 7.22s
11:	learn: 1066.7300784	total: 1.28s	remaining: 6.72s
12:	learn: 1061.9949692	total: 1.37s	remaining: 6.53s
13:	learn: 1060.0768327	total: 1.43s	remaining: 6.25s
14:	learn: 1057.9068637	total: 1.51s	remaining: 6.04s
15:	learn: 1054.9905633	total: 1.6s	remaining: 5.9s
16:	learn: 1054.0891275	total: 1.71s	remaining: 5.84s
17:	learn: 1051.8879242	total: 1.82s	remaining: 5.77s
18:	learn: 1049.2690061	total: 1.91s	remaining: 5.64s
19:	learn: 1048.4172155	total: 2.01s	remaining: 5.53s
20:	learn: 1047.5559459	total: 2.12s	remaining: 5.46s
21:	learn: 1045.7247748	total: 2.29s	remaining: 5.53s
22:	learn: 1044.2100885	total: 2.44s	remaining: 5.51s
23:	learn: 1042.7963216	total: 2.46s	remaining: 5.24s
24:	learn: 1041.8382465	total: 2.6s	remaining: 5.2s
25:	learn: 1041.1721400	total: 2.7s	remaining: 5.1s
26:	learn: 1040.0255300	total: 2.83s	remaining: 5.03s
27:	learn: 1037.8544398	total: 2.99s	remaining: 5.02s
28:	learn: 1036.7335953	total: 3.1s	remaining: 4.91s
29:	learn: 1035.0665593	total: 3.29s	remaining: 4.94s
30:	learn: 1034.0425824	total: 3.4s	remaining: 4.83s
31:	learn: 1032.9705982	total: 3.58s	remaining: 4.81s
32:	learn: 1032.4823471	total: 3.69s	remaining: 4.69s
33:	learn: 1029.5970640	total: 3.81s	remaining: 4.59s
34:	learn: 1029.0809233	total: 3.91s	remaining: 4.47s
35:	learn: 1028.1011095	total: 4.05s	remaining: 4.39s
36:	learn: 1027.4531288	total: 4.1s	remaining: 4.21s
37:	learn: 1027.0657034	total: 4.17s	remaining: 4.05s
38:	learn: 1024.6150966	total: 4.31s	remaining: 3.98s
39:	learn: 1023.9344497	total: 4.45s	remaining: 3.89s
40:	learn: 1023.0828174	total: 4.58s	remaining: 3.8s
41:	learn: 1022.3715164	total: 4.67s	remaining: 3.67s
42:	learn: 1021.5536573	total: 4.75s	remaining: 3.54s
43:	learn: 1020.8526681	total: 4.86s	remaining: 3.43s
44:	learn: 1020.1841538	total: 4.95s	remaining: 3.3s
45:	learn: 1018.1831021	total: 5.08s	remaining: 3.2s
46:	learn: 1017.4997481	total: 5.14s	remaining: 3.06s
47:	learn: 1017.0148339	total: 5.25s	remaining: 2.95s
48:	learn: 1016.2039756	total: 5.39s	remaining: 2.86s
49:	learn: 1015.4135093	total: 5.51s	remaining: 2.75s
50:	learn: 1014.5992265	total: 5.75s	remaining: 2.71s
51:	learn: 1013.6238044	total: 5.79s	remaining: 2.56s
52:	learn: 1012.5123173	total: 5.91s	remaining: 2.45s
53:	learn: 1011.5443017	total: 6.09s	remaining: 2.37s
54:	learn: 1010.5427372	total: 6.15s	remaining: 2.24s
55:	learn: 1009.3196664	total: 6.36s	remaining: 2.16s
56:	learn: 1008.5597432	total: 6.53s	remaining: 2.06s
57:	learn: 1007.8044425	total: 6.67s	remaining: 1.95s
58:	learn: 1006.9640441	total: 6.81s	remaining: 1.85s
59:	learn: 1005.9097107	total: 6.95s	remaining: 1.74s
60:	learn: 1005.2473156	total: 7.07s	remaining: 1.62s
61:	learn: 1004.6952453	total: 7.23s	remaining: 1.51s
62:	learn: 1004.2806730	total: 7.42s	remaining: 1.41s
63:	learn: 1003.5021440	total: 7.5s	remaining: 1.29s
64:	learn: 1002.9674967	total: 7.62s	remaining: 1.17s
65:	learn: 1002.6072631	total: 7.63s	remaining: 1.04s
66:	learn: 1002.2600986	total: 7.72s	remaining: 922ms
67:	learn: 1001.2029492	total: 7.84s	remaining: 807ms
68:	learn: 1000.3106924	total: 7.98s	remaining: 694ms
69:	learn: 999.2155060	total: 8.21s	remaining: 587ms
70:	learn: 998.9260770	total: 8.35s	remaining: 471ms
71:	learn: 998.0037510	total: 8.41s	remaining: 351ms
72:	learn: 997.1566856	total: 8.52s	remaining: 233ms
73:	learn: 996.7615991	total: 8.63s	remaining: 117ms
74:	learn: 996.0474437	total: 8.8s	remaining: 0us
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.297241 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 813
[LightGBM] [Info] Number of data points in the train set: 5454, number of used features: 39
[LightGBM] [Info] Start training from score 2171.037443
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.256373 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 815
[LightGBM] [Info] Number of data points in the train set: 5454, number of used features: 39
[LightGBM] [Info] Start training from score 2184.956129
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.184885 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 814
[LightGBM] [Info] Number of data points in the train set: 5454, number of used features: 39
[LightGBM] [Info] Start training from score 2188.546493
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.252852 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 815
[LightGBM] [Info] Number of data points in the train set: 5455, number of used features: 39
[LightGBM] [Info] Start training from score 2194.700891
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.277775 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 816
[LightGBM] [Info] Number of data points in the train set: 5455, number of used features: 39
[LightGBM] [Info] Start training from score 2195.120754
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.313445 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 816
[LightGBM] [Info] Number of data points in the train set: 5454, number of used features: 39
[LightGBM] [Info] Start training from score 2180.642468
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.217241 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 813
[LightGBM] [Info] Number of data points in the train set: 5454, number of used features: 39
[LightGBM] [Info] Start training from score 2197.953391
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.126505 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 817
[LightGBM] [Info] Number of data points in the train set: 6819, number of used features: 39
[LightGBM] [Info] Start training from score 2193.082712
0:	learn: 1661.9614315	total: 342ms	remaining: 1m 8s
1:	learn: 1617.0761108	total: 546ms	remaining: 54s
2:	learn: 1575.4963997	total: 638ms	remaining: 41.9s
3:	learn: 1538.1922170	total: 930ms	remaining: 45.6s
4:	learn: 1502.7852567	total: 1.17s	remaining: 45.5s
5:	learn: 1470.7939871	total: 1.2s	remaining: 38.9s
6:	learn: 1439.6311496	total: 1.4s	remaining: 38.6s
7:	learn: 1410.7100036	total: 1.64s	remaining: 39.3s
8:	learn: 1384.9071852	total: 1.87s	remaining: 39.7s
9:	learn: 1364.0999420	total: 1.91s	remaining: 36.2s
10:	learn: 1340.3729224	total: 2.08s	remaining: 35.8s
11:	learn: 1319.2290491	total: 2.18s	remaining: 34.2s
12:	learn: 1299.1709202	total: 2.42s	remaining: 34.9s
13:	learn: 1280.3112692	total: 2.52s	remaining: 33.5s
14:	learn: 1264.6366388	total: 2.69s	remaining: 33.2s
15:	learn: 1248.8792438	total: 2.8s	remaining: 32.2s
16:	learn: 1234.4406996	total: 2.96s	remaining: 31.8s
17:	learn: 1222.8577016	total: 3.16s	remaining: 31.9s
18:	learn: 1210.3254604	total: 3.35s	remaining: 31.9s
19:	learn: 1198.2472755	total: 3.47s	remaining: 31.3s
20:	learn: 1188.1260111	total: 3.57s	remaining: 30.4s
21:	learn: 1178.2971554	total: 3.68s	remaining: 29.8s
22:	learn: 1168.8519661	total: 3.89s	remaining: 30s
23:	learn: 1160.9766496	total: 4.08s	remaining: 29.9s
24:	learn: 1153.0011772	total: 4.26s	remaining: 29.8s
25:	learn: 1145.8618073	total: 4.37s	remaining: 29.2s
26:	learn: 1139.6894539	total: 4.55s	remaining: 29.2s
27:	learn: 1133.9976802	total: 4.7s	remaining: 28.9s
28:	learn: 1128.4887876	total: 4.82s	remaining: 28.4s
29:	learn: 1123.8444187	total: 4.86s	remaining: 27.6s
30:	learn: 1118.9054291	total: 5.03s	remaining: 27.4s
31:	learn: 1115.3040786	total: 5.15s	remaining: 27s
32:	learn: 1112.0055371	total: 5.3s	remaining: 26.8s
33:	learn: 1107.9322757	total: 5.49s	remaining: 26.8s
34:	learn: 1104.1654884	total: 5.67s	remaining: 26.7s
35:	learn: 1101.9683107	total: 5.71s	remaining: 26s
36:	learn: 1099.0685016	total: 5.89s	remaining: 25.9s
37:	learn: 1096.0915514	total: 6.06s	remaining: 25.8s
38:	learn: 1094.4701638	total: 6.11s	remaining: 25.2s
39:	learn: 1091.7753246	total: 6.25s	remaining: 25s
40:	learn: 1089.1181750	total: 6.38s	remaining: 24.8s
41:	learn: 1087.5008879	total: 6.61s	remaining: 24.8s
42:	learn: 1086.3502490	total: 6.73s	remaining: 24.6s
43:	learn: 1084.5644057	total: 6.96s	remaining: 24.7s
44:	learn: 1082.6902310	total: 7.14s	remaining: 24.6s
45:	learn: 1081.2177974	total: 7.24s	remaining: 24.2s
46:	learn: 1079.8114770	total: 7.39s	remaining: 24s
47:	learn: 1078.5174940	total: 7.46s	remaining: 23.6s
48:	learn: 1077.0834637	total: 7.61s	remaining: 23.4s
49:	learn: 1075.7443245	total: 7.67s	remaining: 23s
50:	learn: 1073.8583728	total: 7.85s	remaining: 22.9s
51:	learn: 1072.4999120	total: 8.03s	remaining: 22.8s
52:	learn: 1071.3565214	total: 8.21s	remaining: 22.8s
53:	learn: 1070.2991149	total: 8.38s	remaining: 22.6s
54:	learn: 1069.4754422	total: 8.56s	remaining: 22.6s
55:	learn: 1068.5459528	total: 8.7s	remaining: 22.4s
56:	learn: 1067.7059673	total: 8.81s	remaining: 22.1s
57:	learn: 1066.6793730	total: 8.95s	remaining: 21.9s
58:	learn: 1065.6879015	total: 9.16s	remaining: 21.9s
59:	learn: 1064.5712597	total: 9.28s	remaining: 21.6s
60:	learn: 1064.3723233	total: 9.41s	remaining: 21.4s
61:	learn: 1063.6648776	total: 9.56s	remaining: 21.3s
62:	learn: 1062.9263736	total: 9.71s	remaining: 21.1s
63:	learn: 1062.2407386	total: 9.9s	remaining: 21s
64:	learn: 1061.8289137	total: 10.1s	remaining: 21s
65:	learn: 1061.5299106	total: 10.2s	remaining: 20.7s
66:	learn: 1060.4640233	total: 10.5s	remaining: 20.8s
67:	learn: 1060.3356192	total: 10.7s	remaining: 20.7s
68:	learn: 1059.5903067	total: 10.9s	remaining: 20.7s
69:	learn: 1058.8103427	total: 11s	remaining: 20.4s
70:	learn: 1057.7733047	total: 11.1s	remaining: 20.2s
71:	learn: 1057.4298653	total: 11.3s	remaining: 20s
72:	learn: 1057.0463635	total: 11.3s	remaining: 19.7s
73:	learn: 1056.4272468	total: 11.5s	remaining: 19.6s
74:	learn: 1056.0375783	total: 11.6s	remaining: 19.3s
75:	learn: 1055.8409263	total: 11.6s	remaining: 19s
76:	learn: 1055.4894056	total: 11.7s	remaining: 18.7s
77:	learn: 1055.1603425	total: 11.8s	remaining: 18.5s
78:	learn: 1054.6911208	total: 11.9s	remaining: 18.2s
79:	learn: 1054.1830551	total: 11.9s	remaining: 17.9s
80:	learn: 1053.8598353	total: 12s	remaining: 17.7s
81:	learn: 1053.6365286	total: 12.1s	remaining: 17.4s
82:	learn: 1053.1380865	total: 12.2s	remaining: 17.1s
83:	learn: 1052.7736129	total: 12.3s	remaining: 16.9s
84:	learn: 1052.6372056	total: 12.4s	remaining: 16.8s
85:	learn: 1052.3014253	total: 12.5s	remaining: 16.6s
86:	learn: 1052.0065591	total: 12.7s	remaining: 16.5s
87:	learn: 1051.7541070	total: 12.9s	remaining: 16.4s
88:	learn: 1051.3843067	total: 13s	remaining: 16.2s
89:	learn: 1051.1608355	total: 13.1s	remaining: 16s
90:	learn: 1050.9144382	total: 13.2s	remaining: 15.8s
91:	learn: 1050.2143782	total: 13.4s	remaining: 15.7s
92:	learn: 1049.8747131	total: 13.5s	remaining: 15.6s
93:	learn: 1049.5316522	total: 13.8s	remaining: 15.5s
94:	learn: 1049.3604910	total: 13.8s	remaining: 15.3s
95:	learn: 1049.1721425	total: 13.8s	remaining: 15s
96:	learn: 1048.8581062	total: 13.9s	remaining: 14.8s
97:	learn: 1048.5675373	total: 14s	remaining: 14.6s
98:	learn: 1048.1987327	total: 14.2s	remaining: 14.5s
99:	learn: 1048.0320707	total: 14.3s	remaining: 14.3s
100:	learn: 1047.3564155	total: 14.3s	remaining: 14s
101:	learn: 1047.1597598	total: 14.5s	remaining: 13.9s
102:	learn: 1046.6399836	total: 14.7s	remaining: 13.8s
103:	learn: 1046.3216102	total: 14.8s	remaining: 13.7s
104:	learn: 1046.0769368	total: 15s	remaining: 13.6s
105:	learn: 1045.8273477	total: 15.2s	remaining: 13.4s
106:	learn: 1045.3792231	total: 15.3s	remaining: 13.3s
107:	learn: 1045.2745991	total: 15.4s	remaining: 13.1s
108:	learn: 1045.0542475	total: 15.5s	remaining: 12.9s
109:	learn: 1044.6504722	total: 15.6s	remaining: 12.8s
110:	learn: 1044.4379696	total: 15.7s	remaining: 12.6s
111:	learn: 1044.2823475	total: 15.9s	remaining: 12.5s
112:	learn: 1044.0192966	total: 16s	remaining: 12.3s
113:	learn: 1043.8638132	total: 16.1s	remaining: 12.2s
114:	learn: 1043.5815766	total: 16.3s	remaining: 12s
115:	learn: 1043.0995232	total: 16.5s	remaining: 11.9s
116:	learn: 1042.2540566	total: 16.6s	remaining: 11.8s
117:	learn: 1042.0059709	total: 16.8s	remaining: 11.7s
118:	learn: 1041.7659751	total: 17s	remaining: 11.6s
119:	learn: 1041.6291721	total: 17s	remaining: 11.4s
120:	learn: 1041.4488323	total: 17.2s	remaining: 11.2s
121:	learn: 1041.2317597	total: 17.3s	remaining: 11.1s
122:	learn: 1041.0382178	total: 17.3s	remaining: 10.9s
123:	learn: 1040.8473657	total: 17.5s	remaining: 10.7s
124:	learn: 1040.7232138	total: 17.6s	remaining: 10.6s
125:	learn: 1040.5374872	total: 17.8s	remaining: 10.5s
126:	learn: 1040.4034774	total: 17.9s	remaining: 10.3s
127:	learn: 1039.9929766	total: 18s	remaining: 10.1s
128:	learn: 1039.8223955	total: 18.1s	remaining: 9.97s
129:	learn: 1039.2920054	total: 18.3s	remaining: 9.87s
130:	learn: 1038.9760840	total: 18.4s	remaining: 9.69s
131:	learn: 1038.8623023	total: 18.6s	remaining: 9.56s
132:	learn: 1038.7319942	total: 18.7s	remaining: 9.43s
133:	learn: 1038.5464263	total: 18.7s	remaining: 9.23s
134:	learn: 1037.7676312	total: 19s	remaining: 9.12s
135:	learn: 1037.6077436	total: 19s	remaining: 8.96s
136:	learn: 1037.2844886	total: 19.2s	remaining: 8.81s
137:	learn: 1037.1110919	total: 19.2s	remaining: 8.64s
138:	learn: 1036.9508406	total: 19.4s	remaining: 8.54s
139:	learn: 1036.7857195	total: 19.5s	remaining: 8.37s
140:	learn: 1036.4360240	total: 19.6s	remaining: 8.21s
141:	learn: 1036.2707405	total: 19.7s	remaining: 8.06s
142:	learn: 1036.1270044	total: 19.9s	remaining: 7.94s
143:	learn: 1036.0295386	total: 20s	remaining: 7.79s
144:	learn: 1035.8578025	total: 20.2s	remaining: 7.65s
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.188403 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 815
[LightGBM] [Info] Number of data points in the train set: 6818, number of used features: 39
[LightGBM] [Info] Start training from score 2183.057911
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
0:	learn: 1648.9474167	total: 143ms	remaining: 28.5s
1:	learn: 1604.8272806	total: 203ms	remaining: 20.1s
2:	learn: 1565.3439342	total: 254ms	remaining: 16.7s
3:	learn: 1528.1168775	total: 397ms	remaining: 19.4s
4:	learn: 1492.1703267	total: 541ms	remaining: 21.1s
5:	learn: 1458.6619897	total: 775ms	remaining: 25.1s
6:	learn: 1427.4564422	total: 985ms	remaining: 27.2s
7:	learn: 1398.5961836	total: 1.15s	remaining: 27.6s
8:	learn: 1371.7996128	total: 1.34s	remaining: 28.5s
9:	learn: 1347.0529509	total: 1.46s	remaining: 27.7s
10:	learn: 1325.4498252	total: 1.52s	remaining: 26.2s
11:	learn: 1305.1186700	total: 1.71s	remaining: 26.7s
12:	learn: 1285.1794605	total: 1.86s	remaining: 26.8s
13:	learn: 1266.3081387	total: 2.04s	remaining: 27.1s
14:	learn: 1250.2446037	total: 2.13s	remaining: 26.3s
15:	learn: 1235.6441177	total: 2.25s	remaining: 25.9s
16:	learn: 1221.2017776	total: 2.49s	remaining: 26.8s
17:	learn: 1207.9115756	total: 2.6s	remaining: 26.2s
18:	learn: 1195.7473753	total: 2.74s	remaining: 26.1s
19:	learn: 1184.7441636	total: 2.81s	remaining: 25.3s
20:	learn: 1174.7412399	total: 2.87s	remaining: 24.5s
21:	learn: 1165.1843566	total: 2.95s	remaining: 23.9s
22:	learn: 1157.0316264	total: 3.08s	remaining: 23.7s
23:	learn: 1149.2761165	total: 3.22s	remaining: 23.6s
24:	learn: 1141.6676367	total: 3.44s	remaining: 24.1s
25:	learn: 1136.0487555	total: 3.73s	remaining: 24.9s
26:	learn: 1129.9365644	total: 3.93s	remaining: 25.2s
27:	learn: 1125.7154311	total: 3.99s	remaining: 24.5s
28:	learn: 1120.4784174	total: 4.16s	remaining: 24.5s
29:	learn: 1116.0796865	total: 4.24s	remaining: 24s
30:	learn: 1111.8415409	total: 4.51s	remaining: 24.6s
31:	learn: 1108.0980172	total: 4.6s	remaining: 24.1s
32:	learn: 1104.0891234	total: 4.7s	remaining: 23.8s
33:	learn: 1100.7736994	total: 4.83s	remaining: 23.6s
34:	learn: 1097.0472873	total: 5.01s	remaining: 23.6s
35:	learn: 1093.7590702	total: 5.19s	remaining: 23.7s
36:	learn: 1091.0460229	total: 5.3s	remaining: 23.3s
37:	learn: 1088.9066184	total: 5.42s	remaining: 23.1s
38:	learn: 1086.7988265	total: 5.66s	remaining: 23.3s
39:	learn: 1084.8059477	total: 5.75s	remaining: 23s
40:	learn: 1082.8047223	total: 5.84s	remaining: 22.7s
41:	learn: 1081.3896322	total: 6.04s	remaining: 22.7s
42:	learn: 1079.2895199	total: 6.18s	remaining: 22.6s
43:	learn: 1077.1690137	total: 6.33s	remaining: 22.4s
44:	learn: 1075.7176867	total: 6.41s	remaining: 22.1s
45:	learn: 1074.7109908	total: 6.59s	remaining: 22.1s
46:	learn: 1073.6399848	total: 6.69s	remaining: 21.8s
47:	learn: 1071.9421472	total: 6.88s	remaining: 21.8s
48:	learn: 1070.9218518	total: 7.02s	remaining: 21.6s
49:	learn: 1069.3086666	total: 7.11s	remaining: 21.3s
50:	learn: 1068.1364971	total: 7.24s	remaining: 21.1s
51:	learn: 1067.3079041	total: 7.33s	remaining: 20.9s
52:	learn: 1066.0632510	total: 7.44s	remaining: 20.6s
53:	learn: 1064.8623176	total: 7.51s	remaining: 20.3s
54:	learn: 1064.2349634	total: 7.62s	remaining: 20.1s
55:	learn: 1062.8278889	total: 7.77s	remaining: 20s
56:	learn: 1061.9494023	total: 7.84s	remaining: 19.7s
57:	learn: 1061.3120984	total: 7.93s	remaining: 19.4s
58:	learn: 1060.6116963	total: 8.01s	remaining: 19.2s
59:	learn: 1060.1413321	total: 8.12s	remaining: 18.9s
60:	learn: 1059.2738235	total: 8.26s	remaining: 18.8s
61:	learn: 1058.3487075	total: 8.49s	remaining: 18.9s
62:	learn: 1057.7017784	total: 8.66s	remaining: 18.8s
63:	learn: 1057.0214812	total: 8.8s	remaining: 18.7s
64:	learn: 1056.4989217	total: 8.93s	remaining: 18.5s
65:	learn: 1056.1153056	total: 9.04s	remaining: 18.3s
66:	learn: 1055.3686668	total: 9.22s	remaining: 18.3s
67:	learn: 1054.9241566	total: 9.33s	remaining: 18.1s
68:	learn: 1054.3869218	total: 9.41s	remaining: 17.9s
69:	learn: 1054.0108940	total: 9.67s	remaining: 18s
70:	learn: 1053.8486044	total: 9.73s	remaining: 17.7s
71:	learn: 1053.1883867	total: 9.9s	remaining: 17.6s
72:	learn: 1052.7079393	total: 10s	remaining: 17.4s
73:	learn: 1052.3442049	total: 10.2s	remaining: 17.3s
74:	learn: 1051.9691231	total: 10.3s	remaining: 17.1s
75:	learn: 1051.3922988	total: 10.5s	remaining: 17.1s
76:	learn: 1050.8093296	total: 10.6s	remaining: 16.9s
77:	learn: 1050.5151077	total: 10.7s	remaining: 16.8s
78:	learn: 1050.0790452	total: 10.9s	remaining: 16.7s
79:	learn: 1049.6356025	total: 11.1s	remaining: 16.6s
80:	learn: 1049.3490779	total: 11.1s	remaining: 16.4s
81:	learn: 1048.7814392	total: 11.3s	remaining: 16.2s
82:	learn: 1048.5948660	total: 11.4s	remaining: 16.1s
83:	learn: 1048.1720418	total: 11.6s	remaining: 16s
84:	learn: 1047.3783809	total: 11.7s	remaining: 15.8s
85:	learn: 1046.8837821	total: 11.8s	remaining: 15.6s
86:	learn: 1046.6256598	total: 11.8s	remaining: 15.3s
87:	learn: 1046.2499022	total: 12s	remaining: 15.3s
88:	learn: 1045.9321964	total: 12s	remaining: 15s
89:	learn: 1045.6441294	total: 12.3s	remaining: 15s
90:	learn: 1045.0147136	total: 12.4s	remaining: 14.8s
91:	learn: 1044.6773446	total: 12.5s	remaining: 14.7s
92:	learn: 1044.0467241	total: 12.7s	remaining: 14.6s
93:	learn: 1043.7652231	total: 12.9s	remaining: 14.5s
94:	learn: 1043.5480144	total: 13.1s	remaining: 14.4s
95:	learn: 1043.3591170	total: 13.2s	remaining: 14.3s
96:	learn: 1043.1012695	total: 13.3s	remaining: 14.1s
97:	learn: 1042.9352399	total: 13.4s	remaining: 14s
98:	learn: 1042.6165832	total: 13.6s	remaining: 13.8s
99:	learn: 1042.1695330	total: 13.7s	remaining: 13.7s
100:	learn: 1041.6304054	total: 13.9s	remaining: 13.6s
101:	learn: 1041.2266547	total: 14.1s	remaining: 13.6s
102:	learn: 1041.0762615	total: 14.4s	remaining: 13.6s
103:	learn: 1040.4324967	total: 14.5s	remaining: 13.4s
104:	learn: 1040.0190538	total: 14.5s	remaining: 13.2s
105:	learn: 1039.2353856	total: 14.7s	remaining: 13s
106:	learn: 1038.8977184	total: 14.7s	remaining: 12.8s
107:	learn: 1038.4851810	total: 14.9s	remaining: 12.7s
108:	learn: 1038.2596186	total: 15.1s	remaining: 12.6s
109:	learn: 1037.3168531	total: 15.2s	remaining: 12.4s
110:	learn: 1036.7499833	total: 15.5s	remaining: 12.4s
111:	learn: 1036.3214951	total: 15.6s	remaining: 12.2s
112:	learn: 1036.0772635	total: 15.8s	remaining: 12.2s
113:	learn: 1035.9778530	total: 15.9s	remaining: 12s
114:	learn: 1035.5716302	total: 16.1s	remaining: 11.9s
115:	learn: 1035.3034210	total: 16.2s	remaining: 11.7s
116:	learn: 1034.9261658	total: 16.3s	remaining: 11.5s
117:	learn: 1034.7092369	total: 16.5s	remaining: 11.5s
118:	learn: 1034.2071436	total: 16.6s	remaining: 11.3s
119:	learn: 1033.9431805	total: 16.8s	remaining: 11.2s
120:	learn: 1033.7759513	total: 16.9s	remaining: 11s
121:	learn: 1033.6718668	total: 17.1s	remaining: 10.9s
122:	learn: 1033.2889525	total: 17.2s	remaining: 10.7s
123:	learn: 1032.6732075	total: 17.3s	remaining: 10.6s
124:	learn: 1032.4298056	total: 17.4s	remaining: 10.4s
125:	learn: 1032.1819906	total: 17.5s	remaining: 10.3s
126:	learn: 1031.8915346	total: 17.6s	remaining: 10.1s
127:	learn: 1031.3884881	total: 17.8s	remaining: 10s
128:	learn: 1031.0490800	total: 17.9s	remaining: 9.86s
129:	learn: 1030.8686693	total: 18s	remaining: 9.71s
130:	learn: 1030.7149700	total: 18.1s	remaining: 9.54s
131:	learn: 1030.5642995	total: 18.2s	remaining: 9.38s
132:	learn: 1030.1126341	total: 18.4s	remaining: 9.26s
133:	learn: 1029.9619391	total: 18.6s	remaining: 9.15s
134:	learn: 1029.7504999	total: 18.7s	remaining: 9.01s
135:	learn: 1029.2927613	total: 18.9s	remaining: 8.89s
136:	learn: 1028.9887815	total: 19s	remaining: 8.75s
137:	learn: 1028.7335608	total: 19.2s	remaining: 8.61s
138:	learn: 1028.5157928	total: 19.3s	remaining: 8.45s
139:	learn: 1028.1425054	total: 19.3s	remaining: 8.28s
140:	learn: 1028.0166287	total: 19.4s	remaining: 8.13s

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.151814 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 819
[LightGBM] [Info] Number of data points in the train set: 6818, number of used features: 39
[LightGBM] [Info] Start training from score 2180.679468
0:	learn: 1667.4985297	total: 136ms	remaining: 27.1s
1:	learn: 1622.1150447	total: 305ms	remaining: 30.2s
2:	learn: 1581.6007571	total: 385ms	remaining: 25.3s
3:	learn: 1542.3521103	total: 487ms	remaining: 23.9s
4:	learn: 1505.8088116	total: 584ms	remaining: 22.8s
5:	learn: 1476.7010727	total: 704ms	remaining: 22.7s
6:	learn: 1443.8007393	total: 864ms	remaining: 23.8s
7:	learn: 1413.7857345	total: 933ms	remaining: 22.4s
8:	learn: 1388.5815741	total: 1.11s	remaining: 23.7s
9:	learn: 1362.7506643	total: 1.24s	remaining: 23.6s
10:	learn: 1339.2321157	total: 1.4s	remaining: 24.1s
11:	learn: 1316.9977936	total: 1.53s	remaining: 24s
12:	learn: 1296.8004008	total: 1.63s	remaining: 23.5s
13:	learn: 1278.6004249	total: 1.7s	remaining: 22.6s
14:	learn: 1261.8216285	total: 1.84s	remaining: 22.7s
15:	learn: 1246.7184713	total: 1.98s	remaining: 22.7s
16:	learn: 1232.7729174	total: 2.08s	remaining: 22.4s
17:	learn: 1218.6491342	total: 2.18s	remaining: 22s
18:	learn: 1206.2888105	total: 2.33s	remaining: 22.2s
19:	learn: 1195.3887899	total: 2.42s	remaining: 21.8s
20:	learn: 1186.1976733	total: 2.58s	remaining: 22s
21:	learn: 1178.2851909	total: 2.7s	remaining: 21.8s
22:	learn: 1171.0754679	total: 2.8s	remaining: 21.5s
23:	learn: 1162.7444928	total: 2.88s	remaining: 21.2s
24:	learn: 1155.4033107	total: 3.03s	remaining: 21.2s
25:	learn: 1148.8515519	total: 3.26s	remaining: 21.8s
26:	learn: 1142.1435031	total: 3.38s	remaining: 21.7s
27:	learn: 1136.0090456	total: 3.53s	remaining: 21.7s
28:	learn: 1130.9975829	total: 3.67s	remaining: 21.7s
29:	learn: 1125.5149684	total: 3.76s	remaining: 21.3s
30:	learn: 1120.7944730	total: 3.85s	remaining: 21s
31:	learn: 1116.4124154	total: 3.93s	remaining: 20.6s
32:	learn: 1112.0982286	total: 4.12s	remaining: 20.8s
33:	learn: 1108.0209618	total: 4.3s	remaining: 21s
34:	learn: 1104.4535395	total: 4.47s	remaining: 21.1s
35:	learn: 1101.1677210	total: 4.57s	remaining: 20.8s
36:	learn: 1098.0256871	total: 4.65s	remaining: 20.5s
37:	learn: 1095.7010616	total: 4.71s	remaining: 20.1s
38:	learn: 1093.3311764	total: 4.88s	remaining: 20.1s
39:	learn: 1091.3385994	total: 4.97s	remaining: 19.9s
40:	learn: 1089.2429272	total: 5.08s	remaining: 19.7s
41:	learn: 1087.1988951	total: 5.12s	remaining: 19.2s
42:	learn: 1085.4780643	total: 5.23s	remaining: 19.1s
43:	learn: 1083.6248502	total: 5.33s	remaining: 18.9s
44:	learn: 1082.1072246	total: 5.43s	remaining: 18.7s
45:	learn: 1080.3022876	total: 5.53s	remaining: 18.5s
46:	learn: 1079.0516737	total: 5.61s	remaining: 18.3s
47:	learn: 1077.3399526	total: 5.75s	remaining: 18.2s
48:	learn: 1076.1643049	total: 5.89s	remaining: 18.2s
49:	learn: 1074.6943032	total: 6.02s	remaining: 18.1s
50:	learn: 1073.6211047	total: 6.15s	remaining: 18s
51:	learn: 1072.2688308	total: 6.25s	remaining: 17.8s
52:	learn: 1071.3008528	total: 6.36s	remaining: 17.6s
53:	learn: 1070.3521043	total: 6.4s	remaining: 17.3s
54:	learn: 1069.1888490	total: 6.5s	remaining: 17.1s
55:	learn: 1068.2457944	total: 6.65s	remaining: 17.1s
56:	learn: 1067.4946443	total: 6.82s	remaining: 17.1s
57:	learn: 1066.3644952	total: 6.93s	remaining: 17s
58:	learn: 1065.1141964	total: 7.08s	remaining: 16.9s
59:	learn: 1064.3046604	total: 7.21s	remaining: 16.8s
60:	learn: 1063.5157178	total: 7.37s	remaining: 16.8s
61:	learn: 1062.9022364	total: 7.54s	remaining: 16.8s
62:	learn: 1062.3784026	total: 7.74s	remaining: 16.8s
63:	learn: 1061.4713963	total: 7.91s	remaining: 16.8s
64:	learn: 1061.0024693	total: 8.11s	remaining: 16.8s
65:	learn: 1060.4742216	total: 8.31s	remaining: 16.9s
66:	learn: 1059.6334058	total: 8.47s	remaining: 16.8s
67:	learn: 1059.2209497	total: 8.64s	remaining: 16.8s
68:	learn: 1059.0736752	total: 8.77s	remaining: 16.7s
69:	learn: 1058.6346569	total: 8.88s	remaining: 16.5s
70:	learn: 1058.2436546	total: 9s	remaining: 16.3s
71:	learn: 1057.8100218	total: 9.13s	remaining: 16.2s
72:	learn: 1057.5836504	total: 9.27s	remaining: 16.1s
73:	learn: 1057.3167359	total: 9.41s	remaining: 16s
74:	learn: 1056.8724993	total: 9.49s	remaining: 15.8s
75:	learn: 1056.3958670	total: 9.69s	remaining: 15.8s
76:	learn: 1056.0221971	total: 9.91s	remaining: 15.8s
77:	learn: 1055.4199343	total: 10.1s	remaining: 15.7s
78:	learn: 1055.2324392	total: 10.2s	remaining: 15.5s
79:	learn: 1054.8745824	total: 10.3s	remaining: 15.4s
80:	learn: 1054.0407392	total: 10.4s	remaining: 15.2s
81:	learn: 1053.8209408	total: 10.5s	remaining: 15.1s
82:	learn: 1053.6955923	total: 10.6s	remaining: 15s
83:	learn: 1053.4307562	total: 10.6s	remaining: 14.7s
84:	learn: 1053.1604865	total: 10.7s	remaining: 14.4s
85:	learn: 1052.8992310	total: 10.9s	remaining: 14.4s
86:	learn: 1052.4982612	total: 11s	remaining: 14.3s
87:	learn: 1052.2989813	total: 11.2s	remaining: 14.2s
88:	learn: 1051.9329001	total: 11.3s	remaining: 14.1s
89:	learn: 1051.6083654	total: 11.4s	remaining: 14s
90:	learn: 1051.3418647	total: 11.6s	remaining: 13.9s
91:	learn: 1050.6600412	total: 11.8s	remaining: 13.8s
92:	learn: 1050.3760648	total: 11.9s	remaining: 13.7s
93:	learn: 1049.9685338	total: 12s	remaining: 13.5s
94:	learn: 1049.6196516	total: 12.2s	remaining: 13.4s
95:	learn: 1049.2010377	total: 12.4s	remaining: 13.5s
96:	learn: 1049.0340533	total: 12.6s	remaining: 13.3s
97:	learn: 1048.6572043	total: 12.7s	remaining: 13.2s
98:	learn: 1048.1591743	total: 12.7s	remaining: 13s
99:	learn: 1047.8650187	total: 12.9s	remaining: 12.9s
100:	learn: 1047.6384849	total: 13.1s	remaining: 12.8s
101:	learn: 1047.3323931	total: 13.1s	remaining: 12.6s
102:	learn: 1047.1626064	total: 13.2s	remaining: 12.5s
103:	learn: 1046.9227868	total: 13.4s	remaining: 12.4s
104:	learn: 1046.6340190	total: 13.5s	remaining: 12.2s
105:	learn: 1046.4436008	total: 13.7s	remaining: 12.1s
106:	learn: 1046.2783978	total: 13.9s	remaining: 12.1s
107:	learn: 1045.9975955	total: 14s	remaining: 12s
108:	learn: 1045.8211236	total: 14.2s	remaining: 11.8s
109:	learn: 1045.3732468	total: 14.3s	remaining: 11.7s
110:	learn: 1045.1042893	total: 14.4s	remaining: 11.6s
111:	learn: 1044.6987982	total: 14.5s	remaining: 11.4s
112:	learn: 1044.3377951	total: 14.6s	remaining: 11.2s
113:	learn: 1044.0668597	total: 14.8s	remaining: 11.1s
114:	learn: 1043.8795376	total: 14.9s	remaining: 11s
115:	learn: 1043.4859434	total: 15.1s	remaining: 10.9s
116:	learn: 1042.9945212	total: 15.2s	remaining: 10.8s
117:	learn: 1042.7428940	total: 15.3s	remaining: 10.6s
118:	learn: 1042.6918641	total: 15.4s	remaining: 10.5s
119:	learn: 1042.5686967	total: 15.5s	remaining: 10.3s
120:	learn: 1042.2305049	total: 15.7s	remaining: 10.3s
121:	learn: 1042.0009603	total: 15.9s	remaining: 10.2s
122:	learn: 1041.8441218	total: 16.1s	remaining: 10.1s
123:	learn: 1040.8686830	total: 16.2s	remaining: 9.92s
124:	learn: 1040.5672797	total: 16.3s	remaining: 9.75s
125:	learn: 1040.1086604	total: 16.4s	remaining: 9.61s
126:	learn: 1039.8243176	total: 16.5s	remaining: 9.51s
127:	learn: 1039.7024317	total: 16.7s	remaining: 9.38s
128:	learn: 1039.0466607	total: 16.8s	remaining: 9.26s
129:	learn: 1038.8580976	total: 16.9s	remaining: 9.12s
130:	learn: 1038.7300596	total: 17s	remaining: 8.96s
131:	learn: 1038.5331177	total: 17.1s	remaining: 8.81s
132:	learn: 1038.4889722	total: 17.1s	remaining: 8.62s
133:	learn: 1038.3277394	total: 17.2s	remaining: 8.49s
134:	learn: 1038.1784610	total: 17.3s	remaining: 8.31s
135:	learn: 1038.0112000	total: 17.4s	remaining: 8.17s
136:	learn: 1037.8419378	total: 17.5s	remaining: 8.05s
137:	learn: 1037.5304130	total: 17.6s	remaining: 7.92s
138:	learn: 1037.4921521	total: 17.6s	remaining: 7.74s
139:	learn: 1037.2655372	total: 17.7s	remaining: 7.6s
140:	learn: 1036.9413776	total: 17.8s	remaining: 7.46s
141:	learn: 1036.2810376	total: 18s	remaining: 7.33s
142:	learn: 1036.0697371	total: 18s	remaining: 7.18s
143:	learn: 1035.7481176	total: 18.1s	remaining: 7.04s
144:	learn: 1035.6010342	total: 18.2s	remaining: 6.89s
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.113625 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 816
[LightGBM] [Info] Number of data points in the train set: 6818, number of used features: 39
[LightGBM] [Info] Start training from score 2159.816823
0:	learn: 1657.7910349	total: 191ms	remaining: 38.1s
1:	learn: 1612.8735228	total: 400ms	remaining: 39.6s
2:	learn: 1572.5408286	total: 730ms	remaining: 47.9s
3:	learn: 1532.9376353	total: 960ms	remaining: 47s
4:	learn: 1495.9857371	total: 1.08s	remaining: 42s
5:	learn: 1461.8219110	total: 1.29s	remaining: 41.6s
6:	learn: 1432.1973639	total: 1.29s	remaining: 35.7s
7:	learn: 1403.0005434	total: 1.42s	remaining: 34.1s
8:	learn: 1377.3022007	total: 1.56s	remaining: 33.1s
9:	learn: 1352.1836568	total: 1.86s	remaining: 35.4s
10:	learn: 1328.8375094	total: 1.95s	remaining: 33.6s
11:	learn: 1306.4938688	total: 2.06s	remaining: 32.2s
12:	learn: 1286.4160708	total: 2.2s	remaining: 31.6s
13:	learn: 1267.9135029	total: 2.29s	remaining: 30.4s
14:	learn: 1250.9500595	total: 2.45s	remaining: 30.2s
15:	learn: 1235.5921852	total: 2.53s	remaining: 29.1s
16:	learn: 1221.2517774	total: 2.6s	remaining: 28s
17:	learn: 1208.1650842	total: 2.78s	remaining: 28.1s
18:	learn: 1195.0795543	total: 2.94s	remaining: 28s
19:	learn: 1185.4000088	total: 3.02s	remaining: 27.2s
20:	learn: 1174.9073173	total: 3.14s	remaining: 26.8s
21:	learn: 1165.5585534	total: 3.28s	remaining: 26.5s
22:	learn: 1157.1317414	total: 3.38s	remaining: 26s
23:	learn: 1150.5734714	total: 3.52s	remaining: 25.8s
24:	learn: 1143.2434242	total: 3.66s	remaining: 25.6s
25:	learn: 1136.5647503	total: 4.07s	remaining: 27.3s
26:	learn: 1130.8379614	total: 4.15s	remaining: 26.6s
27:	learn: 1124.7238631	total: 4.3s	remaining: 26.4s
28:	learn: 1119.9878028	total: 4.36s	remaining: 25.7s
29:	learn: 1114.6919186	total: 4.47s	remaining: 25.4s
30:	learn: 1110.6667274	total: 4.62s	remaining: 25.2s
31:	learn: 1107.1169501	total: 4.72s	remaining: 24.8s
32:	learn: 1103.8030456	total: 4.73s	remaining: 23.9s
33:	learn: 1100.1345169	total: 4.93s	remaining: 24.1s
34:	learn: 1096.8707956	total: 5s	remaining: 23.6s
35:	learn: 1093.9199055	total: 5.13s	remaining: 23.4s
36:	learn: 1090.6261650	total: 5.26s	remaining: 23.2s
37:	learn: 1088.1776253	total: 5.35s	remaining: 22.8s
38:	learn: 1085.5976589	total: 5.59s	remaining: 23.1s
39:	learn: 1083.1807937	total: 5.74s	remaining: 23s
40:	learn: 1080.8112835	total: 5.92s	remaining: 22.9s
41:	learn: 1078.5181506	total: 5.99s	remaining: 22.5s
42:	learn: 1076.7014846	total: 6.18s	remaining: 22.6s
43:	learn: 1075.2011105	total: 6.21s	remaining: 22s
44:	learn: 1073.6166702	total: 6.31s	remaining: 21.7s
45:	learn: 1072.1860995	total: 6.44s	remaining: 21.6s
46:	learn: 1070.6018180	total: 6.55s	remaining: 21.3s
47:	learn: 1069.3422577	total: 6.72s	remaining: 21.3s
48:	learn: 1068.0726486	total: 6.86s	remaining: 21.2s
49:	learn: 1066.7504671	total: 7.07s	remaining: 21.2s
50:	learn: 1065.4251508	total: 7.18s	remaining: 21s
51:	learn: 1064.3051088	total: 7.29s	remaining: 20.7s
52:	learn: 1063.4669505	total: 7.47s	remaining: 20.7s
53:	learn: 1062.1240524	total: 7.67s	remaining: 20.7s
54:	learn: 1060.7545021	total: 7.91s	remaining: 20.8s
55:	learn: 1060.3805348	total: 8.02s	remaining: 20.6s
56:	learn: 1059.3780270	total: 8.05s	remaining: 20.2s
57:	learn: 1058.3244827	total: 8.28s	remaining: 20.3s
58:	learn: 1056.7028786	total: 8.44s	remaining: 20.2s
59:	learn: 1056.1386313	total: 8.51s	remaining: 19.9s
60:	learn: 1055.1076244	total: 8.68s	remaining: 19.8s
61:	learn: 1054.1046768	total: 8.74s	remaining: 19.5s
62:	learn: 1053.4652283	total: 8.91s	remaining: 19.4s
63:	learn: 1052.3939385	total: 9s	remaining: 19.1s
64:	learn: 1051.9909475	total: 9.1s	remaining: 18.9s
65:	learn: 1051.5834397	total: 9.25s	remaining: 18.8s
66:	learn: 1050.9346481	total: 9.49s	remaining: 18.8s
67:	learn: 1049.9016571	total: 9.69s	remaining: 18.8s
68:	learn: 1049.3126404	total: 9.88s	remaining: 18.8s
69:	learn: 1048.9352196	total: 9.92s	remaining: 18.4s
70:	learn: 1048.6312201	total: 10.1s	remaining: 18.3s
71:	learn: 1048.1536915	total: 10.1s	remaining: 18s
72:	learn: 1047.9420697	total: 10.3s	remaining: 17.9s
73:	learn: 1047.4431937	total: 10.4s	remaining: 17.8s
74:	learn: 1047.0691313	total: 10.6s	remaining: 17.6s
75:	learn: 1046.7874041	total: 10.6s	remaining: 17.3s
76:	learn: 1046.3806666	total: 10.7s	remaining: 17.2s
77:	learn: 1045.9218449	total: 10.9s	remaining: 17s
78:	learn: 1045.7584843	total: 11s	remaining: 16.8s
79:	learn: 1045.3476754	total: 11.1s	remaining: 16.6s
80:	learn: 1045.1582625	total: 11.2s	remaining: 16.5s
81:	learn: 1044.7316070	total: 11.3s	remaining: 16.3s
82:	learn: 1044.4818307	total: 11.5s	remaining: 16.2s
83:	learn: 1044.0723827	total: 11.5s	remaining: 15.9s
84:	learn: 1043.6743538	total: 11.7s	remaining: 15.8s
85:	learn: 1043.3377892	total: 11.8s	remaining: 15.6s
86:	learn: 1043.0526748	total: 11.8s	remaining: 15.4s
87:	learn: 1042.7185992	total: 12s	remaining: 15.2s
88:	learn: 1042.3170508	total: 12.2s	remaining: 15.2s
89:	learn: 1041.8128005	total: 12.3s	remaining: 15.1s
90:	learn: 1041.3242802	total: 12.5s	remaining: 15s
91:	learn: 1040.9962475	total: 12.6s	remaining: 14.8s
92:	learn: 1040.3377914	total: 12.7s	remaining: 14.6s
93:	learn: 1040.1180287	total: 12.9s	remaining: 14.5s
94:	learn: 1039.8341279	total: 13.1s	remaining: 14.5s
95:	learn: 1039.4519350	total: 13.2s	remaining: 14.3s
96:	learn: 1039.1592216	total: 13.4s	remaining: 14.2s
97:	learn: 1038.8068878	total: 13.4s	remaining: 14s
98:	learn: 1038.5662309	total: 13.6s	remaining: 13.9s
99:	learn: 1038.1219150	total: 13.7s	remaining: 13.7s
100:	learn: 1037.8212751	total: 13.9s	remaining: 13.6s
101:	learn: 1037.6707025	total: 14s	remaining: 13.4s
102:	learn: 1037.2420320	total: 14s	remaining: 13.2s
103:	learn: 1037.0805669	total: 14.2s	remaining: 13.1s
104:	learn: 1036.9037556	total: 14.3s	remaining: 12.9s

105:	learn: 1036.7402264	total: 14.4s	remaining: 12.8s
106:	learn: 1036.5473390	total: 14.5s	remaining: 12.6s
107:	learn: 1036.2808486	total: 14.5s	remaining: 12.4s
108:	learn: 1036.0591202	total: 14.7s	remaining: 12.2s
109:	learn: 1035.6180715	total: 14.8s	remaining: 12.1s
110:	learn: 1035.4394713	total: 14.9s	remaining: 11.9s
111:	learn: 1035.1753461	total: 14.9s	remaining: 11.7s
112:	learn: 1034.3162762	total: 15.1s	remaining: 11.7s
113:	learn: 1034.1786690	total: 15.2s	remaining: 11.5s
114:	learn: 1034.0158199	total: 15.3s	remaining: 11.3s
115:	learn: 1033.7186602	total: 15.4s	remaining: 11.2s
116:	learn: 1033.4624382	total: 15.7s	remaining: 11.1s
117:	learn: 1033.0377924	total: 15.8s	remaining: 11s
118:	learn: 1032.8754727	total: 15.9s	remaining: 10.8s
119:	learn: 1032.7323108	total: 16s	remaining: 10.7s
120:	learn: 1032.5011278	total: 16.1s	remaining: 10.5s
121:	learn: 1032.2788413	total: 16.2s	remaining: 10.3s
122:	learn: 1032.1107162	total: 16.2s	remaining: 10.1s
123:	learn: 1031.5931103	total: 16.3s	remaining: 9.99s
124:	learn: 1031.1915569	total: 16.5s	remaining: 9.89s
125:	learn: 1030.7017041	total: 16.6s	remaining: 9.76s
126:	learn: 1030.5479558	total: 16.7s	remaining: 9.61s
127:	learn: 1030.2607020	total: 16.8s	remaining: 9.45s
128:	learn: 1030.0494968	total: 16.9s	remaining: 9.29s
129:	learn: 1029.8914926	total: 17s	remaining: 9.17s
130:	learn: 1029.7240382	total: 17.1s	remaining: 9.01s
131:	learn: 1029.5708282	total: 17.2s	remaining: 8.88s
132:	learn: 1029.4166805	total: 17.3s	remaining: 8.71s
133:	learn: 1029.1915619	total: 17.4s	remaining: 8.59s
134:	learn: 1029.0402361	total: 17.5s	remaining: 8.44s
135:	learn: 1028.1915923	total: 17.6s	remaining: 8.28s
136:	learn: 1027.9641365	total: 17.7s	remaining: 8.12s
137:	learn: 1027.7308650	total: 17.7s	remaining: 7.96s
138:	learn: 1027.5712181	total: 17.8s	remaining: 7.79s
139:	learn: 1027.4576547	total: 17.9s	remaining: 7.67s
140:	learn: 1027.0808836	total: 18s	remaining: 7.55s
141:	learn: 1026.8682937	total: 18.1s	remaining: 7.4s
142:	learn: 1026.7331366	total: 18.2s	remaining: 7.24s
143:	learn: 1026.2644522	total: 18.3s	remaining: 7.1s
144:	learn: 1025.9422763	total: 18.4s	remaining: 6.96s
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.083701 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 820
[LightGBM] [Info] Number of data points in the train set: 6819, number of used features: 39
[LightGBM] [Info] Start training from score 2189.804680
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
0:	learn: 1664.9336909	total: 142ms	remaining: 28.3s
1:	learn: 1619.6396811	total: 278ms	remaining: 27.5s
2:	learn: 1578.6395674	total: 424ms	remaining: 27.9s
3:	learn: 1539.7580434	total: 568ms	remaining: 27.8s
4:	learn: 1503.2639678	total: 768ms	remaining: 29.9s
5:	learn: 1473.5074714	total: 889ms	remaining: 28.8s
6:	learn: 1440.6534621	total: 974ms	remaining: 26.8s
7:	learn: 1410.4530655	total: 1.13s	remaining: 27.2s
8:	learn: 1384.9628614	total: 1.25s	remaining: 26.5s
9:	learn: 1359.5091655	total: 1.41s	remaining: 26.7s
10:	learn: 1335.9425145	total: 1.54s	remaining: 26.5s
11:	learn: 1313.8534984	total: 1.61s	remaining: 25.3s
12:	learn: 1293.6029918	total: 1.74s	remaining: 25s
13:	learn: 1275.7124831	total: 1.82s	remaining: 24.2s
14:	learn: 1258.6819133	total: 1.99s	remaining: 24.5s
15:	learn: 1243.5287692	total: 2.23s	remaining: 25.6s
16:	learn: 1228.8731743	total: 2.35s	remaining: 25.3s
17:	learn: 1214.9712132	total: 2.46s	remaining: 24.8s
18:	learn: 1204.3592118	total: 2.49s	remaining: 23.7s
19:	learn: 1192.8661636	total: 2.54s	remaining: 22.9s
20:	learn: 1182.3454214	total: 2.7s	remaining: 23s
21:	learn: 1172.5549584	total: 2.91s	remaining: 23.5s
22:	learn: 1163.1782921	total: 2.96s	remaining: 22.8s
23:	learn: 1156.1846227	total: 3.03s	remaining: 22.2s
24:	learn: 1149.2903515	total: 3.09s	remaining: 21.6s
25:	learn: 1142.2984051	total: 3.19s	remaining: 21.4s
26:	learn: 1135.5410391	total: 3.29s	remaining: 21.1s
27:	learn: 1129.7710652	total: 3.38s	remaining: 20.8s
28:	learn: 1124.4257833	total: 3.43s	remaining: 20.2s
29:	learn: 1119.1572116	total: 3.51s	remaining: 19.9s
30:	learn: 1114.3901669	total: 3.64s	remaining: 19.8s
31:	learn: 1109.9636590	total: 3.71s	remaining: 19.5s
32:	learn: 1105.9833799	total: 3.77s	remaining: 19.1s
33:	learn: 1102.1913102	total: 3.88s	remaining: 19s
34:	learn: 1098.5237223	total: 3.96s	remaining: 18.6s
35:	learn: 1095.3416658	total: 4.01s	remaining: 18.3s
36:	learn: 1092.5425310	total: 4.09s	remaining: 18s
37:	learn: 1089.6681667	total: 4.14s	remaining: 17.6s
38:	learn: 1087.4977143	total: 4.18s	remaining: 17.2s
39:	learn: 1085.5533492	total: 4.27s	remaining: 17.1s
40:	learn: 1083.5166702	total: 4.33s	remaining: 16.8s
41:	learn: 1081.3812219	total: 4.42s	remaining: 16.6s
42:	learn: 1079.7152256	total: 4.56s	remaining: 16.7s
43:	learn: 1078.1901658	total: 4.66s	remaining: 16.5s
44:	learn: 1076.8845973	total: 4.79s	remaining: 16.5s
45:	learn: 1075.4870769	total: 4.85s	remaining: 16.2s
46:	learn: 1074.0466907	total: 4.97s	remaining: 16.2s
47:	learn: 1072.9977957	total: 4.99s	remaining: 15.8s
48:	learn: 1071.7463965	total: 5.11s	remaining: 15.7s
49:	learn: 1070.6364291	total: 5.15s	remaining: 15.4s
50:	learn: 1070.1867171	total: 5.16s	remaining: 15.1s
51:	learn: 1069.2010547	total: 5.29s	remaining: 15.1s
52:	learn: 1068.1984141	total: 5.42s	remaining: 15s
53:	learn: 1067.2541508	total: 5.56s	remaining: 15s
54:	learn: 1066.4917938	total: 5.67s	remaining: 14.9s
55:	learn: 1066.1502047	total: 5.81s	remaining: 14.9s
56:	learn: 1065.1856377	total: 5.9s	remaining: 14.8s
57:	learn: 1064.7112782	total: 6.08s	remaining: 14.9s
58:	learn: 1064.1525988	total: 6.11s	remaining: 14.6s
59:	learn: 1063.6889854	total: 6.18s	remaining: 14.4s
60:	learn: 1063.1330674	total: 6.26s	remaining: 14.3s
61:	learn: 1062.4872562	total: 6.4s	remaining: 14.2s
62:	learn: 1062.1592019	total: 6.57s	remaining: 14.3s
63:	learn: 1061.4475164	total: 6.66s	remaining: 14.1s
64:	learn: 1061.0927055	total: 6.73s	remaining: 14s
65:	learn: 1060.9121542	total: 6.78s	remaining: 13.8s
66:	learn: 1060.6838767	total: 6.85s	remaining: 13.6s
67:	learn: 1060.1861723	total: 6.97s	remaining: 13.5s
68:	learn: 1059.3643011	total: 7.08s	remaining: 13.4s
69:	learn: 1058.8693153	total: 7.13s	remaining: 13.3s
70:	learn: 1058.6404972	total: 7.22s	remaining: 13.1s
71:	learn: 1057.9543065	total: 7.34s	remaining: 13s
72:	learn: 1057.3368114	total: 7.43s	remaining: 12.9s
73:	learn: 1056.9679905	total: 7.52s	remaining: 12.8s
74:	learn: 1056.5693435	total: 7.65s	remaining: 12.8s
75:	learn: 1056.0257879	total: 7.76s	remaining: 12.7s
76:	learn: 1055.4123213	total: 7.8s	remaining: 12.5s
77:	learn: 1054.9158721	total: 7.99s	remaining: 12.5s
78:	learn: 1054.5709953	total: 8.1s	remaining: 12.4s
79:	learn: 1053.7172446	total: 8.21s	remaining: 12.3s
80:	learn: 1053.4805874	total: 8.28s	remaining: 12.2s
81:	learn: 1053.0173692	total: 8.42s	remaining: 12.1s
82:	learn: 1052.4766938	total: 8.55s	remaining: 12.1s
83:	learn: 1052.3708897	total: 8.6s	remaining: 11.9s
84:	learn: 1052.1378039	total: 8.7s	remaining: 11.8s
85:	learn: 1052.0249846	total: 8.75s	remaining: 11.6s
86:	learn: 1051.7767123	total: 8.84s	remaining: 11.5s
87:	learn: 1051.5386479	total: 8.96s	remaining: 11.4s
88:	learn: 1051.2002671	total: 9.06s	remaining: 11.3s
89:	learn: 1050.8907518	total: 9.18s	remaining: 11.2s
90:	learn: 1050.3449346	total: 9.24s	remaining: 11.1s
91:	learn: 1050.0960238	total: 9.4s	remaining: 11s
92:	learn: 1049.7092805	total: 9.47s	remaining: 10.9s
93:	learn: 1049.3884907	total: 9.62s	remaining: 10.8s
94:	learn: 1049.2793595	total: 9.69s	remaining: 10.7s
95:	learn: 1048.7548738	total: 9.77s	remaining: 10.6s
96:	learn: 1048.3955538	total: 9.86s	remaining: 10.5s
97:	learn: 1048.1670045	total: 9.95s	remaining: 10.4s
98:	learn: 1047.7115096	total: 10s	remaining: 10.2s
99:	learn: 1046.8634983	total: 10.1s	remaining: 10.1s
100:	learn: 1046.1761647	total: 10.2s	remaining: 10s
101:	learn: 1045.9791315	total: 10.3s	remaining: 9.9s
102:	learn: 1045.4765578	total: 10.4s	remaining: 9.78s
103:	learn: 1045.1923890	total: 10.5s	remaining: 9.69s
104:	learn: 1044.6475795	total: 10.6s	remaining: 9.57s
105:	learn: 1044.2556836	total: 10.7s	remaining: 9.48s
106:	learn: 1044.0062074	total: 10.8s	remaining: 9.37s
107:	learn: 1043.6773894	total: 10.9s	remaining: 9.25s
108:	learn: 1043.0967449	total: 10.9s	remaining: 9.1s
109:	learn: 1042.8610399	total: 10.9s	remaining: 8.95s
110:	learn: 1042.7429709	total: 11s	remaining: 8.8s
111:	learn: 1042.4311138	total: 11s	remaining: 8.65s
112:	learn: 1042.2490097	total: 11s	remaining: 8.49s
113:	learn: 1042.1050533	total: 11.1s	remaining: 8.35s
114:	learn: 1041.9688344	total: 11.2s	remaining: 8.27s
115:	learn: 1041.4895447	total: 11.2s	remaining: 8.13s
116:	learn: 1041.4147534	total: 11.3s	remaining: 8.05s
117:	learn: 1041.1276494	total: 11.4s	remaining: 7.93s
118:	learn: 1040.9661602	total: 11.5s	remaining: 7.8s
119:	learn: 1040.7820103	total: 11.5s	remaining: 7.67s
120:	learn: 1040.3526397	total: 11.5s	remaining: 7.54s
121:	learn: 1039.6669451	total: 11.6s	remaining: 7.41s
122:	learn: 1039.5270194	total: 11.6s	remaining: 7.29s
123:	learn: 1039.2355484	total: 11.7s	remaining: 7.16s
124:	learn: 1039.0898327	total: 11.8s	remaining: 7.06s
125:	learn: 1038.9286150	total: 11.8s	remaining: 6.95s
126:	learn: 1038.7548347	total: 11.9s	remaining: 6.83s
127:	learn: 1038.3835684	total: 11.9s	remaining: 6.7s
128:	learn: 1038.0403912	total: 12s	remaining: 6.59s
129:	learn: 1037.7975043	total: 12s	remaining: 6.47s
130:	learn: 1037.6500556	total: 12.1s	remaining: 6.36s
131:	learn: 1037.3788983	total: 12.1s	remaining: 6.23s
132:	learn: 1037.2372116	total: 12.1s	remaining: 6.12s
133:	learn: 1037.0191184	total: 12.2s	remaining: 6s
134:	learn: 1036.8866124	total: 12.3s	remaining: 5.91s
135:	learn: 1036.6791318	total: 12.3s	remaining: 5.81s
136:	learn: 1036.3134423	total: 12.4s	remaining: 5.7s
137:	learn: 1035.9832426	total: 12.4s	remaining: 5.59s
138:	learn: 1035.7129738	total: 12.6s	remaining: 5.51s
139:	learn: 1035.5103197	total: 12.7s	remaining: 5.44s
140:	learn: 1035.1677801	total: 12.8s	remaining: 5.33s
141:	learn: 1035.0680896	total: 12.8s	remaining: 5.21s

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.221208 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 814
[LightGBM] [Info] Number of data points in the train set: 5455, number of used features: 39
[LightGBM] [Info] Start training from score 2173.197686
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.208101 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 816
[LightGBM] [Info] Number of data points in the train set: 5454, number of used features: 39
[LightGBM] [Info] Start training from score 2180.707534
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.225301 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 815
[LightGBM] [Info] Number of data points in the train set: 5455, number of used features: 39
[LightGBM] [Info] Start training from score 2185.996669
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.225305 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 816
[LightGBM] [Info] Number of data points in the train set: 5455, number of used features: 39
[LightGBM] [Info] Start training from score 2182.058258
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.325781 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 814
[LightGBM] [Info] Number of data points in the train set: 5454, number of used features: 39
[LightGBM] [Info] Start training from score 2149.096927
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.261205 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 815
[LightGBM] [Info] Number of data points in the train set: 5454, number of used features: 39
[LightGBM] [Info] Start training from score 2184.956129
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.373184 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 814
[LightGBM] [Info] Number of data points in the train set: 5455, number of used features: 39
[LightGBM] [Info] Start training from score 2188.145782
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
0:	learn: 1634.0394294	total: 48.5ms	remaining: 3.59s
1:	learn: 1595.0287268	total: 178ms	remaining: 6.48s
2:	learn: 1561.8975462	total: 270ms	remaining: 6.47s
3:	learn: 1525.6800801	total: 410ms	remaining: 7.27s
4:	learn: 1491.6081737	total: 509ms	remaining: 7.13s
5:	learn: 1458.3314114	total: 524ms	remaining: 6.02s
6:	learn: 1428.7820956	total: 591ms	remaining: 5.75s
7:	learn: 1401.7175699	total: 685ms	remaining: 5.74s
8:	learn: 1376.4444399	total: 748ms	remaining: 5.49s
9:	learn: 1350.8924013	total: 836ms	remaining: 5.43s
10:	learn: 1329.4573586	total: 915ms	remaining: 5.33s
11:	learn: 1308.5372202	total: 958ms	remaining: 5.03s
12:	learn: 1289.8647751	total: 1.02s	remaining: 4.89s
13:	learn: 1272.0501203	total: 1.14s	remaining: 4.98s
14:	learn: 1255.2771157	total: 1.25s	remaining: 5s
15:	learn: 1242.6914253	total: 1.26s	remaining: 4.64s
16:	learn: 1228.6150748	total: 1.32s	remaining: 4.5s
17:	learn: 1214.7727967	total: 1.37s	remaining: 4.34s
18:	learn: 1203.6857616	total: 1.39s	remaining: 4.08s
19:	learn: 1191.2466274	total: 1.41s	remaining: 3.87s
20:	learn: 1182.4339705	total: 1.41s	remaining: 3.63s
21:	learn: 1172.3446048	total: 1.42s	remaining: 3.42s
22:	learn: 1163.1933980	total: 1.44s	remaining: 3.25s
23:	learn: 1154.7601846	total: 1.44s	remaining: 3.07s
24:	learn: 1147.4595159	total: 1.47s	remaining: 2.94s
25:	learn: 1140.6269895	total: 1.5s	remaining: 2.83s
26:	learn: 1135.1332950	total: 1.66s	remaining: 2.95s
27:	learn: 1129.7544604	total: 1.68s	remaining: 2.82s
28:	learn: 1125.2061450	total: 1.72s	remaining: 2.73s
29:	learn: 1120.0484711	total: 1.76s	remaining: 2.64s
30:	learn: 1115.9646688	total: 1.81s	remaining: 2.58s
31:	learn: 1111.9415710	total: 1.82s	remaining: 2.45s
32:	learn: 1108.0502047	total: 1.91s	remaining: 2.43s
33:	learn: 1104.4474651	total: 1.92s	remaining: 2.31s
34:	learn: 1101.8531007	total: 1.99s	remaining: 2.27s
35:	learn: 1099.0893172	total: 2.03s	remaining: 2.2s
36:	learn: 1095.2976242	total: 2.04s	remaining: 2.09s
37:	learn: 1092.0705301	total: 2.06s	remaining: 2.01s
38:	learn: 1089.0756515	total: 2.23s	remaining: 2.06s
39:	learn: 1087.1242842	total: 2.27s	remaining: 1.98s
40:	learn: 1085.1413769	total: 2.31s	remaining: 1.92s
41:	learn: 1082.4860165	total: 2.37s	remaining: 1.86s
42:	learn: 1080.9174544	total: 2.43s	remaining: 1.81s
43:	learn: 1079.4427850	total: 2.44s	remaining: 1.72s
44:	learn: 1077.7045256	total: 2.47s	remaining: 1.65s
45:	learn: 1076.2340253	total: 2.56s	remaining: 1.62s
46:	learn: 1075.2218870	total: 2.65s	remaining: 1.58s
47:	learn: 1073.4118724	total: 2.85s	remaining: 1.6s
48:	learn: 1072.0822928	total: 3.02s	remaining: 1.6s
49:	learn: 1070.7430755	total: 3.07s	remaining: 1.53s
50:	learn: 1069.8588077	total: 3.15s	remaining: 1.48s
51:	learn: 1068.8348080	total: 3.26s	remaining: 1.44s
52:	learn: 1067.9129924	total: 3.39s	remaining: 1.41s
53:	learn: 1066.8332418	total: 3.47s	remaining: 1.35s
54:	learn: 1066.1729695	total: 3.55s	remaining: 1.29s
55:	learn: 1065.2322178	total: 3.61s	remaining: 1.23s
56:	learn: 1064.3821359	total: 3.65s	remaining: 1.15s
57:	learn: 1063.8470234	total: 3.71s	remaining: 1.09s
58:	learn: 1063.1514998	total: 3.78s	remaining: 1.02s
59:	learn: 1062.6305966	total: 3.83s	remaining: 956ms
60:	learn: 1061.7506149	total: 3.91s	remaining: 898ms
61:	learn: 1061.1603310	total: 3.96s	remaining: 830ms
62:	learn: 1060.5664906	total: 4.08s	remaining: 777ms
63:	learn: 1060.0463852	total: 4.09s	remaining: 703ms
64:	learn: 1059.6599102	total: 4.18s	remaining: 643ms
65:	learn: 1059.4040733	total: 4.3s	remaining: 587ms
66:	learn: 1059.0384721	total: 4.36s	remaining: 521ms
67:	learn: 1058.7652297	total: 4.43s	remaining: 456ms
68:	learn: 1058.1432585	total: 4.49s	remaining: 391ms
69:	learn: 1057.7579711	total: 4.54s	remaining: 325ms
70:	learn: 1057.4104145	total: 4.61s	remaining: 260ms
71:	learn: 1056.6865726	total: 4.67s	remaining: 195ms
72:	learn: 1056.3721811	total: 4.75s	remaining: 130ms
73:	learn: 1056.1275382	total: 4.8s	remaining: 64.8ms
74:	learn: 1055.3552042	total: 4.86s	remaining: 0us
0:	learn: 1657.8003928	total: 38.7ms	remaining: 2.87s
1:	learn: 1614.1117031	total: 117ms	remaining: 4.28s
2:	learn: 1573.9100047	total: 196ms	remaining: 4.69s
3:	learn: 1537.2647874	total: 264ms	remaining: 4.68s
4:	learn: 1502.1790714	total: 321ms	remaining: 4.5s
5:	learn: 1470.3825063	total: 373ms	remaining: 4.29s
6:	learn: 1438.0095723	total: 480ms	remaining: 4.66s
7:	learn: 1409.8921456	total: 577ms	remaining: 4.83s
8:	learn: 1386.6574622	total: 639ms	remaining: 4.69s
9:	learn: 1362.3736877	total: 727ms	remaining: 4.73s
10:	learn: 1338.6905818	total: 771ms	remaining: 4.49s
11:	learn: 1319.1057199	total: 816ms	remaining: 4.28s
12:	learn: 1299.6646497	total: 1.02s	remaining: 4.88s
13:	learn: 1281.5992392	total: 1.08s	remaining: 4.72s
14:	learn: 1264.8477811	total: 1.29s	remaining: 5.17s
15:	learn: 1251.7737470	total: 1.34s	remaining: 4.95s
16:	learn: 1237.2908127	total: 1.42s	remaining: 4.84s
17:	learn: 1225.5474374	total: 1.52s	remaining: 4.82s
18:	learn: 1213.2693145	total: 1.58s	remaining: 4.66s
19:	learn: 1201.2049202	total: 1.6s	remaining: 4.4s
20:	learn: 1191.9521165	total: 1.64s	remaining: 4.2s
21:	learn: 1181.0123834	total: 1.7s	remaining: 4.1s
22:	learn: 1172.1761109	total: 1.73s	remaining: 3.91s
23:	learn: 1164.3585598	total: 1.93s	remaining: 4.11s
24:	learn: 1157.4007779	total: 1.99s	remaining: 3.99s
25:	learn: 1150.1398825	total: 2.09s	remaining: 3.94s
26:	learn: 1143.4043321	total: 2.19s	remaining: 3.89s
27:	learn: 1138.6100896	total: 2.28s	remaining: 3.83s
28:	learn: 1132.0308325	total: 2.42s	remaining: 3.85s
29:	learn: 1128.2955805	total: 2.46s	remaining: 3.69s
30:	learn: 1123.9924173	total: 2.56s	remaining: 3.63s
31:	learn: 1118.8140894	total: 2.58s	remaining: 3.47s
32:	learn: 1115.5569460	total: 2.62s	remaining: 3.33s
33:	learn: 1112.5410547	total: 2.7s	remaining: 3.25s
34:	learn: 1108.4539062	total: 2.83s	remaining: 3.23s
35:	learn: 1105.4942227	total: 2.88s	remaining: 3.12s
36:	learn: 1102.2440101	total: 2.97s	remaining: 3.05s
37:	learn: 1098.9249944	total: 3.02s	remaining: 2.94s
38:	learn: 1096.6540099	total: 3.15s	remaining: 2.91s
39:	learn: 1095.1615698	total: 3.26s	remaining: 2.85s
40:	learn: 1092.6472184	total: 3.27s	remaining: 2.71s
41:	learn: 1091.4662700	total: 3.37s	remaining: 2.65s
42:	learn: 1089.1079867	total: 3.48s	remaining: 2.59s
43:	learn: 1087.0134785	total: 3.51s	remaining: 2.47s
44:	learn: 1085.2590324	total: 3.59s	remaining: 2.39s
45:	learn: 1084.1667352	total: 3.67s	remaining: 2.31s
46:	learn: 1083.1673375	total: 3.7s	remaining: 2.2s
47:	learn: 1082.3850223	total: 3.77s	remaining: 2.12s
48:	learn: 1081.2267112	total: 3.78s	remaining: 2.01s
49:	learn: 1079.9713607	total: 3.83s	remaining: 1.91s
50:	learn: 1078.6573182	total: 3.86s	remaining: 1.81s
51:	learn: 1077.2736266	total: 3.9s	remaining: 1.73s
52:	learn: 1075.9856018	total: 3.99s	remaining: 1.66s
53:	learn: 1075.2836958	total: 4.09s	remaining: 1.59s
54:	learn: 1074.5035065	total: 4.16s	remaining: 1.51s
55:	learn: 1073.6711417	total: 4.21s	remaining: 1.43s
56:	learn: 1072.9840429	total: 4.25s	remaining: 1.34s
57:	learn: 1071.8712925	total: 4.27s	remaining: 1.25s
58:	learn: 1071.3515407	total: 4.35s	remaining: 1.18s
59:	learn: 1070.7348924	total: 4.38s	remaining: 1.09s
60:	learn: 1070.1758111	total: 4.42s	remaining: 1.01s
61:	learn: 1069.5396371	total: 4.47s	remaining: 938ms
62:	learn: 1069.1458324	total: 4.52s	remaining: 861ms
63:	learn: 1068.8061679	total: 4.6s	remaining: 790ms
64:	learn: 1068.3278207	total: 4.65s	remaining: 715ms
65:	learn: 1067.4752095	total: 4.84s	remaining: 660ms
66:	learn: 1067.1131343	total: 4.88s	remaining: 583ms
67:	learn: 1066.3470253	total: 4.98s	remaining: 513ms
68:	learn: 1065.6539497	total: 5.04s	remaining: 438ms
69:	learn: 1064.8825053	total: 5.15s	remaining: 368ms
70:	learn: 1064.5950353	total: 5.18s	remaining: 292ms
71:	learn: 1064.1821227	total: 5.27s	remaining: 219ms
72:	learn: 1063.7692547	total: 5.31s	remaining: 146ms
73:	learn: 1063.2992299	total: 5.42s	remaining: 73.3ms
74:	learn: 1062.9366133	total: 5.44s	remaining: 0us
0:	learn: 1664.7490888	total: 84.6ms	remaining: 6.26s
1:	learn: 1620.0471540	total: 145ms	remaining: 5.31s
2:	learn: 1579.7530762	total: 227ms	remaining: 5.46s
3:	learn: 1542.0608557	total: 301ms	remaining: 5.34s
4:	learn: 1507.0374418	total: 344ms	remaining: 4.82s
5:	learn: 1474.3378641	total: 418ms	remaining: 4.8s
6:	learn: 1442.3133653	total: 475ms	remaining: 4.62s
7:	learn: 1414.1206129	total: 527ms	remaining: 4.41s
8:	learn: 1388.5910562	total: 593ms	remaining: 4.35s
9:	learn: 1364.0975616	total: 659ms	remaining: 4.28s
10:	learn: 1344.1346143	total: 700ms	remaining: 4.07s
11:	learn: 1323.1297412	total: 738ms	remaining: 3.88s
12:	learn: 1303.6036227	total: 767ms	remaining: 3.66s
13:	learn: 1287.4148131	total: 832ms	remaining: 3.62s
14:	learn: 1271.5206881	total: 908ms	remaining: 3.63s
15:	learn: 1256.1308359	total: 928ms	remaining: 3.42s
16:	learn: 1241.3663763	total: 990ms	remaining: 3.38s
17:	learn: 1227.7929233	total: 1.04s	remaining: 3.3s
18:	learn: 1217.0886777	total: 1.11s	remaining: 3.28s

19:	learn: 1205.4676439	total: 1.14s	remaining: 3.12s
20:	learn: 1194.1191799	total: 1.35s	remaining: 3.47s
21:	learn: 1183.5800124	total: 1.4s	remaining: 3.36s
22:	learn: 1176.0087248	total: 1.48s	remaining: 3.33s
23:	learn: 1167.6402949	total: 1.56s	remaining: 3.31s
24:	learn: 1160.1755179	total: 1.59s	remaining: 3.18s
25:	learn: 1152.5990053	total: 1.63s	remaining: 3.07s
26:	learn: 1146.1505719	total: 1.68s	remaining: 2.99s
27:	learn: 1140.3996821	total: 1.75s	remaining: 2.94s
28:	learn: 1134.7308656	total: 1.82s	remaining: 2.89s
29:	learn: 1130.1550136	total: 1.88s	remaining: 2.82s
30:	learn: 1125.3433263	total: 1.99s	remaining: 2.82s
31:	learn: 1121.8566036	total: 2.08s	remaining: 2.79s
32:	learn: 1118.0082730	total: 2.15s	remaining: 2.74s
33:	learn: 1114.5557080	total: 2.2s	remaining: 2.65s
34:	learn: 1111.3681902	total: 2.3s	remaining: 2.63s
35:	learn: 1107.8317920	total: 2.35s	remaining: 2.55s
36:	learn: 1105.2790212	total: 2.38s	remaining: 2.44s
37:	learn: 1103.1712874	total: 2.46s	remaining: 2.4s
38:	learn: 1100.3266153	total: 2.52s	remaining: 2.33s
39:	learn: 1098.5330675	total: 2.57s	remaining: 2.25s
40:	learn: 1097.2298181	total: 2.69s	remaining: 2.23s
41:	learn: 1095.1173227	total: 2.75s	remaining: 2.16s
42:	learn: 1093.8435817	total: 2.82s	remaining: 2.1s
43:	learn: 1091.8653162	total: 2.91s	remaining: 2.05s
44:	learn: 1090.3414859	total: 3.03s	remaining: 2.02s
45:	learn: 1088.6569295	total: 3.09s	remaining: 1.95s
46:	learn: 1087.6902253	total: 3.14s	remaining: 1.87s
47:	learn: 1086.6507624	total: 3.21s	remaining: 1.8s
48:	learn: 1085.5533103	total: 3.29s	remaining: 1.75s
49:	learn: 1084.3109709	total: 3.38s	remaining: 1.69s
50:	learn: 1083.4899932	total: 3.45s	remaining: 1.63s
51:	learn: 1082.4934636	total: 3.56s	remaining: 1.58s
52:	learn: 1081.2346336	total: 3.64s	remaining: 1.51s
53:	learn: 1080.4094181	total: 3.66s	remaining: 1.42s
54:	learn: 1079.8912543	total: 3.8s	remaining: 1.38s
55:	learn: 1079.0392377	total: 3.88s	remaining: 1.32s
56:	learn: 1078.2977355	total: 3.9s	remaining: 1.23s
57:	learn: 1077.7153268	total: 4.02s	remaining: 1.18s
58:	learn: 1076.7031354	total: 4.08s	remaining: 1.11s
59:	learn: 1075.9196470	total: 4.17s	remaining: 1.04s
60:	learn: 1075.2641839	total: 4.24s	remaining: 972ms
61:	learn: 1074.7870100	total: 4.25s	remaining: 891ms
62:	learn: 1074.0651943	total: 4.39s	remaining: 837ms
63:	learn: 1073.4178836	total: 4.46s	remaining: 766ms
64:	learn: 1072.9762292	total: 4.53s	remaining: 696ms
65:	learn: 1072.8797886	total: 4.58s	remaining: 624ms
66:	learn: 1072.3704413	total: 4.72s	remaining: 564ms
67:	learn: 1071.8203661	total: 4.79s	remaining: 494ms
68:	learn: 1071.2095791	total: 4.86s	remaining: 423ms
69:	learn: 1070.8329372	total: 4.94s	remaining: 353ms
70:	learn: 1070.3867194	total: 5.02s	remaining: 283ms
71:	learn: 1070.2268005	total: 5.12s	remaining: 213ms
72:	learn: 1070.0472514	total: 5.17s	remaining: 142ms
73:	learn: 1069.7603224	total: 5.22s	remaining: 70.5ms
74:	learn: 1069.5710555	total: 5.32s	remaining: 0us
0:	learn: 1655.0962605	total: 110ms	remaining: 8.14s
1:	learn: 1611.6668413	total: 337ms	remaining: 12.3s
2:	learn: 1570.1174032	total: 434ms	remaining: 10.4s
3:	learn: 1532.9761785	total: 498ms	remaining: 8.83s
4:	learn: 1497.8281274	total: 563ms	remaining: 7.88s
5:	learn: 1468.6474632	total: 609ms	remaining: 7s
6:	learn: 1441.6638036	total: 703ms	remaining: 6.83s
7:	learn: 1412.9520777	total: 789ms	remaining: 6.6s
8:	learn: 1385.4384686	total: 875ms	remaining: 6.42s
9:	learn: 1361.7902988	total: 995ms	remaining: 6.47s
10:	learn: 1338.6153920	total: 1.04s	remaining: 6.04s
11:	learn: 1315.8931924	total: 1.07s	remaining: 5.63s
12:	learn: 1296.2723606	total: 1.12s	remaining: 5.36s
13:	learn: 1277.5816529	total: 1.18s	remaining: 5.13s
14:	learn: 1260.6888542	total: 1.33s	remaining: 5.3s
15:	learn: 1245.9943121	total: 1.35s	remaining: 4.99s
16:	learn: 1230.6432325	total: 1.44s	remaining: 4.9s
17:	learn: 1217.0836636	total: 1.52s	remaining: 4.81s
18:	learn: 1203.7976232	total: 1.57s	remaining: 4.64s
19:	learn: 1193.1672593	total: 1.62s	remaining: 4.46s
20:	learn: 1182.0596280	total: 1.69s	remaining: 4.36s
21:	learn: 1172.8152482	total: 1.77s	remaining: 4.27s
22:	learn: 1163.1682442	total: 1.86s	remaining: 4.2s
23:	learn: 1154.5955839	total: 1.93s	remaining: 4.1s
24:	learn: 1147.6495919	total: 1.98s	remaining: 3.96s
25:	learn: 1140.2742058	total: 2s	remaining: 3.77s
26:	learn: 1134.6115874	total: 2.11s	remaining: 3.75s
27:	learn: 1128.3303157	total: 2.19s	remaining: 3.69s
28:	learn: 1123.5304027	total: 2.23s	remaining: 3.54s
29:	learn: 1119.2110376	total: 2.28s	remaining: 3.42s
30:	learn: 1114.6935728	total: 2.38s	remaining: 3.37s
31:	learn: 1110.8204338	total: 2.44s	remaining: 3.28s
32:	learn: 1106.6012951	total: 2.51s	remaining: 3.19s
33:	learn: 1102.6125166	total: 2.56s	remaining: 3.08s
34:	learn: 1099.1036734	total: 2.63s	remaining: 3s
35:	learn: 1096.2247706	total: 2.7s	remaining: 2.92s
36:	learn: 1092.9362890	total: 2.74s	remaining: 2.82s
37:	learn: 1090.6125796	total: 2.78s	remaining: 2.71s
38:	learn: 1088.5245424	total: 2.88s	remaining: 2.66s
39:	learn: 1086.2180373	total: 2.94s	remaining: 2.57s
40:	learn: 1084.6257483	total: 3s	remaining: 2.49s
41:	learn: 1082.7816013	total: 3.08s	remaining: 2.42s
42:	learn: 1080.6472248	total: 3.13s	remaining: 2.33s
43:	learn: 1079.2618067	total: 3.24s	remaining: 2.28s
44:	learn: 1077.7142942	total: 3.3s	remaining: 2.2s
45:	learn: 1076.1975419	total: 3.36s	remaining: 2.12s
46:	learn: 1074.8968273	total: 3.4s	remaining: 2.02s
47:	learn: 1073.7946518	total: 3.43s	remaining: 1.93s
48:	learn: 1072.3672109	total: 3.5s	remaining: 1.86s
49:	learn: 1071.1570435	total: 3.62s	remaining: 1.81s
50:	learn: 1070.2420427	total: 3.66s	remaining: 1.72s
51:	learn: 1069.4539637	total: 3.72s	remaining: 1.65s
52:	learn: 1068.8709131	total: 3.79s	remaining: 1.57s
53:	learn: 1068.0518586	total: 3.88s	remaining: 1.51s
54:	learn: 1066.9157277	total: 3.89s	remaining: 1.42s
55:	learn: 1066.2737895	total: 3.9s	remaining: 1.32s
56:	learn: 1065.6048818	total: 3.9s	remaining: 1.23s
57:	learn: 1064.8641415	total: 3.91s	remaining: 1.15s
58:	learn: 1064.2793901	total: 3.92s	remaining: 1.06s
59:	learn: 1063.8193172	total: 3.93s	remaining: 983ms
60:	learn: 1063.2383530	total: 3.94s	remaining: 904ms
61:	learn: 1062.6511627	total: 4.04s	remaining: 846ms
62:	learn: 1061.9209316	total: 4.05s	remaining: 771ms
63:	learn: 1061.3154914	total: 4.12s	remaining: 708ms
64:	learn: 1060.8889537	total: 4.18s	remaining: 643ms
65:	learn: 1060.0991801	total: 4.24s	remaining: 579ms
66:	learn: 1059.2391504	total: 4.3s	remaining: 513ms
67:	learn: 1058.9167352	total: 4.37s	remaining: 450ms
68:	learn: 1058.4083565	total: 4.41s	remaining: 384ms
69:	learn: 1057.8783770	total: 4.51s	remaining: 322ms
70:	learn: 1057.3155562	total: 4.56s	remaining: 257ms
71:	learn: 1056.9550160	total: 4.63s	remaining: 193ms
72:	learn: 1056.7129207	total: 4.69s	remaining: 129ms
73:	learn: 1056.4332140	total: 4.75s	remaining: 64.2ms
74:	learn: 1056.1932451	total: 4.79s	remaining: 0us
0:	learn: 1644.7095411	total: 99.9ms	remaining: 7.39s
1:	learn: 1603.2660682	total: 171ms	remaining: 6.23s
2:	learn: 1561.8505237	total: 238ms	remaining: 5.71s
3:	learn: 1526.3002886	total: 291ms	remaining: 5.16s
4:	learn: 1492.8292411	total: 342ms	remaining: 4.79s
5:	learn: 1460.6620862	total: 405ms	remaining: 4.66s
6:	learn: 1429.5507479	total: 461ms	remaining: 4.48s
7:	learn: 1402.6805362	total: 539ms	remaining: 4.51s
8:	learn: 1380.7098180	total: 551ms	remaining: 4.04s
9:	learn: 1355.4350491	total: 611ms	remaining: 3.97s
10:	learn: 1333.0911845	total: 725ms	remaining: 4.22s
11:	learn: 1311.5449435	total: 799ms	remaining: 4.2s
12:	learn: 1293.0370886	total: 869ms	remaining: 4.14s
13:	learn: 1275.4897230	total: 989ms	remaining: 4.31s
14:	learn: 1259.2001474	total: 1.13s	remaining: 4.52s
15:	learn: 1243.7599495	total: 1.32s	remaining: 4.89s
16:	learn: 1230.6384645	total: 1.4s	remaining: 4.76s
17:	learn: 1217.9244083	total: 1.44s	remaining: 4.55s
18:	learn: 1206.3845627	total: 1.55s	remaining: 4.58s
19:	learn: 1197.1787294	total: 1.64s	remaining: 4.5s
20:	learn: 1188.1472782	total: 1.72s	remaining: 4.43s
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

21:	learn: 1179.8317639	total: 1.83s	remaining: 4.41s
22:	learn: 1170.6839184	total: 1.89s	remaining: 4.27s
23:	learn: 1162.6119142	total: 1.98s	remaining: 4.22s
24:	learn: 1154.6720342	total: 2.03s	remaining: 4.05s
25:	learn: 1147.6725707	total: 2.11s	remaining: 3.98s
26:	learn: 1141.1990725	total: 2.15s	remaining: 3.83s
27:	learn: 1135.1958809	total: 2.2s	remaining: 3.7s
28:	learn: 1130.3418594	total: 2.25s	remaining: 3.57s
29:	learn: 1126.1698903	total: 2.29s	remaining: 3.44s
30:	learn: 1121.0851065	total: 2.35s	remaining: 3.33s
31:	learn: 1116.7105598	total: 2.49s	remaining: 3.34s
32:	learn: 1113.0188550	total: 2.53s	remaining: 3.22s
33:	learn: 1109.9999141	total: 2.67s	remaining: 3.22s
34:	learn: 1106.1113497	total: 2.75s	remaining: 3.14s
35:	learn: 1103.4789116	total: 2.88s	remaining: 3.12s
36:	learn: 1100.4063922	total: 3.01s	remaining: 3.09s
37:	learn: 1098.1545310	total: 3.06s	remaining: 2.98s
38:	learn: 1095.5325134	total: 3.19s	remaining: 2.94s
39:	learn: 1093.0722889	total: 3.41s	remaining: 2.98s
40:	learn: 1090.5671622	total: 3.53s	remaining: 2.93s
41:	learn: 1088.7602715	total: 3.6s	remaining: 2.83s
42:	learn: 1087.4483663	total: 3.65s	remaining: 2.72s
43:	learn: 1086.0083581	total: 3.7s	remaining: 2.61s
44:	learn: 1084.4919497	total: 3.76s	remaining: 2.51s
45:	learn: 1082.7699873	total: 3.87s	remaining: 2.44s
46:	learn: 1081.6761994	total: 3.93s	remaining: 2.34s
47:	learn: 1080.5824306	total: 4.01s	remaining: 2.25s
48:	learn: 1079.5568499	total: 4.05s	remaining: 2.15s
49:	learn: 1078.3803310	total: 4.11s	remaining: 2.05s
50:	learn: 1077.3080913	total: 4.19s	remaining: 1.97s
51:	learn: 1076.4705467	total: 4.25s	remaining: 1.88s
52:	learn: 1075.4687767	total: 4.3s	remaining: 1.79s
53:	learn: 1074.7662690	total: 4.35s	remaining: 1.69s
54:	learn: 1073.8689822	total: 4.42s	remaining: 1.61s
55:	learn: 1072.9830562	total: 4.51s	remaining: 1.53s
56:	learn: 1072.1205148	total: 4.56s	remaining: 1.44s
57:	learn: 1070.9172785	total: 4.66s	remaining: 1.37s
58:	learn: 1070.2407668	total: 4.71s	remaining: 1.28s
59:	learn: 1069.7418749	total: 4.76s	remaining: 1.19s
60:	learn: 1068.9470182	total: 4.81s	remaining: 1.1s
61:	learn: 1068.4451451	total: 4.85s	remaining: 1.02s
62:	learn: 1067.9875917	total: 5s	remaining: 952ms
63:	learn: 1067.5773593	total: 5.05s	remaining: 868ms
64:	learn: 1067.0480290	total: 5.11s	remaining: 786ms
65:	learn: 1066.4217419	total: 5.17s	remaining: 705ms
66:	learn: 1066.1097696	total: 5.24s	remaining: 626ms
67:	learn: 1065.6398770	total: 5.3s	remaining: 546ms
68:	learn: 1065.2785397	total: 5.32s	remaining: 463ms
69:	learn: 1064.7872410	total: 5.43s	remaining: 388ms
70:	learn: 1064.2905154	total: 5.48s	remaining: 309ms
71:	learn: 1063.6508769	total: 5.59s	remaining: 233ms
72:	learn: 1063.1823117	total: 5.67s	remaining: 155ms
73:	learn: 1062.7784336	total: 5.73s	remaining: 77.4ms
74:	learn: 1062.4822100	total: 5.82s	remaining: 0us
[CV] END stack__CAT__learning_rate=0.05, stack__CAT__max_depth=6, stack__CAT__n_estimators=75, stack__LGBM__learning_rate=0.05, stack__LGBM__max_depth=4, stack__LGBM__n_estimators=75, stack__XGB__learning_rate=0.3, stack__XGB__max_depth=6, stack__XGB__n_estimators=100, stack__final_estimator__max_depth=6, stack__final_estimator__n_estimators=100; total time=26.1min
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.247192 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 816
[LightGBM] [Info] Number of data points in the train set: 6818, number of used features: 39
[LightGBM] [Info] Start training from score 2159.816823
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.289126 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 813
[LightGBM] [Info] Number of data points in the train set: 5455, number of used features: 39
[LightGBM] [Info] Start training from score 2175.226332
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.249278 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 812
[LightGBM] [Info] Number of data points in the train set: 5455, number of used features: 39
[LightGBM] [Info] Start training from score 2198.135467
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.253309 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 818
[LightGBM] [Info] Number of data points in the train set: 5455, number of used features: 39
[LightGBM] [Info] Start training from score 2190.691077
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.238101 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 813
[LightGBM] [Info] Number of data points in the train set: 5455, number of used features: 39
[LightGBM] [Info] Start training from score 2162.504121
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.289126 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 814
[LightGBM] [Info] Number of data points in the train set: 5455, number of used features: 39
[LightGBM] [Info] Start training from score 2173.197686
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
0:	learn: 1660.7169807	total: 75.3ms	remaining: 5.58s
1:	learn: 1615.6038769	total: 142ms	remaining: 5.18s
2:	learn: 1574.7079424	total: 205ms	remaining: 4.93s
3:	learn: 1538.3383496	total: 239ms	remaining: 4.24s
4:	learn: 1501.3988808	total: 325ms	remaining: 4.55s
5:	learn: 1469.5883719	total: 359ms	remaining: 4.13s
6:	learn: 1442.9496826	total: 455ms	remaining: 4.42s
7:	learn: 1417.4842543	total: 510ms	remaining: 4.27s
8:	learn: 1389.0248420	total: 601ms	remaining: 4.41s
9:	learn: 1362.6233036	total: 616ms	remaining: 4s
10:	learn: 1339.4285482	total: 788ms	remaining: 4.58s
11:	learn: 1321.1131781	total: 831ms	remaining: 4.36s
12:	learn: 1301.7810360	total: 896ms	remaining: 4.28s
13:	learn: 1283.9539484	total: 936ms	remaining: 4.08s
14:	learn: 1265.6403817	total: 952ms	remaining: 3.81s
15:	learn: 1249.3924949	total: 1.06s	remaining: 3.9s
16:	learn: 1234.4034765	total: 1.08s	remaining: 3.7s
17:	learn: 1221.1236784	total: 1.2s	remaining: 3.8s
18:	learn: 1209.1449141	total: 1.21s	remaining: 3.57s
19:	learn: 1197.4895621	total: 1.26s	remaining: 3.48s
20:	learn: 1186.6444970	total: 1.33s	remaining: 3.42s
21:	learn: 1176.7625625	total: 1.39s	remaining: 3.34s
22:	learn: 1167.6680105	total: 1.48s	remaining: 3.35s
23:	learn: 1158.8928972	total: 1.54s	remaining: 3.28s
24:	learn: 1150.6427183	total: 1.59s	remaining: 3.17s
25:	learn: 1143.7700688	total: 1.68s	remaining: 3.17s
26:	learn: 1137.1181380	total: 1.73s	remaining: 3.07s
27:	learn: 1131.3176519	total: 1.81s	remaining: 3.04s
28:	learn: 1125.8154576	total: 1.86s	remaining: 2.95s
29:	learn: 1121.4883414	total: 1.92s	remaining: 2.89s
30:	learn: 1117.0575144	total: 2.06s	remaining: 2.92s
31:	learn: 1112.2607453	total: 2.13s	remaining: 2.86s
32:	learn: 1108.5833405	total: 2.21s	remaining: 2.81s
33:	learn: 1104.7640388	total: 2.29s	remaining: 2.76s
34:	learn: 1101.6378594	total: 2.35s	remaining: 2.69s
35:	learn: 1098.3835165	total: 2.4s	remaining: 2.6s
36:	learn: 1095.7516042	total: 2.48s	remaining: 2.55s
37:	learn: 1092.8376656	total: 2.53s	remaining: 2.46s
38:	learn: 1090.6923564	total: 2.6s	remaining: 2.4s
39:	learn: 1088.4421576	total: 2.64s	remaining: 2.31s
40:	learn: 1087.0087893	total: 2.71s	remaining: 2.25s
41:	learn: 1085.1775788	total: 2.77s	remaining: 2.18s
42:	learn: 1084.0283719	total: 2.8s	remaining: 2.08s
43:	learn: 1082.7212007	total: 2.88s	remaining: 2.02s
44:	learn: 1081.3381837	total: 2.91s	remaining: 1.94s
45:	learn: 1079.7805450	total: 3.01s	remaining: 1.9s
46:	learn: 1078.6270595	total: 3.07s	remaining: 1.83s
47:	learn: 1077.3645375	total: 3.21s	remaining: 1.81s
48:	learn: 1076.0814288	total: 3.26s	remaining: 1.73s
49:	learn: 1075.0518648	total: 3.4s	remaining: 1.7s
50:	learn: 1073.6570211	total: 3.47s	remaining: 1.63s
51:	learn: 1072.6897291	total: 3.58s	remaining: 1.58s
52:	learn: 1071.9064817	total: 3.66s	remaining: 1.52s
53:	learn: 1071.4005461	total: 3.73s	remaining: 1.45s
54:	learn: 1070.6647545	total: 3.87s	remaining: 1.41s
55:	learn: 1070.1149311	total: 3.95s	remaining: 1.34s
56:	learn: 1069.2992667	total: 4.02s	remaining: 1.27s
57:	learn: 1068.7052059	total: 4.09s	remaining: 1.2s
58:	learn: 1068.2348366	total: 4.12s	remaining: 1.12s
59:	learn: 1067.9303427	total: 4.18s	remaining: 1.04s
60:	learn: 1067.0569008	total: 4.25s	remaining: 976ms
61:	learn: 1066.5889695	total: 4.37s	remaining: 916ms
62:	learn: 1066.3503137	total: 4.41s	remaining: 840ms
63:	learn: 1065.2282592	total: 4.47s	remaining: 769ms
64:	learn: 1064.7318629	total: 4.61s	remaining: 709ms
65:	learn: 1064.2550681	total: 4.66s	remaining: 636ms
66:	learn: 1063.7037384	total: 4.73s	remaining: 565ms
67:	learn: 1063.0362835	total: 4.75s	remaining: 489ms
68:	learn: 1062.2906473	total: 4.78s	remaining: 416ms
69:	learn: 1062.0215614	total: 4.88s	remaining: 348ms
70:	learn: 1061.7008632	total: 4.93s	remaining: 278ms
71:	learn: 1061.3613181	total: 4.98s	remaining: 208ms
72:	learn: 1061.2061931	total: 5.05s	remaining: 138ms
73:	learn: 1060.9720055	total: 5.12s	remaining: 69.2ms
74:	learn: 1060.6090440	total: 5.19s	remaining: 0us
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.256896 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 816
[LightGBM] [Info] Number of data points in the train set: 5454, number of used features: 39
[LightGBM] [Info] Start training from score 2147.784860
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.245760 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 815
[LightGBM] [Info] Number of data points in the train set: 5455, number of used features: 39
[LightGBM] [Info] Start training from score 2185.850083
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.245253 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 818
[LightGBM] [Info] Number of data points in the train set: 5456, number of used features: 39
[LightGBM] [Info] Start training from score 2199.213061
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.300243 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 818
[LightGBM] [Info] Number of data points in the train set: 5456, number of used features: 39
[LightGBM] [Info] Start training from score 2196.918271
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.227087 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 818
[LightGBM] [Info] Number of data points in the train set: 5455, number of used features: 39
[LightGBM] [Info] Start training from score 2159.055387
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.249325 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 814
[LightGBM] [Info] Number of data points in the train set: 5455, number of used features: 39
[LightGBM] [Info] Start training from score 2188.145782
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
0:	learn: 1543.7664909	total: 144ms	remaining: 10.7s
1:	learn: 1402.8481272	total: 292ms	remaining: 10.6s
2:	learn: 1301.6944995	total: 434ms	remaining: 10.4s
3:	learn: 1230.5106674	total: 506ms	remaining: 8.97s
4:	learn: 1186.3101495	total: 651ms	remaining: 9.12s
5:	learn: 1151.4509216	total: 782ms	remaining: 9s
6:	learn: 1127.6046316	total: 878ms	remaining: 8.53s
7:	learn: 1111.2186233	total: 1.1s	remaining: 9.26s
8:	learn: 1095.4895045	total: 1.26s	remaining: 9.26s
9:	learn: 1084.0350384	total: 1.39s	remaining: 9.06s
10:	learn: 1077.4830760	total: 1.52s	remaining: 8.86s
11:	learn: 1073.2062091	total: 1.69s	remaining: 8.88s
12:	learn: 1066.2869276	total: 1.86s	remaining: 8.88s
13:	learn: 1062.7970301	total: 1.99s	remaining: 8.65s
14:	learn: 1059.6334245	total: 2.1s	remaining: 8.4s
15:	learn: 1056.5977605	total: 2.27s	remaining: 8.38s
16:	learn: 1053.8581864	total: 2.39s	remaining: 8.14s
17:	learn: 1051.7261652	total: 2.46s	remaining: 7.78s
18:	learn: 1049.7414969	total: 2.59s	remaining: 7.62s
19:	learn: 1048.6145749	total: 2.71s	remaining: 7.44s
20:	learn: 1046.7249184	total: 2.9s	remaining: 7.47s
21:	learn: 1045.8560999	total: 3s	remaining: 7.23s
22:	learn: 1043.7170758	total: 3.11s	remaining: 7.02s
23:	learn: 1041.6260652	total: 3.21s	remaining: 6.83s
24:	learn: 1037.5221610	total: 3.37s	remaining: 6.74s
25:	learn: 1035.6668273	total: 3.53s	remaining: 6.65s
26:	learn: 1034.8408088	total: 3.69s	remaining: 6.55s
27:	learn: 1034.1106660	total: 3.83s	remaining: 6.42s
28:	learn: 1033.1051206	total: 3.87s	remaining: 6.13s
29:	learn: 1031.6861767	total: 3.97s	remaining: 5.95s
30:	learn: 1030.4799815	total: 4.18s	remaining: 5.93s
31:	learn: 1029.6909517	total: 4.37s	remaining: 5.87s
32:	learn: 1028.8997372	total: 4.57s	remaining: 5.81s
33:	learn: 1026.3005309	total: 4.83s	remaining: 5.83s
34:	learn: 1025.3808543	total: 4.98s	remaining: 5.7s
35:	learn: 1023.6756989	total: 5.1s	remaining: 5.53s
36:	learn: 1022.0197538	total: 5.26s	remaining: 5.4s
37:	learn: 1021.1836707	total: 5.42s	remaining: 5.28s
38:	learn: 1020.8921714	total: 5.42s	remaining: 5.01s
39:	learn: 1018.9602773	total: 5.63s	remaining: 4.93s
40:	learn: 1018.3971481	total: 5.78s	remaining: 4.79s
41:	learn: 1017.3625948	total: 5.89s	remaining: 4.63s
42:	learn: 1016.4591664	total: 6s	remaining: 4.47s
43:	learn: 1015.5912976	total: 6.17s	remaining: 4.35s
44:	learn: 1014.5175008	total: 6.28s	remaining: 4.19s
45:	learn: 1013.8766733	total: 6.4s	remaining: 4.03s
46:	learn: 1012.9302783	total: 6.58s	remaining: 3.92s
47:	learn: 1011.9856056	total: 6.68s	remaining: 3.76s
48:	learn: 1010.8064944	total: 6.96s	remaining: 3.69s
49:	learn: 1009.6400384	total: 7.13s	remaining: 3.56s
50:	learn: 1008.7226128	total: 7.31s	remaining: 3.44s
51:	learn: 1007.4366365	total: 7.48s	remaining: 3.31s
52:	learn: 1006.2737600	total: 7.66s	remaining: 3.18s
53:	learn: 1005.4121165	total: 7.86s	remaining: 3.05s
54:	learn: 1004.7152233	total: 8s	remaining: 2.91s
55:	learn: 1003.6060455	total: 8.21s	remaining: 2.79s
56:	learn: 1002.6290667	total: 8.35s	remaining: 2.64s
57:	learn: 1001.8312088	total: 8.46s	remaining: 2.48s
58:	learn: 1000.9114946	total: 8.67s	remaining: 2.35s
59:	learn: 999.9344030	total: 8.9s	remaining: 2.23s
60:	learn: 998.5113676	total: 9.14s	remaining: 2.1s
61:	learn: 998.0311903	total: 9.3s	remaining: 1.95s
62:	learn: 997.0227702	total: 9.44s	remaining: 1.8s
63:	learn: 996.1128217	total: 9.53s	remaining: 1.64s
64:	learn: 995.0087956	total: 9.7s	remaining: 1.49s
65:	learn: 994.3444252	total: 9.98s	remaining: 1.36s
66:	learn: 993.8566212	total: 10.2s	remaining: 1.21s
67:	learn: 992.8185331	total: 10.3s	remaining: 1.06s
68:	learn: 992.1379777	total: 10.4s	remaining: 905ms
69:	learn: 991.7334256	total: 10.6s	remaining: 754ms
70:	learn: 990.6330054	total: 10.7s	remaining: 602ms
71:	learn: 987.8310480	total: 10.8s	remaining: 451ms
72:	learn: 987.0687080	total: 10.9s	remaining: 299ms
73:	learn: 986.1909838	total: 11s	remaining: 149ms
74:	learn: 985.3145811	total: 11.2s	remaining: 0us
0:	learn: 1543.0569201	total: 119ms	remaining: 8.78s
1:	learn: 1414.2446146	total: 295ms	remaining: 10.8s
2:	learn: 1315.9465598	total: 509ms	remaining: 12.2s
3:	learn: 1237.7200570	total: 614ms	remaining: 10.9s
4:	learn: 1191.7340854	total: 896ms	remaining: 12.5s
5:	learn: 1159.0933906	total: 1.04s	remaining: 11.9s
6:	learn: 1133.0042265	total: 1.17s	remaining: 11.3s
7:	learn: 1112.3563323	total: 1.28s	remaining: 10.7s
8:	learn: 1097.8795239	total: 1.45s	remaining: 10.6s
9:	learn: 1086.9677127	total: 1.56s	remaining: 10.2s
10:	learn: 1080.6036820	total: 1.65s	remaining: 9.57s
11:	learn: 1074.7102723	total: 1.73s	remaining: 9.08s
12:	learn: 1070.3445471	total: 1.83s	remaining: 8.72s
13:	learn: 1066.3974389	total: 1.95s	remaining: 8.5s
14:	learn: 1063.2661768	total: 2.04s	remaining: 8.17s
15:	learn: 1061.9547746	total: 2.3s	remaining: 8.5s
16:	learn: 1060.4593059	total: 2.44s	remaining: 8.32s
17:	learn: 1059.4544045	total: 2.56s	remaining: 8.11s
18:	learn: 1056.6409625	total: 2.76s	remaining: 8.13s
19:	learn: 1055.3040858	total: 2.94s	remaining: 8.08s
20:	learn: 1053.4709350	total: 3.16s	remaining: 8.12s
21:	learn: 1052.7151718	total: 3.38s	remaining: 8.15s
22:	learn: 1051.7707359	total: 3.54s	remaining: 8s
23:	learn: 1051.0712337	total: 3.77s	remaining: 8.02s
24:	learn: 1049.8804463	total: 3.96s	remaining: 7.93s
25:	learn: 1049.2537251	total: 4.02s	remaining: 7.57s
26:	learn: 1048.4027957	total: 4.21s	remaining: 7.48s
27:	learn: 1047.4899791	total: 4.34s	remaining: 7.29s
28:	learn: 1044.5847574	total: 4.54s	remaining: 7.2s
29:	learn: 1043.6668726	total: 4.61s	remaining: 6.92s
30:	learn: 1042.4937573	total: 4.84s	remaining: 6.86s
31:	learn: 1042.0235175	total: 4.89s	remaining: 6.58s
32:	learn: 1041.0798148	total: 5.11s	remaining: 6.5s
33:	learn: 1040.2800116	total: 5.22s	remaining: 6.29s
34:	learn: 1039.4556161	total: 5.31s	remaining: 6.07s
35:	learn: 1034.4452853	total: 5.49s	remaining: 5.95s
36:	learn: 1033.2237586	total: 5.62s	remaining: 5.78s
37:	learn: 1032.1329142	total: 5.74s	remaining: 5.59s
38:	learn: 1031.3828267	total: 5.96s	remaining: 5.5s
39:	learn: 1030.6875878	total: 6.09s	remaining: 5.33s
40:	learn: 1028.9969982	total: 6.25s	remaining: 5.18s
41:	learn: 1028.1478879	total: 6.4s	remaining: 5.03s
42:	learn: 1027.3268482	total: 6.53s	remaining: 4.86s
43:	learn: 1026.0639522	total: 6.67s	remaining: 4.7s
44:	learn: 1025.0605183	total: 6.79s	remaining: 4.52s
45:	learn: 1024.3583865	total: 7.03s	remaining: 4.43s
46:	learn: 1023.2875803	total: 7.17s	remaining: 4.27s
47:	learn: 1022.2243079	total: 7.31s	remaining: 4.11s
48:	learn: 1021.3836409	total: 7.46s	remaining: 3.96s
49:	learn: 1020.5403753	total: 7.63s	remaining: 3.82s
50:	learn: 1019.4818795	total: 7.85s	remaining: 3.69s
51:	learn: 1018.8532542	total: 8.01s	remaining: 3.54s
52:	learn: 1018.1942729	total: 8.18s	remaining: 3.4s
53:	learn: 1017.2881947	total: 8.36s	remaining: 3.25s
54:	learn: 1016.8252174	total: 8.53s	remaining: 3.1s
55:	learn: 1015.5519762	total: 8.7s	remaining: 2.95s
56:	learn: 1014.5712039	total: 8.87s	remaining: 2.8s
57:	learn: 1013.8643359	total: 8.96s	remaining: 2.63s
58:	learn: 1013.0540572	total: 9.2s	remaining: 2.49s
59:	learn: 1012.6358762	total: 9.31s	remaining: 2.33s
60:	learn: 1011.5827051	total: 9.43s	remaining: 2.16s
61:	learn: 1010.7463603	total: 9.55s	remaining: 2s
62:	learn: 1009.7562098	total: 9.74s	remaining: 1.86s
63:	learn: 1009.1578261	total: 9.88s	remaining: 1.7s
64:	learn: 1008.2839459	total: 9.96s	remaining: 1.53s
65:	learn: 1007.8722116	total: 10.1s	remaining: 1.38s
66:	learn: 1007.4193336	total: 10.3s	remaining: 1.23s
67:	learn: 1006.5552874	total: 10.4s	remaining: 1.07s
68:	learn: 1005.6114436	total: 10.6s	remaining: 918ms
69:	learn: 1004.8652630	total: 10.7s	remaining: 767ms
70:	learn: 1004.2041397	total: 10.9s	remaining: 612ms
71:	learn: 1003.8816599	total: 10.9s	remaining: 455ms
72:	learn: 1002.6982297	total: 11s	remaining: 302ms
73:	learn: 1001.9487865	total: 11.2s	remaining: 151ms
74:	learn: 1001.1133550	total: 11.3s	remaining: 0us

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.251642 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 816
[LightGBM] [Info] Number of data points in the train set: 5454, number of used features: 39
[LightGBM] [Info] Start training from score 2180.642468
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
0:	learn: 1543.5714374	total: 176ms	remaining: 13s
1:	learn: 1408.6830348	total: 222ms	remaining: 8.1s
2:	learn: 1309.4541824	total: 256ms	remaining: 6.14s
3:	learn: 1235.4213896	total: 417ms	remaining: 7.4s
4:	learn: 1181.2230229	total: 627ms	remaining: 8.77s
5:	learn: 1147.6221648	total: 648ms	remaining: 7.45s
6:	learn: 1122.2216005	total: 819ms	remaining: 7.96s
7:	learn: 1106.4672705	total: 879ms	remaining: 7.36s
8:	learn: 1095.8728378	total: 1.07s	remaining: 7.87s
9:	learn: 1087.0320915	total: 1.22s	remaining: 7.91s
10:	learn: 1078.6148534	total: 1.33s	remaining: 7.75s
11:	learn: 1073.8235798	total: 1.5s	remaining: 7.86s
12:	learn: 1068.6135875	total: 1.64s	remaining: 7.82s
13:	learn: 1066.0094926	total: 1.84s	remaining: 8.01s
14:	learn: 1062.3400531	total: 1.95s	remaining: 7.79s
15:	learn: 1058.7460962	total: 2.02s	remaining: 7.45s
16:	learn: 1056.3696331	total: 2.1s	remaining: 7.17s
17:	learn: 1055.1259011	total: 2.18s	remaining: 6.91s
18:	learn: 1054.1904829	total: 2.28s	remaining: 6.72s
19:	learn: 1052.0179049	total: 2.4s	remaining: 6.59s
20:	learn: 1050.0247360	total: 2.51s	remaining: 6.44s
21:	learn: 1047.4922364	total: 2.64s	remaining: 6.36s
22:	learn: 1046.8352658	total: 2.81s	remaining: 6.34s
23:	learn: 1045.9016089	total: 2.99s	remaining: 6.35s
24:	learn: 1045.1820665	total: 3.06s	remaining: 6.13s
25:	learn: 1043.9619480	total: 3.14s	remaining: 5.92s
26:	learn: 1043.5227029	total: 3.2s	remaining: 5.68s
27:	learn: 1041.1238489	total: 3.33s	remaining: 5.59s
28:	learn: 1040.3420754	total: 3.44s	remaining: 5.45s
29:	learn: 1038.9911719	total: 3.55s	remaining: 5.32s
30:	learn: 1037.1530890	total: 3.83s	remaining: 5.43s
31:	learn: 1036.3550112	total: 4s	remaining: 5.38s
32:	learn: 1035.2841538	total: 4.13s	remaining: 5.25s
33:	learn: 1034.3882621	total: 4.21s	remaining: 5.08s
34:	learn: 1032.9157419	total: 4.43s	remaining: 5.06s
35:	learn: 1031.6945671	total: 4.67s	remaining: 5.06s
36:	learn: 1030.3501906	total: 4.98s	remaining: 5.11s
37:	learn: 1030.0930302	total: 4.98s	remaining: 4.85s
38:	learn: 1029.2802253	total: 5.12s	remaining: 4.72s
39:	learn: 1028.3410164	total: 5.28s	remaining: 4.62s
40:	learn: 1027.8064106	total: 5.41s	remaining: 4.49s
41:	learn: 1026.8201697	total: 5.53s	remaining: 4.35s
42:	learn: 1026.1448941	total: 5.61s	remaining: 4.17s
43:	learn: 1024.4771734	total: 5.71s	remaining: 4.03s
44:	learn: 1023.4232767	total: 5.88s	remaining: 3.92s
45:	learn: 1022.3765148	total: 6.01s	remaining: 3.79s
46:	learn: 1021.4179621	total: 6.17s	remaining: 3.67s
47:	learn: 1020.1865044	total: 6.26s	remaining: 3.52s
48:	learn: 1019.3443837	total: 6.45s	remaining: 3.42s
49:	learn: 1018.5870134	total: 6.54s	remaining: 3.27s
50:	learn: 1017.7579120	total: 6.69s	remaining: 3.15s
51:	learn: 1016.1440791	total: 6.85s	remaining: 3.03s
52:	learn: 1015.5417895	total: 7.02s	remaining: 2.91s
53:	learn: 1014.2884260	total: 7.19s	remaining: 2.8s
54:	learn: 1013.3235071	total: 7.33s	remaining: 2.67s
55:	learn: 1012.3738232	total: 7.46s	remaining: 2.53s
56:	learn: 1011.4440547	total: 7.53s	remaining: 2.38s
57:	learn: 1010.4730898	total: 7.67s	remaining: 2.25s
58:	learn: 1009.9762484	total: 7.76s	remaining: 2.1s
59:	learn: 1009.4964771	total: 7.91s	remaining: 1.98s
60:	learn: 1008.6619180	total: 8.05s	remaining: 1.85s
61:	learn: 1007.4492813	total: 8.29s	remaining: 1.74s
62:	learn: 1007.0428882	total: 8.36s	remaining: 1.59s
63:	learn: 1006.2119875	total: 8.47s	remaining: 1.46s
64:	learn: 1005.4007365	total: 8.6s	remaining: 1.32s
65:	learn: 1004.8415493	total: 8.72s	remaining: 1.19s
66:	learn: 1004.1514595	total: 8.87s	remaining: 1.06s
67:	learn: 1003.0913217	total: 9.04s	remaining: 931ms
68:	learn: 1002.0281997	total: 9.17s	remaining: 797ms
69:	learn: 1001.6654728	total: 9.26s	remaining: 661ms
70:	learn: 1000.6250544	total: 9.41s	remaining: 530ms
71:	learn: 999.8004467	total: 9.54s	remaining: 398ms
72:	learn: 999.0425234	total: 9.64s	remaining: 264ms
73:	learn: 998.0626246	total: 9.8s	remaining: 133ms
74:	learn: 997.4578095	total: 9.97s	remaining: 0us
0:	learn: 1538.0771000	total: 182ms	remaining: 13.5s
1:	learn: 1399.7090664	total: 352ms	remaining: 12.8s
2:	learn: 1302.2389619	total: 468ms	remaining: 11.2s
3:	learn: 1234.7935572	total: 660ms	remaining: 11.7s
4:	learn: 1192.3131988	total: 725ms	remaining: 10.2s
5:	learn: 1157.7669010	total: 874ms	remaining: 10s
6:	learn: 1134.3033815	total: 1.2s	remaining: 11.6s
7:	learn: 1116.1853599	total: 1.31s	remaining: 11s
8:	learn: 1101.1183733	total: 1.4s	remaining: 10.2s
9:	learn: 1089.2499014	total: 1.52s	remaining: 9.86s
10:	learn: 1082.5879673	total: 1.64s	remaining: 9.56s
11:	learn: 1077.2235225	total: 1.79s	remaining: 9.38s
12:	learn: 1072.2990855	total: 1.89s	remaining: 9s
13:	learn: 1068.9164830	total: 2.06s	remaining: 8.97s
14:	learn: 1065.8735654	total: 2.26s	remaining: 9.05s
15:	learn: 1060.8284506	total: 2.35s	remaining: 8.67s
16:	learn: 1058.8902779	total: 2.44s	remaining: 8.34s
17:	learn: 1056.1424179	total: 2.58s	remaining: 8.18s
18:	learn: 1052.8187839	total: 2.66s	remaining: 7.84s
19:	learn: 1049.4841351	total: 2.73s	remaining: 7.51s
20:	learn: 1048.5817738	total: 2.83s	remaining: 7.28s
21:	learn: 1046.6848285	total: 2.96s	remaining: 7.13s
22:	learn: 1045.7706859	total: 3.03s	remaining: 6.85s
23:	learn: 1044.8692738	total: 3.19s	remaining: 6.77s
24:	learn: 1041.4673429	total: 3.41s	remaining: 6.81s
25:	learn: 1039.5496016	total: 3.56s	remaining: 6.71s
26:	learn: 1038.6611020	total: 3.78s	remaining: 6.72s
27:	learn: 1037.7174955	total: 3.97s	remaining: 6.67s
28:	learn: 1036.1474496	total: 4.07s	remaining: 6.46s
29:	learn: 1035.8121916	total: 4.14s	remaining: 6.22s
30:	learn: 1034.8674376	total: 4.36s	remaining: 6.19s
31:	learn: 1033.3494758	total: 4.45s	remaining: 5.98s
32:	learn: 1033.0554767	total: 4.53s	remaining: 5.77s
33:	learn: 1032.0648778	total: 4.65s	remaining: 5.61s
34:	learn: 1031.3159542	total: 4.84s	remaining: 5.53s
35:	learn: 1030.0875406	total: 5.07s	remaining: 5.49s
36:	learn: 1028.9405484	total: 5.28s	remaining: 5.42s
37:	learn: 1026.3599674	total: 5.51s	remaining: 5.37s
38:	learn: 1025.5200121	total: 5.64s	remaining: 5.21s
39:	learn: 1024.5544666	total: 5.78s	remaining: 5.06s
40:	learn: 1023.7712063	total: 5.91s	remaining: 4.9s
41:	learn: 1022.9521589	total: 5.98s	remaining: 4.7s
42:	learn: 1022.2570244	total: 6.04s	remaining: 4.5s
43:	learn: 1020.5739015	total: 6.13s	remaining: 4.32s
44:	learn: 1019.5925915	total: 6.22s	remaining: 4.15s
45:	learn: 1018.7362492	total: 6.29s	remaining: 3.97s
46:	learn: 1017.6167027	total: 6.36s	remaining: 3.79s
47:	learn: 1016.4616029	total: 6.42s	remaining: 3.61s
48:	learn: 1015.3881540	total: 6.49s	remaining: 3.44s
49:	learn: 1014.5006694	total: 6.59s	remaining: 3.29s
50:	learn: 1013.6767897	total: 6.68s	remaining: 3.14s
51:	learn: 1012.5831743	total: 6.77s	remaining: 2.99s
52:	learn: 1011.6744510	total: 6.9s	remaining: 2.86s
53:	learn: 1010.6546929	total: 7.04s	remaining: 2.74s
54:	learn: 1009.6788513	total: 7.16s	remaining: 2.6s
55:	learn: 1008.8195400	total: 7.28s	remaining: 2.47s
56:	learn: 1008.2112138	total: 7.37s	remaining: 2.33s
57:	learn: 1007.4118122	total: 7.55s	remaining: 2.21s
58:	learn: 1006.3194980	total: 7.7s	remaining: 2.09s
59:	learn: 1005.6015227	total: 7.8s	remaining: 1.95s
60:	learn: 1003.8685080	total: 7.9s	remaining: 1.81s
61:	learn: 1003.0164589	total: 8.04s	remaining: 1.69s
62:	learn: 1002.3805604	total: 8.29s	remaining: 1.58s
63:	learn: 1001.4300396	total: 8.47s	remaining: 1.46s
64:	learn: 1000.8813873	total: 8.58s	remaining: 1.32s
65:	learn: 1000.0653741	total: 8.69s	remaining: 1.19s
66:	learn: 999.0902846	total: 8.81s	remaining: 1.05s
67:	learn: 998.6846496	total: 8.94s	remaining: 920ms
68:	learn: 997.8622559	total: 9.02s	remaining: 785ms
69:	learn: 996.9456807	total: 9.12s	remaining: 651ms
70:	learn: 995.8982911	total: 9.26s	remaining: 522ms
71:	learn: 994.8967026	total: 9.38s	remaining: 391ms
72:	learn: 993.7310255	total: 9.53s	remaining: 261ms
73:	learn: 993.3388931	total: 9.75s	remaining: 132ms
74:	learn: 992.4596398	total: 9.96s	remaining: 0us
0:	learn: 1520.2857790	total: 298ms	remaining: 22.1s
1:	learn: 1388.4446418	total: 500ms	remaining: 18.2s
2:	learn: 1293.7768458	total: 661ms	remaining: 15.9s

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
0:	learn: 1529.7447310	total: 110ms	remaining: 8.17s
1:	learn: 1394.5077789	total: 285ms	remaining: 10.4s
2:	learn: 1293.6596924	total: 369ms	remaining: 8.86s
3:	learn: 1223.5787740	total: 497ms	remaining: 8.82s
4:	learn: 1174.9648301	total: 620ms	remaining: 8.68s
5:	learn: 1141.2988287	total: 756ms	remaining: 8.69s
6:	learn: 1117.1181703	total: 928ms	remaining: 9.01s
7:	learn: 1102.1880746	total: 981ms	remaining: 8.21s
8:	learn: 1091.5464543	total: 1.14s	remaining: 8.34s
9:	learn: 1082.2733349	total: 1.24s	remaining: 8.04s
10:	learn: 1076.4431524	total: 1.4s	remaining: 8.16s
11:	learn: 1070.4505612	total: 1.58s	remaining: 8.28s
12:	learn: 1067.5077682	total: 1.7s	remaining: 8.1s
13:	learn: 1062.4362040	total: 1.79s	remaining: 7.8s
14:	learn: 1059.6198685	total: 1.93s	remaining: 7.71s
15:	learn: 1058.4593041	total: 2.1s	remaining: 7.75s
16:	learn: 1055.8566139	total: 2.18s	remaining: 7.44s
17:	learn: 1053.8842545	total: 2.3s	remaining: 7.28s
18:	learn: 1051.9796362	total: 2.43s	remaining: 7.16s
19:	learn: 1051.1556216	total: 2.53s	remaining: 6.97s
20:	learn: 1048.6303366	total: 2.74s	remaining: 7.04s
21:	learn: 1047.5905056	total: 2.89s	remaining: 6.96s
22:	learn: 1045.7518307	total: 3.02s	remaining: 6.84s
23:	learn: 1044.1734758	total: 3.19s	remaining: 6.78s
24:	learn: 1041.8215988	total: 3.3s	remaining: 6.6s
25:	learn: 1040.5036907	total: 3.47s	remaining: 6.55s
26:	learn: 1039.9540453	total: 3.61s	remaining: 6.42s
27:	learn: 1038.9678623	total: 3.7s	remaining: 6.21s
28:	learn: 1037.6607049	total: 3.85s	remaining: 6.11s
29:	learn: 1036.8693013	total: 3.92s	remaining: 5.88s
30:	learn: 1036.0726732	total: 4.14s	remaining: 5.87s
31:	learn: 1035.0822252	total: 4.26s	remaining: 5.72s
32:	learn: 1034.2640306	total: 4.37s	remaining: 5.56s
33:	learn: 1033.7920172	total: 4.6s	remaining: 5.54s
34:	learn: 1033.2289773	total: 4.67s	remaining: 5.34s
35:	learn: 1032.1316256	total: 4.76s	remaining: 5.16s
36:	learn: 1030.9280853	total: 4.9s	remaining: 5.03s
37:	learn: 1029.1580536	total: 4.99s	remaining: 4.86s
38:	learn: 1027.9861716	total: 5.2s	remaining: 4.8s
39:	learn: 1026.9011438	total: 5.38s	remaining: 4.71s
40:	learn: 1026.2592330	total: 5.47s	remaining: 4.53s
41:	learn: 1025.5478126	total: 5.59s	remaining: 4.39s
42:	learn: 1025.0690354	total: 5.75s	remaining: 4.28s
43:	learn: 1023.7475981	total: 5.9s	remaining: 4.16s
44:	learn: 1022.4971409	total: 6s	remaining: 4s
45:	learn: 1021.4426487	total: 6.11s	remaining: 3.85s
46:	learn: 1020.3895891	total: 6.28s	remaining: 3.74s
47:	learn: 1019.5483842	total: 6.47s	remaining: 3.64s
48:	learn: 1018.8086799	total: 6.62s	remaining: 3.51s
49:	learn: 1017.4921428	total: 6.8s	remaining: 3.4s
50:	learn: 1016.6004682	total: 6.88s	remaining: 3.24s
51:	learn: 1015.7981272	total: 6.99s	remaining: 3.09s
52:	learn: 1014.7861814	total: 7.12s	remaining: 2.96s
53:	learn: 1013.7485852	total: 7.3s	remaining: 2.84s
54:	learn: 1012.7355436	total: 7.51s	remaining: 2.73s
55:	learn: 1011.8425426	total: 7.62s	remaining: 2.58s
56:	learn: 1011.2670202	total: 7.72s	remaining: 2.44s
57:	learn: 1010.3014808	total: 7.89s	remaining: 2.31s
58:	learn: 1009.5132885	total: 8s	remaining: 2.17s
59:	learn: 1008.5817535	total: 8.12s	remaining: 2.03s
60:	learn: 1007.8671596	total: 8.33s	remaining: 1.91s
61:	learn: 1006.7901011	total: 8.4s	remaining: 1.76s
62:	learn: 1005.8420247	total: 8.53s	remaining: 1.63s
63:	learn: 1005.4261934	total: 8.68s	remaining: 1.49s
64:	learn: 1004.6235594	total: 8.8s	remaining: 1.35s
65:	learn: 1003.5567450	total: 8.96s	remaining: 1.22s
66:	learn: 1002.1972513	total: 9.12s	remaining: 1.09s
67:	learn: 1001.4364237	total: 9.18s	remaining: 945ms
68:	learn: 1000.4288635	total: 9.34s	remaining: 812ms
69:	learn: 1000.0017837	total: 9.44s	remaining: 674ms
70:	learn: 999.6411537	total: 9.56s	remaining: 538ms
71:	learn: 998.8406395	total: 9.64s	remaining: 402ms
72:	learn: 997.8415392	total: 9.74s	remaining: 267ms
73:	learn: 996.8959885	total: 9.83s	remaining: 133ms
74:	learn: 996.1894831	total: 9.93s	remaining: 0us
0:	learn: 1542.0954041	total: 269ms	remaining: 19.9s
1:	learn: 1402.4473395	total: 363ms	remaining: 13.2s
2:	learn: 1316.4111040	total: 446ms	remaining: 10.7s
3:	learn: 1241.9499173	total: 574ms	remaining: 10.2s
4:	learn: 1189.0586870	total: 633ms	remaining: 8.86s
5:	learn: 1152.9547896	total: 759ms	remaining: 8.72s
6:	learn: 1128.5511873	total: 941ms	remaining: 9.14s
7:	learn: 1110.8205580	total: 1.12s	remaining: 9.35s
8:	learn: 1096.1221205	total: 1.21s	remaining: 8.88s
9:	learn: 1089.3471250	total: 1.27s	remaining: 8.29s
10:	learn: 1082.6528318	total: 1.4s	remaining: 8.12s
11:	learn: 1080.3386301	total: 1.41s	remaining: 7.41s
12:	learn: 1074.9235432	total: 1.51s	remaining: 7.18s
13:	learn: 1071.7098773	total: 1.61s	remaining: 7.01s
14:	learn: 1071.0557316	total: 1.63s	remaining: 6.54s
15:	learn: 1068.3451845	total: 1.72s	remaining: 6.33s
16:	learn: 1067.0671791	total: 1.76s	remaining: 6.01s
17:	learn: 1065.2976552	total: 2s	remaining: 6.32s
18:	learn: 1063.9566773	total: 2.14s	remaining: 6.32s
19:	learn: 1062.8889275	total: 2.25s	remaining: 6.2s
20:	learn: 1059.9735799	total: 2.43s	remaining: 6.25s
21:	learn: 1059.2873287	total: 2.57s	remaining: 6.19s
22:	learn: 1058.1986790	total: 2.66s	remaining: 6.02s
23:	learn: 1056.7358084	total: 2.77s	remaining: 5.89s
24:	learn: 1055.7532465	total: 2.85s	remaining: 5.69s
25:	learn: 1053.5043356	total: 2.91s	remaining: 5.48s
26:	learn: 1051.2774594	total: 3.16s	remaining: 5.62s
27:	learn: 1050.6822723	total: 3.26s	remaining: 5.47s
28:	learn: 1049.7632850	total: 3.43s	remaining: 5.45s
29:	learn: 1048.9347676	total: 3.61s	remaining: 5.41s
30:	learn: 1048.4336171	total: 3.76s	remaining: 5.34s
31:	learn: 1047.7924119	total: 3.85s	remaining: 5.18s
32:	learn: 1046.8588596	total: 4.04s	remaining: 5.14s
33:	learn: 1046.4497052	total: 4.18s	remaining: 5.05s
34:	learn: 1045.0608731	total: 4.24s	remaining: 4.84s
35:	learn: 1044.1479200	total: 4.42s	remaining: 4.79s
36:	learn: 1043.2206038	total: 4.51s	remaining: 4.64s
37:	learn: 1041.8806291	total: 4.52s	remaining: 4.4s
38:	learn: 1041.2589181	total: 4.67s	remaining: 4.32s
39:	learn: 1039.8741197	total: 4.79s	remaining: 4.19s
40:	learn: 1038.9932123	total: 4.88s	remaining: 4.04s
41:	learn: 1035.7370531	total: 5.01s	remaining: 3.94s
42:	learn: 1035.0388712	total: 5.26s	remaining: 3.91s
43:	learn: 1033.4994335	total: 5.44s	remaining: 3.83s
44:	learn: 1032.4575539	total: 5.59s	remaining: 3.73s
45:	learn: 1031.4055987	total: 5.7s	remaining: 3.59s
46:	learn: 1030.4585095	total: 5.88s	remaining: 3.51s
47:	learn: 1029.3816279	total: 6s	remaining: 3.38s
48:	learn: 1028.4143147	total: 6.09s	remaining: 3.23s
49:	learn: 1027.1516456	total: 6.27s	remaining: 3.13s
50:	learn: 1026.5636680	total: 6.46s	remaining: 3.04s
51:	learn: 1025.4699652	total: 6.67s	remaining: 2.95s
52:	learn: 1024.4873569	total: 6.87s	remaining: 2.85s
53:	learn: 1023.4027065	total: 7.09s	remaining: 2.76s
54:	learn: 1022.4474939	total: 7.18s	remaining: 2.61s
55:	learn: 1021.6381981	total: 7.22s	remaining: 2.45s
56:	learn: 1020.9236092	total: 7.42s	remaining: 2.34s
57:	learn: 1019.7581937	total: 7.57s	remaining: 2.22s
58:	learn: 1019.0044130	total: 7.62s	remaining: 2.07s
59:	learn: 1018.4482766	total: 7.69s	remaining: 1.92s
60:	learn: 1017.8658107	total: 7.8s	remaining: 1.79s
61:	learn: 1016.8113249	total: 7.89s	remaining: 1.65s
62:	learn: 1016.1499441	total: 8.02s	remaining: 1.53s
63:	learn: 1015.4925045	total: 8.17s	remaining: 1.4s
64:	learn: 1014.2778955	total: 8.3s	remaining: 1.28s
65:	learn: 1013.3738977	total: 8.46s	remaining: 1.15s
66:	learn: 1012.4760039	total: 8.56s	remaining: 1.02s
67:	learn: 1012.0606928	total: 8.73s	remaining: 898ms
68:	learn: 1011.2661565	total: 8.92s	remaining: 776ms
69:	learn: 1010.4157258	total: 9.12s	remaining: 652ms
70:	learn: 1009.3059120	total: 9.24s	remaining: 521ms
71:	learn: 1008.9560244	total: 9.32s	remaining: 388ms
72:	learn: 1007.8233546	total: 9.42s	remaining: 258ms
73:	learn: 1007.2074546	total: 9.51s	remaining: 128ms
74:	learn: 1006.6422593	total: 9.61s	remaining: 0us
0:	learn: 1541.7172122	total: 137ms	remaining: 10.1s
1:	learn: 1413.2464558	total: 231ms	remaining: 8.43s
2:	learn: 1329.1216292	total: 300ms	remaining: 7.2s
3:	learn: 1259.6540669	total: 316ms	remaining: 5.62s
4:	learn: 1203.3708322	total: 502ms	remaining: 7.03s
5:	learn: 1163.8326418	total: 525ms	remaining: 6.04s
6:	learn: 1140.6149642	total: 565ms	remaining: 5.49s
7:	learn: 1119.2925324	total: 663ms	remaining: 5.55s
8:	learn: 1103.4106066	total: 781ms	remaining: 5.73s
9:	learn: 1097.2431739	total: 815ms	remaining: 5.3s
10:	learn: 1089.2935522	total: 992ms	remaining: 5.77s
11:	learn: 1083.0573838	total: 1.04s	remaining: 5.45s
12:	learn: 1079.4961240	total: 1.11s	remaining: 5.31s
13:	learn: 1074.3307803	total: 1.2s	remaining: 5.21s
14:	learn: 1069.3894480	total: 1.3s	remaining: 5.19s
15:	learn: 1067.0229383	total: 1.48s	remaining: 5.44s
16:	learn: 1065.0706697	total: 1.58s	remaining: 5.38s
17:	learn: 1063.0254410	total: 1.67s	remaining: 5.3s
18:	learn: 1062.1575027	total: 1.74s	remaining: 5.13s
19:	learn: 1059.6587412	total: 1.89s	remaining: 5.18s
20:	learn: 1058.8137871	total: 2.04s	remaining: 5.25s
21:	learn: 1057.8136546	total: 2.08s	remaining: 5.01s
22:	learn: 1056.4881874	total: 2.23s	remaining: 5.03s
23:	learn: 1053.7127867	total: 2.38s	remaining: 5.07s
24:	learn: 1052.9774104	total: 2.51s	remaining: 5.01s
25:	learn: 1051.5040951	total: 2.66s	remaining: 5.01s
26:	learn: 1049.6231492	total: 2.82s	remaining: 5.02s
27:	learn: 1048.9315375	total: 2.97s	remaining: 4.99s
28:	learn: 1047.8162263	total: 3.1s	remaining: 4.92s
29:	learn: 1046.2063600	total: 3.28s	remaining: 4.92s
30:	learn: 1045.2713489	total: 3.35s	remaining: 4.75s
31:	learn: 1043.9773117	total: 3.45s	remaining: 4.63s
32:	learn: 1042.2085492	total: 3.63s	remaining: 4.62s
33:	learn: 1040.9882330	total: 3.69s	remaining: 4.46s
34:	learn: 1040.1827229	total: 3.85s	remaining: 4.4s
35:	learn: 1039.6788829	total: 3.9s	remaining: 4.22s
36:	learn: 1038.6593419	total: 4.02s	remaining: 4.13s
37:	learn: 1037.8781493	total: 4.15s	remaining: 4.04s
38:	learn: 1037.3785134	total: 4.21s	remaining: 3.89s
39:	learn: 1036.4826601	total: 4.37s	remaining: 3.82s
40:	learn: 1035.1416833	total: 4.51s	remaining: 3.74s
41:	learn: 1033.9956017	total: 4.66s	remaining: 3.66s
42:	learn: 1033.0795425	total: 4.84s	remaining: 3.6s
43:	learn: 1031.9023519	total: 5s	remaining: 3.52s
44:	learn: 1030.8908641	total: 5.14s	remaining: 3.43s
45:	learn: 1029.4754859	total: 5.3s	remaining: 3.34s
46:	learn: 1028.6204550	total: 5.42s	remaining: 3.23s
47:	learn: 1027.7589101	total: 5.6s	remaining: 3.15s
48:	learn: 1026.7110953	total: 5.75s	remaining: 3.05s
49:	learn: 1025.9429954	total: 5.88s	remaining: 2.94s
50:	learn: 1024.8313402	total: 5.95s	remaining: 2.8s
51:	learn: 1023.7940845	total: 6.04s	remaining: 2.67s
52:	learn: 1022.7244614	total: 6.12s	remaining: 2.54s
53:	learn: 1021.9738556	total: 6.24s	remaining: 2.43s
54:	learn: 1021.4161611	total: 6.36s	remaining: 2.31s
55:	learn: 1020.9238269	total: 6.47s	remaining: 2.2s
56:	learn: 1020.3962576	total: 6.64s	remaining: 2.1s
57:	learn: 1019.4248581	total: 6.8s	remaining: 1.99s
58:	learn: 1018.2989054	total: 6.92s	remaining: 1.88s
59:	learn: 1017.4992616	total: 7.1s	remaining: 1.77s
60:	learn: 1016.6805683	total: 7.29s	remaining: 1.67s
61:	learn: 1016.1188250	total: 7.6s	remaining: 1.59s
62:	learn: 1014.9500039	total: 7.79s	remaining: 1.48s
63:	learn: 1014.3797650	total: 7.92s	remaining: 1.36s
64:	learn: 1013.0959334	total: 7.98s	remaining: 1.23s
65:	learn: 1012.0166946	total: 8.06s	remaining: 1.1s
66:	learn: 1011.4744229	total: 8.21s	remaining: 981ms
67:	learn: 1010.5476888	total: 8.27s	remaining: 851ms
68:	learn: 1009.7364893	total: 8.38s	remaining: 729ms
69:	learn: 1008.7344630	total: 8.49s	remaining: 606ms
70:	learn: 1007.8109437	total: 8.65s	remaining: 487ms
71:	learn: 1006.9308521	total: 8.75s	remaining: 365ms
72:	learn: 1005.8630943	total: 8.85s	remaining: 242ms
73:	learn: 1005.0847267	total: 8.96s	remaining: 121ms
74:	learn: 1004.2425404	total: 9.13s	remaining: 0us
0:	learn: 1523.2021743	total: 238ms	remaining: 17.6s
1:	learn: 1396.2119852	total: 353ms	remaining: 12.9s
2:	learn: 1314.5345151	total: 411ms	remaining: 9.86s
3:	learn: 1245.9540820	total: 643ms	remaining: 11.4s
4:	learn: 1194.4188456	total: 768ms	remaining: 10.7s
5:	learn: 1162.7412574	total: 958ms	remaining: 11s
6:	learn: 1138.0189067	total: 1.08s	remaining: 10.5s
7:	learn: 1115.9874234	total: 1.21s	remaining: 10.2s
8:	learn: 1103.1945981	total: 1.41s	remaining: 10.3s
9:	learn: 1093.8047215	total: 1.57s	remaining: 10.2s
10:	learn: 1088.0340841	total: 1.73s	remaining: 10.1s
11:	learn: 1081.5131268	total: 1.93s	remaining: 10.1s
12:	learn: 1077.8861365	total: 2.07s	remaining: 9.85s
13:	learn: 1074.0152993	total: 2.2s	remaining: 9.59s
14:	learn: 1069.9743851	total: 2.37s	remaining: 9.5s
15:	learn: 1067.0376730	total: 2.51s	remaining: 9.26s
16:	learn: 1065.9300703	total: 2.67s	remaining: 9.1s
17:	learn: 1065.4664276	total: 2.8s	remaining: 8.88s
18:	learn: 1063.9677644	total: 3.06s	remaining: 9.04s
19:	learn: 1062.4940541	total: 3.17s	remaining: 8.73s
20:	learn: 1061.3247158	total: 3.37s	remaining: 8.65s
21:	learn: 1057.7201630	total: 3.69s	remaining: 8.88s
22:	learn: 1054.2483897	total: 3.83s	remaining: 8.67s
23:	learn: 1050.6843724	total: 4.02s	remaining: 8.55s
24:	learn: 1049.4978479	total: 4.16s	remaining: 8.31s
25:	learn: 1048.5106266	total: 4.33s	remaining: 8.16s
26:	learn: 1047.9283680	total: 4.46s	remaining: 7.93s
27:	learn: 1046.1317535	total: 4.68s	remaining: 7.86s
28:	learn: 1045.6924390	total: 4.83s	remaining: 7.67s
29:	learn: 1044.5984105	total: 4.96s	remaining: 7.44s
30:	learn: 1043.8225772	total: 5.15s	remaining: 7.31s
31:	learn: 1042.7599173	total: 5.26s	remaining: 7.07s
32:	learn: 1041.7733478	total: 5.4s	remaining: 6.88s
33:	learn: 1039.8864134	total: 5.49s	remaining: 6.63s
34:	learn: 1037.8083866	total: 5.74s	remaining: 6.56s
35:	learn: 1036.8209118	total: 5.89s	remaining: 6.38s
36:	learn: 1035.5374766	total: 6.05s	remaining: 6.21s
37:	learn: 1032.4627922	total: 6.07s	remaining: 5.91s
38:	learn: 1031.1719472	total: 6.21s	remaining: 5.73s
39:	learn: 1030.0512173	total: 6.41s	remaining: 5.61s
40:	learn: 1029.0860134	total: 6.79s	remaining: 5.63s
41:	learn: 1028.5548409	total: 6.94s	remaining: 5.45s
42:	learn: 1028.1904413	total: 7.1s	remaining: 5.28s
43:	learn: 1026.7116840	total: 7.17s	remaining: 5.05s
44:	learn: 1025.2916186	total: 7.28s	remaining: 4.85s
45:	learn: 1024.3261296	total: 7.37s	remaining: 4.65s
46:	learn: 1023.4588557	total: 7.57s	remaining: 4.51s
47:	learn: 1022.6033073	total: 7.72s	remaining: 4.34s
48:	learn: 1021.6322380	total: 7.85s	remaining: 4.17s
49:	learn: 1020.2067115	total: 7.97s	remaining: 3.99s
50:	learn: 1019.2518302	total: 8.09s	remaining: 3.81s
51:	learn: 1018.3802492	total: 8.25s	remaining: 3.65s
52:	learn: 1017.3042359	total: 8.55s	remaining: 3.55s
53:	learn: 1016.4301953	total: 8.73s	remaining: 3.39s
54:	learn: 1015.6091955	total: 8.81s	remaining: 3.2s
55:	learn: 1015.0989739	total: 8.9s	remaining: 3.02s
56:	learn: 1013.8028230	total: 9.1s	remaining: 2.87s
57:	learn: 1013.2212553	total: 9.29s	remaining: 2.72s
58:	learn: 1012.5730073	total: 9.42s	remaining: 2.56s
59:	learn: 1011.6925435	total: 9.63s	remaining: 2.41s
60:	learn: 1010.6483232	total: 9.77s	remaining: 2.24s
61:	learn: 1010.2361085	total: 9.88s	remaining: 2.07s
62:	learn: 1009.3408433	total: 10s	remaining: 1.91s
63:	learn: 1009.0003325	total: 10.2s	remaining: 1.75s
64:	learn: 1008.6142746	total: 10.2s	remaining: 1.57s
65:	learn: 1007.6357194	total: 10.4s	remaining: 1.42s
66:	learn: 1006.8385973	total: 10.5s	remaining: 1.25s
67:	learn: 1005.9006894	total: 10.7s	remaining: 1.1s
68:	learn: 1004.8705848	total: 10.9s	remaining: 944ms
69:	learn: 1003.7370203	total: 11s	remaining: 783ms
70:	learn: 1002.9227379	total: 11.1s	remaining: 626ms
71:	learn: 1001.6691604	total: 11.2s	remaining: 467ms
72:	learn: 1000.8413868	total: 11.3s	remaining: 310ms
73:	learn: 1000.1363780	total: 11.5s	remaining: 155ms
74:	learn: 998.6649342	total: 11.7s	remaining: 0us
0:	learn: 1525.9291114	total: 147ms	remaining: 10.9s
1:	learn: 1398.3882725	total: 280ms	remaining: 10.2s
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
0:	learn: 1521.6537695	total: 128ms	remaining: 9.45s
1:	learn: 1385.2125097	total: 237ms	remaining: 8.66s
2:	learn: 1287.8248722	total: 332ms	remaining: 7.96s
3:	learn: 1221.7560085	total: 522ms	remaining: 9.26s
4:	learn: 1173.5956925	total: 676ms	remaining: 9.46s
5:	learn: 1142.2979994	total: 767ms	remaining: 8.82s
6:	learn: 1120.4571488	total: 899ms	remaining: 8.73s
7:	learn: 1099.2003603	total: 1.01s	remaining: 8.46s
8:	learn: 1085.0061698	total: 1.12s	remaining: 8.21s
9:	learn: 1076.3376597	total: 1.26s	remaining: 8.22s
10:	learn: 1069.3688224	total: 1.55s	remaining: 9.05s
11:	learn: 1063.9311734	total: 1.68s	remaining: 8.8s
12:	learn: 1059.5792145	total: 1.77s	remaining: 8.44s
13:	learn: 1054.9568758	total: 1.86s	remaining: 8.09s
14:	learn: 1051.2850748	total: 1.96s	remaining: 7.85s
15:	learn: 1048.5053067	total: 2.06s	remaining: 7.59s
16:	learn: 1047.5844833	total: 2.16s	remaining: 7.38s
17:	learn: 1044.6415107	total: 2.32s	remaining: 7.36s
18:	learn: 1041.2437183	total: 2.47s	remaining: 7.28s
19:	learn: 1037.1840512	total: 2.64s	remaining: 7.27s
20:	learn: 1035.1845826	total: 2.81s	remaining: 7.23s
21:	learn: 1034.6422730	total: 2.9s	remaining: 7s
22:	learn: 1032.4713593	total: 3.19s	remaining: 7.21s
23:	learn: 1031.6796517	total: 3.33s	remaining: 7.08s
24:	learn: 1030.3688169	total: 3.44s	remaining: 6.88s
25:	learn: 1029.2303011	total: 3.5s	remaining: 6.6s
26:	learn: 1025.2319432	total: 3.57s	remaining: 6.34s
27:	learn: 1023.9523905	total: 3.78s	remaining: 6.35s
28:	learn: 1021.8009646	total: 4.08s	remaining: 6.48s
29:	learn: 1020.5716376	total: 4.19s	remaining: 6.29s
30:	learn: 1020.0831954	total: 4.39s	remaining: 6.24s
31:	learn: 1019.4367972	total: 4.52s	remaining: 6.07s
32:	learn: 1018.7085359	total: 4.62s	remaining: 5.89s
33:	learn: 1018.1558080	total: 4.75s	remaining: 5.73s
34:	learn: 1017.5351659	total: 4.85s	remaining: 5.55s
35:	learn: 1016.8376167	total: 5s	remaining: 5.42s
36:	learn: 1015.9585610	total: 5.19s	remaining: 5.33s
37:	learn: 1015.2120144	total: 5.36s	remaining: 5.22s
38:	learn: 1014.4910490	total: 5.4s	remaining: 4.98s
39:	learn: 1013.4558865	total: 5.56s	remaining: 4.87s
40:	learn: 1012.6028517	total: 5.61s	remaining: 4.65s
41:	learn: 1011.7944450	total: 5.75s	remaining: 4.52s
42:	learn: 1011.0148675	total: 5.89s	remaining: 4.38s
43:	learn: 1010.3041779	total: 6.11s	remaining: 4.3s
44:	learn: 1009.1912908	total: 6.22s	remaining: 4.15s
45:	learn: 1008.0177210	total: 6.37s	remaining: 4.02s
46:	learn: 1007.2242528	total: 6.46s	remaining: 3.85s
47:	learn: 1005.7537932	total: 6.7s	remaining: 3.77s
48:	learn: 1004.2754871	total: 6.77s	remaining: 3.59s
49:	learn: 1002.9446751	total: 6.99s	remaining: 3.5s
50:	learn: 1002.2233791	total: 7.1s	remaining: 3.34s
51:	learn: 1000.6398400	total: 7.24s	remaining: 3.2s
52:	learn: 999.5335322	total: 7.38s	remaining: 3.06s
53:	learn: 998.9069744	total: 7.47s	remaining: 2.91s
54:	learn: 998.1583045	total: 7.68s	remaining: 2.79s
55:	learn: 997.2278560	total: 7.77s	remaining: 2.64s
56:	learn: 995.7949701	total: 7.92s	remaining: 2.5s
57:	learn: 995.2914422	total: 8.08s	remaining: 2.37s
58:	learn: 994.4703788	total: 8.25s	remaining: 2.24s
59:	learn: 993.3694443	total: 8.38s	remaining: 2.09s
60:	learn: 992.3325140	total: 8.52s	remaining: 1.95s
61:	learn: 991.8504615	total: 8.79s	remaining: 1.84s
62:	learn: 991.0416516	total: 8.94s	remaining: 1.7s
63:	learn: 990.6358169	total: 9.09s	remaining: 1.56s

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
74:	learn: 994.2029219	total: 7.96s	remaining: 0us
0:	learn: 1533.6682699	total: 243ms	remaining: 18s
1:	learn: 1406.8309166	total: 425ms	remaining: 15.5s
2:	learn: 1302.5944409	total: 589ms	remaining: 14.1s
3:	learn: 1233.1966479	total: 748ms	remaining: 13.3s
4:	learn: 1178.2989450	total: 898ms	remaining: 12.6s
5:	learn: 1141.1526627	total: 980ms	remaining: 11.3s
6:	learn: 1117.0442774	total: 1.18s	remaining: 11.5s
7:	learn: 1097.4496632	total: 1.3s	remaining: 10.9s
8:	learn: 1083.8368576	total: 1.49s	remaining: 10.9s
9:	learn: 1075.7274240	total: 1.58s	remaining: 10.3s
10:	learn: 1071.4438060	total: 1.63s	remaining: 9.46s
11:	learn: 1064.9380179	total: 1.82s	remaining: 9.56s
12:	learn: 1060.9547755	total: 1.92s	remaining: 9.17s
13:	learn: 1058.6328995	total: 2.08s	remaining: 9.08s
14:	learn: 1057.6935965	total: 2.29s	remaining: 9.16s
15:	learn: 1052.7756454	total: 2.42s	remaining: 8.91s
16:	learn: 1052.4910308	total: 2.45s	remaining: 8.35s
17:	learn: 1050.2927889	total: 2.5s	remaining: 7.93s
18:	learn: 1046.2861960	total: 2.56s	remaining: 7.56s
19:	learn: 1044.2981439	total: 2.61s	remaining: 7.19s
20:	learn: 1042.6269853	total: 2.68s	remaining: 6.89s
21:	learn: 1039.3957818	total: 2.77s	remaining: 6.67s
22:	learn: 1038.6696664	total: 2.83s	remaining: 6.4s
23:	learn: 1036.3704689	total: 2.92s	remaining: 6.21s
24:	learn: 1032.7027075	total: 2.96s	remaining: 5.92s
25:	learn: 1031.2718857	total: 3.09s	remaining: 5.82s
26:	learn: 1030.5142027	total: 3.37s	remaining: 5.99s
27:	learn: 1029.1904355	total: 3.54s	remaining: 5.94s
28:	learn: 1028.4932901	total: 3.63s	remaining: 5.77s
29:	learn: 1027.5406016	total: 3.77s	remaining: 5.66s
30:	learn: 1025.7357852	total: 3.83s	remaining: 5.43s
31:	learn: 1024.6714875	total: 3.94s	remaining: 5.3s
32:	learn: 1024.2008817	total: 4.05s	remaining: 5.15s
33:	learn: 1022.0558973	total: 4.16s	remaining: 5.01s
34:	learn: 1021.5159531	total: 4.22s	remaining: 4.82s
35:	learn: 1020.3981985	total: 4.34s	remaining: 4.7s
36:	learn: 1019.6561461	total: 4.41s	remaining: 4.53s
37:	learn: 1018.7281313	total: 4.47s	remaining: 4.35s
38:	learn: 1017.8936280	total: 4.55s	remaining: 4.2s
39:	learn: 1017.1070550	total: 4.61s	remaining: 4.03s
40:	learn: 1016.3919105	total: 4.68s	remaining: 3.88s
41:	learn: 1013.8695641	total: 4.8s	remaining: 3.77s
42:	learn: 1011.6425610	total: 4.97s	remaining: 3.7s
43:	learn: 1010.7093969	total: 5.23s	remaining: 3.69s
44:	learn: 1009.8788926	total: 5.4s	remaining: 3.6s
45:	learn: 1008.7229595	total: 5.55s	remaining: 3.5s
46:	learn: 1008.0610112	total: 5.68s	remaining: 3.38s
47:	learn: 1007.0616395	total: 5.8s	remaining: 3.26s
48:	learn: 1006.3148143	total: 5.91s	remaining: 3.14s
49:	learn: 1005.1768374	total: 6.07s	remaining: 3.04s
50:	learn: 1004.1135797	total: 6.26s	remaining: 2.94s
51:	learn: 1002.9740998	total: 6.37s	remaining: 2.82s
52:	learn: 1002.4572244	total: 6.46s	remaining: 2.68s
53:	learn: 1001.5328269	total: 6.59s	remaining: 2.56s
54:	learn: 1000.6054386	total: 6.78s	remaining: 2.47s
55:	learn: 999.6906268	total: 7.06s	remaining: 2.4s
56:	learn: 998.8299213	total: 7.24s	remaining: 2.29s
57:	learn: 997.9042868	total: 7.4s	remaining: 2.17s
58:	learn: 996.7719248	total: 7.52s	remaining: 2.04s
59:	learn: 996.3203316	total: 7.71s	remaining: 1.93s
60:	learn: 995.3297919	total: 7.87s	remaining: 1.8s
61:	learn: 994.4712010	total: 7.97s	remaining: 1.67s
62:	learn: 993.9811427	total: 8.1s	remaining: 1.54s
63:	learn: 992.7790000	total: 8.36s	remaining: 1.44s
64:	learn: 991.7595429	total: 8.48s	remaining: 1.3s
65:	learn: 990.8761787	total: 8.62s	remaining: 1.18s
66:	learn: 990.1794232	total: 8.8s	remaining: 1.05s
67:	learn: 989.7900649	total: 8.93s	remaining: 920ms
68:	learn: 988.7107633	total: 9.09s	remaining: 790ms
69:	learn: 987.5413387	total: 9.19s	remaining: 656ms
70:	learn: 986.7285161	total: 9.32s	remaining: 525ms
71:	learn: 985.9552840	total: 9.4s	remaining: 392ms
72:	learn: 985.5873308	total: 9.59s	remaining: 263ms
73:	learn: 984.6997067	total: 9.7s	remaining: 131ms
74:	learn: 983.7365533	total: 9.78s	remaining: 0us
0:	learn: 1534.0049804	total: 169ms	remaining: 12.5s
1:	learn: 1407.2532753	total: 333ms	remaining: 12.1s
2:	learn: 1308.3304954	total: 464ms	remaining: 11.1s
3:	learn: 1232.8346545	total: 566ms	remaining: 10s
4:	learn: 1191.2582377	total: 625ms	remaining: 8.75s
5:	learn: 1158.6401087	total: 830ms	remaining: 9.55s
6:	learn: 1135.5931320	total: 909ms	remaining: 8.83s
7:	learn: 1118.4792108	total: 1.04s	remaining: 8.74s
8:	learn: 1100.2287002	total: 1.11s	remaining: 8.18s
9:	learn: 1088.3729047	total: 1.25s	remaining: 8.13s
10:	learn: 1079.6725812	total: 1.45s	remaining: 8.42s
11:	learn: 1074.0643593	total: 1.58s	remaining: 8.32s
12:	learn: 1070.5264942	total: 1.68s	remaining: 8.02s
13:	learn: 1066.1995989	total: 1.86s	remaining: 8.1s
14:	learn: 1063.5170585	total: 1.99s	remaining: 7.96s
15:	learn: 1062.2815843	total: 2.17s	remaining: 7.99s
16:	learn: 1060.3874670	total: 2.37s	remaining: 8.09s
17:	learn: 1055.9459038	total: 2.48s	remaining: 7.86s
18:	learn: 1054.3001432	total: 2.67s	remaining: 7.88s
19:	learn: 1049.6743374	total: 2.85s	remaining: 7.85s
20:	learn: 1048.0738283	total: 3.04s	remaining: 7.81s
21:	learn: 1047.1717420	total: 3.14s	remaining: 7.57s
22:	learn: 1045.1963226	total: 3.3s	remaining: 7.45s
23:	learn: 1042.6383993	total: 3.41s	remaining: 7.25s
24:	learn: 1041.6440561	total: 3.51s	remaining: 7.02s
25:	learn: 1039.9335253	total: 3.59s	remaining: 6.76s
26:	learn: 1037.9712099	total: 3.74s	remaining: 6.65s
27:	learn: 1035.4629444	total: 3.92s	remaining: 6.58s
28:	learn: 1033.1111996	total: 4.03s	remaining: 6.39s
29:	learn: 1032.1338922	total: 4.17s	remaining: 6.25s
30:	learn: 1030.8393336	total: 4.27s	remaining: 6.07s
31:	learn: 1030.6502084	total: 4.28s	remaining: 5.75s
32:	learn: 1029.5520165	total: 4.47s	remaining: 5.69s
33:	learn: 1028.2095903	total: 4.58s	remaining: 5.53s
34:	learn: 1027.1683663	total: 4.76s	remaining: 5.44s
35:	learn: 1026.6145744	total: 4.99s	remaining: 5.41s
36:	learn: 1025.8787617	total: 5.14s	remaining: 5.27s
37:	learn: 1025.1117778	total: 5.3s	remaining: 5.17s
38:	learn: 1024.2185042	total: 5.42s	remaining: 5s
39:	learn: 1023.5035630	total: 5.52s	remaining: 4.83s
40:	learn: 1022.3542597	total: 5.68s	remaining: 4.71s
41:	learn: 1021.5248247	total: 5.8s	remaining: 4.56s
42:	learn: 1020.8788772	total: 5.96s	remaining: 4.43s
43:	learn: 1019.0375000	total: 6.06s	remaining: 4.27s
44:	learn: 1018.3610931	total: 6.16s	remaining: 4.11s
45:	learn: 1017.4508939	total: 6.29s	remaining: 3.96s
46:	learn: 1016.3101536	total: 6.42s	remaining: 3.83s
47:	learn: 1015.2032746	total: 6.54s	remaining: 3.68s
48:	learn: 1014.1798249	total: 6.62s	remaining: 3.52s
49:	learn: 1013.0721742	total: 6.69s	remaining: 3.34s
50:	learn: 1012.0429743	total: 6.74s	remaining: 3.17s
51:	learn: 1011.3554834	total: 6.97s	remaining: 3.08s
52:	learn: 1010.4357286	total: 7.21s	remaining: 3s
53:	learn: 1009.2902783	total: 7.31s	remaining: 2.84s
54:	learn: 1008.0490556	total: 7.46s	remaining: 2.71s
55:	learn: 1007.1118300	total: 7.54s	remaining: 2.56s
56:	learn: 1005.9172615	total: 7.65s	remaining: 2.41s
57:	learn: 1005.2657254	total: 7.76s	remaining: 2.27s
58:	learn: 1004.2971390	total: 7.87s	remaining: 2.13s
59:	learn: 1003.2659929	total: 7.96s	remaining: 1.99s
60:	learn: 1002.1415926	total: 8.12s	remaining: 1.86s
61:	learn: 1001.2953285	total: 8.31s	remaining: 1.74s
62:	learn: 1000.3733648	total: 8.45s	remaining: 1.61s
63:	learn: 999.4930519	total: 8.59s	remaining: 1.48s
64:	learn: 998.9849010	total: 8.81s	remaining: 1.35s
65:	learn: 998.0630684	total: 8.89s	remaining: 1.21s
66:	learn: 997.2184858	total: 8.94s	remaining: 1.07s
67:	learn: 996.4998516	total: 8.95s	remaining: 922ms
68:	learn: 996.0222604	total: 9.04s	remaining: 786ms
69:	learn: 995.1271301	total: 9.21s	remaining: 658ms
70:	learn: 994.5397525	total: 9.31s	remaining: 525ms
71:	learn: 993.5283893	total: 9.47s	remaining: 395ms
72:	learn: 992.6199958	total: 9.64s	remaining: 264ms
73:	learn: 992.0300892	total: 9.84s	remaining: 133ms
74:	learn: 990.8508722	total: 10s	remaining: 0us
0:	learn: 1523.6485678	total: 132ms	remaining: 9.76s
1:	learn: 1391.7996629	total: 256ms	remaining: 9.33s

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
0:	learn: 1521.4246617	total: 97.7ms	remaining: 7.23s
1:	learn: 1386.3842847	total: 242ms	remaining: 8.84s
2:	learn: 1286.3042394	total: 395ms	remaining: 9.48s
3:	learn: 1215.7897265	total: 536ms	remaining: 9.51s
4:	learn: 1167.6222463	total: 625ms	remaining: 8.74s
5:	learn: 1134.3866204	total: 727ms	remaining: 8.36s
6:	learn: 1109.1834423	total: 887ms	remaining: 8.61s
7:	learn: 1093.8450605	total: 1.06s	remaining: 8.88s
8:	learn: 1082.3333004	total: 1.29s	remaining: 9.49s
9:	learn: 1072.6250647	total: 1.41s	remaining: 9.16s
10:	learn: 1065.3001058	total: 1.54s	remaining: 8.98s
11:	learn: 1059.9312997	total: 1.67s	remaining: 8.77s
12:	learn: 1055.6201107	total: 1.81s	remaining: 8.66s
13:	learn: 1052.2063811	total: 1.88s	remaining: 8.19s
14:	learn: 1049.6238125	total: 2.02s	remaining: 8.1s
15:	learn: 1046.4960125	total: 2.16s	remaining: 7.96s
16:	learn: 1043.7947846	total: 2.33s	remaining: 7.95s
17:	learn: 1043.2505941	total: 2.49s	remaining: 7.88s
18:	learn: 1042.4420748	total: 2.67s	remaining: 7.86s
19:	learn: 1040.9484238	total: 2.79s	remaining: 7.67s
20:	learn: 1038.1165822	total: 2.93s	remaining: 7.53s
21:	learn: 1036.6156536	total: 3.16s	remaining: 7.61s
22:	learn: 1033.3616278	total: 3.29s	remaining: 7.45s
23:	learn: 1032.3561783	total: 3.46s	remaining: 7.36s
24:	learn: 1029.6696189	total: 3.57s	remaining: 7.13s
25:	learn: 1028.1075004	total: 3.77s	remaining: 7.1s
26:	learn: 1027.2920248	total: 3.89s	remaining: 6.92s
27:	learn: 1023.8771278	total: 4.02s	remaining: 6.74s
28:	learn: 1021.4545223	total: 4.14s	remaining: 6.56s
29:	learn: 1020.8761993	total: 4.16s	remaining: 6.24s
30:	learn: 1018.7718897	total: 4.18s	remaining: 5.93s
31:	learn: 1018.1835902	total: 4.33s	remaining: 5.82s
32:	learn: 1016.9967698	total: 4.48s	remaining: 5.7s
33:	learn: 1016.1098184	total: 4.58s	remaining: 5.52s
34:	learn: 1014.7180125	total: 4.68s	remaining: 5.35s
35:	learn: 1012.4856839	total: 4.86s	remaining: 5.27s
36:	learn: 1011.9620141	total: 5.02s	remaining: 5.15s
37:	learn: 1010.6591756	total: 5.23s	remaining: 5.09s
38:	learn: 1009.9316904	total: 5.33s	remaining: 4.92s
39:	learn: 1008.9904469	total: 5.48s	remaining: 4.8s
40:	learn: 1007.7487905	total: 5.63s	remaining: 4.67s
41:	learn: 1006.7705885	total: 5.73s	remaining: 4.5s
42:	learn: 1006.2407052	total: 5.84s	remaining: 4.34s
43:	learn: 1005.4940531	total: 5.97s	remaining: 4.21s
44:	learn: 1004.9190528	total: 6.06s	remaining: 4.04s
45:	learn: 1003.9412469	total: 6.17s	remaining: 3.89s
46:	learn: 1002.5516550	total: 6.32s	remaining: 3.77s
47:	learn: 1001.4977328	total: 6.44s	remaining: 3.62s
48:	learn: 1000.6584412	total: 6.54s	remaining: 3.47s
49:	learn: 1000.0239034	total: 6.71s	remaining: 3.35s
50:	learn: 999.3502970	total: 6.78s	remaining: 3.19s
51:	learn: 998.7734595	total: 6.89s	remaining: 3.05s
52:	learn: 998.1744634	total: 7.04s	remaining: 2.92s
53:	learn: 997.0117212	total: 7.19s	remaining: 2.8s
54:	learn: 995.8125756	total: 7.31s	remaining: 2.66s
55:	learn: 994.7089717	total: 7.46s	remaining: 2.53s
56:	learn: 994.0766315	total: 7.52s	remaining: 2.38s
57:	learn: 993.1453196	total: 7.72s	remaining: 2.26s
58:	learn: 991.9516060	total: 7.84s	remaining: 2.13s
59:	learn: 991.0268538	total: 8.18s	remaining: 2.04s
60:	learn: 990.5561108	total: 8.4s	remaining: 1.93s
61:	learn: 989.3555937	total: 8.55s	remaining: 1.79s
62:	learn: 988.4615270	total: 8.65s	remaining: 1.65s
63:	learn: 987.9896413	total: 8.71s	remaining: 1.5s
64:	learn: 987.5751479	total: 8.79s	remaining: 1.35s
65:	learn: 986.4997913	total: 9.13s	remaining: 1.25s
66:	learn: 985.6010085	total: 9.31s	remaining: 1.11s
67:	learn: 984.7456018	total: 9.46s	remaining: 974ms
68:	learn: 983.7875390	total: 9.61s	remaining: 835ms
69:	learn: 982.7311616	total: 9.68s	remaining: 691ms
70:	learn: 981.2144372	total: 9.8s	remaining: 552ms
71:	learn: 980.3769912	total: 9.96s	remaining: 415ms
72:	learn: 979.6637120	total: 10.1s	remaining: 276ms
73:	learn: 978.6434222	total: 10.2s	remaining: 138ms
74:	learn: 977.5258700	total: 10.3s	remaining: 0us
0:	learn: 1541.8600516	total: 165ms	remaining: 12.2s
1:	learn: 1397.9233237	total: 266ms	remaining: 9.7s
2:	learn: 1297.2542240	total: 367ms	remaining: 8.81s
3:	learn: 1227.2973179	total: 456ms	remaining: 8.1s
4:	learn: 1174.5498398	total: 577ms	remaining: 8.08s
5:	learn: 1140.5000024	total: 878ms	remaining: 10.1s
6:	learn: 1120.1132729	total: 1.04s	remaining: 10.1s
7:	learn: 1101.4433537	total: 1.26s	remaining: 10.6s
8:	learn: 1087.8906715	total: 1.47s	remaining: 10.8s
9:	learn: 1080.1345938	total: 1.68s	remaining: 10.9s
10:	learn: 1070.9518093	total: 1.79s	remaining: 10.4s
11:	learn: 1065.5899140	total: 1.99s	remaining: 10.5s
12:	learn: 1061.6193693	total: 2.12s	remaining: 10.1s
13:	learn: 1058.8676571	total: 2.19s	remaining: 9.52s
14:	learn: 1055.9067747	total: 2.38s	remaining: 9.54s
15:	learn: 1051.5989380	total: 2.54s	remaining: 9.35s
16:	learn: 1050.4384960	total: 2.65s	remaining: 9.03s
17:	learn: 1047.8682386	total: 2.84s	remaining: 9s
18:	learn: 1043.7438896	total: 2.95s	remaining: 8.7s
19:	learn: 1043.0389789	total: 2.96s	remaining: 8.15s
20:	learn: 1041.6273253	total: 3.05s	remaining: 7.85s
21:	learn: 1038.9275322	total: 3.15s	remaining: 7.6s
22:	learn: 1037.6756493	total: 3.21s	remaining: 7.26s
23:	learn: 1036.5498549	total: 3.29s	remaining: 6.99s
24:	learn: 1034.9663333	total: 3.44s	remaining: 6.89s
25:	learn: 1034.1354664	total: 3.65s	remaining: 6.87s
26:	learn: 1033.3176454	total: 3.79s	remaining: 6.75s
27:	learn: 1032.4895379	total: 3.86s	remaining: 6.47s
28:	learn: 1031.6955119	total: 4.02s	remaining: 6.38s
29:	learn: 1030.1290086	total: 4.1s	remaining: 6.15s
30:	learn: 1029.2409096	total: 4.21s	remaining: 5.98s
31:	learn: 1026.2470000	total: 4.28s	remaining: 5.75s
32:	learn: 1025.7838304	total: 4.29s	remaining: 5.46s
33:	learn: 1025.0026212	total: 4.41s	remaining: 5.31s
34:	learn: 1023.7063577	total: 4.59s	remaining: 5.25s
35:	learn: 1022.7859571	total: 4.74s	remaining: 5.14s
36:	learn: 1022.0609554	total: 4.85s	remaining: 4.98s
37:	learn: 1021.5104453	total: 4.98s	remaining: 4.85s
38:	learn: 1020.3244925	total: 5.13s	remaining: 4.74s
39:	learn: 1019.1385413	total: 5.29s	remaining: 4.63s
40:	learn: 1018.1318962	total: 5.42s	remaining: 4.5s
41:	learn: 1017.4934574	total: 5.53s	remaining: 4.35s
42:	learn: 1016.6452137	total: 5.71s	remaining: 4.25s
43:	learn: 1015.7695441	total: 5.96s	remaining: 4.2s
44:	learn: 1014.9341054	total: 6.12s	remaining: 4.08s
45:	learn: 1014.1599211	total: 6.25s	remaining: 3.94s
46:	learn: 1013.0812068	total: 6.38s	remaining: 3.8s
47:	learn: 1011.8228945	total: 6.53s	remaining: 3.67s
48:	learn: 1010.8022447	total: 6.62s	remaining: 3.51s
49:	learn: 1009.8786673	total: 6.8s	remaining: 3.4s
50:	learn: 1008.8061591	total: 6.91s	remaining: 3.25s
51:	learn: 1007.1973746	total: 7.05s	remaining: 3.12s
52:	learn: 1006.3233561	total: 7.15s	remaining: 2.97s
53:	learn: 1005.6415941	total: 7.34s	remaining: 2.85s
54:	learn: 1004.5380413	total: 7.45s	remaining: 2.71s
55:	learn: 1003.9980820	total: 7.61s	remaining: 2.58s
56:	learn: 1003.0665387	total: 7.69s	remaining: 2.43s
57:	learn: 1002.3016573	total: 7.92s	remaining: 2.32s
58:	learn: 1001.7564351	total: 8.03s	remaining: 2.18s
59:	learn: 1001.3395463	total: 8.09s	remaining: 2.02s
60:	learn: 1000.4571770	total: 8.3s	remaining: 1.91s
61:	learn: 999.4352351	total: 8.42s	remaining: 1.76s
62:	learn: 998.5811049	total: 8.5s	remaining: 1.62s
63:	learn: 998.1210733	total: 8.65s	remaining: 1.49s
64:	learn: 997.2363768	total: 8.75s	remaining: 1.35s
65:	learn: 995.9874712	total: 8.9s	remaining: 1.21s
66:	learn: 995.0676570	total: 9.08s	remaining: 1.08s
67:	learn: 994.3732024	total: 9.22s	remaining: 949ms
68:	learn: 993.3183224	total: 9.35s	remaining: 813ms
69:	learn: 992.7721188	total: 9.44s	remaining: 675ms
70:	learn: 992.3886619	total: 9.51s	remaining: 536ms
71:	learn: 991.7407834	total: 9.66s	remaining: 403ms
72:	learn: 990.8582795	total: 9.79s	remaining: 268ms
73:	learn: 989.9686170	total: 9.88s	remaining: 134ms
74:	learn: 989.6219525	total: 9.99s	remaining: 0us

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
0:	learn: 1507.8967725	total: 116ms	remaining: 8.59s
1:	learn: 1379.8765683	total: 240ms	remaining: 8.77s
2:	learn: 1284.0571548	total: 405ms	remaining: 9.71s
3:	learn: 1229.9620053	total: 440ms	remaining: 7.82s
4:	learn: 1177.4479476	total: 567ms	remaining: 7.94s
5:	learn: 1141.6810564	total: 701ms	remaining: 8.06s
6:	learn: 1116.5776575	total: 876ms	remaining: 8.51s
7:	learn: 1095.1815638	total: 935ms	remaining: 7.83s
8:	learn: 1083.3687239	total: 1.03s	remaining: 7.58s
9:	learn: 1074.5864265	total: 1.22s	remaining: 7.91s
10:	learn: 1065.5119991	total: 1.32s	remaining: 7.66s
11:	learn: 1060.3397947	total: 1.41s	remaining: 7.41s
12:	learn: 1055.6335695	total: 1.58s	remaining: 7.54s
13:	learn: 1051.5108521	total: 1.76s	remaining: 7.66s
14:	learn: 1048.8606777	total: 1.93s	remaining: 7.74s
15:	learn: 1046.2710013	total: 2.07s	remaining: 7.64s
16:	learn: 1043.9109132	total: 2.18s	remaining: 7.45s
17:	learn: 1042.1963907	total: 2.29s	remaining: 7.26s
18:	learn: 1040.9410904	total: 2.42s	remaining: 7.15s
19:	learn: 1039.0132396	total: 2.64s	remaining: 7.27s
20:	learn: 1037.0750820	total: 2.77s	remaining: 7.11s
21:	learn: 1034.5005802	total: 2.88s	remaining: 6.95s
22:	learn: 1032.5299708	total: 3.21s	remaining: 7.27s
23:	learn: 1030.9918089	total: 3.35s	remaining: 7.13s
24:	learn: 1030.1275248	total: 3.56s	remaining: 7.12s
25:	learn: 1028.5260520	total: 3.65s	remaining: 6.88s
26:	learn: 1027.1356283	total: 3.84s	remaining: 6.83s
27:	learn: 1025.7930030	total: 4.03s	remaining: 6.77s
28:	learn: 1024.2763420	total: 4.18s	remaining: 6.63s
29:	learn: 1023.4925380	total: 4.33s	remaining: 6.49s
30:	learn: 1022.8324551	total: 4.53s	remaining: 6.43s
31:	learn: 1020.6548108	total: 4.69s	remaining: 6.31s
32:	learn: 1019.9225866	total: 4.83s	remaining: 6.14s
33:	learn: 1019.0023670	total: 4.88s	remaining: 5.89s
34:	learn: 1016.6365750	total: 5.08s	remaining: 5.8s
35:	learn: 1015.3185910	total: 5.18s	remaining: 5.62s
36:	learn: 1014.5541248	total: 5.33s	remaining: 5.48s
37:	learn: 1013.7583468	total: 5.45s	remaining: 5.31s
38:	learn: 1011.7701873	total: 5.62s	remaining: 5.18s
39:	learn: 1010.3995406	total: 5.73s	remaining: 5.02s
40:	learn: 1009.1564933	total: 5.81s	remaining: 4.82s
41:	learn: 1008.3150851	total: 6.08s	remaining: 4.78s
42:	learn: 1007.4858834	total: 6.15s	remaining: 4.58s
43:	learn: 1006.4071842	total: 6.26s	remaining: 4.41s
44:	learn: 1005.3137288	total: 6.41s	remaining: 4.27s
45:	learn: 1004.2900687	total: 6.42s	remaining: 4.05s
46:	learn: 1003.5435954	total: 6.63s	remaining: 3.95s
47:	learn: 1002.2665766	total: 6.75s	remaining: 3.8s
48:	learn: 1000.9760188	total: 6.93s	remaining: 3.67s
49:	learn: 999.7824958	total: 7.07s	remaining: 3.53s
50:	learn: 998.5262561	total: 7.21s	remaining: 3.39s
51:	learn: 997.7409436	total: 7.33s	remaining: 3.24s
52:	learn: 997.0738510	total: 7.5s	remaining: 3.11s
53:	learn: 996.1191865	total: 7.64s	remaining: 2.97s
54:	learn: 995.5612282	total: 7.73s	remaining: 2.81s
55:	learn: 994.9915612	total: 7.83s	remaining: 2.66s
56:	learn: 994.4329446	total: 7.95s	remaining: 2.51s
57:	learn: 993.2100656	total: 8.09s	remaining: 2.37s
58:	learn: 992.2187506	total: 8.25s	remaining: 2.24s
59:	learn: 991.2300902	total: 8.39s	remaining: 2.1s
60:	learn: 990.7728622	total: 8.56s	remaining: 1.97s
61:	learn: 989.7613353	total: 8.69s	remaining: 1.82s
62:	learn: 989.0467052	total: 8.84s	remaining: 1.68s
63:	learn: 988.0982912	total: 9.01s	remaining: 1.55s
64:	learn: 986.7868369	total: 9.14s	remaining: 1.41s
65:	learn: 986.0459217	total: 9.23s	remaining: 1.26s
66:	learn: 985.1077540	total: 9.44s	remaining: 1.13s
67:	learn: 983.8858829	total: 9.6s	remaining: 988ms
68:	learn: 983.3639618	total: 9.7s	remaining: 843ms
69:	learn: 982.2191140	total: 9.79s	remaining: 700ms
70:	learn: 981.8029646	total: 9.98s	remaining: 562ms
71:	learn: 981.0889680	total: 10.1s	remaining: 422ms
72:	learn: 979.8388924	total: 10.3s	remaining: 283ms
73:	learn: 978.8782487	total: 10.5s	remaining: 141ms
74:	learn: 978.1704961	total: 10.5s	remaining: 0us
0:	learn: 1532.5920583	total: 55.1ms	remaining: 4.08s
1:	learn: 1396.8752487	total: 229ms	remaining: 8.37s
2:	learn: 1296.6274193	total: 431ms	remaining: 10.3s
3:	learn: 1224.6093562	total: 595ms	remaining: 10.6s
4:	learn: 1175.2505853	total: 806ms	remaining: 11.3s
5:	learn: 1141.0431946	total: 952ms	remaining: 11s
6:	learn: 1116.7917509	total: 1.08s	remaining: 10.5s
7:	learn: 1100.0197843	total: 1.18s	remaining: 9.86s
8:	learn: 1088.8833356	total: 1.32s	remaining: 9.68s
9:	learn: 1076.9041982	total: 1.48s	remaining: 9.65s
10:	learn: 1070.5856439	total: 1.61s	remaining: 9.4s
11:	learn: 1066.3792474	total: 1.81s	remaining: 9.48s
12:	learn: 1062.5084069	total: 1.89s	remaining: 9s
13:	learn: 1058.6179263	total: 2.09s	remaining: 9.13s
14:	learn: 1056.1855373	total: 2.2s	remaining: 8.8s
15:	learn: 1053.9927865	total: 2.27s	remaining: 8.38s
16:	learn: 1051.4646525	total: 2.46s	remaining: 8.4s
17:	learn: 1050.6904227	total: 2.57s	remaining: 8.15s
18:	learn: 1048.9212282	total: 2.71s	remaining: 7.99s
19:	learn: 1047.6104376	total: 2.79s	remaining: 7.69s
20:	learn: 1043.9350563	total: 2.94s	remaining: 7.55s
21:	learn: 1042.8362953	total: 3.1s	remaining: 7.47s
22:	learn: 1041.1186783	total: 3.27s	remaining: 7.39s
23:	learn: 1040.3528893	total: 3.33s	remaining: 7.08s
24:	learn: 1037.5162665	total: 3.51s	remaining: 7.03s
25:	learn: 1035.3995287	total: 3.63s	remaining: 6.83s
26:	learn: 1034.3030549	total: 3.78s	remaining: 6.72s
27:	learn: 1031.3469133	total: 3.89s	remaining: 6.53s
28:	learn: 1028.6901167	total: 4.08s	remaining: 6.48s
29:	learn: 1027.6684306	total: 4.18s	remaining: 6.27s
30:	learn: 1025.8516028	total: 4.24s	remaining: 6.02s
31:	learn: 1025.0492708	total: 4.38s	remaining: 5.88s
32:	learn: 1024.2665822	total: 4.62s	remaining: 5.88s
33:	learn: 1023.6768112	total: 4.76s	remaining: 5.74s
34:	learn: 1022.0915152	total: 4.97s	remaining: 5.68s
35:	learn: 1020.3905813	total: 5.06s	remaining: 5.48s
36:	learn: 1018.3309059	total: 5.36s	remaining: 5.51s
37:	learn: 1017.6340525	total: 5.4s	remaining: 5.26s
38:	learn: 1017.0520822	total: 5.64s	remaining: 5.2s
39:	learn: 1016.0114453	total: 5.72s	remaining: 5.01s
40:	learn: 1014.9320358	total: 5.89s	remaining: 4.88s
41:	learn: 1013.8838612	total: 6.02s	remaining: 4.73s
42:	learn: 1012.6840599	total: 6.05s	remaining: 4.5s
43:	learn: 1011.8360018	total: 6.17s	remaining: 4.35s
44:	learn: 1010.5865203	total: 6.38s	remaining: 4.25s
45:	learn: 1009.3803515	total: 6.57s	remaining: 4.14s
46:	learn: 1008.4031358	total: 6.65s	remaining: 3.96s
47:	learn: 1007.4664526	total: 6.78s	remaining: 3.81s
48:	learn: 1006.6142701	total: 6.89s	remaining: 3.66s
49:	learn: 1005.6903182	total: 7.15s	remaining: 3.57s
50:	learn: 1005.0138681	total: 7.32s	remaining: 3.44s
51:	learn: 1004.0432085	total: 7.42s	remaining: 3.28s
52:	learn: 1002.8799422	total: 7.53s	remaining: 3.13s
53:	learn: 1001.9204748	total: 7.67s	remaining: 2.98s
54:	learn: 1001.2475299	total: 7.8s	remaining: 2.83s
55:	learn: 1000.2395609	total: 7.88s	remaining: 2.67s
56:	learn: 999.7087253	total: 7.92s	remaining: 2.5s
57:	learn: 998.9488754	total: 8.06s	remaining: 2.36s
58:	learn: 997.9061183	total: 8.21s	remaining: 2.23s
59:	learn: 997.0142470	total: 8.36s	remaining: 2.09s
60:	learn: 995.6899051	total: 8.51s	remaining: 1.95s
61:	learn: 994.9025539	total: 8.71s	remaining: 1.83s
62:	learn: 994.0329247	total: 8.88s	remaining: 1.69s
63:	learn: 993.2458359	total: 9.02s	remaining: 1.55s
64:	learn: 992.8019642	total: 9.18s	remaining: 1.41s
65:	learn: 992.2292214	total: 9.39s	remaining: 1.28s
66:	learn: 990.9435665	total: 9.53s	remaining: 1.14s
67:	learn: 990.5323420	total: 9.7s	remaining: 998ms
68:	learn: 989.6618253	total: 9.81s	remaining: 853ms
69:	learn: 988.7659717	total: 9.88s	remaining: 706ms
70:	learn: 988.0649675	total: 10.2s	remaining: 572ms
71:	learn: 987.0673082	total: 10.3s	remaining: 428ms
72:	learn: 986.6528027	total: 10.4s	remaining: 285ms
73:	learn: 986.2831490	total: 10.5s	remaining: 142ms
0:	learn: 1533.4105304	total: 139ms	remaining: 10.3s
1:	learn: 1390.2178862	total: 293ms	remaining: 10.7s
2:	learn: 1290.3827910	total: 392ms	remaining: 9.41s
3:	learn: 1215.2349856	total: 538ms	remaining: 9.54s
4:	learn: 1169.1687998	total: 712ms	remaining: 9.97s
5:	learn: 1135.1938657	total: 809ms	remaining: 9.31s
6:	learn: 1114.6710036	total: 982ms	remaining: 9.54s
7:	learn: 1095.4902059	total: 1.12s	remaining: 9.41s
8:	learn: 1081.7734916	total: 1.25s	remaining: 9.14s
9:	learn: 1074.7946076	total: 1.48s	remaining: 9.64s
10:	learn: 1068.5423917	total: 1.64s	remaining: 9.52s
11:	learn: 1064.3286514	total: 1.65s	remaining: 8.67s
12:	learn: 1058.5074052	total: 1.7s	remaining: 8.12s
13:	learn: 1055.0742480	total: 1.82s	remaining: 7.95s
14:	learn: 1052.2667045	total: 2.07s	remaining: 8.27s
15:	learn: 1048.7349826	total: 2.29s	remaining: 8.43s
16:	learn: 1047.7136934	total: 2.49s	remaining: 8.5s
17:	learn: 1045.2663948	total: 2.75s	remaining: 8.71s
18:	learn: 1042.7443716	total: 2.88s	remaining: 8.49s
19:	learn: 1042.0667985	total: 3.01s	remaining: 8.29s
20:	learn: 1041.0394154	total: 3.11s	remaining: 8s
21:	learn: 1037.9852600	total: 3.29s	remaining: 7.94s
22:	learn: 1036.6049721	total: 3.38s	remaining: 7.64s
23:	learn: 1035.4475469	total: 3.58s	remaining: 7.6s
24:	learn: 1033.0677072	total: 3.91s	remaining: 7.82s
25:	learn: 1032.4554002	total: 4.09s	remaining: 7.71s
26:	learn: 1031.9094275	total: 4.28s	remaining: 7.6s
27:	learn: 1031.3602348	total: 4.48s	remaining: 7.53s
28:	learn: 1028.1996788	total: 4.66s	remaining: 7.4s
29:	learn: 1025.6793345	total: 4.84s	remaining: 7.25s
30:	learn: 1025.3524767	total: 4.91s	remaining: 6.96s
31:	learn: 1022.8740688	total: 5.02s	remaining: 6.74s
32:	learn: 1022.2921042	total: 5.19s	remaining: 6.6s
33:	learn: 1021.1612967	total: 5.28s	remaining: 6.37s
34:	learn: 1019.3216793	total: 5.4s	remaining: 6.17s
35:	learn: 1018.4476997	total: 5.64s	remaining: 6.12s
36:	learn: 1016.6140298	total: 5.87s	remaining: 6.03s
37:	learn: 1016.1527643	total: 6.06s	remaining: 5.9s
38:	learn: 1015.2752900	total: 6.24s	remaining: 5.76s
39:	learn: 1014.1564113	total: 6.41s	remaining: 5.61s
40:	learn: 1013.1404590	total: 6.55s	remaining: 5.43s
41:	learn: 1012.5566287	total: 6.63s	remaining: 5.21s
42:	learn: 1009.9356356	total: 6.73s	remaining: 5.01s
43:	learn: 1008.9728966	total: 6.8s	remaining: 4.79s
44:	learn: 1007.9496641	total: 6.87s	remaining: 4.58s
45:	learn: 1007.1420939	total: 6.96s	remaining: 4.39s
46:	learn: 1006.0107546	total: 7.1s	remaining: 4.23s
47:	learn: 1005.2231440	total: 7.24s	remaining: 4.07s
48:	learn: 1004.1186453	total: 7.38s	remaining: 3.91s
49:	learn: 1003.0110141	total: 7.5s	remaining: 3.75s
50:	learn: 1002.2256127	total: 7.66s	remaining: 3.6s
51:	learn: 1001.3904982	total: 7.84s	remaining: 3.47s
52:	learn: 1000.1131827	total: 7.98s	remaining: 3.31s
53:	learn: 999.1263663	total: 8.17s	remaining: 3.18s
54:	learn: 998.5892486	total: 8.32s	remaining: 3.03s
55:	learn: 997.5101560	total: 8.48s	remaining: 2.88s
56:	learn: 997.0091440	total: 8.71s	remaining: 2.75s
57:	learn: 996.1675332	total: 8.86s	remaining: 2.6s
58:	learn: 995.0159437	total: 8.98s	remaining: 2.44s
59:	learn: 994.3261381	total: 9.01s	remaining: 2.25s
60:	learn: 993.8994847	total: 9.08s	remaining: 2.08s
61:	learn: 992.9010789	total: 9.26s	remaining: 1.94s
62:	learn: 991.6588811	total: 9.31s	remaining: 1.77s
63:	learn: 991.1920581	total: 9.49s	remaining: 1.63s
64:	learn: 990.4582040	total: 9.75s	remaining: 1.5s
65:	learn: 989.9090616	total: 9.79s	remaining: 1.33s
66:	learn: 989.0704207	total: 9.86s	remaining: 1.18s
67:	learn: 987.8660782	total: 10s	remaining: 1.03s
68:	learn: 987.5057056	total: 10.1s	remaining: 882ms
69:	learn: 986.3454706	total: 10.2s	remaining: 731ms
70:	learn: 984.9288768	total: 10.3s	remaining: 581ms
71:	learn: 983.9055283	total: 10.4s	remaining: 432ms
72:	learn: 982.9106584	total: 10.4s	remaining: 286ms
73:	learn: 982.1670103	total: 10.8s	remaining: 146ms
74:	learn: 981.0049581	total: 10.9s	remaining: 0us
0:	learn: 1530.5488104	total: 122ms	remaining: 9.02s
1:	learn: 1396.0786312	total: 344ms	remaining: 12.6s
2:	learn: 1296.3990955	total: 481ms	remaining: 11.5s
3:	learn: 1224.8417327	total: 680ms	remaining: 12.1s
4:	learn: 1180.8713039	total: 789ms	remaining: 11s
5:	learn: 1144.9515777	total: 900ms	remaining: 10.3s
6:	learn: 1118.9369121	total: 1.15s	remaining: 11.2s
7:	learn: 1100.8677259	total: 1.29s	remaining: 10.8s
8:	learn: 1089.1011715	total: 1.39s	remaining: 10.2s
9:	learn: 1080.5809182	total: 1.51s	remaining: 9.8s
10:	learn: 1074.5570399	total: 1.64s	remaining: 9.53s
11:	learn: 1067.5330892	total: 1.84s	remaining: 9.66s
12:	learn: 1063.7063579	total: 2s	remaining: 9.57s
13:	learn: 1058.5506091	total: 2.08s	remaining: 9.06s
14:	learn: 1056.1854881	total: 2.3s	remaining: 9.21s
15:	learn: 1054.3397946	total: 2.49s	remaining: 9.18s
16:	learn: 1050.6240279	total: 2.63s	remaining: 8.98s
17:	learn: 1049.1579771	total: 2.77s	remaining: 8.76s
18:	learn: 1047.0504155	total: 2.86s	remaining: 8.43s
19:	learn: 1046.1694317	total: 3.04s	remaining: 8.37s
20:	learn: 1045.1328223	total: 3.14s	remaining: 8.07s
21:	learn: 1043.8525341	total: 3.25s	remaining: 7.82s
22:	learn: 1041.3776777	total: 3.41s	remaining: 7.71s
23:	learn: 1040.4444364	total: 3.7s	remaining: 7.86s
24:	learn: 1039.0038363	total: 3.81s	remaining: 7.63s
25:	learn: 1038.2186093	total: 3.89s	remaining: 7.34s
26:	learn: 1036.6137903	total: 4.07s	remaining: 7.24s
27:	learn: 1035.0685831	total: 4.23s	remaining: 7.1s
28:	learn: 1032.4783018	total: 4.34s	remaining: 6.88s
29:	learn: 1031.3055037	total: 4.52s	remaining: 6.79s
30:	learn: 1030.6594010	total: 4.67s	remaining: 6.63s
31:	learn: 1029.8994450	total: 4.78s	remaining: 6.42s
32:	learn: 1028.9374047	total: 4.84s	remaining: 6.17s
33:	learn: 1027.7162616	total: 4.89s	remaining: 5.89s
34:	learn: 1025.7688238	total: 5.07s	remaining: 5.8s
35:	learn: 1024.6714955	total: 5.22s	remaining: 5.66s
36:	learn: 1023.5278356	total: 5.39s	remaining: 5.53s
37:	learn: 1022.4077891	total: 5.53s	remaining: 5.39s
38:	learn: 1021.7654990	total: 5.73s	remaining: 5.29s
39:	learn: 1020.8025769	total: 5.89s	remaining: 5.15s
40:	learn: 1019.8409439	total: 6.01s	remaining: 4.99s
41:	learn: 1017.6485677	total: 6.24s	remaining: 4.9s
42:	learn: 1016.8587156	total: 6.41s	remaining: 4.77s
43:	learn: 1016.1274378	total: 6.54s	remaining: 4.61s
44:	learn: 1015.0651353	total: 6.68s	remaining: 4.46s
45:	learn: 1014.0086849	total: 6.88s	remaining: 4.33s
46:	learn: 1013.1472446	total: 7.05s	remaining: 4.2s
47:	learn: 1012.1235443	total: 7.2s	remaining: 4.05s
48:	learn: 1011.3941041	total: 7.33s	remaining: 3.89s
49:	learn: 1010.4284404	total: 7.44s	remaining: 3.72s
50:	learn: 1009.7265271	total: 7.57s	remaining: 3.56s
51:	learn: 1008.7598609	total: 7.76s	remaining: 3.43s
52:	learn: 1007.7672704	total: 7.99s	remaining: 3.32s
53:	learn: 1007.0433382	total: 8.2s	remaining: 3.19s
54:	learn: 1005.7206985	total: 8.33s	remaining: 3.03s
55:	learn: 1004.9091071	total: 8.49s	remaining: 2.88s
56:	learn: 1004.3763598	total: 8.64s	remaining: 2.73s
57:	learn: 1003.9363363	total: 8.8s	remaining: 2.58s
58:	learn: 1002.6126949	total: 8.94s	remaining: 2.42s
59:	learn: 1001.4767338	total: 9.01s	remaining: 2.25s
60:	learn: 1000.3713947	total: 9.15s	remaining: 2.1s
61:	learn: 999.5442188	total: 9.37s	remaining: 1.97s
62:	learn: 998.4657320	total: 9.54s	remaining: 1.82s
63:	learn: 997.5979971	total: 9.69s	remaining: 1.67s
64:	learn: 996.8211911	total: 9.87s	remaining: 1.52s
65:	learn: 996.0946734	total: 10s	remaining: 1.37s
66:	learn: 995.4118299	total: 10.1s	remaining: 1.21s
67:	learn: 994.5339465	total: 10.3s	remaining: 1.06s
68:	learn: 993.5712597	total: 10.4s	remaining: 901ms
69:	learn: 993.1333863	total: 10.4s	remaining: 746ms
70:	learn: 992.2730388	total: 10.6s	remaining: 597ms
71:	learn: 991.8708574	total: 10.7s	remaining: 447ms
72:	learn: 991.2672070	total: 11s	remaining: 300ms
73:	learn: 990.9106628	total: 11.1s	remaining: 150ms
74:	learn: 990.0260101	total: 11.3s	remaining: 0us
0:	learn: 1523.9581740	total: 71.2ms	remaining: 5.27s
1:	learn: 1388.9797081	total: 241ms	remaining: 8.78s
2:	learn: 1289.1250240	total: 325ms	remaining: 7.79s

74:	learn: 985.6371669	total: 10.6s	remaining: 0us
0:	learn: 1534.0380420	total: 136ms	remaining: 10.1s
1:	learn: 1406.0526279	total: 240ms	remaining: 8.75s
2:	learn: 1305.7402585	total: 451ms	remaining: 10.8s
3:	learn: 1234.7042343	total: 585ms	remaining: 10.4s
4:	learn: 1181.7887264	total: 754ms	remaining: 10.6s
5:	learn: 1148.7766854	total: 893ms	remaining: 10.3s
6:	learn: 1124.5062783	total: 1.11s	remaining: 10.8s
7:	learn: 1107.4280897	total: 1.24s	remaining: 10.3s
8:	learn: 1094.1117572	total: 1.38s	remaining: 10.1s
9:	learn: 1085.8624607	total: 1.5s	remaining: 9.77s
10:	learn: 1077.9217055	total: 1.69s	remaining: 9.84s
11:	learn: 1073.1596986	total: 1.77s	remaining: 9.31s
12:	learn: 1069.8002898	total: 1.88s	remaining: 8.96s
13:	learn: 1067.5378994	total: 2.02s	remaining: 8.78s
14:	learn: 1064.3166435	total: 2.17s	remaining: 8.68s
15:	learn: 1061.9167785	total: 2.26s	remaining: 8.34s
16:	learn: 1057.7550765	total: 2.37s	remaining: 8.1s
17:	learn: 1055.4036565	total: 2.47s	remaining: 7.83s
18:	learn: 1054.0465524	total: 2.58s	remaining: 7.61s
19:	learn: 1052.9808897	total: 2.69s	remaining: 7.4s
20:	learn: 1051.1877145	total: 2.84s	remaining: 7.31s
21:	learn: 1049.6384187	total: 2.96s	remaining: 7.13s
22:	learn: 1048.5799485	total: 3.05s	remaining: 6.9s
23:	learn: 1047.4435434	total: 3.19s	remaining: 6.78s
24:	learn: 1046.5034459	total: 3.37s	remaining: 6.74s
25:	learn: 1043.8060513	total: 3.5s	remaining: 6.59s
26:	learn: 1042.4287865	total: 3.63s	remaining: 6.46s
27:	learn: 1041.7779176	total: 3.71s	remaining: 6.23s
28:	learn: 1040.7063388	total: 3.79s	remaining: 6.01s
29:	learn: 1037.8238608	total: 3.93s	remaining: 5.89s
30:	learn: 1037.1313616	total: 4.13s	remaining: 5.86s
31:	learn: 1036.0508651	total: 4.25s	remaining: 5.72s
32:	learn: 1035.4334551	total: 4.44s	remaining: 5.65s
33:	learn: 1034.7891151	total: 4.76s	remaining: 5.74s
34:	learn: 1033.6073373	total: 4.93s	remaining: 5.64s
35:	learn: 1032.2368413	total: 5.01s	remaining: 5.43s
36:	learn: 1031.6047046	total: 5.08s	remaining: 5.22s
37:	learn: 1030.9764467	total: 5.2s	remaining: 5.07s
38:	learn: 1029.8489151	total: 5.28s	remaining: 4.87s
39:	learn: 1028.8033720	total: 5.44s	remaining: 4.76s
40:	learn: 1028.0723794	total: 5.56s	remaining: 4.61s
41:	learn: 1027.2276293	total: 5.66s	remaining: 4.45s
42:	learn: 1025.7825149	total: 5.81s	remaining: 4.32s
43:	learn: 1025.0942272	total: 5.93s	remaining: 4.18s
44:	learn: 1024.5539820	total: 5.99s	remaining: 3.99s
45:	learn: 1023.5201793	total: 6.22s	remaining: 3.92s
46:	learn: 1022.4059065	total: 6.4s	remaining: 3.81s
47:	learn: 1021.4072573	total: 6.48s	remaining: 3.64s
48:	learn: 1020.4428513	total: 6.65s	remaining: 3.53s
49:	learn: 1019.2008894	total: 6.88s	remaining: 3.44s
50:	learn: 1018.3718063	total: 7.13s	remaining: 3.36s
51:	learn: 1017.7812850	total: 7.25s	remaining: 3.21s
52:	learn: 1016.7087255	total: 7.34s	remaining: 3.04s
53:	learn: 1015.8448944	total: 7.45s	remaining: 2.9s
54:	learn: 1015.0063131	total: 7.66s	remaining: 2.79s
55:	learn: 1014.1756751	total: 7.73s	remaining: 2.62s
56:	learn: 1013.6531647	total: 7.92s	remaining: 2.5s
57:	learn: 1012.5310644	total: 7.99s	remaining: 2.34s
58:	learn: 1011.7931259	total: 8.08s	remaining: 2.19s
59:	learn: 1011.1619754	total: 8.26s	remaining: 2.06s
60:	learn: 1010.1307408	total: 8.42s	remaining: 1.93s
61:	learn: 1009.4173496	total: 8.51s	remaining: 1.78s
62:	learn: 1008.6703767	total: 8.72s	remaining: 1.66s
63:	learn: 1007.7414189	total: 8.89s	remaining: 1.53s
64:	learn: 1007.3708197	total: 9.02s	remaining: 1.39s
65:	learn: 1006.9694377	total: 9.15s	remaining: 1.25s
66:	learn: 1006.4815093	total: 9.32s	remaining: 1.11s
67:	learn: 1005.4793697	total: 9.46s	remaining: 974ms
68:	learn: 1004.5372840	total: 9.56s	remaining: 832ms
69:	learn: 1003.5096315	total: 9.69s	remaining: 692ms
70:	learn: 1002.6815336	total: 9.81s	remaining: 553ms
71:	learn: 1001.6442657	total: 10.1s	remaining: 420ms
72:	learn: 1000.6921788	total: 10.2s	remaining: 279ms
73:	learn: 1000.3196517	total: 10.3s	remaining: 140ms
74:	learn: 999.5275884	total: 10.5s	remaining: 0us
0:	learn: 1537.3643884	total: 241ms	remaining: 17.8s
1:	learn: 1395.4793020	total: 360ms	remaining: 13.1s
2:	learn: 1321.9213444	total: 428ms	remaining: 10.3s
3:	learn: 1243.3544551	total: 586ms	remaining: 10.4s
4:	learn: 1187.9057459	total: 699ms	remaining: 9.78s
5:	learn: 1147.2792664	total: 778ms	remaining: 8.94s
6:	learn: 1119.5847860	total: 886ms	remaining: 8.61s
7:	learn: 1099.8265766	total: 1.03s	remaining: 8.59s
8:	learn: 1088.6742063	total: 1.14s	remaining: 8.35s
9:	learn: 1077.4287894	total: 1.24s	remaining: 8.06s
10:	learn: 1071.0612916	total: 1.39s	remaining: 8.09s
11:	learn: 1068.5147923	total: 1.43s	remaining: 7.53s
12:	learn: 1063.3312957	total: 1.56s	remaining: 7.42s
13:	learn: 1059.1945965	total: 1.72s	remaining: 7.51s
14:	learn: 1058.6445815	total: 1.74s	remaining: 6.97s
15:	learn: 1052.9350818	total: 1.84s	remaining: 6.79s
16:	learn: 1049.6822692	total: 1.96s	remaining: 6.68s
17:	learn: 1047.0434986	total: 2.08s	remaining: 6.57s
18:	learn: 1045.6954480	total: 2.21s	remaining: 6.51s
19:	learn: 1044.2576168	total: 2.39s	remaining: 6.56s
20:	learn: 1039.8305957	total: 2.44s	remaining: 6.29s
21:	learn: 1038.4998710	total: 2.53s	remaining: 6.09s
22:	learn: 1036.3356384	total: 2.64s	remaining: 5.97s
23:	learn: 1035.4006715	total: 2.74s	remaining: 5.82s
24:	learn: 1034.4850602	total: 2.79s	remaining: 5.58s
25:	learn: 1031.0347140	total: 2.87s	remaining: 5.41s
26:	learn: 1029.2050053	total: 3.06s	remaining: 5.44s
27:	learn: 1028.3596661	total: 3.14s	remaining: 5.27s
28:	learn: 1027.3891755	total: 3.23s	remaining: 5.13s
29:	learn: 1025.6679143	total: 3.35s	remaining: 5.03s
30:	learn: 1025.0423126	total: 3.55s	remaining: 5.04s
31:	learn: 1024.5850108	total: 3.71s	remaining: 4.99s
32:	learn: 1023.6663946	total: 3.8s	remaining: 4.83s
33:	learn: 1023.1290573	total: 3.95s	remaining: 4.77s
34:	learn: 1022.5081333	total: 4.1s	remaining: 4.68s
35:	learn: 1021.8170543	total: 4.22s	remaining: 4.57s
36:	learn: 1021.0140519	total: 4.37s	remaining: 4.49s
37:	learn: 1020.7017594	total: 4.39s	remaining: 4.27s
38:	learn: 1018.5064889	total: 4.58s	remaining: 4.23s
39:	learn: 1017.5831148	total: 4.75s	remaining: 4.16s
40:	learn: 1016.8278706	total: 4.79s	remaining: 3.98s
41:	learn: 1014.4688100	total: 4.83s	remaining: 3.8s
42:	learn: 1013.7379862	total: 4.99s	remaining: 3.71s
43:	learn: 1012.5460303	total: 5.09s	remaining: 3.58s
44:	learn: 1011.7556243	total: 5.16s	remaining: 3.44s
45:	learn: 1010.8682622	total: 5.29s	remaining: 3.33s
46:	learn: 1010.0699113	total: 5.45s	remaining: 3.25s
47:	learn: 1009.0068369	total: 5.58s	remaining: 3.14s
48:	learn: 1008.2129604	total: 5.72s	remaining: 3.04s
49:	learn: 1007.3086926	total: 5.85s	remaining: 2.92s
50:	learn: 1006.2350802	total: 6.06s	remaining: 2.85s
51:	learn: 1005.3889075	total: 6.16s	remaining: 2.73s
52:	learn: 1004.6323681	total: 6.22s	remaining: 2.58s
53:	learn: 1003.2289703	total: 6.29s	remaining: 2.44s
54:	learn: 1002.3782606	total: 6.48s	remaining: 2.36s
55:	learn: 1001.8337617	total: 6.55s	remaining: 2.22s
56:	learn: 1000.8241294	total: 6.67s	remaining: 2.1s
57:	learn: 999.2802838	total: 6.76s	remaining: 1.98s
58:	learn: 998.8304153	total: 6.87s	remaining: 1.86s
59:	learn: 997.8465300	total: 7.06s	remaining: 1.77s
60:	learn: 996.6827394	total: 7.22s	remaining: 1.66s
61:	learn: 996.2133015	total: 7.53s	remaining: 1.58s
62:	learn: 995.5806367	total: 7.62s	remaining: 1.45s
63:	learn: 994.8858064	total: 7.73s	remaining: 1.33s
64:	learn: 994.2173882	total: 7.82s	remaining: 1.2s
65:	learn: 992.9995682	total: 8.05s	remaining: 1.1s
66:	learn: 992.1393286	total: 8.26s	remaining: 986ms
67:	learn: 991.2413518	total: 8.36s	remaining: 861ms
68:	learn: 990.8244991	total: 8.43s	remaining: 733ms
69:	learn: 990.1432512	total: 8.5s	remaining: 607ms
70:	learn: 989.2556009	total: 8.66s	remaining: 488ms
71:	learn: 988.5600922	total: 8.78s	remaining: 366ms
72:	learn: 988.1713079	total: 8.91s	remaining: 244ms
73:	learn: 987.2526992	total: 9.06s	remaining: 122ms
74:	learn: 986.9400802	total: 9.18s	remaining: 0us
0:	learn: 1517.4186682	total: 222ms	remaining: 16.4s
3:	learn: 1225.7839669	total: 757ms	remaining: 13.4s
4:	learn: 1177.9495803	total: 934ms	remaining: 13.1s
5:	learn: 1144.5588474	total: 1.1s	remaining: 12.7s
6:	learn: 1122.2754911	total: 1.23s	remaining: 11.9s
7:	learn: 1108.5762972	total: 1.32s	remaining: 11.1s
8:	learn: 1097.1202326	total: 1.47s	remaining: 10.8s
9:	learn: 1089.9788840	total: 1.63s	remaining: 10.6s
10:	learn: 1083.9659323	total: 1.77s	remaining: 10.3s
11:	learn: 1076.8509708	total: 1.89s	remaining: 9.91s
12:	learn: 1072.8526146	total: 1.98s	remaining: 9.45s
13:	learn: 1070.0774961	total: 2.07s	remaining: 9.01s
14:	learn: 1066.8327840	total: 2.28s	remaining: 9.11s
15:	learn: 1064.0930675	total: 2.49s	remaining: 9.2s
16:	learn: 1063.6540315	total: 2.66s	remaining: 9.09s
17:	learn: 1061.3166208	total: 2.8s	remaining: 8.87s
18:	learn: 1060.4776639	total: 2.87s	remaining: 8.46s
19:	learn: 1059.4172478	total: 3.01s	remaining: 8.27s
20:	learn: 1058.5166687	total: 3.17s	remaining: 8.14s
21:	learn: 1056.9853674	total: 3.27s	remaining: 7.88s
22:	learn: 1054.6445614	total: 3.48s	remaining: 7.86s
23:	learn: 1053.0343600	total: 3.61s	remaining: 7.67s
24:	learn: 1052.0898157	total: 3.74s	remaining: 7.49s
25:	learn: 1051.5261362	total: 3.85s	remaining: 7.25s
26:	learn: 1050.8395832	total: 4s	remaining: 7.11s
27:	learn: 1049.4114842	total: 4.11s	remaining: 6.91s
28:	learn: 1047.1174846	total: 4.25s	remaining: 6.74s
29:	learn: 1045.7023844	total: 4.37s	remaining: 6.56s
30:	learn: 1045.0426144	total: 4.53s	remaining: 6.42s
31:	learn: 1044.3951714	total: 4.73s	remaining: 6.36s
32:	learn: 1043.2797999	total: 4.88s	remaining: 6.22s
33:	learn: 1042.4663112	total: 5.02s	remaining: 6.06s
34:	learn: 1040.0541210	total: 5.2s	remaining: 5.94s
35:	learn: 1039.1034304	total: 5.42s	remaining: 5.87s
36:	learn: 1038.4667819	total: 5.6s	remaining: 5.75s
37:	learn: 1037.8970706	total: 5.71s	remaining: 5.57s
38:	learn: 1036.8349029	total: 5.85s	remaining: 5.4s
39:	learn: 1036.2120110	total: 5.95s	remaining: 5.2s
40:	learn: 1035.3998095	total: 6.08s	remaining: 5.05s
41:	learn: 1032.0985371	total: 6.2s	remaining: 4.87s
42:	learn: 1031.2257815	total: 6.38s	remaining: 4.75s
43:	learn: 1029.6114791	total: 6.5s	remaining: 4.58s
44:	learn: 1027.8920888	total: 6.65s	remaining: 4.43s
45:	learn: 1026.8131585	total: 6.76s	remaining: 4.26s
46:	learn: 1025.7129080	total: 6.87s	remaining: 4.09s
47:	learn: 1024.8616732	total: 7.1s	remaining: 3.99s
48:	learn: 1023.9924085	total: 7.25s	remaining: 3.85s
49:	learn: 1023.1912340	total: 7.35s	remaining: 3.67s
50:	learn: 1022.3413460	total: 7.52s	remaining: 3.54s
51:	learn: 1021.4831551	total: 7.63s	remaining: 3.37s
52:	learn: 1020.4551896	total: 7.72s	remaining: 3.2s
53:	learn: 1019.5196699	total: 7.83s	remaining: 3.04s
54:	learn: 1018.5286694	total: 7.98s	remaining: 2.9s
55:	learn: 1017.6751858	total: 8.05s	remaining: 2.73s
56:	learn: 1016.9746795	total: 8.26s	remaining: 2.61s
57:	learn: 1015.8450239	total: 8.49s	remaining: 2.49s
58:	learn: 1014.7653987	total: 8.74s	remaining: 2.37s
59:	learn: 1013.7824273	total: 8.85s	remaining: 2.21s
60:	learn: 1013.0926031	total: 9s	remaining: 2.07s
61:	learn: 1011.7187202	total: 9.11s	remaining: 1.91s
62:	learn: 1010.7998173	total: 9.39s	remaining: 1.79s
63:	learn: 1010.0880548	total: 9.5s	remaining: 1.63s
64:	learn: 1009.6464236	total: 9.56s	remaining: 1.47s
65:	learn: 1008.8183929	total: 9.82s	remaining: 1.34s
66:	learn: 1007.9833136	total: 10s	remaining: 1.2s
67:	learn: 1007.1196703	total: 10.2s	remaining: 1.05s
68:	learn: 1006.6113243	total: 10.3s	remaining: 891ms
69:	learn: 1005.8381349	total: 10.5s	remaining: 752ms
70:	learn: 1005.0381105	total: 10.7s	remaining: 602ms
71:	learn: 1003.7582747	total: 10.7s	remaining: 447ms
72:	learn: 1002.7649145	total: 10.8s	remaining: 297ms
73:	learn: 1001.9222287	total: 11s	remaining: 148ms
74:	learn: 1001.5086591	total: 11.2s	remaining: 0us
[CV] END stack__CAT__learning_rate=0.2, stack__CAT__max_depth=8, stack__CAT__n_estimators=75, stack__LGBM__learning_rate=0.3, stack__LGBM__max_depth=4, stack__LGBM__n_estimators=150, stack__XGB__learning_rate=0.05, stack__XGB__max_depth=6, stack__XGB__n_estimators=200, stack__final_estimator__max_depth=4, stack__final_estimator__n_estimators=150; total time=40.0min
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.287980 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 819
[LightGBM] [Info] Number of data points in the train set: 6818, number of used features: 39
[LightGBM] [Info] Start training from score 2180.679468
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

2:	learn: 1299.2010182	total: 437ms	remaining: 10.5s
3:	learn: 1231.2414933	total: 551ms	remaining: 9.78s
4:	learn: 1178.3268631	total: 694ms	remaining: 9.71s
5:	learn: 1143.2181396	total: 785ms	remaining: 9.02s
6:	learn: 1120.9140638	total: 959ms	remaining: 9.32s
7:	learn: 1106.0275218	total: 1.14s	remaining: 9.57s
8:	learn: 1095.1011029	total: 1.22s	remaining: 8.96s
9:	learn: 1084.3736056	total: 1.38s	remaining: 8.95s
10:	learn: 1076.5931377	total: 1.55s	remaining: 9.01s
11:	learn: 1071.0951625	total: 1.74s	remaining: 9.11s
12:	learn: 1068.3007889	total: 1.91s	remaining: 9.13s
13:	learn: 1064.1248645	total: 2.13s	remaining: 9.3s
14:	learn: 1061.3736696	total: 2.21s	remaining: 8.86s
15:	learn: 1056.6483982	total: 2.41s	remaining: 8.89s
16:	learn: 1054.1893113	total: 2.57s	remaining: 8.78s
17:	learn: 1051.7093231	total: 2.73s	remaining: 8.64s
18:	learn: 1050.3531428	total: 2.82s	remaining: 8.31s
19:	learn: 1048.5740119	total: 2.88s	remaining: 7.93s
20:	learn: 1047.1176761	total: 3s	remaining: 7.71s
21:	learn: 1046.0888077	total: 3.11s	remaining: 7.49s
22:	learn: 1043.8803084	total: 3.24s	remaining: 7.32s
23:	learn: 1042.2563647	total: 3.38s	remaining: 7.19s
24:	learn: 1041.8367825	total: 3.55s	remaining: 7.09s
25:	learn: 1041.3261887	total: 3.71s	remaining: 7s
26:	learn: 1040.6362465	total: 3.88s	remaining: 6.9s
27:	learn: 1039.8044043	total: 4.11s	remaining: 6.89s
28:	learn: 1038.2978372	total: 4.24s	remaining: 6.73s
29:	learn: 1036.2101210	total: 4.39s	remaining: 6.59s
30:	learn: 1035.7831715	total: 4.63s	remaining: 6.57s
31:	learn: 1034.6565569	total: 4.76s	remaining: 6.39s
32:	learn: 1031.9944787	total: 4.9s	remaining: 6.23s
33:	learn: 1030.0974323	total: 4.95s	remaining: 5.97s
34:	learn: 1029.4144194	total: 5.14s	remaining: 5.88s
35:	learn: 1028.6850282	total: 5.25s	remaining: 5.69s
36:	learn: 1027.6416501	total: 5.4s	remaining: 5.55s
37:	learn: 1027.1703579	total: 5.43s	remaining: 5.29s
38:	learn: 1026.4348668	total: 5.54s	remaining: 5.11s
39:	learn: 1024.9770775	total: 5.61s	remaining: 4.91s
40:	learn: 1023.9947021	total: 5.73s	remaining: 4.75s
41:	learn: 1023.4393417	total: 5.82s	remaining: 4.57s
42:	learn: 1022.7568060	total: 6.06s	remaining: 4.51s
43:	learn: 1021.7110576	total: 6.21s	remaining: 4.37s
44:	learn: 1020.9177195	total: 6.38s	remaining: 4.25s
45:	learn: 1020.2344823	total: 6.5s	remaining: 4.1s
46:	learn: 1019.2537150	total: 6.61s	remaining: 3.94s
47:	learn: 1018.4722639	total: 6.79s	remaining: 3.82s
48:	learn: 1017.3628829	total: 6.91s	remaining: 3.67s
49:	learn: 1016.5297485	total: 6.97s	remaining: 3.49s
50:	learn: 1015.7971454	total: 7.12s	remaining: 3.35s
51:	learn: 1015.0824342	total: 7.17s	remaining: 3.17s
52:	learn: 1014.2149548	total: 7.22s	remaining: 3s
53:	learn: 1013.1495504	total: 7.33s	remaining: 2.85s
54:	learn: 1012.5850873	total: 7.43s	remaining: 2.7s
55:	learn: 1011.4509257	total: 7.58s	remaining: 2.57s
56:	learn: 1010.7349407	total: 7.7s	remaining: 2.43s
57:	learn: 1009.6159674	total: 7.85s	remaining: 2.3s
58:	learn: 1008.7290887	total: 7.97s	remaining: 2.16s
59:	learn: 1007.4067703	total: 8.06s	remaining: 2.02s
60:	learn: 1006.6289699	total: 8.18s	remaining: 1.88s
61:	learn: 1006.0189891	total: 8.3s	remaining: 1.74s
62:	learn: 1005.5939650	total: 8.42s	remaining: 1.6s
63:	learn: 1004.2163810	total: 8.46s	remaining: 1.45s
64:	learn: 1003.4139429	total: 8.66s	remaining: 1.33s
65:	learn: 1002.1644186	total: 8.75s	remaining: 1.19s
66:	learn: 1001.2404477	total: 8.88s	remaining: 1.06s
67:	learn: 1000.2736494	total: 9.08s	remaining: 934ms
68:	learn: 999.2861575	total: 9.15s	remaining: 796ms
69:	learn: 998.4223175	total: 9.21s	remaining: 658ms
70:	learn: 997.6034208	total: 9.38s	remaining: 528ms
71:	learn: 996.7837237	total: 9.59s	remaining: 399ms
72:	learn: 996.0799154	total: 9.73s	remaining: 267ms
73:	learn: 994.9570015	total: 9.9s	remaining: 134ms
74:	learn: 993.7448725	total: 10s	remaining: 0us
[CV] END stack__CAT__learning_rate=0.2, stack__CAT__max_depth=8, stack__CAT__n_estimators=75, stack__LGBM__learning_rate=0.3, stack__LGBM__max_depth=4, stack__LGBM__n_estimators=150, stack__XGB__learning_rate=0.05, stack__XGB__max_depth=6, stack__XGB__n_estimators=200, stack__final_estimator__max_depth=4, stack__final_estimator__n_estimators=150; total time=41.0min
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.236993 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 817
[LightGBM] [Info] Number of data points in the train set: 6819, number of used features: 39
[LightGBM] [Info] Start training from score 2193.082712
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
2:	learn: 1293.6710313	total: 398ms	remaining: 9.56s
3:	learn: 1226.2491492	total: 547ms	remaining: 9.71s
4:	learn: 1173.8830983	total: 734ms	remaining: 10.3s
5:	learn: 1139.7693768	total: 807ms	remaining: 9.28s
6:	learn: 1117.6163953	total: 1.05s	remaining: 10.2s
7:	learn: 1099.4984553	total: 1.14s	remaining: 9.54s
8:	learn: 1088.2148771	total: 1.28s	remaining: 9.4s
9:	learn: 1082.2573127	total: 1.41s	remaining: 9.18s
10:	learn: 1074.9401426	total: 1.54s	remaining: 8.94s
11:	learn: 1069.6311836	total: 1.7s	remaining: 8.92s
12:	learn: 1064.4663221	total: 1.82s	remaining: 8.66s
13:	learn: 1060.9859646	total: 1.99s	remaining: 8.69s
14:	learn: 1057.5069437	total: 2.24s	remaining: 8.96s
15:	learn: 1054.3369448	total: 2.39s	remaining: 8.82s
16:	learn: 1052.7366967	total: 2.56s	remaining: 8.74s
17:	learn: 1051.4762957	total: 2.69s	remaining: 8.54s
18:	learn: 1050.6383911	total: 2.92s	remaining: 8.62s
19:	learn: 1048.7890319	total: 3.08s	remaining: 8.46s
20:	learn: 1047.2665976	total: 3.22s	remaining: 8.28s
21:	learn: 1044.2788156	total: 3.33s	remaining: 8.02s
22:	learn: 1042.9051029	total: 3.42s	remaining: 7.74s
23:	learn: 1042.2009833	total: 3.66s	remaining: 7.77s
24:	learn: 1039.8442739	total: 3.76s	remaining: 7.51s
25:	learn: 1038.6956639	total: 3.81s	remaining: 7.19s
26:	learn: 1036.3000164	total: 3.93s	remaining: 6.99s
27:	learn: 1035.6778216	total: 4s	remaining: 6.72s
28:	learn: 1033.6712600	total: 4.2s	remaining: 6.66s
29:	learn: 1032.6939872	total: 4.29s	remaining: 6.44s
30:	learn: 1031.9809473	total: 4.47s	remaining: 6.34s
31:	learn: 1031.3329346	total: 4.6s	remaining: 6.18s
32:	learn: 1028.8768690	total: 4.74s	remaining: 6.04s
33:	learn: 1028.1639621	total: 4.89s	remaining: 5.9s
34:	learn: 1027.2222704	total: 5.12s	remaining: 5.85s
35:	learn: 1026.2285745	total: 5.34s	remaining: 5.78s
36:	learn: 1025.5145482	total: 5.5s	remaining: 5.65s
37:	learn: 1023.4556692	total: 5.62s	remaining: 5.48s
38:	learn: 1022.5789242	total: 5.85s	remaining: 5.4s
39:	learn: 1022.0118937	total: 6.06s	remaining: 5.3s
40:	learn: 1021.1823442	total: 6.24s	remaining: 5.17s
41:	learn: 1019.6503315	total: 6.46s	remaining: 5.07s
42:	learn: 1018.4625467	total: 6.64s	remaining: 4.94s
43:	learn: 1017.8457820	total: 6.74s	remaining: 4.75s
44:	learn: 1016.8901386	total: 6.92s	remaining: 4.61s
45:	learn: 1016.2185158	total: 7.05s	remaining: 4.45s
46:	learn: 1015.5189222	total: 7.22s	remaining: 4.3s
47:	learn: 1014.8943126	total: 7.28s	remaining: 4.1s
48:	learn: 1014.1815417	total: 7.39s	remaining: 3.92s
49:	learn: 1012.8957726	total: 7.72s	remaining: 3.86s
50:	learn: 1012.1339701	total: 7.86s	remaining: 3.7s
51:	learn: 1011.3571357	total: 7.92s	remaining: 3.5s
52:	learn: 1010.6739712	total: 8.09s	remaining: 3.36s
53:	learn: 1009.3453771	total: 8.17s	remaining: 3.18s
54:	learn: 1008.3947951	total: 8.37s	remaining: 3.04s
55:	learn: 1007.7715889	total: 8.49s	remaining: 2.88s
56:	learn: 1007.2357747	total: 8.6s	remaining: 2.72s
57:	learn: 1005.9303892	total: 8.77s	remaining: 2.57s
58:	learn: 1004.9305457	total: 8.95s	remaining: 2.43s
59:	learn: 1003.9519655	total: 9.07s	remaining: 2.27s
60:	learn: 1002.6675546	total: 9.15s	remaining: 2.1s
61:	learn: 1001.7781196	total: 9.42s	remaining: 1.98s
62:	learn: 1000.8684506	total: 9.54s	remaining: 1.82s
63:	learn: 999.3443671	total: 9.71s	remaining: 1.67s
64:	learn: 998.8448161	total: 9.85s	remaining: 1.51s
65:	learn: 998.3365599	total: 9.96s	remaining: 1.36s
66:	learn: 997.0868926	total: 10s	remaining: 1.2s
67:	learn: 996.1603733	total: 10.2s	remaining: 1.05s
68:	learn: 995.2040580	total: 10.3s	remaining: 898ms
69:	learn: 994.3110088	total: 10.5s	remaining: 748ms
70:	learn: 993.6907198	total: 10.7s	remaining: 603ms
71:	learn: 992.7117093	total: 10.8s	remaining: 451ms
72:	learn: 992.3854439	total: 11s	remaining: 301ms
73:	learn: 991.6632740	total: 11.2s	remaining: 151ms
74:	learn: 990.8482046	total: 11.3s	remaining: 0us
[CV] END stack__CAT__learning_rate=0.2, stack__CAT__max_depth=8, stack__CAT__n_estimators=75, stack__LGBM__learning_rate=0.3, stack__LGBM__max_depth=4, stack__LGBM__n_estimators=150, stack__XGB__learning_rate=0.05, stack__XGB__max_depth=6, stack__XGB__n_estimators=200, stack__final_estimator__max_depth=4, stack__final_estimator__n_estimators=150; total time=41.5min
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.346760 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 820
[LightGBM] [Info] Number of data points in the train set: 6819, number of used features: 39
[LightGBM] [Info] Start training from score 2189.804680
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.233677 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 814
[LightGBM] [Info] Number of data points in the train set: 5454, number of used features: 39
[LightGBM] [Info] Start training from score 2149.096927
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.262992 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 813
[LightGBM] [Info] Number of data points in the train set: 5455, number of used features: 39
[LightGBM] [Info] Start training from score 2162.504121
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
3:	learn: 1224.0033494	total: 464ms	remaining: 8.24s
4:	learn: 1175.3775817	total: 595ms	remaining: 8.34s
5:	learn: 1138.6768959	total: 681ms	remaining: 7.83s
6:	learn: 1113.2714304	total: 789ms	remaining: 7.67s
7:	learn: 1098.3223684	total: 923ms	remaining: 7.73s
8:	learn: 1085.3376980	total: 1.07s	remaining: 7.83s
9:	learn: 1076.2415960	total: 1.23s	remaining: 7.99s
10:	learn: 1069.0752116	total: 1.35s	remaining: 7.85s
11:	learn: 1062.9838501	total: 1.54s	remaining: 8.1s
12:	learn: 1059.6158927	total: 1.71s	remaining: 8.15s
13:	learn: 1056.6214912	total: 1.88s	remaining: 8.2s
14:	learn: 1055.2756014	total: 2s	remaining: 8.02s
15:	learn: 1051.4168053	total: 2.14s	remaining: 7.89s
16:	learn: 1048.5257555	total: 2.21s	remaining: 7.52s
17:	learn: 1047.1216665	total: 2.3s	remaining: 7.28s
18:	learn: 1044.4225695	total: 2.39s	remaining: 7.05s
19:	learn: 1043.5413022	total: 2.59s	remaining: 7.13s
20:	learn: 1042.8902247	total: 2.7s	remaining: 6.95s
21:	learn: 1041.0630083	total: 2.83s	remaining: 6.83s
22:	learn: 1039.8665975	total: 2.92s	remaining: 6.6s
23:	learn: 1037.5608155	total: 3.02s	remaining: 6.42s
24:	learn: 1035.8818089	total: 3.15s	remaining: 6.3s
25:	learn: 1035.0468406	total: 3.35s	remaining: 6.32s
26:	learn: 1034.1371718	total: 3.52s	remaining: 6.25s
27:	learn: 1033.4444061	total: 3.66s	remaining: 6.14s
28:	learn: 1032.8210166	total: 3.76s	remaining: 5.96s
29:	learn: 1031.0070169	total: 3.9s	remaining: 5.85s
30:	learn: 1030.1901825	total: 4s	remaining: 5.68s
31:	learn: 1028.9668292	total: 4.26s	remaining: 5.73s
32:	learn: 1028.1663346	total: 4.42s	remaining: 5.63s
33:	learn: 1027.6007893	total: 4.56s	remaining: 5.5s
34:	learn: 1026.9980489	total: 4.72s	remaining: 5.39s
35:	learn: 1026.1423594	total: 4.83s	remaining: 5.23s
36:	learn: 1024.7764946	total: 4.93s	remaining: 5.06s
37:	learn: 1024.1146690	total: 5.02s	remaining: 4.88s
38:	learn: 1023.3392921	total: 5.15s	remaining: 4.75s
39:	learn: 1022.3692230	total: 5.27s	remaining: 4.61s
40:	learn: 1020.8634363	total: 5.42s	remaining: 4.49s
41:	learn: 1020.1242579	total: 5.52s	remaining: 4.34s
42:	learn: 1019.1442375	total: 5.62s	remaining: 4.18s
43:	learn: 1018.4487750	total: 5.82s	remaining: 4.1s
44:	learn: 1017.1677352	total: 5.97s	remaining: 3.98s
45:	learn: 1016.4168043	total: 6.11s	remaining: 3.85s
46:	learn: 1015.4282725	total: 6.31s	remaining: 3.76s
47:	learn: 1014.6355021	total: 6.55s	remaining: 3.69s
48:	learn: 1013.5071602	total: 6.72s	remaining: 3.56s
49:	learn: 1012.7557546	total: 6.92s	remaining: 3.46s
50:	learn: 1011.6636920	total: 7.07s	remaining: 3.33s
51:	learn: 1010.3444516	total: 7.26s	remaining: 3.21s
52:	learn: 1009.7304526	total: 7.38s	remaining: 3.06s
53:	learn: 1008.4709889	total: 7.54s	remaining: 2.93s
54:	learn: 1007.6132183	total: 7.66s	remaining: 2.79s
55:	learn: 1006.7679113	total: 7.78s	remaining: 2.64s
56:	learn: 1005.9195324	total: 7.89s	remaining: 2.49s
57:	learn: 1005.3761339	total: 7.97s	remaining: 2.34s
58:	learn: 1004.7582027	total: 8.06s	remaining: 2.19s
59:	learn: 1004.2372374	total: 8.18s	remaining: 2.04s
60:	learn: 1003.2933319	total: 8.43s	remaining: 1.94s
61:	learn: 1002.5976486	total: 8.58s	remaining: 1.8s
62:	learn: 1001.3605034	total: 8.72s	remaining: 1.66s
63:	learn: 1000.4452541	total: 8.85s	remaining: 1.52s
64:	learn: 999.8463103	total: 9.14s	remaining: 1.41s
65:	learn: 999.0919750	total: 9.28s	remaining: 1.26s
66:	learn: 998.6905955	total: 9.43s	remaining: 1.13s
67:	learn: 997.5394180	total: 9.66s	remaining: 995ms
68:	learn: 996.6790995	total: 9.82s	remaining: 854ms
69:	learn: 995.9821345	total: 10s	remaining: 716ms
70:	learn: 995.5988890	total: 10.1s	remaining: 568ms
71:	learn: 994.5043887	total: 10.4s	remaining: 434ms
72:	learn: 993.8717327	total: 10.6s	remaining: 290ms
73:	learn: 992.6249410	total: 10.7s	remaining: 145ms
74:	learn: 992.2891483	total: 10.8s	remaining: 0us
[CV] END stack__CAT__learning_rate=0.2, stack__CAT__max_depth=8, stack__CAT__n_estimators=75, stack__LGBM__learning_rate=0.3, stack__LGBM__max_depth=4, stack__LGBM__n_estimators=150, stack__XGB__learning_rate=0.05, stack__XGB__max_depth=6, stack__XGB__n_estimators=200, stack__final_estimator__max_depth=4, stack__final_estimator__n_estimators=150; total time=42.3min
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.221038 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 815
[LightGBM] [Info] Number of data points in the train set: 6818, number of used features: 39
[LightGBM] [Info] Start training from score 2183.057911
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

1:	learn: 1395.0394356	total: 407ms	remaining: 14.8s
2:	learn: 1297.5885841	total: 549ms	remaining: 13.2s
3:	learn: 1227.1544438	total: 676ms	remaining: 12s
4:	learn: 1179.6436002	total: 794ms	remaining: 11.1s
5:	learn: 1147.7382864	total: 918ms	remaining: 10.6s
6:	learn: 1122.7309418	total: 1.06s	remaining: 10.3s
7:	learn: 1103.5190222	total: 1.2s	remaining: 10.1s
8:	learn: 1088.9513385	total: 1.35s	remaining: 9.88s
9:	learn: 1078.1432860	total: 1.43s	remaining: 9.28s
10:	learn: 1070.9122328	total: 1.55s	remaining: 9.03s
11:	learn: 1065.1853880	total: 1.68s	remaining: 8.83s
12:	learn: 1061.1998542	total: 1.77s	remaining: 8.44s
13:	learn: 1057.1709764	total: 1.93s	remaining: 8.42s
14:	learn: 1053.3460337	total: 2.08s	remaining: 8.31s
15:	learn: 1052.3363703	total: 2.18s	remaining: 8.04s
16:	learn: 1050.5027303	total: 2.3s	remaining: 7.85s
17:	learn: 1048.4797603	total: 2.38s	remaining: 7.55s
18:	learn: 1046.5169490	total: 2.52s	remaining: 7.43s
19:	learn: 1044.3398395	total: 2.56s	remaining: 7.03s
20:	learn: 1042.7296789	total: 2.75s	remaining: 7.06s
21:	learn: 1041.9734066	total: 2.86s	remaining: 6.89s
22:	learn: 1039.8457919	total: 2.96s	remaining: 6.7s
23:	learn: 1038.0997202	total: 3.15s	remaining: 6.69s
24:	learn: 1037.3218159	total: 3.36s	remaining: 6.71s
25:	learn: 1036.1715094	total: 3.54s	remaining: 6.67s
26:	learn: 1033.3170518	total: 3.6s	remaining: 6.39s
27:	learn: 1032.3631811	total: 3.82s	remaining: 6.42s
28:	learn: 1029.5693802	total: 3.98s	remaining: 6.31s
29:	learn: 1028.6051178	total: 4.07s	remaining: 6.11s
30:	learn: 1026.9792386	total: 4.29s	remaining: 6.09s
31:	learn: 1026.1428166	total: 4.41s	remaining: 5.93s
32:	learn: 1025.4196800	total: 4.52s	remaining: 5.75s
33:	learn: 1024.4381838	total: 4.65s	remaining: 5.61s
34:	learn: 1023.5565869	total: 4.9s	remaining: 5.6s
35:	learn: 1022.5695074	total: 5.06s	remaining: 5.49s
36:	learn: 1020.8937987	total: 5.17s	remaining: 5.31s
37:	learn: 1019.4122079	total: 5.3s	remaining: 5.16s
38:	learn: 1018.6493704	total: 5.37s	remaining: 4.95s
39:	learn: 1017.6939806	total: 5.47s	remaining: 4.78s
40:	learn: 1016.8131021	total: 5.64s	remaining: 4.68s
41:	learn: 1016.2044433	total: 5.77s	remaining: 4.53s
42:	learn: 1015.1375374	total: 5.94s	remaining: 4.42s
43:	learn: 1014.2803192	total: 6.17s	remaining: 4.34s
44:	learn: 1013.3695604	total: 6.26s	remaining: 4.18s
45:	learn: 1012.5165300	total: 6.49s	remaining: 4.09s
46:	learn: 1011.6342898	total: 6.65s	remaining: 3.96s
47:	learn: 1010.8609160	total: 6.76s	remaining: 3.8s
48:	learn: 1009.6927311	total: 6.91s	remaining: 3.67s
49:	learn: 1008.4894275	total: 7.04s	remaining: 3.52s
50:	learn: 1007.6034109	total: 7.15s	remaining: 3.36s
51:	learn: 1006.5992830	total: 7.21s	remaining: 3.19s
52:	learn: 1005.5902582	total: 7.33s	remaining: 3.04s
53:	learn: 1004.3361510	total: 7.52s	remaining: 2.93s
54:	learn: 1003.5405752	total: 7.6s	remaining: 2.76s
55:	learn: 1002.6992908	total: 7.79s	remaining: 2.64s
56:	learn: 1002.0357802	total: 7.89s	remaining: 2.49s
57:	learn: 1000.6347542	total: 8.01s	remaining: 2.35s
58:	learn: 999.3624528	total: 8.16s	remaining: 2.21s
59:	learn: 998.7600776	total: 8.25s	remaining: 2.06s
60:	learn: 997.7686877	total: 8.45s	remaining: 1.94s
61:	learn: 996.5688124	total: 8.57s	remaining: 1.8s
62:	learn: 995.5277693	total: 8.65s	remaining: 1.65s
63:	learn: 994.8826017	total: 8.82s	remaining: 1.51s
64:	learn: 993.9282997	total: 8.91s	remaining: 1.37s
65:	learn: 993.1978213	total: 9.04s	remaining: 1.23s
66:	learn: 992.3569249	total: 9.18s	remaining: 1.09s
67:	learn: 991.9630522	total: 9.32s	remaining: 959ms
68:	learn: 991.0985318	total: 9.41s	remaining: 819ms
69:	learn: 989.9809153	total: 9.53s	remaining: 681ms
70:	learn: 989.5780989	total: 9.65s	remaining: 544ms
71:	learn: 988.9931344	total: 9.73s	remaining: 406ms
72:	learn: 988.4224412	total: 9.95s	remaining: 273ms
73:	learn: 987.2339053	total: 10.1s	remaining: 136ms
74:	learn: 986.2778348	total: 10.2s	remaining: 0us
[CV] END stack__CAT__learning_rate=0.2, stack__CAT__max_depth=8, stack__CAT__n_estimators=75, stack__LGBM__learning_rate=0.3, stack__LGBM__max_depth=4, stack__LGBM__n_estimators=150, stack__XGB__learning_rate=0.05, stack__XGB__max_depth=6, stack__XGB__n_estimators=200, stack__final_estimator__max_depth=4, stack__final_estimator__n_estimators=150; total time=42.7min
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.228647 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 816
[LightGBM] [Info] Number of data points in the train set: 6818, number of used features: 39
[LightGBM] [Info] Start training from score 2159.816823
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
0:	learn: 1666.9598966	total: 77.3ms	remaining: 5.72s
1:	learn: 1623.6909694	total: 147ms	remaining: 5.37s
2:	learn: 1586.2359676	total: 173ms	remaining: 4.16s
3:	learn: 1546.3761595	total: 223ms	remaining: 3.95s
4:	learn: 1511.6702452	total: 292ms	remaining: 4.09s
5:	learn: 1479.6495183	total: 357ms	remaining: 4.11s
6:	learn: 1449.6566859	total: 421ms	remaining: 4.09s
7:	learn: 1422.0607487	total: 471ms	remaining: 3.95s
8:	learn: 1395.4095003	total: 523ms	remaining: 3.83s
9:	learn: 1370.1602864	total: 607ms	remaining: 3.95s
10:	learn: 1348.7253867	total: 690ms	remaining: 4.01s
11:	learn: 1327.3274591	total: 778ms	remaining: 4.08s
12:	learn: 1308.0509328	total: 881ms	remaining: 4.2s
13:	learn: 1290.3148181	total: 900ms	remaining: 3.92s
14:	learn: 1275.7941087	total: 979ms	remaining: 3.91s
15:	learn: 1262.5574571	total: 1.1s	remaining: 4.04s
16:	learn: 1248.2610391	total: 1.13s	remaining: 3.86s
17:	learn: 1234.4071466	total: 1.21s	remaining: 3.83s
18:	learn: 1222.6436203	total: 1.25s	remaining: 3.7s
19:	learn: 1209.8036101	total: 1.37s	remaining: 3.77s
20:	learn: 1198.0721187	total: 1.43s	remaining: 3.67s
21:	learn: 1187.4301681	total: 1.5s	remaining: 3.63s
22:	learn: 1178.3233936	total: 1.58s	remaining: 3.57s
23:	learn: 1169.8283644	total: 1.68s	remaining: 3.58s
24:	learn: 1161.9925173	total: 1.73s	remaining: 3.45s
25:	learn: 1154.6450655	total: 1.76s	remaining: 3.32s
26:	learn: 1148.2692579	total: 1.94s	remaining: 3.46s
27:	learn: 1141.9523848	total: 2.05s	remaining: 3.45s
28:	learn: 1136.9057302	total: 2.11s	remaining: 3.35s
29:	learn: 1132.3018707	total: 2.23s	remaining: 3.35s
30:	learn: 1126.8147398	total: 2.36s	remaining: 3.35s
31:	learn: 1122.2438103	total: 2.42s	remaining: 3.26s
32:	learn: 1119.1169919	total: 2.47s	remaining: 3.14s
33:	learn: 1115.2107607	total: 2.53s	remaining: 3.05s
34:	learn: 1112.3253864	total: 2.64s	remaining: 3.01s
35:	learn: 1109.5171809	total: 2.7s	remaining: 2.93s
36:	learn: 1107.4349615	total: 2.83s	remaining: 2.9s
37:	learn: 1104.8280400	total: 2.85s	remaining: 2.78s
38:	learn: 1102.3301514	total: 2.98s	remaining: 2.75s
39:	learn: 1099.7713505	total: 3.04s	remaining: 2.66s
40:	learn: 1097.5432189	total: 3.14s	remaining: 2.6s
41:	learn: 1095.0884018	total: 3.15s	remaining: 2.48s
42:	learn: 1093.1550802	total: 3.3s	remaining: 2.46s
43:	learn: 1091.2245651	total: 3.37s	remaining: 2.38s
44:	learn: 1089.8214969	total: 3.47s	remaining: 2.31s
45:	learn: 1088.3310048	total: 3.51s	remaining: 2.21s
46:	learn: 1087.5610340	total: 3.58s	remaining: 2.13s
47:	learn: 1086.5025872	total: 3.72s	remaining: 2.09s
48:	learn: 1085.1430210	total: 3.79s	remaining: 2.01s
49:	learn: 1084.0469013	total: 3.92s	remaining: 1.96s
50:	learn: 1083.2812024	total: 3.98s	remaining: 1.88s
51:	learn: 1082.4689213	total: 4.15s	remaining: 1.83s
52:	learn: 1081.8776593	total: 4.21s	remaining: 1.75s
53:	learn: 1080.7588356	total: 4.33s	remaining: 1.68s
54:	learn: 1079.9153691	total: 4.37s	remaining: 1.59s
55:	learn: 1079.1999855	total: 4.44s	remaining: 1.5s
56:	learn: 1078.4289689	total: 4.47s	remaining: 1.41s
57:	learn: 1077.5934752	total: 4.57s	remaining: 1.34s
58:	learn: 1077.0311602	total: 4.62s	remaining: 1.25s
59:	learn: 1076.4696503	total: 4.75s	remaining: 1.19s
60:	learn: 1075.7076525	total: 4.87s	remaining: 1.12s
61:	learn: 1075.1639178	total: 4.9s	remaining: 1.03s
62:	learn: 1074.5739276	total: 5s	remaining: 952ms
63:	learn: 1073.9334579	total: 5.08s	remaining: 874ms
64:	learn: 1073.2334906	total: 5.16s	remaining: 794ms
65:	learn: 1072.7611703	total: 5.23s	remaining: 713ms
66:	learn: 1072.3245526	total: 5.24s	remaining: 626ms
67:	learn: 1071.9622820	total: 5.37s	remaining: 553ms
68:	learn: 1071.6519731	total: 5.43s	remaining: 472ms
69:	learn: 1071.2920008	total: 5.49s	remaining: 392ms
70:	learn: 1070.9203084	total: 5.56s	remaining: 313ms
71:	learn: 1070.4955770	total: 5.64s	remaining: 235ms
72:	learn: 1069.9234402	total: 5.72s	remaining: 157ms
73:	learn: 1069.5258446	total: 5.74s	remaining: 77.5ms
74:	learn: 1069.1201249	total: 5.86s	remaining: 0us
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.315301 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 817
[LightGBM] [Info] Number of data points in the train set: 5454, number of used features: 39
[LightGBM] [Info] Start training from score 2173.066949
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
0:	learn: 1663.9594521	total: 102ms	remaining: 7.53s
1:	learn: 1624.7498639	total: 164ms	remaining: 5.99s
2:	learn: 1582.1277462	total: 179ms	remaining: 4.3s
3:	learn: 1548.0221265	total: 255ms	remaining: 4.53s
4:	learn: 1511.8951720	total: 352ms	remaining: 4.93s
5:	learn: 1478.0655768	total: 429ms	remaining: 4.93s
6:	learn: 1447.6104081	total: 451ms	remaining: 4.38s
7:	learn: 1420.3578741	total: 556ms	remaining: 4.65s
8:	learn: 1398.0674796	total: 636ms	remaining: 4.67s
9:	learn: 1372.8130090	total: 729ms	remaining: 4.74s
10:	learn: 1348.1828605	total: 772ms	remaining: 4.49s
11:	learn: 1327.1136878	total: 782ms	remaining: 4.11s
12:	learn: 1306.0550029	total: 879ms	remaining: 4.19s
13:	learn: 1286.7962870	total: 970ms	remaining: 4.23s
14:	learn: 1269.8393905	total: 1.03s	remaining: 4.13s
15:	learn: 1254.3079946	total: 1.11s	remaining: 4.08s
16:	learn: 1238.9650618	total: 1.17s	remaining: 3.99s
17:	learn: 1224.8965270	total: 1.25s	remaining: 3.95s
18:	learn: 1212.9260012	total: 1.32s	remaining: 3.88s
19:	learn: 1201.6829624	total: 1.37s	remaining: 3.77s
20:	learn: 1192.6587067	total: 1.46s	remaining: 3.74s
21:	learn: 1182.9881855	total: 1.5s	remaining: 3.62s
22:	learn: 1174.9349793	total: 1.59s	remaining: 3.61s
23:	learn: 1167.8724512	total: 1.68s	remaining: 3.58s
24:	learn: 1161.4613401	total: 1.76s	remaining: 3.51s
25:	learn: 1154.5521116	total: 1.77s	remaining: 3.33s
26:	learn: 1148.0494270	total: 1.94s	remaining: 3.46s
27:	learn: 1143.6676594	total: 2s	remaining: 3.36s
28:	learn: 1137.7105376	total: 2.07s	remaining: 3.28s
29:	learn: 1132.4644131	total: 2.14s	remaining: 3.21s
30:	learn: 1128.7622918	total: 2.18s	remaining: 3.1s
31:	learn: 1123.9091838	total: 2.27s	remaining: 3.05s
32:	learn: 1119.8965303	total: 2.33s	remaining: 2.96s
33:	learn: 1116.1808004	total: 2.38s	remaining: 2.87s
34:	learn: 1113.3524833	total: 2.43s	remaining: 2.78s
35:	learn: 1109.9949769	total: 2.52s	remaining: 2.73s
36:	learn: 1107.4969781	total: 2.57s	remaining: 2.64s
37:	learn: 1105.2255810	total: 2.58s	remaining: 2.51s
38:	learn: 1102.6585810	total: 2.65s	remaining: 2.44s
39:	learn: 1100.8725107	total: 2.67s	remaining: 2.33s
40:	learn: 1099.0229308	total: 2.75s	remaining: 2.28s
41:	learn: 1096.7138899	total: 2.81s	remaining: 2.21s
42:	learn: 1095.2931601	total: 2.85s	remaining: 2.12s
43:	learn: 1093.5805127	total: 2.94s	remaining: 2.07s
44:	learn: 1091.7894923	total: 3.07s	remaining: 2.04s
45:	learn: 1090.6384761	total: 3.1s	remaining: 1.95s
46:	learn: 1089.2341984	total: 3.21s	remaining: 1.91s
47:	learn: 1088.2645214	total: 3.27s	remaining: 1.84s
48:	learn: 1086.7748428	total: 3.33s	remaining: 1.77s
49:	learn: 1085.7212197	total: 3.43s	remaining: 1.71s
50:	learn: 1084.6605057	total: 3.46s	remaining: 1.63s
51:	learn: 1083.3917791	total: 3.52s	remaining: 1.55s
52:	learn: 1082.5968861	total: 3.56s	remaining: 1.48s
53:	learn: 1081.7581801	total: 3.65s	remaining: 1.42s
54:	learn: 1081.1240808	total: 3.72s	remaining: 1.35s
55:	learn: 1080.6172328	total: 3.76s	remaining: 1.28s
56:	learn: 1079.7966031	total: 3.83s	remaining: 1.21s
57:	learn: 1079.4453418	total: 3.88s	remaining: 1.14s
58:	learn: 1078.8802846	total: 3.96s	remaining: 1.07s
59:	learn: 1078.2116315	total: 4.01s	remaining: 1s
60:	learn: 1077.7667201	total: 4.08s	remaining: 936ms
61:	learn: 1077.4069006	total: 4.1s	remaining: 860ms
62:	learn: 1076.6626122	total: 4.19s	remaining: 799ms
63:	learn: 1076.0784659	total: 4.32s	remaining: 742ms
64:	learn: 1075.7483106	total: 4.36s	remaining: 671ms
65:	learn: 1075.2270409	total: 4.38s	remaining: 597ms
66:	learn: 1074.8386078	total: 4.44s	remaining: 531ms
67:	learn: 1074.4031231	total: 4.49s	remaining: 463ms
68:	learn: 1074.0359117	total: 4.57s	remaining: 398ms
69:	learn: 1073.4412894	total: 4.61s	remaining: 330ms
70:	learn: 1072.9162900	total: 4.65s	remaining: 262ms
71:	learn: 1072.5184648	total: 4.71s	remaining: 196ms
72:	learn: 1072.2569072	total: 4.78s	remaining: 131ms
73:	learn: 1071.9666198	total: 4.86s	remaining: 65.7ms
74:	learn: 1071.7314957	total: 4.93s	remaining: 0us
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.204527 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 816
[LightGBM] [Info] Number of data points in the train set: 5455, number of used features: 39
[LightGBM] [Info] Start training from score 2186.946488
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
0:	learn: 1664.3581930	total: 77ms	remaining: 5.7s
1:	learn: 1622.3603159	total: 109ms	remaining: 3.98s
2:	learn: 1585.8221733	total: 194ms	remaining: 4.65s
3:	learn: 1546.4616461	total: 223ms	remaining: 3.95s
4:	learn: 1511.7718527	total: 273ms	remaining: 3.81s
5:	learn: 1479.5340075	total: 377ms	remaining: 4.34s
6:	learn: 1449.2956613	total: 467ms	remaining: 4.54s
7:	learn: 1421.0824915	total: 484ms	remaining: 4.05s
8:	learn: 1397.8870619	total: 600ms	remaining: 4.4s
9:	learn: 1372.2064457	total: 663ms	remaining: 4.31s
10:	learn: 1349.6737048	total: 775ms	remaining: 4.51s
11:	learn: 1328.3178702	total: 852ms	remaining: 4.47s
12:	learn: 1307.9699356	total: 942ms	remaining: 4.49s
13:	learn: 1290.1581618	total: 1s	remaining: 4.37s
14:	learn: 1275.6260575	total: 1.08s	remaining: 4.33s
15:	learn: 1262.4522888	total: 1.15s	remaining: 4.24s
16:	learn: 1247.7972933	total: 1.2s	remaining: 4.1s
17:	learn: 1233.9337864	total: 1.25s	remaining: 3.98s
18:	learn: 1222.1040037	total: 1.3s	remaining: 3.83s
19:	learn: 1209.4333095	total: 1.35s	remaining: 3.72s
20:	learn: 1197.6845941	total: 1.44s	remaining: 3.69s
21:	learn: 1186.6924192	total: 1.49s	remaining: 3.6s
22:	learn: 1177.2041518	total: 1.6s	remaining: 3.63s
23:	learn: 1168.4536059	total: 1.61s	remaining: 3.43s
24:	learn: 1160.8558647	total: 1.69s	remaining: 3.38s
25:	learn: 1153.3965894	total: 1.73s	remaining: 3.26s
26:	learn: 1147.7759243	total: 1.78s	remaining: 3.17s
27:	learn: 1141.2117488	total: 1.85s	remaining: 3.11s
28:	learn: 1135.6469822	total: 1.93s	remaining: 3.07s
29:	learn: 1131.2725854	total: 1.98s	remaining: 2.98s
30:	learn: 1125.7549569	total: 2.04s	remaining: 2.89s
31:	learn: 1122.4359281	total: 2.1s	remaining: 2.82s
32:	learn: 1118.9329013	total: 2.17s	remaining: 2.76s
33:	learn: 1115.1373345	total: 2.22s	remaining: 2.68s
34:	learn: 1111.9667157	total: 2.29s	remaining: 2.62s
35:	learn: 1108.8568792	total: 2.34s	remaining: 2.54s
36:	learn: 1106.6990640	total: 2.36s	remaining: 2.42s
37:	learn: 1103.3188325	total: 2.48s	remaining: 2.41s
38:	learn: 1100.8234748	total: 2.54s	remaining: 2.34s
39:	learn: 1099.0611169	total: 2.6s	remaining: 2.27s
40:	learn: 1097.0288373	total: 2.65s	remaining: 2.19s
41:	learn: 1094.6287089	total: 2.69s	remaining: 2.12s
42:	learn: 1092.4110690	total: 2.79s	remaining: 2.08s
43:	learn: 1090.2066640	total: 2.83s	remaining: 2s
44:	learn: 1088.4938990	total: 2.95s	remaining: 1.97s
45:	learn: 1086.9190885	total: 3.19s	remaining: 2.01s
46:	learn: 1085.9522636	total: 3.34s	remaining: 1.99s
47:	learn: 1084.8688043	total: 3.39s	remaining: 1.91s
48:	learn: 1083.2234779	total: 3.47s	remaining: 1.84s
49:	learn: 1082.1425628	total: 3.58s	remaining: 1.79s
50:	learn: 1081.4068009	total: 3.62s	remaining: 1.7s
51:	learn: 1080.6373206	total: 3.67s	remaining: 1.62s
52:	learn: 1080.0171923	total: 3.71s	remaining: 1.54s
53:	learn: 1078.8113986	total: 3.77s	remaining: 1.47s
54:	learn: 1078.2740249	total: 3.82s	remaining: 1.39s
55:	learn: 1077.7086675	total: 3.88s	remaining: 1.32s
56:	learn: 1076.7854279	total: 3.95s	remaining: 1.25s
57:	learn: 1075.7904181	total: 4s	remaining: 1.17s
58:	learn: 1075.1478235	total: 4.07s	remaining: 1.1s
59:	learn: 1074.5515020	total: 4.13s	remaining: 1.03s
60:	learn: 1073.8344416	total: 4.18s	remaining: 959ms
61:	learn: 1073.2779244	total: 4.24s	remaining: 888ms
62:	learn: 1072.8629642	total: 4.29s	remaining: 817ms
63:	learn: 1072.2884224	total: 4.37s	remaining: 751ms
64:	learn: 1071.7819170	total: 4.48s	remaining: 689ms
65:	learn: 1071.5197499	total: 4.54s	remaining: 619ms
66:	learn: 1070.8269112	total: 4.6s	remaining: 550ms
67:	learn: 1070.0457141	total: 4.71s	remaining: 485ms
68:	learn: 1069.7232456	total: 4.76s	remaining: 414ms
69:	learn: 1069.2669011	total: 4.85s	remaining: 346ms
70:	learn: 1068.8226042	total: 4.88s	remaining: 275ms
71:	learn: 1068.2877260	total: 4.94s	remaining: 206ms
72:	learn: 1067.9115170	total: 5.06s	remaining: 139ms
73:	learn: 1067.5452730	total: 5.14s	remaining: 69.5ms
74:	learn: 1067.2845888	total: 5.25s	remaining: 0us
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.224834 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 817
[LightGBM] [Info] Number of data points in the train set: 5455, number of used features: 39
[LightGBM] [Info] Start training from score 2184.653597
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
0:	learn: 1515.1591341	total: 84.9ms	remaining: 8.41s
1:	learn: 1390.3793865	total: 133ms	remaining: 6.51s
2:	learn: 1297.8438614	total: 195ms	remaining: 6.3s
3:	learn: 1228.2542222	total: 231ms	remaining: 5.55s
4:	learn: 1185.0472300	total: 293ms	remaining: 5.57s
5:	learn: 1146.8700442	total: 375ms	remaining: 5.88s
6:	learn: 1127.3200113	total: 392ms	remaining: 5.21s
7:	learn: 1108.1779954	total: 479ms	remaining: 5.51s
8:	learn: 1095.5224496	total: 628ms	remaining: 6.34s
9:	learn: 1090.6462378	total: 651ms	remaining: 5.85s
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
0:	learn: 1540.4868460	total: 86.5ms	remaining: 8.56s
1:	learn: 1400.3602292	total: 142ms	remaining: 6.98s
2:	learn: 1301.6346725	total: 201ms	remaining: 6.5s
3:	learn: 1237.6148485	total: 249ms	remaining: 5.99s
4:	learn: 1182.5590077	total: 330ms	remaining: 6.27s
5:	learn: 1148.0705829	total: 405ms	remaining: 6.34s
6:	learn: 1121.0004380	total: 469ms	remaining: 6.23s
7:	learn: 1102.7960375	total: 551ms	remaining: 6.33s

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.295271 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 818
[LightGBM] [Info] Number of data points in the train set: 5455, number of used features: 39
[LightGBM] [Info] Start training from score 2159.055387
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
0:	learn: 1646.1542178	total: 32.3ms	remaining: 2.39s
1:	learn: 1602.7644193	total: 123ms	remaining: 4.5s
2:	learn: 1561.0661688	total: 169ms	remaining: 4.05s
3:	learn: 1524.6409384	total: 204ms	remaining: 3.62s
4:	learn: 1490.3195719	total: 333ms	remaining: 4.66s
5:	learn: 1461.7786106	total: 383ms	remaining: 4.4s
6:	learn: 1432.1439177	total: 446ms	remaining: 4.33s
7:	learn: 1404.0449442	total: 545ms	remaining: 4.57s
8:	learn: 1380.6983452	total: 565ms	remaining: 4.14s
9:	learn: 1356.9457833	total: 573ms	remaining: 3.72s
10:	learn: 1333.4473454	total: 581ms	remaining: 3.38s
11:	learn: 1312.2509857	total: 588ms	remaining: 3.08s
12:	learn: 1293.5216885	total: 595ms	remaining: 2.84s
13:	learn: 1278.1496085	total: 677ms	remaining: 2.95s
14:	learn: 1261.2710112	total: 806ms	remaining: 3.23s
15:	learn: 1248.0833742	total: 815ms	remaining: 3s
16:	learn: 1232.9907534	total: 924ms	remaining: 3.15s
17:	learn: 1221.3094499	total: 952ms	remaining: 3.02s
18:	learn: 1208.9570848	total: 1s	remaining: 2.96s
19:	learn: 1197.0171873	total: 1.08s	remaining: 2.97s
20:	learn: 1187.4437994	total: 1.28s	remaining: 3.29s
21:	learn: 1176.4654130	total: 1.34s	remaining: 3.23s
22:	learn: 1170.0490545	total: 1.4s	remaining: 3.17s
23:	learn: 1161.5730664	total: 1.47s	remaining: 3.13s
24:	learn: 1153.5940089	total: 1.53s	remaining: 3.06s
25:	learn: 1145.8633225	total: 1.59s	remaining: 3.01s
26:	learn: 1139.5394637	total: 1.65s	remaining: 2.94s
27:	learn: 1132.4281779	total: 1.79s	remaining: 3s
28:	learn: 1126.4737337	total: 1.86s	remaining: 2.94s
29:	learn: 1121.2828503	total: 1.93s	remaining: 2.9s
30:	learn: 1116.9394425	total: 2.05s	remaining: 2.91s
31:	learn: 1113.1046517	total: 2.12s	remaining: 2.84s
32:	learn: 1109.3523941	total: 2.18s	remaining: 2.77s
33:	learn: 1106.4605167	total: 2.32s	remaining: 2.8s
34:	learn: 1103.4060459	total: 2.45s	remaining: 2.81s
35:	learn: 1100.7299371	total: 2.5s	remaining: 2.7s
36:	learn: 1097.2645057	total: 2.59s	remaining: 2.66s
37:	learn: 1093.9764866	total: 2.66s	remaining: 2.59s
38:	learn: 1092.5231372	total: 2.67s	remaining: 2.46s
39:	learn: 1089.3505841	total: 2.94s	remaining: 2.57s
40:	learn: 1087.0717785	total: 3.08s	remaining: 2.56s
41:	learn: 1084.8803520	total: 3.16s	remaining: 2.48s
42:	learn: 1082.3236838	total: 3.23s	remaining: 2.4s
43:	learn: 1080.2870564	total: 3.42s	remaining: 2.41s
44:	learn: 1078.6649297	total: 3.57s	remaining: 2.38s
45:	learn: 1077.1743013	total: 3.67s	remaining: 2.31s
46:	learn: 1075.9511276	total: 3.71s	remaining: 2.21s
47:	learn: 1074.2371109	total: 3.77s	remaining: 2.12s
48:	learn: 1073.2623237	total: 3.82s	remaining: 2.03s
49:	learn: 1071.9991814	total: 3.89s	remaining: 1.94s
50:	learn: 1070.4027128	total: 3.97s	remaining: 1.87s
51:	learn: 1069.3175734	total: 4.04s	remaining: 1.79s
52:	learn: 1067.8762967	total: 4.17s	remaining: 1.73s
53:	learn: 1067.2043323	total: 4.18s	remaining: 1.62s
54:	learn: 1066.4838784	total: 4.23s	remaining: 1.54s
55:	learn: 1066.0041791	total: 4.38s	remaining: 1.48s
56:	learn: 1065.3641786	total: 4.53s	remaining: 1.43s
57:	learn: 1064.7207210	total: 4.65s	remaining: 1.36s
58:	learn: 1064.0228355	total: 4.72s	remaining: 1.28s
59:	learn: 1063.5332472	total: 5.08s	remaining: 1.27s
60:	learn: 1063.2260763	total: 5.13s	remaining: 1.18s
61:	learn: 1062.5539821	total: 5.14s	remaining: 1.08s
62:	learn: 1062.0119364	total: 5.17s	remaining: 985ms
63:	learn: 1061.4715843	total: 5.24s	remaining: 900ms
64:	learn: 1060.7956556	total: 5.33s	remaining: 819ms
65:	learn: 1060.0504369	total: 5.37s	remaining: 732ms
66:	learn: 1059.5890965	total: 5.46s	remaining: 652ms
67:	learn: 1058.9169099	total: 5.49s	remaining: 566ms
68:	learn: 1058.5557854	total: 5.58s	remaining: 486ms
69:	learn: 1058.0589977	total: 5.65s	remaining: 404ms
70:	learn: 1057.4104184	total: 5.7s	remaining: 321ms
71:	learn: 1056.2741776	total: 5.75s	remaining: 239ms
72:	learn: 1055.8935584	total: 5.83s	remaining: 160ms
73:	learn: 1055.3325149	total: 5.9s	remaining: 79.8ms
74:	learn: 1055.1394432	total: 5.97s	remaining: 0us
0:	learn: 1671.5761877	total: 9.3ms	remaining: 688ms
1:	learn: 1628.5208669	total: 46.9ms	remaining: 1.71s
2:	learn: 1588.6629185	total: 55.1ms	remaining: 1.32s
3:	learn: 1554.2085864	total: 168ms	remaining: 2.98s
4:	learn: 1518.6505273	total: 206ms	remaining: 2.88s
5:	learn: 1485.1005712	total: 297ms	remaining: 3.41s
6:	learn: 1452.6486093	total: 306ms	remaining: 2.97s
7:	learn: 1422.8461886	total: 319ms	remaining: 2.67s
8:	learn: 1394.1952497	total: 330ms	remaining: 2.42s
9:	learn: 1368.8662185	total: 336ms	remaining: 2.19s
10:	learn: 1347.5672002	total: 346ms	remaining: 2.01s
11:	learn: 1328.0708173	total: 371ms	remaining: 1.95s
12:	learn: 1309.9671089	total: 379ms	remaining: 1.81s
13:	learn: 1290.0541624	total: 390ms	remaining: 1.7s
14:	learn: 1274.5920994	total: 426ms	remaining: 1.7s
15:	learn: 1258.5436573	total: 476ms	remaining: 1.75s
16:	learn: 1243.3600784	total: 508ms	remaining: 1.73s
17:	learn: 1228.6835466	total: 538ms	remaining: 1.7s
18:	learn: 1217.1676416	total: 625ms	remaining: 1.84s
19:	learn: 1204.5580962	total: 641ms	remaining: 1.76s
20:	learn: 1193.5610270	total: 725ms	remaining: 1.86s
21:	learn: 1183.5636697	total: 805ms	remaining: 1.94s
22:	learn: 1175.1389109	total: 910ms	remaining: 2.06s
23:	learn: 1166.6734852	total: 953ms	remaining: 2.02s
24:	learn: 1159.5812377	total: 1.02s	remaining: 2.05s
25:	learn: 1152.2377709	total: 1.21s	remaining: 2.27s
26:	learn: 1146.4820833	total: 1.22s	remaining: 2.17s
27:	learn: 1139.9063961	total: 1.23s	remaining: 2.06s
28:	learn: 1134.0409817	total: 1.24s	remaining: 1.96s
29:	learn: 1128.4178322	total: 1.25s	remaining: 1.87s
30:	learn: 1123.1524889	total: 1.28s	remaining: 1.81s
31:	learn: 1118.6908354	total: 1.29s	remaining: 1.73s
32:	learn: 1114.9417147	total: 1.31s	remaining: 1.67s
33:	learn: 1111.2030083	total: 1.45s	remaining: 1.75s
34:	learn: 1107.7282640	total: 1.49s	remaining: 1.71s

35:	learn: 1105.4485134	total: 1.55s	remaining: 1.68s
36:	learn: 1103.0702177	total: 1.61s	remaining: 1.65s
37:	learn: 1100.7625040	total: 1.69s	remaining: 1.64s
38:	learn: 1098.8177511	total: 1.8s	remaining: 1.66s
39:	learn: 1096.6706873	total: 1.83s	remaining: 1.6s
40:	learn: 1094.5083389	total: 1.91s	remaining: 1.58s
41:	learn: 1091.8592299	total: 2.02s	remaining: 1.59s
42:	learn: 1089.9290656	total: 2.08s	remaining: 1.55s
43:	learn: 1088.6102308	total: 2.13s	remaining: 1.5s
44:	learn: 1087.1370925	total: 2.26s	remaining: 1.51s
45:	learn: 1086.1208244	total: 2.31s	remaining: 1.45s
46:	learn: 1085.2007276	total: 2.42s	remaining: 1.44s
47:	learn: 1084.0941283	total: 2.44s	remaining: 1.37s
48:	learn: 1082.6367061	total: 2.5s	remaining: 1.33s
49:	learn: 1081.4936195	total: 2.63s	remaining: 1.31s
50:	learn: 1080.6797053	total: 2.64s	remaining: 1.24s
51:	learn: 1079.0606809	total: 2.74s	remaining: 1.21s
52:	learn: 1077.6291249	total: 2.77s	remaining: 1.15s
53:	learn: 1076.8290571	total: 2.82s	remaining: 1.1s
54:	learn: 1076.0352943	total: 2.83s	remaining: 1.03s
55:	learn: 1075.4662901	total: 2.83s	remaining: 962ms
56:	learn: 1074.6487125	total: 2.85s	remaining: 900ms
57:	learn: 1073.9711321	total: 2.86s	remaining: 838ms
58:	learn: 1073.2755773	total: 2.87s	remaining: 778ms
59:	learn: 1072.2306531	total: 2.88s	remaining: 720ms
60:	learn: 1071.3490563	total: 2.89s	remaining: 663ms
61:	learn: 1070.3056854	total: 2.89s	remaining: 607ms
62:	learn: 1069.6309075	total: 2.9s	remaining: 553ms
63:	learn: 1069.2811398	total: 2.91s	remaining: 500ms
64:	learn: 1068.6360851	total: 2.92s	remaining: 449ms
65:	learn: 1068.3312765	total: 2.92s	remaining: 399ms
66:	learn: 1067.6475501	total: 2.93s	remaining: 350ms
67:	learn: 1067.2555571	total: 2.94s	remaining: 303ms
68:	learn: 1067.0948205	total: 2.95s	remaining: 256ms
69:	learn: 1066.5443792	total: 2.95s	remaining: 211ms
70:	learn: 1065.7795675	total: 2.96s	remaining: 167ms
71:	learn: 1065.5138890	total: 2.97s	remaining: 124ms
72:	learn: 1065.2037979	total: 2.99s	remaining: 81.8ms
73:	learn: 1064.5950411	total: 3.06s	remaining: 41.3ms
74:	learn: 1064.3834628	total: 3.12s	remaining: 0us
0:	learn: 1663.8941078	total: 71.2ms	remaining: 5.27s
1:	learn: 1620.1995407	total: 77.5ms	remaining: 2.83s
2:	learn: 1580.8922614	total: 84.6ms	remaining: 2.03s
3:	learn: 1546.4595973	total: 91ms	remaining: 1.61s
4:	learn: 1508.4249876	total: 107ms	remaining: 1.49s
5:	learn: 1475.0069085	total: 117ms	remaining: 1.34s
6:	learn: 1442.6745528	total: 124ms	remaining: 1.2s
7:	learn: 1414.6733157	total: 135ms	remaining: 1.13s
8:	learn: 1386.0439804	total: 146ms	remaining: 1.07s
9:	learn: 1360.6633299	total: 164ms	remaining: 1.06s
10:	learn: 1339.3658885	total: 176ms	remaining: 1.03s
11:	learn: 1319.8998538	total: 232ms	remaining: 1.22s
12:	learn: 1301.9638975	total: 266ms	remaining: 1.27s
13:	learn: 1281.9730427	total: 305ms	remaining: 1.33s
14:	learn: 1266.2527113	total: 349ms	remaining: 1.39s
15:	learn: 1250.1540958	total: 402ms	remaining: 1.48s
16:	learn: 1235.1034176	total: 448ms	remaining: 1.53s
17:	learn: 1221.6628190	total: 458ms	remaining: 1.45s
18:	learn: 1208.5135677	total: 501ms	remaining: 1.48s
19:	learn: 1195.9216363	total: 537ms	remaining: 1.48s
20:	learn: 1184.1342265	total: 672ms	remaining: 1.73s
21:	learn: 1174.2437806	total: 768ms	remaining: 1.85s
22:	learn: 1168.2029759	total: 838ms	remaining: 1.89s
23:	learn: 1159.0851456	total: 872ms	remaining: 1.85s
24:	learn: 1151.3125700	total: 944ms	remaining: 1.89s
25:	learn: 1143.6364689	total: 1s	remaining: 1.89s
26:	learn: 1136.5714538	total: 1.12s	remaining: 1.99s
27:	learn: 1130.5298506	total: 1.2s	remaining: 2.01s
28:	learn: 1125.5163002	total: 1.34s	remaining: 2.13s
29:	learn: 1119.6022599	total: 1.4s	remaining: 2.1s
30:	learn: 1114.5742112	total: 1.46s	remaining: 2.07s
31:	learn: 1110.0277722	total: 1.5s	remaining: 2.02s
32:	learn: 1106.5920128	total: 1.55s	remaining: 1.98s
33:	learn: 1104.0445921	total: 1.67s	remaining: 2.01s
34:	learn: 1100.9396315	total: 1.71s	remaining: 1.96s
35:	learn: 1098.7415398	total: 1.83s	remaining: 1.98s
36:	learn: 1095.4523102	total: 1.86s	remaining: 1.91s
37:	learn: 1092.8005429	total: 1.97s	remaining: 1.92s
38:	learn: 1089.8105767	total: 2.14s	remaining: 1.97s
39:	learn: 1087.5079704	total: 2.44s	remaining: 2.13s
40:	learn: 1085.1016949	total: 2.52s	remaining: 2.09s
41:	learn: 1083.5977483	total: 2.65s	remaining: 2.08s
42:	learn: 1082.0265528	total: 2.72s	remaining: 2.02s
43:	learn: 1080.1888227	total: 2.78s	remaining: 1.96s
44:	learn: 1078.3257758	total: 2.91s	remaining: 1.94s
45:	learn: 1077.0863631	total: 2.98s	remaining: 1.88s
46:	learn: 1076.0343311	total: 3.04s	remaining: 1.81s
47:	learn: 1074.9695244	total: 3.17s	remaining: 1.78s
48:	learn: 1073.9626870	total: 3.23s	remaining: 1.71s
49:	learn: 1072.4125163	total: 3.34s	remaining: 1.67s
50:	learn: 1071.1704981	total: 3.42s	remaining: 1.61s
51:	learn: 1070.2809651	total: 3.48s	remaining: 1.54s
52:	learn: 1069.4189704	total: 3.55s	remaining: 1.47s
53:	learn: 1068.6627418	total: 3.65s	remaining: 1.42s
54:	learn: 1067.9098108	total: 3.7s	remaining: 1.35s
55:	learn: 1066.6900885	total: 3.75s	remaining: 1.27s
56:	learn: 1066.1489724	total: 3.81s	remaining: 1.2s
57:	learn: 1065.1735376	total: 3.85s	remaining: 1.13s
58:	learn: 1064.6803713	total: 3.9s	remaining: 1.06s
59:	learn: 1063.9454624	total: 3.99s	remaining: 998ms
60:	learn: 1063.3962669	total: 4.11s	remaining: 944ms
61:	learn: 1062.7333335	total: 4.16s	remaining: 872ms
62:	learn: 1062.3002534	total: 4.24s	remaining: 807ms
63:	learn: 1062.1210461	total: 4.25s	remaining: 731ms
64:	learn: 1061.7931812	total: 4.3s	remaining: 662ms
65:	learn: 1061.2431288	total: 4.39s	remaining: 599ms
66:	learn: 1060.7498483	total: 4.47s	remaining: 534ms
67:	learn: 1060.1876480	total: 4.53s	remaining: 466ms
68:	learn: 1059.9018728	total: 4.7s	remaining: 409ms
69:	learn: 1059.6850024	total: 4.75s	remaining: 339ms
70:	learn: 1059.4988139	total: 4.82s	remaining: 272ms
71:	learn: 1059.2651496	total: 4.9s	remaining: 204ms
72:	learn: 1058.7483250	total: 4.91s	remaining: 135ms
73:	learn: 1058.2124489	total: 5.01s	remaining: 67.7ms
74:	learn: 1057.6874947	total: 5.06s	remaining: 0us
0:	learn: 1657.9729428	total: 44.6ms	remaining: 3.3s
1:	learn: 1613.3212511	total: 108ms	remaining: 3.93s
2:	learn: 1577.7994492	total: 136ms	remaining: 3.26s
3:	learn: 1541.5972195	total: 270ms	remaining: 4.79s
4:	learn: 1507.8564586	total: 364ms	remaining: 5.1s
5:	learn: 1480.5048525	total: 424ms	remaining: 4.88s
6:	learn: 1448.1128617	total: 477ms	remaining: 4.63s
7:	learn: 1419.3036238	total: 491ms	remaining: 4.11s
8:	learn: 1392.8093605	total: 532ms	remaining: 3.9s
9:	learn: 1368.2700826	total: 582ms	remaining: 3.78s
10:	learn: 1345.0252675	total: 683ms	remaining: 3.97s
11:	learn: 1324.1209710	total: 694ms	remaining: 3.64s
12:	learn: 1304.8913785	total: 820ms	remaining: 3.91s
13:	learn: 1286.4795894	total: 837ms	remaining: 3.65s
14:	learn: 1269.3658895	total: 843ms	remaining: 3.37s
15:	learn: 1252.5631231	total: 903ms	remaining: 3.33s
16:	learn: 1240.6730556	total: 922ms	remaining: 3.15s
17:	learn: 1226.6135248	total: 966ms	remaining: 3.06s
18:	learn: 1214.0866911	total: 1.04s	remaining: 3.06s
19:	learn: 1203.4221320	total: 1.09s	remaining: 3.01s
20:	learn: 1193.4506194	total: 1.11s	remaining: 2.86s
21:	learn: 1183.2601463	total: 1.16s	remaining: 2.8s
22:	learn: 1173.9101208	total: 1.19s	remaining: 2.68s
23:	learn: 1165.2932311	total: 1.23s	remaining: 2.61s
24:	learn: 1157.6007894	total: 1.29s	remaining: 2.58s
25:	learn: 1151.6510122	total: 1.31s	remaining: 2.47s
26:	learn: 1145.7021086	total: 1.37s	remaining: 2.44s
27:	learn: 1140.5808118	total: 1.43s	remaining: 2.4s
28:	learn: 1135.6091654	total: 1.46s	remaining: 2.31s
29:	learn: 1131.0763213	total: 1.53s	remaining: 2.3s
30:	learn: 1126.6570016	total: 1.61s	remaining: 2.28s
31:	learn: 1122.5456881	total: 1.72s	remaining: 2.31s
32:	learn: 1118.0774161	total: 1.82s	remaining: 2.32s
33:	learn: 1113.7205819	total: 1.94s	remaining: 2.33s
34:	learn: 1109.6467070	total: 2.05s	remaining: 2.35s
35:	learn: 1106.9635475	total: 2.19s	remaining: 2.37s
36:	learn: 1104.2584910	total: 2.25s	remaining: 2.31s
10:	learn: 1084.2336117	total: 757ms	remaining: 6.13s
11:	learn: 1078.9793078	total: 774ms	remaining: 5.68s
12:	learn: 1074.8617572	total: 782ms	remaining: 5.23s
13:	learn: 1072.9371740	total: 789ms	remaining: 4.84s
14:	learn: 1070.1063936	total: 795ms	remaining: 4.5s
15:	learn: 1067.2147953	total: 802ms	remaining: 4.21s
16:	learn: 1065.0229074	total: 820ms	remaining: 4s
17:	learn: 1064.3208546	total: 828ms	remaining: 3.77s
18:	learn: 1063.5987418	total: 861ms	remaining: 3.67s
19:	learn: 1062.7941125	total: 904ms	remaining: 3.62s
20:	learn: 1060.8595836	total: 950ms	remaining: 3.57s
21:	learn: 1059.7841366	total: 999ms	remaining: 3.54s
22:	learn: 1058.8735747	total: 1.04s	remaining: 3.5s
23:	learn: 1057.4074038	total: 1.1s	remaining: 3.48s
24:	learn: 1056.6458759	total: 1.23s	remaining: 3.69s
25:	learn: 1056.1754641	total: 1.3s	remaining: 3.69s
26:	learn: 1055.5065769	total: 1.36s	remaining: 3.68s
27:	learn: 1054.7535536	total: 1.4s	remaining: 3.61s
28:	learn: 1053.9439908	total: 1.47s	remaining: 3.6s
29:	learn: 1053.3258735	total: 1.53s	remaining: 3.57s
30:	learn: 1052.6360193	total: 1.59s	remaining: 3.54s
31:	learn: 1051.9547290	total: 1.72s	remaining: 3.65s
32:	learn: 1051.0040940	total: 1.8s	remaining: 3.66s
33:	learn: 1050.3912570	total: 1.87s	remaining: 3.62s
34:	learn: 1049.6175008	total: 1.9s	remaining: 3.52s
35:	learn: 1049.1373669	total: 1.92s	remaining: 3.41s
36:	learn: 1048.3851874	total: 1.97s	remaining: 3.36s
37:	learn: 1047.6099125	total: 2.04s	remaining: 3.32s
38:	learn: 1047.1903697	total: 2.12s	remaining: 3.32s
39:	learn: 1044.9772792	total: 2.17s	remaining: 3.26s
40:	learn: 1044.3996264	total: 2.22s	remaining: 3.19s
41:	learn: 1043.8535977	total: 2.38s	remaining: 3.29s
42:	learn: 1043.2947160	total: 2.47s	remaining: 3.27s
43:	learn: 1042.3512584	total: 2.54s	remaining: 3.23s
44:	learn: 1041.6099643	total: 2.6s	remaining: 3.17s
45:	learn: 1040.7071345	total: 2.65s	remaining: 3.11s
46:	learn: 1040.3243616	total: 2.77s	remaining: 3.12s
47:	learn: 1039.7389157	total: 2.81s	remaining: 3.05s
48:	learn: 1039.2158774	total: 2.86s	remaining: 2.98s
49:	learn: 1038.0617820	total: 2.95s	remaining: 2.95s
50:	learn: 1037.5510567	total: 3.04s	remaining: 2.92s
51:	learn: 1036.8756752	total: 3.1s	remaining: 2.86s
52:	learn: 1036.3104164	total: 3.19s	remaining: 2.83s
53:	learn: 1035.6244734	total: 3.25s	remaining: 2.77s
54:	learn: 1035.2480187	total: 3.31s	remaining: 2.71s
55:	learn: 1034.8403604	total: 3.46s	remaining: 2.72s
56:	learn: 1033.9346556	total: 3.53s	remaining: 2.66s
57:	learn: 1033.5772158	total: 3.58s	remaining: 2.6s
58:	learn: 1032.8066536	total: 3.63s	remaining: 2.52s
59:	learn: 1032.0213127	total: 3.67s	remaining: 2.45s
60:	learn: 1031.3778549	total: 3.77s	remaining: 2.41s
61:	learn: 1031.0965200	total: 3.83s	remaining: 2.35s
62:	learn: 1030.8190132	total: 3.89s	remaining: 2.29s
63:	learn: 1030.2185930	total: 3.94s	remaining: 2.22s
64:	learn: 1029.6821670	total: 3.99s	remaining: 2.15s
65:	learn: 1029.1478931	total: 4.04s	remaining: 2.08s
66:	learn: 1028.5323466	total: 4.13s	remaining: 2.03s
67:	learn: 1027.8489811	total: 4.18s	remaining: 1.97s
68:	learn: 1026.9665737	total: 4.22s	remaining: 1.9s
69:	learn: 1026.1904588	total: 4.32s	remaining: 1.85s
70:	learn: 1025.4845755	total: 4.37s	remaining: 1.78s
71:	learn: 1025.2730200	total: 4.47s	remaining: 1.74s
72:	learn: 1024.8050901	total: 4.52s	remaining: 1.67s
73:	learn: 1024.1847183	total: 4.62s	remaining: 1.62s
74:	learn: 1023.4698498	total: 4.69s	remaining: 1.56s
75:	learn: 1023.1097976	total: 4.75s	remaining: 1.5s
76:	learn: 1022.7600274	total: 4.8s	remaining: 1.44s
77:	learn: 1022.1124550	total: 4.87s	remaining: 1.37s
78:	learn: 1021.6208782	total: 5s	remaining: 1.33s
79:	learn: 1020.8221791	total: 5.04s	remaining: 1.26s
80:	learn: 1020.1789205	total: 5.1s	remaining: 1.2s
81:	learn: 1019.8352431	total: 5.18s	remaining: 1.14s
82:	learn: 1019.6083672	total: 5.24s	remaining: 1.07s
83:	learn: 1019.2597085	total: 5.3s	remaining: 1.01s
84:	learn: 1018.5814005	total: 5.36s	remaining: 946ms
85:	learn: 1018.1734312	total: 5.41s	remaining: 881ms
86:	learn: 1017.5919854	total: 5.49s	remaining: 820ms
87:	learn: 1017.4038140	total: 5.55s	remaining: 756ms
88:	learn: 1016.9763085	total: 5.62s	remaining: 694ms
89:	learn: 1016.8028723	total: 5.66s	remaining: 629ms
90:	learn: 1016.1219430	total: 5.75s	remaining: 569ms
91:	learn: 1015.7211698	total: 5.82s	remaining: 506ms
92:	learn: 1015.1403583	total: 5.87s	remaining: 442ms
93:	learn: 1014.3590174	total: 5.95s	remaining: 380ms
94:	learn: 1013.8408238	total: 6.02s	remaining: 317ms
95:	learn: 1013.3959575	total: 6.08s	remaining: 254ms
96:	learn: 1012.9414376	total: 6.15s	remaining: 190ms
97:	learn: 1012.4137123	total: 6.27s	remaining: 128ms
98:	learn: 1012.1565237	total: 6.28s	remaining: 63.4ms
99:	learn: 1011.4542513	total: 6.37s	remaining: 0us
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.225686 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 813
[LightGBM] [Info] Number of data points in the train set: 5454, number of used features: 39
[LightGBM] [Info] Start training from score 2171.037443
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.233240 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 814
[LightGBM] [Info] Number of data points in the train set: 5454, number of used features: 39
[LightGBM] [Info] Start training from score 2188.546493
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
8:	learn: 1089.8500423	total: 611ms	remaining: 6.18s
9:	learn: 1083.3962208	total: 655ms	remaining: 5.89s
10:	learn: 1076.8361860	total: 663ms	remaining: 5.36s
11:	learn: 1073.5873524	total: 675ms	remaining: 4.95s
12:	learn: 1070.3005925	total: 766ms	remaining: 5.13s
13:	learn: 1067.4295530	total: 937ms	remaining: 5.76s
14:	learn: 1065.3627603	total: 989ms	remaining: 5.61s
15:	learn: 1063.4870143	total: 1.02s	remaining: 5.38s
16:	learn: 1062.1145750	total: 1.08s	remaining: 5.29s
17:	learn: 1061.5919137	total: 1.16s	remaining: 5.26s
18:	learn: 1060.6950294	total: 1.24s	remaining: 5.27s
19:	learn: 1059.8627288	total: 1.27s	remaining: 5.1s
20:	learn: 1058.8292787	total: 1.36s	remaining: 5.11s
21:	learn: 1057.7080252	total: 1.42s	remaining: 5.04s
22:	learn: 1055.8752551	total: 1.47s	remaining: 4.93s
23:	learn: 1054.5941567	total: 1.48s	remaining: 4.7s
24:	learn: 1053.7147004	total: 1.58s	remaining: 4.75s
25:	learn: 1051.6767355	total: 1.68s	remaining: 4.79s
26:	learn: 1050.9051963	total: 1.73s	remaining: 4.68s
27:	learn: 1050.0855561	total: 1.81s	remaining: 4.67s
28:	learn: 1049.3504701	total: 1.85s	remaining: 4.53s
29:	learn: 1048.7403914	total: 1.9s	remaining: 4.43s
30:	learn: 1047.9774725	total: 1.96s	remaining: 4.36s
31:	learn: 1047.2892232	total: 2.04s	remaining: 4.33s
32:	learn: 1046.2698151	total: 2.08s	remaining: 4.23s
33:	learn: 1045.8763445	total: 2.16s	remaining: 4.19s
34:	learn: 1045.3793453	total: 2.23s	remaining: 4.14s
35:	learn: 1044.8275032	total: 2.28s	remaining: 4.06s
36:	learn: 1043.6092505	total: 2.35s	remaining: 4.01s
37:	learn: 1042.8622278	total: 2.42s	remaining: 3.96s
38:	learn: 1042.3165810	total: 2.49s	remaining: 3.89s
39:	learn: 1041.6043324	total: 2.56s	remaining: 3.84s
40:	learn: 1040.8998125	total: 2.69s	remaining: 3.86s
41:	learn: 1040.0218483	total: 2.76s	remaining: 3.81s
42:	learn: 1039.4219771	total: 2.83s	remaining: 3.76s
43:	learn: 1038.8075894	total: 2.88s	remaining: 3.66s
44:	learn: 1038.2286160	total: 2.95s	remaining: 3.6s
45:	learn: 1037.6693438	total: 3.01s	remaining: 3.53s
46:	learn: 1037.1343330	total: 3.06s	remaining: 3.46s
47:	learn: 1036.4027837	total: 3.16s	remaining: 3.42s
48:	learn: 1035.8902373	total: 3.22s	remaining: 3.35s
49:	learn: 1034.8976412	total: 3.33s	remaining: 3.33s
50:	learn: 1033.9053168	total: 3.44s	remaining: 3.3s
51:	learn: 1033.3442258	total: 3.5s	remaining: 3.23s
52:	learn: 1032.9399023	total: 3.54s	remaining: 3.14s
53:	learn: 1032.0202420	total: 3.57s	remaining: 3.04s
54:	learn: 1031.2178359	total: 3.66s	remaining: 2.99s
55:	learn: 1030.4324678	total: 3.74s	remaining: 2.94s
56:	learn: 1029.6101276	total: 3.89s	remaining: 2.94s
57:	learn: 1028.8750895	total: 3.9s	remaining: 2.83s
58:	learn: 1028.1799782	total: 3.96s	remaining: 2.75s
59:	learn: 1027.5783450	total: 4.02s	remaining: 2.68s
60:	learn: 1027.1865627	total: 4.11s	remaining: 2.63s
61:	learn: 1026.5767747	total: 4.24s	remaining: 2.6s
62:	learn: 1026.0566895	total: 4.33s	remaining: 2.54s
63:	learn: 1025.5891276	total: 4.41s	remaining: 2.48s
64:	learn: 1025.1814914	total: 4.49s	remaining: 2.42s
65:	learn: 1024.6934055	total: 4.54s	remaining: 2.34s
66:	learn: 1024.3752978	total: 4.62s	remaining: 2.27s
67:	learn: 1024.1156005	total: 4.73s	remaining: 2.23s
68:	learn: 1023.4401744	total: 4.76s	remaining: 2.14s
69:	learn: 1022.6658037	total: 4.78s	remaining: 2.05s
70:	learn: 1021.7113306	total: 4.81s	remaining: 1.97s
71:	learn: 1021.0826497	total: 4.95s	remaining: 1.92s
72:	learn: 1020.6424570	total: 5s	remaining: 1.85s
73:	learn: 1020.0788615	total: 5.04s	remaining: 1.77s
74:	learn: 1019.2473323	total: 5.08s	remaining: 1.69s
75:	learn: 1018.8092349	total: 5.17s	remaining: 1.63s
76:	learn: 1017.9853873	total: 5.25s	remaining: 1.57s
77:	learn: 1017.5147679	total: 5.34s	remaining: 1.5s
78:	learn: 1016.8076024	total: 5.42s	remaining: 1.44s
79:	learn: 1016.5771366	total: 5.46s	remaining: 1.36s
80:	learn: 1016.0068297	total: 5.54s	remaining: 1.3s
81:	learn: 1015.0995414	total: 5.59s	remaining: 1.23s
82:	learn: 1014.5151066	total: 5.71s	remaining: 1.17s
83:	learn: 1013.6732260	total: 5.79s	remaining: 1.1s
84:	learn: 1012.8608258	total: 5.82s	remaining: 1.03s
85:	learn: 1012.5016652	total: 5.88s	remaining: 957ms
86:	learn: 1012.0699657	total: 5.89s	remaining: 880ms
87:	learn: 1011.3034079	total: 5.95s	remaining: 811ms
88:	learn: 1010.8130913	total: 6.02s	remaining: 745ms
89:	learn: 1010.3302700	total: 6.07s	remaining: 674ms
90:	learn: 1010.0046220	total: 6.1s	remaining: 604ms
91:	learn: 1009.6031821	total: 6.17s	remaining: 536ms
92:	learn: 1008.8706440	total: 6.24s	remaining: 470ms
93:	learn: 1008.3182459	total: 6.33s	remaining: 404ms
94:	learn: 1007.7931913	total: 6.34s	remaining: 334ms
95:	learn: 1007.2083625	total: 6.4s	remaining: 267ms
96:	learn: 1006.8191316	total: 6.43s	remaining: 199ms
97:	learn: 1006.3774566	total: 6.44s	remaining: 131ms
98:	learn: 1005.6037678	total: 6.45s	remaining: 65.2ms
99:	learn: 1005.1880079	total: 6.46s	remaining: 0us
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.161053 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 816
[LightGBM] [Info] Number of data points in the train set: 5454, number of used features: 39
[LightGBM] [Info] Start training from score 2147.784860
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.225892 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 816
[LightGBM] [Info] Number of data points in the train set: 5455, number of used features: 39
[LightGBM] [Info] Start training from score 2195.120754
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
37:	learn: 1100.9715014	total: 2.33s	remaining: 2.26s
38:	learn: 1098.7382815	total: 2.37s	remaining: 2.18s
39:	learn: 1096.5199343	total: 2.44s	remaining: 2.14s
40:	learn: 1094.7530205	total: 2.54s	remaining: 2.11s
41:	learn: 1092.1038539	total: 2.6s	remaining: 2.04s
42:	learn: 1089.6362805	total: 2.66s	remaining: 1.98s
43:	learn: 1088.0116670	total: 2.78s	remaining: 1.96s
44:	learn: 1086.0713810	total: 2.82s	remaining: 1.88s
45:	learn: 1084.6842051	total: 2.85s	remaining: 1.79s
46:	learn: 1083.4906078	total: 2.91s	remaining: 1.73s
47:	learn: 1082.2544055	total: 2.97s	remaining: 1.67s
48:	learn: 1081.0395185	total: 3.03s	remaining: 1.61s
49:	learn: 1079.7276506	total: 3.12s	remaining: 1.56s
50:	learn: 1078.7871550	total: 3.18s	remaining: 1.5s
51:	learn: 1078.1710122	total: 3.23s	remaining: 1.43s
52:	learn: 1076.8844534	total: 3.32s	remaining: 1.38s
53:	learn: 1075.5153795	total: 3.39s	remaining: 1.32s
54:	learn: 1074.5296140	total: 3.48s	remaining: 1.26s
55:	learn: 1073.9514640	total: 3.53s	remaining: 1.2s
56:	learn: 1073.0981517	total: 3.62s	remaining: 1.14s
57:	learn: 1072.1375460	total: 3.65s	remaining: 1.07s
58:	learn: 1071.1814060	total: 3.71s	remaining: 1.01s
59:	learn: 1070.3776306	total: 3.77s	remaining: 942ms
60:	learn: 1069.5428143	total: 3.84s	remaining: 882ms
61:	learn: 1068.8167207	total: 3.98s	remaining: 836ms
62:	learn: 1068.0598725	total: 4.05s	remaining: 772ms
63:	learn: 1067.6669902	total: 4.1s	remaining: 704ms
64:	learn: 1067.4771032	total: 4.14s	remaining: 637ms
65:	learn: 1066.9242335	total: 4.14s	remaining: 565ms
66:	learn: 1066.2827221	total: 4.15s	remaining: 496ms
67:	learn: 1065.6807133	total: 4.16s	remaining: 428ms
68:	learn: 1065.4752464	total: 4.16s	remaining: 362ms
69:	learn: 1064.9634366	total: 4.17s	remaining: 298ms
70:	learn: 1064.6460721	total: 4.18s	remaining: 235ms
71:	learn: 1064.2080782	total: 4.18s	remaining: 174ms
72:	learn: 1063.7180186	total: 4.19s	remaining: 115ms
73:	learn: 1063.3861438	total: 4.2s	remaining: 56.7ms
74:	learn: 1063.1402345	total: 4.2s	remaining: 0us
0:	learn: 1650.6479572	total: 86.5ms	remaining: 6.4s
1:	learn: 1605.8972477	total: 204ms	remaining: 7.43s
2:	learn: 1567.0629886	total: 253ms	remaining: 6.08s
3:	learn: 1533.8405178	total: 312ms	remaining: 5.53s
4:	learn: 1498.9936106	total: 363ms	remaining: 5.08s
5:	learn: 1466.4100003	total: 441ms	remaining: 5.07s
6:	learn: 1434.4333514	total: 539ms	remaining: 5.24s
7:	learn: 1406.8156784	total: 568ms	remaining: 4.76s
8:	learn: 1381.2135222	total: 658ms	remaining: 4.82s
9:	learn: 1358.2062271	total: 739ms	remaining: 4.8s
10:	learn: 1334.7946198	total: 763ms	remaining: 4.44s
11:	learn: 1314.4410032	total: 774ms	remaining: 4.06s
12:	learn: 1295.4744095	total: 786ms	remaining: 3.75s
13:	learn: 1276.1374963	total: 863ms	remaining: 3.76s
14:	learn: 1258.6546791	total: 872ms	remaining: 3.49s
15:	learn: 1244.8857407	total: 979ms	remaining: 3.61s
16:	learn: 1230.5479318	total: 1.05s	remaining: 3.6s
17:	learn: 1216.1913349	total: 1.12s	remaining: 3.56s
18:	learn: 1205.9548239	total: 1.18s	remaining: 3.48s
19:	learn: 1197.4188363	total: 1.24s	remaining: 3.41s
20:	learn: 1185.8276263	total: 1.28s	remaining: 3.29s
21:	learn: 1176.1854784	total: 1.35s	remaining: 3.25s
22:	learn: 1168.0416837	total: 1.45s	remaining: 3.28s
23:	learn: 1159.1419104	total: 1.5s	remaining: 3.18s
24:	learn: 1151.6655624	total: 1.54s	remaining: 3.08s
25:	learn: 1143.8033544	total: 1.62s	remaining: 3.05s
26:	learn: 1137.0319427	total: 1.72s	remaining: 3.06s
27:	learn: 1131.0495237	total: 1.78s	remaining: 2.99s
28:	learn: 1126.2011856	total: 1.84s	remaining: 2.92s
29:	learn: 1120.6068064	total: 1.92s	remaining: 2.88s
30:	learn: 1115.6201541	total: 1.98s	remaining: 2.81s
31:	learn: 1111.2795904	total: 2.05s	remaining: 2.76s
32:	learn: 1107.8346846	total: 2.14s	remaining: 2.73s
33:	learn: 1104.2820403	total: 2.15s	remaining: 2.59s
34:	learn: 1101.3199194	total: 2.27s	remaining: 2.6s
35:	learn: 1098.5804448	total: 2.48s	remaining: 2.69s
36:	learn: 1095.3370767	total: 2.56s	remaining: 2.63s
37:	learn: 1092.5895104	total: 2.6s	remaining: 2.53s
38:	learn: 1090.4991254	total: 2.71s	remaining: 2.51s
39:	learn: 1088.7569416	total: 2.87s	remaining: 2.52s
40:	learn: 1086.7421614	total: 2.92s	remaining: 2.42s
41:	learn: 1085.1035300	total: 2.96s	remaining: 2.33s
42:	learn: 1083.2519183	total: 3.03s	remaining: 2.26s
43:	learn: 1081.0726551	total: 3.09s	remaining: 2.18s
44:	learn: 1079.5718156	total: 3.12s	remaining: 2.08s
45:	learn: 1077.6360832	total: 3.21s	remaining: 2.02s
46:	learn: 1076.3107951	total: 3.24s	remaining: 1.93s
47:	learn: 1075.0720070	total: 3.39s	remaining: 1.9s
48:	learn: 1074.3354198	total: 3.43s	remaining: 1.82s
49:	learn: 1073.3289379	total: 3.56s	remaining: 1.78s
50:	learn: 1072.5512493	total: 3.6s	remaining: 1.7s
51:	learn: 1071.7159189	total: 3.69s	remaining: 1.63s
52:	learn: 1070.5977660	total: 3.73s	remaining: 1.55s
53:	learn: 1069.5783367	total: 3.81s	remaining: 1.48s
54:	learn: 1068.8114301	total: 3.89s	remaining: 1.41s
55:	learn: 1068.1463542	total: 4s	remaining: 1.36s
56:	learn: 1067.2792630	total: 4.04s	remaining: 1.27s
57:	learn: 1066.0911885	total: 4.13s	remaining: 1.21s
58:	learn: 1065.6966969	total: 4.19s	remaining: 1.14s
59:	learn: 1064.5974427	total: 4.24s	remaining: 1.06s
60:	learn: 1064.2679269	total: 4.33s	remaining: 994ms
61:	learn: 1063.9591218	total: 4.4s	remaining: 923ms
62:	learn: 1063.4889777	total: 4.45s	remaining: 848ms
63:	learn: 1062.5338683	total: 4.52s	remaining: 777ms
64:	learn: 1062.3695008	total: 4.6s	remaining: 707ms
65:	learn: 1061.8315912	total: 4.64s	remaining: 633ms
66:	learn: 1061.2926437	total: 4.75s	remaining: 567ms
67:	learn: 1060.9599143	total: 4.8s	remaining: 494ms
68:	learn: 1060.5274235	total: 4.85s	remaining: 422ms
69:	learn: 1060.1135212	total: 4.92s	remaining: 352ms
70:	learn: 1059.5092731	total: 4.95s	remaining: 279ms
71:	learn: 1058.8585357	total: 5.12s	remaining: 213ms
72:	learn: 1058.1479988	total: 5.15s	remaining: 141ms
73:	learn: 1057.6082562	total: 5.24s	remaining: 70.8ms
74:	learn: 1057.4481559	total: 5.25s	remaining: 0us
[CV] END stack__CAT__learning_rate=0.05, stack__CAT__max_depth=6, stack__CAT__n_estimators=75, stack__LGBM__learning_rate=0.05, stack__LGBM__max_depth=4, stack__LGBM__n_estimators=75, stack__XGB__learning_rate=0.3, stack__XGB__max_depth=6, stack__XGB__n_estimators=100, stack__final_estimator__max_depth=6, stack__final_estimator__n_estimators=100; total time=25.8min
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.300838 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 819
[LightGBM] [Info] Number of data points in the train set: 6818, number of used features: 39
[LightGBM] [Info] Start training from score 2180.679468
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.248895 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 815
[LightGBM] [Info] Number of data points in the train set: 5455, number of used features: 39
[LightGBM] [Info] Start training from score 2194.700891
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.169912 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 819
[LightGBM] [Info] Number of data points in the train set: 6818, number of used features: 39
[LightGBM] [Info] Start training from score 2180.679468
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
0:	learn: 1622.8482637	total: 230ms	remaining: 22.8s
1:	learn: 1539.3899822	total: 417ms	remaining: 20.4s
2:	learn: 1469.6290121	total: 505ms	remaining: 16.3s
3:	learn: 1408.6646244	total: 609ms	remaining: 14.6s
4:	learn: 1355.6971458	total: 728ms	remaining: 13.8s
5:	learn: 1316.6651942	total: 889ms	remaining: 13.9s
6:	learn: 1275.7999054	total: 1.14s	remaining: 15.1s
7:	learn: 1241.8528131	total: 1.25s	remaining: 14.4s
8:	learn: 1216.3093858	total: 1.35s	remaining: 13.6s
9:	learn: 1192.6923184	total: 1.5s	remaining: 13.5s
10:	learn: 1171.6997083	total: 1.68s	remaining: 13.6s
11:	learn: 1154.0421880	total: 1.9s	remaining: 13.9s
12:	learn: 1139.3642000	total: 2.07s	remaining: 13.8s
13:	learn: 1127.9775437	total: 2.17s	remaining: 13.3s
14:	learn: 1118.4978877	total: 2.28s	remaining: 12.9s
15:	learn: 1109.9125461	total: 2.4s	remaining: 12.6s
16:	learn: 1103.1288648	total: 2.5s	remaining: 12.2s
17:	learn: 1098.2058668	total: 2.62s	remaining: 11.9s
18:	learn: 1093.9566115	total: 2.74s	remaining: 11.7s
19:	learn: 1088.9759656	total: 2.94s	remaining: 11.7s
20:	learn: 1087.0450306	total: 2.95s	remaining: 11.1s
21:	learn: 1084.1150981	total: 3.2s	remaining: 11.3s
22:	learn: 1081.2492739	total: 3.31s	remaining: 11.1s
23:	learn: 1078.6502689	total: 3.49s	remaining: 11.1s
24:	learn: 1075.7353477	total: 3.66s	remaining: 11s
25:	learn: 1072.6092666	total: 3.77s	remaining: 10.7s
26:	learn: 1070.5982667	total: 3.9s	remaining: 10.5s
27:	learn: 1067.8436918	total: 4.11s	remaining: 10.6s
28:	learn: 1066.4435408	total: 4.3s	remaining: 10.5s
29:	learn: 1065.3989657	total: 4.37s	remaining: 10.2s
30:	learn: 1064.8260382	total: 4.49s	remaining: 10s
31:	learn: 1063.2719567	total: 4.64s	remaining: 9.87s
32:	learn: 1062.9382570	total: 4.69s	remaining: 9.52s
33:	learn: 1061.8664105	total: 4.88s	remaining: 9.46s
34:	learn: 1060.4419341	total: 5.05s	remaining: 9.39s
35:	learn: 1059.5330750	total: 5.26s	remaining: 9.35s
36:	learn: 1057.8790013	total: 5.42s	remaining: 9.22s
37:	learn: 1056.7652620	total: 5.57s	remaining: 9.09s
38:	learn: 1056.2019482	total: 5.69s	remaining: 8.9s
39:	learn: 1055.6484669	total: 5.78s	remaining: 8.67s
40:	learn: 1054.7802790	total: 5.88s	remaining: 8.46s
41:	learn: 1054.0762406	total: 5.99s	remaining: 8.27s
42:	learn: 1053.6702826	total: 6.18s	remaining: 8.19s
43:	learn: 1053.0176780	total: 6.36s	remaining: 8.09s
44:	learn: 1052.3699447	total: 6.43s	remaining: 7.86s
45:	learn: 1052.1369372	total: 6.56s	remaining: 7.7s
46:	learn: 1051.7561385	total: 6.78s	remaining: 7.64s
47:	learn: 1051.2592368	total: 7.03s	remaining: 7.61s
48:	learn: 1050.7982771	total: 7.21s	remaining: 7.51s
49:	learn: 1050.0496172	total: 7.38s	remaining: 7.38s
50:	learn: 1049.3542593	total: 7.66s	remaining: 7.36s
51:	learn: 1048.9591381	total: 7.76s	remaining: 7.16s
52:	learn: 1048.7006973	total: 7.95s	remaining: 7.05s
53:	learn: 1047.8242985	total: 8.11s	remaining: 6.91s
54:	learn: 1045.9898926	total: 8.25s	remaining: 6.75s
55:	learn: 1045.2359352	total: 8.41s	remaining: 6.61s
56:	learn: 1044.1906372	total: 8.54s	remaining: 6.45s
57:	learn: 1043.8897251	total: 8.73s	remaining: 6.32s
58:	learn: 1043.4161011	total: 8.82s	remaining: 6.13s
59:	learn: 1042.8731126	total: 8.97s	remaining: 5.98s
60:	learn: 1042.3579496	total: 9.22s	remaining: 5.89s
61:	learn: 1042.0281543	total: 9.39s	remaining: 5.76s
62:	learn: 1041.7049040	total: 9.47s	remaining: 5.56s
63:	learn: 1040.5800787	total: 9.61s	remaining: 5.4s
64:	learn: 1038.4761120	total: 9.81s	remaining: 5.28s
65:	learn: 1038.2195857	total: 9.96s	remaining: 5.13s
66:	learn: 1037.7186104	total: 10.1s	remaining: 4.95s
67:	learn: 1037.2018074	total: 10.3s	remaining: 4.83s
68:	learn: 1036.7230330	total: 10.5s	remaining: 4.7s
69:	learn: 1036.3252007	total: 10.6s	remaining: 4.55s
70:	learn: 1036.0249833	total: 10.8s	remaining: 4.42s
71:	learn: 1035.3830402	total: 11s	remaining: 4.28s
72:	learn: 1035.1688104	total: 11.1s	remaining: 4.11s
73:	learn: 1034.5130000	total: 11.3s	remaining: 3.96s
74:	learn: 1033.1469865	total: 11.4s	remaining: 3.8s
75:	learn: 1032.6922117	total: 11.5s	remaining: 3.63s
76:	learn: 1032.2327705	total: 11.7s	remaining: 3.48s
77:	learn: 1031.7438692	total: 11.7s	remaining: 3.3s
78:	learn: 1031.2563130	total: 11.9s	remaining: 3.17s
79:	learn: 1030.8718682	total: 12.1s	remaining: 3.03s
80:	learn: 1030.5033671	total: 12.2s	remaining: 2.87s
81:	learn: 1030.1230220	total: 12.3s	remaining: 2.7s
82:	learn: 1029.6028509	total: 12.5s	remaining: 2.57s
83:	learn: 1028.9199394	total: 12.7s	remaining: 2.41s
84:	learn: 1028.5211488	total: 12.9s	remaining: 2.27s
85:	learn: 1028.1413868	total: 13s	remaining: 2.12s
86:	learn: 1027.9075770	total: 13.1s	remaining: 1.95s
87:	learn: 1027.4629018	total: 13.2s	remaining: 1.8s
88:	learn: 1027.0337447	total: 13.4s	remaining: 1.66s
89:	learn: 1026.4356213	total: 13.5s	remaining: 1.5s
90:	learn: 1025.9146627	total: 13.6s	remaining: 1.35s
91:	learn: 1025.5362628	total: 13.8s	remaining: 1.2s
92:	learn: 1025.1429397	total: 13.9s	remaining: 1.05s
93:	learn: 1024.6520357	total: 14.1s	remaining: 903ms
94:	learn: 1024.1355327	total: 14.3s	remaining: 750ms
95:	learn: 1023.7742273	total: 14.4s	remaining: 600ms
96:	learn: 1023.2747905	total: 14.5s	remaining: 449ms
97:	learn: 1022.2730049	total: 14.6s	remaining: 298ms
98:	learn: 1021.9218627	total: 14.8s	remaining: 149ms
99:	learn: 1021.4434499	total: 14.8s	remaining: 0us
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.234756 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 817
[LightGBM] [Info] Number of data points in the train set: 5454, number of used features: 39
[LightGBM] [Info] Start training from score 2173.066949
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.290467 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 814
[LightGBM] [Info] Number of data points in the train set: 5454, number of used features: 39
[LightGBM] [Info] Start training from score 2188.546493
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.221233 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 816
[LightGBM] [Info] Number of data points in the train set: 5454, number of used features: 39

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.252955 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 816
[LightGBM] [Info] Number of data points in the train set: 5454, number of used features: 39
[LightGBM] [Info] Start training from score 2180.707534
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.256446 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 813
[LightGBM] [Info] Number of data points in the train set: 5455, number of used features: 39
[LightGBM] [Info] Start training from score 2175.226332
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.245103 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 815
[LightGBM] [Info] Number of data points in the train set: 5455, number of used features: 39
[LightGBM] [Info] Start training from score 2185.996669
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.209313 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 812
[LightGBM] [Info] Number of data points in the train set: 5455, number of used features: 39
[LightGBM] [Info] Start training from score 2198.135467
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.229350 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 816
[LightGBM] [Info] Number of data points in the train set: 5455, number of used features: 39
[LightGBM] [Info] Start training from score 2182.058258
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.255415 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 818
[LightGBM] [Info] Number of data points in the train set: 5455, number of used features: 39
[LightGBM] [Info] Start training from score 2190.691077
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
0:	learn: 1535.2356585	total: 9.66ms	remaining: 956ms
1:	learn: 1407.3584860	total: 55.5ms	remaining: 2.72s
2:	learn: 1310.0463453	total: 148ms	remaining: 4.77s
3:	learn: 1247.2447079	total: 233ms	remaining: 5.58s
4:	learn: 1192.4376824	total: 279ms	remaining: 5.29s
5:	learn: 1153.8953084	total: 436ms	remaining: 6.83s
6:	learn: 1130.4500945	total: 511ms	remaining: 6.79s
7:	learn: 1112.9466254	total: 669ms	remaining: 7.69s
8:	learn: 1101.0233315	total: 788ms	remaining: 7.97s
9:	learn: 1092.3898527	total: 944ms	remaining: 8.5s
10:	learn: 1085.1897017	total: 1.04s	remaining: 8.39s
11:	learn: 1081.0482570	total: 1.09s	remaining: 8.02s
12:	learn: 1077.1976869	total: 1.15s	remaining: 7.71s
13:	learn: 1073.8204368	total: 1.23s	remaining: 7.55s
14:	learn: 1072.2076815	total: 1.33s	remaining: 7.51s
15:	learn: 1070.2731955	total: 1.42s	remaining: 7.48s
16:	learn: 1067.6862307	total: 1.46s	remaining: 7.13s
17:	learn: 1066.8559514	total: 1.51s	remaining: 6.88s
18:	learn: 1065.0772154	total: 1.57s	remaining: 6.71s
19:	learn: 1064.2687191	total: 1.58s	remaining: 6.33s
20:	learn: 1063.2262097	total: 1.76s	remaining: 6.64s
21:	learn: 1062.3783012	total: 1.82s	remaining: 6.44s
22:	learn: 1061.7098141	total: 1.95s	remaining: 6.51s
23:	learn: 1060.8763058	total: 1.99s	remaining: 6.29s
24:	learn: 1060.3107904	total: 2.02s	remaining: 6.07s
25:	learn: 1059.8839370	total: 2.15s	remaining: 6.11s
26:	learn: 1059.0898266	total: 2.23s	remaining: 6.04s
27:	learn: 1058.1180813	total: 2.32s	remaining: 5.96s
28:	learn: 1056.6217332	total: 2.39s	remaining: 5.86s
29:	learn: 1056.0827581	total: 2.51s	remaining: 5.86s
30:	learn: 1054.4503115	total: 2.59s	remaining: 5.76s
31:	learn: 1053.8792885	total: 2.67s	remaining: 5.67s
32:	learn: 1053.5562912	total: 2.72s	remaining: 5.53s
33:	learn: 1052.4634329	total: 2.78s	remaining: 5.39s
34:	learn: 1051.8235631	total: 2.87s	remaining: 5.33s
35:	learn: 1051.0412983	total: 2.93s	remaining: 5.22s
36:	learn: 1050.7082978	total: 3s	remaining: 5.11s
37:	learn: 1050.0102305	total: 3.05s	remaining: 4.98s
38:	learn: 1049.2633178	total: 3.08s	remaining: 4.81s
39:	learn: 1049.0982401	total: 3.15s	remaining: 4.72s
40:	learn: 1048.5587256	total: 3.23s	remaining: 4.64s
41:	learn: 1047.7083973	total: 3.32s	remaining: 4.58s
42:	learn: 1047.0567904	total: 3.37s	remaining: 4.47s
43:	learn: 1046.5149461	total: 3.48s	remaining: 4.43s
44:	learn: 1045.8630972	total: 3.53s	remaining: 4.32s
45:	learn: 1045.1218970	total: 3.63s	remaining: 4.26s
46:	learn: 1044.5737358	total: 3.71s	remaining: 4.19s
47:	learn: 1043.9122206	total: 3.76s	remaining: 4.08s
48:	learn: 1042.9216282	total: 3.85s	remaining: 4.01s
49:	learn: 1042.2583238	total: 3.93s	remaining: 3.93s
50:	learn: 1041.5484658	total: 4.01s	remaining: 3.85s
51:	learn: 1041.0719748	total: 4.01s	remaining: 3.71s
52:	learn: 1040.4061278	total: 4.13s	remaining: 3.66s
53:	learn: 1039.8011072	total: 4.2s	remaining: 3.58s
54:	learn: 1039.2320223	total: 4.29s	remaining: 3.51s
55:	learn: 1038.5086347	total: 4.34s	remaining: 3.41s
56:	learn: 1037.9733974	total: 4.39s	remaining: 3.31s
57:	learn: 1037.2691678	total: 4.57s	remaining: 3.31s
58:	learn: 1036.7953963	total: 4.64s	remaining: 3.23s
59:	learn: 1036.1870970	total: 4.7s	remaining: 3.13s
60:	learn: 1035.5563976	total: 4.86s	remaining: 3.1s
61:	learn: 1035.1533140	total: 4.91s	remaining: 3.01s
62:	learn: 1034.7337564	total: 5.04s	remaining: 2.96s
63:	learn: 1034.4562706	total: 5.11s	remaining: 2.87s
64:	learn: 1033.6089850	total: 5.16s	remaining: 2.78s
65:	learn: 1033.3772556	total: 5.24s	remaining: 2.7s
66:	learn: 1032.8436829	total: 5.29s	remaining: 2.61s
67:	learn: 1032.3184607	total: 5.45s	remaining: 2.56s
68:	learn: 1031.9166671	total: 5.52s	remaining: 2.48s
69:	learn: 1031.4547085	total: 5.61s	remaining: 2.4s
70:	learn: 1030.8414670	total: 5.69s	remaining: 2.32s
71:	learn: 1030.1366249	total: 5.75s	remaining: 2.23s
72:	learn: 1029.2893992	total: 5.82s	remaining: 2.15s
73:	learn: 1028.7739889	total: 5.89s	remaining: 2.07s
74:	learn: 1028.2474550	total: 5.93s	remaining: 1.98s
75:	learn: 1027.6013264	total: 6.02s	remaining: 1.9s
76:	learn: 1026.9874373	total: 6.08s	remaining: 1.82s
77:	learn: 1026.7307197	total: 6.1s	remaining: 1.72s
78:	learn: 1026.1508841	total: 6.1s	remaining: 1.62s
79:	learn: 1025.5191310	total: 6.11s	remaining: 1.53s
80:	learn: 1024.9414723	total: 6.2s	remaining: 1.45s
81:	learn: 1024.4801118	total: 6.26s	remaining: 1.37s
82:	learn: 1023.9842486	total: 6.27s	remaining: 1.28s
83:	learn: 1023.4615484	total: 6.28s	remaining: 1.2s
84:	learn: 1022.7715378	total: 6.29s	remaining: 1.11s
85:	learn: 1021.7215999	total: 6.33s	remaining: 1.03s
86:	learn: 1021.1391613	total: 6.36s	remaining: 950ms
87:	learn: 1020.4679810	total: 6.38s	remaining: 870ms
88:	learn: 1019.7964608	total: 6.42s	remaining: 794ms
89:	learn: 1019.5280874	total: 6.43s	remaining: 715ms
90:	learn: 1019.0013839	total: 6.44s	remaining: 637ms
91:	learn: 1018.4964188	total: 6.45s	remaining: 561ms
92:	learn: 1018.1342808	total: 6.47s	remaining: 487ms
93:	learn: 1017.5094757	total: 6.48s	remaining: 414ms
94:	learn: 1016.9992513	total: 6.49s	remaining: 342ms
95:	learn: 1016.4748623	total: 6.5s	remaining: 271ms
96:	learn: 1016.0751993	total: 6.5s	remaining: 201ms
97:	learn: 1015.4670089	total: 6.51s	remaining: 133ms
98:	learn: 1015.1017176	total: 6.52s	remaining: 65.9ms
99:	learn: 1014.7009566	total: 6.53s	remaining: 0us
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.258842 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 817
[LightGBM] [Info] Number of data points in the train set: 5454, number of used features: 39
[LightGBM] [Info] Start training from score 2173.066949
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.279954 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 813
[LightGBM] [Info] Number of data points in the train set: 5454, number of used features: 39
[LightGBM] [Info] Start training from score 2197.953391
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.249168 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 816
[LightGBM] [Info] Number of data points in the train set: 5454, number of used features: 39
[LightGBM] [Info] Start training from score 2180.642468
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.273134 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 815
[LightGBM] [Info] Number of data points in the train set: 5455, number of used features: 39
[LightGBM] [Info] Start training from score 2185.850083
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.233215 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 818
[LightGBM] [Info] Number of data points in the train set: 5456, number of used features: 39
[LightGBM] [Info] Start training from score 2199.213061
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.258946 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 818
[LightGBM] [Info] Number of data points in the train set: 5456, number of used features: 39
[LightGBM] [Info] Start training from score 2196.918271
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.233362 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 815
[LightGBM] [Info] Number of data points in the train set: 5454, number of used features: 39
[LightGBM] [Info] Start training from score 2184.956129
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
0:	learn: 1661.5571196	total: 95.4ms	remaining: 7.06s
1:	learn: 1616.8279301	total: 104ms	remaining: 3.79s
2:	learn: 1574.6800474	total: 231ms	remaining: 5.54s
3:	learn: 1537.4449496	total: 274ms	remaining: 4.87s
4:	learn: 1502.5765550	total: 370ms	remaining: 5.18s
5:	learn: 1472.8030345	total: 437ms	remaining: 5.02s
6:	learn: 1445.8381722	total: 568ms	remaining: 5.52s
7:	learn: 1417.6322265	total: 632ms	remaining: 5.29s
8:	learn: 1389.8318958	total: 704ms	remaining: 5.17s
9:	learn: 1366.4319516	total: 791ms	remaining: 5.14s
10:	learn: 1343.6306145	total: 867ms	remaining: 5.04s
11:	learn: 1321.2780116	total: 905ms	remaining: 4.75s
12:	learn: 1301.9290079	total: 925ms	remaining: 4.41s
13:	learn: 1286.1425259	total: 933ms	remaining: 4.07s
14:	learn: 1269.4976267	total: 953ms	remaining: 3.81s
15:	learn: 1256.1811873	total: 1.09s	remaining: 4.01s
16:	learn: 1243.1938850	total: 1.12s	remaining: 3.82s
17:	learn: 1228.6234641	total: 1.18s	remaining: 3.74s
18:	learn: 1215.0309890	total: 1.31s	remaining: 3.87s
19:	learn: 1204.4241190	total: 1.36s	remaining: 3.75s
20:	learn: 1192.8689278	total: 1.39s	remaining: 3.58s
21:	learn: 1182.9930208	total: 1.44s	remaining: 3.48s
22:	learn: 1173.9078742	total: 1.51s	remaining: 3.41s
23:	learn: 1165.7993453	total: 1.54s	remaining: 3.28s
24:	learn: 1158.9566109	total: 1.59s	remaining: 3.18s
25:	learn: 1151.5153269	total: 1.62s	remaining: 3.05s
26:	learn: 1145.2907062	total: 1.66s	remaining: 2.96s
27:	learn: 1138.7677641	total: 1.72s	remaining: 2.88s
28:	learn: 1133.7654389	total: 1.77s	remaining: 2.81s
29:	learn: 1128.9919270	total: 1.84s	remaining: 2.75s
30:	learn: 1124.1523169	total: 1.88s	remaining: 2.66s
31:	learn: 1120.5249239	total: 1.96s	remaining: 2.63s
32:	learn: 1116.3103813	total: 2.01s	remaining: 2.56s
33:	learn: 1112.1478499	total: 2.04s	remaining: 2.46s
34:	learn: 1108.6155094	total: 2.05s	remaining: 2.34s
35:	learn: 1105.7893442	total: 2.06s	remaining: 2.23s
36:	learn: 1102.2952672	total: 2.06s	remaining: 2.12s
37:	learn: 1100.2055082	total: 2.07s	remaining: 2.02s
38:	learn: 1097.9360232	total: 2.08s	remaining: 1.92s
39:	learn: 1095.2099638	total: 2.08s	remaining: 1.82s
40:	learn: 1092.9352284	total: 2.09s	remaining: 1.73s
41:	learn: 1091.2227196	total: 2.1s	remaining: 1.65s
42:	learn: 1089.0403463	total: 2.1s	remaining: 1.57s
43:	learn: 1087.6258374	total: 2.11s	remaining: 1.49s
44:	learn: 1086.2703419	total: 2.14s	remaining: 1.43s
45:	learn: 1085.0057080	total: 2.16s	remaining: 1.36s
46:	learn: 1083.7122660	total: 2.17s	remaining: 1.29s
47:	learn: 1082.7168527	total: 2.18s	remaining: 1.23s
48:	learn: 1080.7193136	total: 2.19s	remaining: 1.16s
49:	learn: 1079.5012816	total: 2.23s	remaining: 1.12s
50:	learn: 1078.4944858	total: 2.31s	remaining: 1.09s
51:	learn: 1077.6205652	total: 2.39s	remaining: 1.06s
52:	learn: 1076.5037306	total: 2.46s	remaining: 1.02s
53:	learn: 1075.5397315	total: 2.49s	remaining: 968ms
54:	learn: 1074.3415630	total: 2.53s	remaining: 919ms
55:	learn: 1073.9851878	total: 2.59s	remaining: 878ms
56:	learn: 1073.3653680	total: 2.61s	remaining: 826ms
57:	learn: 1072.6871001	total: 2.65s	remaining: 776ms
58:	learn: 1072.1840565	total: 2.69s	remaining: 729ms
59:	learn: 1071.5695898	total: 2.71s	remaining: 678ms
60:	learn: 1070.5315861	total: 2.76s	remaining: 633ms
61:	learn: 1069.6574651	total: 2.79s	remaining: 586ms
62:	learn: 1069.0483897	total: 2.81s	remaining: 535ms
63:	learn: 1068.2120835	total: 2.84s	remaining: 489ms
64:	learn: 1067.7093635	total: 2.9s	remaining: 446ms
65:	learn: 1067.1246226	total: 2.92s	remaining: 399ms
66:	learn: 1066.2518566	total: 3.02s	remaining: 361ms
67:	learn: 1065.7607536	total: 3.03s	remaining: 312ms
68:	learn: 1065.3369073	total: 3.07s	remaining: 267ms
69:	learn: 1064.8029538	total: 3.16s	remaining: 226ms
70:	learn: 1064.5666576	total: 3.23s	remaining: 182ms
71:	learn: 1064.2717977	total: 3.33s	remaining: 139ms
72:	learn: 1064.1334007	total: 3.42s	remaining: 93.7ms
73:	learn: 1063.7770989	total: 3.46s	remaining: 46.7ms
74:	learn: 1063.5336001	total: 3.47s	remaining: 0us
0:	learn: 1674.1035404	total: 91.4ms	remaining: 6.76s
1:	learn: 1634.1960537	total: 131ms	remaining: 4.79s
2:	learn: 1591.3377337	total: 195ms	remaining: 4.68s
3:	learn: 1551.9096043	total: 229ms	remaining: 4.06s
4:	learn: 1516.4793272	total: 382ms	remaining: 5.35s
5:	learn: 1486.1670784	total: 432ms	remaining: 4.97s
6:	learn: 1456.0669975	total: 485ms	remaining: 4.71s
7:	learn: 1430.0343522	total: 524ms	remaining: 4.39s
8:	learn: 1405.7952246	total: 535ms	remaining: 3.93s
9:	learn: 1380.0094483	total: 543ms	remaining: 3.53s
10:	learn: 1359.0544674	total: 557ms	remaining: 3.24s
11:	learn: 1341.2112701	total: 573ms	remaining: 3.01s
12:	learn: 1323.1960005	total: 589ms	remaining: 2.81s
13:	learn: 1303.9492396	total: 607ms	remaining: 2.65s
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
0:	learn: 1654.7008261	total: 11.2ms	remaining: 831ms
1:	learn: 1612.9055404	total: 18.6ms	remaining: 680ms
2:	learn: 1571.3308803	total: 32ms	remaining: 769ms
3:	learn: 1535.4585706	total: 38.3ms	remaining: 679ms
4:	learn: 1500.7919714	total: 101ms	remaining: 1.41s
5:	learn: 1471.5475795	total: 185ms	remaining: 2.13s
6:	learn: 1440.5188745	total: 243ms	remaining: 2.36s
7:	learn: 1412.0555555	total: 252ms	remaining: 2.11s
8:	learn: 1388.4812957	total: 257ms	remaining: 1.88s
9:	learn: 1363.8463989	total: 265ms	remaining: 1.72s
10:	learn: 1340.5611543	total: 272ms	remaining: 1.58s
11:	learn: 1319.2902395	total: 281ms	remaining: 1.48s
12:	learn: 1299.8220452	total: 287ms	remaining: 1.37s
13:	learn: 1284.2519848	total: 295ms	remaining: 1.28s
14:	learn: 1267.5513678	total: 302ms	remaining: 1.21s
15:	learn: 1254.5591631	total: 310ms	remaining: 1.14s
16:	learn: 1239.7504714	total: 318ms	remaining: 1.08s
17:	learn: 1228.0132531	total: 387ms	remaining: 1.22s
18:	learn: 1215.9652301	total: 481ms	remaining: 1.42s
19:	learn: 1203.9381738	total: 531ms	remaining: 1.46s
20:	learn: 1195.3943196	total: 591ms	remaining: 1.52s
21:	learn: 1184.6069863	total: 649ms	remaining: 1.56s
22:	learn: 1175.6441742	total: 794ms	remaining: 1.79s
23:	learn: 1168.7065628	total: 823ms	remaining: 1.75s
24:	learn: 1161.8227302	total: 856ms	remaining: 1.71s
25:	learn: 1154.4458940	total: 929ms	remaining: 1.75s
26:	learn: 1148.4856551	total: 1.01s	remaining: 1.79s
27:	learn: 1143.5228832	total: 1.05s	remaining: 1.75s
28:	learn: 1136.8964858	total: 1.08s	remaining: 1.71s
29:	learn: 1133.0449959	total: 1.19s	remaining: 1.78s
30:	learn: 1129.0169045	total: 1.23s	remaining: 1.75s
31:	learn: 1123.6759638	total: 1.27s	remaining: 1.71s
32:	learn: 1119.3827988	total: 1.37s	remaining: 1.75s
33:	learn: 1116.2493937	total: 1.45s	remaining: 1.75s
34:	learn: 1112.1216862	total: 1.46s	remaining: 1.67s
35:	learn: 1109.1492081	total: 1.57s	remaining: 1.7s
36:	learn: 1106.6513335	total: 1.61s	remaining: 1.66s
37:	learn: 1103.3872089	total: 1.71s	remaining: 1.66s
38:	learn: 1100.8821288	total: 1.73s	remaining: 1.6s
39:	learn: 1099.2584122	total: 1.77s	remaining: 1.55s
40:	learn: 1097.1125942	total: 1.86s	remaining: 1.54s
41:	learn: 1095.7851466	total: 1.89s	remaining: 1.48s
42:	learn: 1093.2839573	total: 1.92s	remaining: 1.43s
43:	learn: 1091.2162943	total: 1.98s	remaining: 1.4s
44:	learn: 1089.7093814	total: 1.99s	remaining: 1.33s
45:	learn: 1088.4182104	total: 2s	remaining: 1.26s
46:	learn: 1087.3392088	total: 2.09s	remaining: 1.24s
47:	learn: 1086.0612474	total: 2.11s	remaining: 1.19s
48:	learn: 1084.8744128	total: 2.14s	remaining: 1.14s
49:	learn: 1083.9849957	total: 2.16s	remaining: 1.08s
50:	learn: 1082.5006516	total: 2.23s	remaining: 1.05s
51:	learn: 1080.8930633	total: 2.3s	remaining: 1.02s
52:	learn: 1079.3813185	total: 2.36s	remaining: 981ms
53:	learn: 1078.5720672	total: 2.39s	remaining: 928ms
54:	learn: 1077.6900129	total: 2.39s	remaining: 870ms
55:	learn: 1076.7672721	total: 2.4s	remaining: 814ms
56:	learn: 1076.0705739	total: 2.4s	remaining: 760ms
57:	learn: 1075.2943114	total: 2.42s	remaining: 710ms
58:	learn: 1075.1970743	total: 2.44s	remaining: 661ms
59:	learn: 1074.6822026	total: 2.52s	remaining: 629ms
60:	learn: 1073.8893758	total: 2.57s	remaining: 589ms
61:	learn: 1073.0877045	total: 2.63s	remaining: 551ms
62:	learn: 1072.6532391	total: 2.73s	remaining: 521ms
63:	learn: 1072.2182513	total: 2.79s	remaining: 480ms
64:	learn: 1071.8468455	total: 2.86s	remaining: 440ms
65:	learn: 1071.3743462	total: 3s	remaining: 409ms
66:	learn: 1071.0406838	total: 3.07s	remaining: 367ms
67:	learn: 1070.3824031	total: 3.13s	remaining: 322ms
68:	learn: 1069.7640356	total: 3.2s	remaining: 278ms
69:	learn: 1068.8999440	total: 3.28s	remaining: 234ms
70:	learn: 1068.6082892	total: 3.34s	remaining: 188ms
71:	learn: 1068.2729914	total: 3.43s	remaining: 143ms
72:	learn: 1067.9909167	total: 3.55s	remaining: 97.3ms
73:	learn: 1067.1864448	total: 3.63s	remaining: 49ms
74:	learn: 1066.5274361	total: 3.74s	remaining: 0us
0:	learn: 1671.1224119	total: 207ms	remaining: 15.3s
1:	learn: 1625.2741952	total: 283ms	remaining: 10.3s
2:	learn: 1583.1404774	total: 331ms	remaining: 7.95s
3:	learn: 1548.9851532	total: 356ms	remaining: 6.32s
4:	learn: 1513.2191030	total: 423ms	remaining: 5.92s
5:	learn: 1483.9014837	total: 512ms	remaining: 5.89s
6:	learn: 1456.7847122	total: 636ms	remaining: 6.17s
7:	learn: 1427.9074239	total: 721ms	remaining: 6.04s
8:	learn: 1400.2289996	total: 805ms	remaining: 5.91s
9:	learn: 1379.0430146	total: 883ms	remaining: 5.74s
10:	learn: 1357.5621865	total: 930ms	remaining: 5.41s
11:	learn: 1334.5160375	total: 1.11s	remaining: 5.81s
12:	learn: 1314.4355927	total: 1.18s	remaining: 5.63s
13:	learn: 1297.8658989	total: 1.3s	remaining: 5.66s

14:	learn: 1284.7084135	total: 638ms	remaining: 2.55s
15:	learn: 1270.9439491	total: 643ms	remaining: 2.37s
16:	learn: 1255.5212480	total: 656ms	remaining: 2.24s
17:	learn: 1241.4524143	total: 665ms	remaining: 2.1s
18:	learn: 1230.1516612	total: 675ms	remaining: 1.99s
19:	learn: 1218.1326972	total: 681ms	remaining: 1.87s
20:	learn: 1206.8398165	total: 691ms	remaining: 1.78s
21:	learn: 1197.5738656	total: 719ms	remaining: 1.73s
22:	learn: 1187.5969104	total: 772ms	remaining: 1.75s
23:	learn: 1177.9102799	total: 828ms	remaining: 1.76s
24:	learn: 1169.7820564	total: 862ms	remaining: 1.72s
25:	learn: 1161.8965899	total: 872ms	remaining: 1.64s
26:	learn: 1155.5960497	total: 892ms	remaining: 1.59s
27:	learn: 1149.0283945	total: 901ms	remaining: 1.51s
28:	learn: 1143.8130539	total: 917ms	remaining: 1.45s
29:	learn: 1139.4001929	total: 969ms	remaining: 1.45s
30:	learn: 1133.8135534	total: 1.03s	remaining: 1.46s
31:	learn: 1128.9059916	total: 1.09s	remaining: 1.46s
32:	learn: 1124.5243683	total: 1.17s	remaining: 1.48s
33:	learn: 1121.4555030	total: 1.24s	remaining: 1.5s
34:	learn: 1117.5500313	total: 1.29s	remaining: 1.47s
35:	learn: 1113.9726172	total: 1.31s	remaining: 1.42s
36:	learn: 1111.3947439	total: 1.35s	remaining: 1.39s
37:	learn: 1108.9725443	total: 1.44s	remaining: 1.4s
38:	learn: 1106.1140316	total: 1.49s	remaining: 1.37s
39:	learn: 1102.8911644	total: 1.53s	remaining: 1.34s
40:	learn: 1100.7324696	total: 1.59s	remaining: 1.31s
41:	learn: 1098.6630702	total: 1.67s	remaining: 1.31s
42:	learn: 1097.3498947	total: 1.72s	remaining: 1.28s
43:	learn: 1095.6902576	total: 1.73s	remaining: 1.22s
44:	learn: 1093.6818164	total: 1.85s	remaining: 1.24s
45:	learn: 1092.1833842	total: 1.91s	remaining: 1.2s
46:	learn: 1091.2733575	total: 1.99s	remaining: 1.19s
47:	learn: 1090.2348114	total: 2.08s	remaining: 1.17s
48:	learn: 1089.1688558	total: 2.15s	remaining: 1.14s
49:	learn: 1088.0489156	total: 2.16s	remaining: 1.08s
50:	learn: 1086.6147488	total: 2.27s	remaining: 1.07s
51:	learn: 1085.4644867	total: 2.33s	remaining: 1.03s
52:	learn: 1084.1909899	total: 2.38s	remaining: 987ms
53:	learn: 1083.4583293	total: 2.54s	remaining: 989ms
54:	learn: 1082.4824804	total: 2.56s	remaining: 933ms
55:	learn: 1081.2295298	total: 2.84s	remaining: 965ms
56:	learn: 1080.5569524	total: 2.88s	remaining: 910ms
57:	learn: 1079.4968594	total: 2.9s	remaining: 851ms
58:	learn: 1078.7197827	total: 2.93s	remaining: 794ms
59:	learn: 1078.2246929	total: 2.94s	remaining: 734ms
60:	learn: 1077.1522850	total: 3s	remaining: 688ms
61:	learn: 1076.3140721	total: 3s	remaining: 630ms
62:	learn: 1075.9311515	total: 3.01s	remaining: 574ms
63:	learn: 1075.5402431	total: 3.02s	remaining: 519ms
64:	learn: 1074.6945695	total: 3.03s	remaining: 466ms
65:	learn: 1074.3058946	total: 3.04s	remaining: 414ms
66:	learn: 1073.6346488	total: 3.04s	remaining: 364ms
67:	learn: 1072.8571282	total: 3.06s	remaining: 315ms
68:	learn: 1072.5567683	total: 3.07s	remaining: 267ms
69:	learn: 1071.8117746	total: 3.08s	remaining: 220ms
70:	learn: 1071.4090769	total: 3.09s	remaining: 174ms
71:	learn: 1070.7217804	total: 3.1s	remaining: 129ms
72:	learn: 1070.0463610	total: 3.11s	remaining: 85.1ms
73:	learn: 1069.8253679	total: 3.11s	remaining: 42.1ms
74:	learn: 1069.2227772	total: 3.13s	remaining: 0us
0:	learn: 1676.9287768	total: 50.5ms	remaining: 3.74s
1:	learn: 1631.3364642	total: 106ms	remaining: 3.87s
2:	learn: 1590.2598566	total: 174ms	remaining: 4.17s
3:	learn: 1551.7321892	total: 211ms	remaining: 3.74s
4:	learn: 1516.0172535	total: 324ms	remaining: 4.54s
5:	learn: 1482.5369398	total: 436ms	remaining: 5.02s
6:	learn: 1449.5521920	total: 486ms	remaining: 4.72s
7:	learn: 1420.3738571	total: 620ms	remaining: 5.2s
8:	learn: 1394.5970214	total: 687ms	remaining: 5.04s
9:	learn: 1369.6915859	total: 769ms	remaining: 5s
10:	learn: 1348.8490734	total: 852ms	remaining: 4.96s
11:	learn: 1329.0046740	total: 907ms	remaining: 4.76s
12:	learn: 1308.8848575	total: 983ms	remaining: 4.69s
13:	learn: 1292.0580129	total: 1.02s	remaining: 4.46s
14:	learn: 1273.7934427	total: 1.04s	remaining: 4.17s
15:	learn: 1258.2154807	total: 1.06s	remaining: 3.9s
16:	learn: 1243.0048205	total: 1.15s	remaining: 3.92s
17:	learn: 1228.6441379	total: 1.18s	remaining: 3.73s
18:	learn: 1217.7348786	total: 1.27s	remaining: 3.73s
19:	learn: 1205.5369901	total: 1.33s	remaining: 3.66s
20:	learn: 1194.3193805	total: 1.36s	remaining: 3.49s
21:	learn: 1183.3656271	total: 1.38s	remaining: 3.33s
22:	learn: 1175.3853096	total: 1.43s	remaining: 3.22s
23:	learn: 1166.7609021	total: 1.45s	remaining: 3.08s
24:	learn: 1158.9718346	total: 1.46s	remaining: 2.91s
25:	learn: 1152.2773977	total: 1.54s	remaining: 2.9s
26:	learn: 1146.4416739	total: 1.55s	remaining: 2.75s
27:	learn: 1139.8717492	total: 1.57s	remaining: 2.64s
28:	learn: 1133.8222666	total: 1.62s	remaining: 2.57s
29:	learn: 1128.9469002	total: 1.67s	remaining: 2.51s
30:	learn: 1124.7919074	total: 1.75s	remaining: 2.48s
31:	learn: 1120.8303620	total: 1.8s	remaining: 2.43s
32:	learn: 1116.8881591	total: 1.86s	remaining: 2.36s
33:	learn: 1112.8518531	total: 1.94s	remaining: 2.34s
34:	learn: 1108.9146841	total: 2s	remaining: 2.29s
35:	learn: 1106.0799858	total: 2.06s	remaining: 2.23s
36:	learn: 1103.4842909	total: 2.14s	remaining: 2.2s
37:	learn: 1100.4932273	total: 2.17s	remaining: 2.11s
38:	learn: 1098.0431818	total: 2.2s	remaining: 2.03s
39:	learn: 1095.5624729	total: 2.21s	remaining: 1.93s
40:	learn: 1093.6445580	total: 2.21s	remaining: 1.83s
41:	learn: 1091.9129005	total: 2.22s	remaining: 1.74s
42:	learn: 1090.3117433	total: 2.23s	remaining: 1.66s
43:	learn: 1088.2718872	total: 2.23s	remaining: 1.57s
44:	learn: 1086.3620970	total: 2.24s	remaining: 1.49s
45:	learn: 1085.5249416	total: 2.25s	remaining: 1.42s
46:	learn: 1084.1288761	total: 2.25s	remaining: 1.34s
47:	learn: 1083.1065244	total: 2.26s	remaining: 1.27s
48:	learn: 1081.8952566	total: 2.27s	remaining: 1.21s
49:	learn: 1081.0478340	total: 2.29s	remaining: 1.15s
50:	learn: 1079.7828700	total: 2.32s	remaining: 1.09s
51:	learn: 1078.9762243	total: 2.33s	remaining: 1.03s
52:	learn: 1078.2129887	total: 2.37s	remaining: 983ms
53:	learn: 1077.3994027	total: 2.39s	remaining: 930ms
54:	learn: 1076.3701478	total: 2.4s	remaining: 875ms
55:	learn: 1075.1817431	total: 2.43s	remaining: 825ms
56:	learn: 1074.3220072	total: 2.44s	remaining: 771ms
57:	learn: 1073.6712927	total: 2.45s	remaining: 717ms
58:	learn: 1073.2734825	total: 2.46s	remaining: 667ms
59:	learn: 1072.6337652	total: 2.51s	remaining: 627ms
60:	learn: 1072.1576133	total: 2.56s	remaining: 589ms
61:	learn: 1071.4539859	total: 2.66s	remaining: 557ms
62:	learn: 1070.7678608	total: 2.69s	remaining: 513ms
63:	learn: 1070.3400545	total: 2.75s	remaining: 472ms
64:	learn: 1069.0786709	total: 2.83s	remaining: 435ms
65:	learn: 1068.4326824	total: 2.88s	remaining: 393ms
66:	learn: 1068.0496896	total: 2.93s	remaining: 350ms
67:	learn: 1067.2860114	total: 3s	remaining: 309ms
68:	learn: 1066.6877355	total: 3.02s	remaining: 263ms
69:	learn: 1066.0319538	total: 3.03s	remaining: 216ms
70:	learn: 1065.6153242	total: 3.03s	remaining: 171ms
71:	learn: 1065.4102440	total: 3.04s	remaining: 127ms
72:	learn: 1064.9034903	total: 3.05s	remaining: 83.5ms
73:	learn: 1064.4042643	total: 3.05s	remaining: 41.3ms
74:	learn: 1063.9358106	total: 3.06s	remaining: 0us
0:	learn: 1666.2842379	total: 82.4ms	remaining: 6.1s
1:	learn: 1622.8078473	total: 179ms	remaining: 6.54s
2:	learn: 1580.7051509	total: 305ms	remaining: 7.33s
3:	learn: 1543.4096559	total: 364ms	remaining: 6.46s
4:	learn: 1508.3418970	total: 467ms	remaining: 6.54s
5:	learn: 1475.6025641	total: 528ms	remaining: 6.07s
6:	learn: 1448.6373531	total: 536ms	remaining: 5.21s
7:	learn: 1420.5123989	total: 570ms	remaining: 4.77s
8:	learn: 1397.2437348	total: 637ms	remaining: 4.67s
9:	learn: 1372.2944351	total: 781ms	remaining: 5.08s
10:	learn: 1352.9112960	total: 833ms	remaining: 4.84s
11:	learn: 1332.4228948	total: 923ms	remaining: 4.84s
12:	learn: 1312.1641688	total: 967ms	remaining: 4.61s
13:	learn: 1291.9195728	total: 1.01s	remaining: 4.41s
14:	learn: 1274.7617456	total: 1.07s	remaining: 4.28s
15:	learn: 1257.7507250	total: 1.31s	remaining: 4.83s
14:	learn: 1280.2384964	total: 1.41s	remaining: 5.63s
15:	learn: 1265.1925214	total: 1.46s	remaining: 5.4s
16:	learn: 1251.6113764	total: 1.47s	remaining: 5.03s
17:	learn: 1237.8979859	total: 1.5s	remaining: 4.74s
18:	learn: 1225.1031211	total: 1.5s	remaining: 4.43s
19:	learn: 1214.1251549	total: 1.58s	remaining: 4.35s
20:	learn: 1202.0940206	total: 1.66s	remaining: 4.27s
21:	learn: 1192.3747219	total: 1.69s	remaining: 4.07s
22:	learn: 1182.8147950	total: 1.7s	remaining: 3.85s
23:	learn: 1174.4649756	total: 1.71s	remaining: 3.63s
24:	learn: 1167.3953769	total: 1.75s	remaining: 3.5s
25:	learn: 1159.5675942	total: 1.89s	remaining: 3.55s
26:	learn: 1153.1755733	total: 2.02s	remaining: 3.59s
27:	learn: 1146.5152734	total: 2.13s	remaining: 3.57s
28:	learn: 1141.3237500	total: 2.23s	remaining: 3.53s
29:	learn: 1135.4555162	total: 2.32s	remaining: 3.48s
30:	learn: 1130.3108112	total: 2.4s	remaining: 3.4s
31:	learn: 1126.5248148	total: 2.47s	remaining: 3.32s
32:	learn: 1122.2269449	total: 2.61s	remaining: 3.32s
33:	learn: 1118.1587147	total: 2.69s	remaining: 3.24s
34:	learn: 1114.5031557	total: 2.76s	remaining: 3.15s
35:	learn: 1111.3320987	total: 2.82s	remaining: 3.06s
36:	learn: 1108.1086829	total: 2.96s	remaining: 3.04s
37:	learn: 1105.7524148	total: 3.04s	remaining: 2.96s
38:	learn: 1102.8322973	total: 3.05s	remaining: 2.81s
39:	learn: 1100.1274833	total: 3.12s	remaining: 2.73s
40:	learn: 1098.4547394	total: 3.16s	remaining: 2.62s
41:	learn: 1096.7687849	total: 3.17s	remaining: 2.49s
42:	learn: 1094.9992997	total: 3.34s	remaining: 2.48s
43:	learn: 1093.4168859	total: 3.39s	remaining: 2.39s
44:	learn: 1091.7509146	total: 3.47s	remaining: 2.31s
45:	learn: 1089.7124864	total: 3.55s	remaining: 2.24s
46:	learn: 1088.2813705	total: 3.7s	remaining: 2.2s
47:	learn: 1087.1884231	total: 3.76s	remaining: 2.12s
48:	learn: 1085.4062079	total: 3.8s	remaining: 2.02s
49:	learn: 1084.2067803	total: 3.82s	remaining: 1.91s
50:	learn: 1083.3265285	total: 3.83s	remaining: 1.8s
51:	learn: 1082.4945243	total: 3.84s	remaining: 1.7s
52:	learn: 1081.8397847	total: 3.85s	remaining: 1.6s
53:	learn: 1080.8503022	total: 3.85s	remaining: 1.5s
54:	learn: 1080.3954465	total: 3.86s	remaining: 1.4s
55:	learn: 1079.4050874	total: 3.87s	remaining: 1.31s
56:	learn: 1078.8597208	total: 3.88s	remaining: 1.23s
57:	learn: 1077.7990935	total: 3.89s	remaining: 1.14s
58:	learn: 1077.0425254	total: 3.91s	remaining: 1.06s
59:	learn: 1076.5001344	total: 3.94s	remaining: 986ms
60:	learn: 1075.7416979	total: 3.96s	remaining: 908ms
61:	learn: 1075.5862145	total: 3.96s	remaining: 831ms
62:	learn: 1075.3383430	total: 3.97s	remaining: 756ms
63:	learn: 1074.9966553	total: 3.98s	remaining: 684ms
64:	learn: 1074.5006767	total: 3.99s	remaining: 614ms
65:	learn: 1073.8893889	total: 4.03s	remaining: 549ms
66:	learn: 1073.1182165	total: 4.09s	remaining: 489ms
67:	learn: 1072.5721284	total: 4.2s	remaining: 432ms
68:	learn: 1072.1760805	total: 4.36s	remaining: 379ms
69:	learn: 1071.8064786	total: 4.55s	remaining: 325ms
70:	learn: 1071.4751743	total: 4.69s	remaining: 264ms
71:	learn: 1071.2916050	total: 4.72s	remaining: 197ms
72:	learn: 1070.7501865	total: 4.73s	remaining: 130ms
73:	learn: 1069.9681321	total: 4.74s	remaining: 64.1ms
74:	learn: 1069.7256044	total: 4.75s	remaining: 0us
0:	learn: 1675.1081350	total: 11.2ms	remaining: 825ms
1:	learn: 1629.9397591	total: 18.7ms	remaining: 681ms
2:	learn: 1588.9699083	total: 32.1ms	remaining: 769ms
3:	learn: 1550.3639648	total: 92.3ms	remaining: 1.64s
4:	learn: 1515.2138280	total: 105ms	remaining: 1.47s
5:	learn: 1481.9517328	total: 229ms	remaining: 2.64s
6:	learn: 1449.7047856	total: 272ms	remaining: 2.64s
7:	learn: 1421.1248556	total: 329ms	remaining: 2.75s
8:	learn: 1395.9171369	total: 373ms	remaining: 2.73s
9:	learn: 1370.9969875	total: 393ms	remaining: 2.55s
10:	learn: 1350.4841627	total: 447ms	remaining: 2.6s
11:	learn: 1333.3717368	total: 519ms	remaining: 2.72s
12:	learn: 1315.7968564	total: 637ms	remaining: 3.04s
13:	learn: 1299.2535275	total: 679ms	remaining: 2.96s
14:	learn: 1283.1265829	total: 703ms	remaining: 2.81s
15:	learn: 1268.8883563	total: 724ms	remaining: 2.67s
16:	learn: 1254.8564620	total: 765ms	remaining: 2.61s
17:	learn: 1240.1141497	total: 794ms	remaining: 2.51s
18:	learn: 1227.7094810	total: 846ms	remaining: 2.49s
19:	learn: 1215.3534094	total: 908ms	remaining: 2.5s
20:	learn: 1203.3632587	total: 972ms	remaining: 2.5s
21:	learn: 1192.4512738	total: 997ms	remaining: 2.4s
22:	learn: 1184.6294607	total: 1.06s	remaining: 2.39s
23:	learn: 1175.8844682	total: 1.08s	remaining: 2.29s
24:	learn: 1168.1059138	total: 1.09s	remaining: 2.17s
25:	learn: 1159.9381315	total: 1.1s	remaining: 2.07s
26:	learn: 1154.2366938	total: 1.1s	remaining: 1.96s
27:	learn: 1148.6014243	total: 1.11s	remaining: 1.87s
28:	learn: 1142.5466467	total: 1.12s	remaining: 1.78s
29:	learn: 1137.7330945	total: 1.13s	remaining: 1.69s
30:	learn: 1133.6645708	total: 1.14s	remaining: 1.61s
31:	learn: 1129.9251201	total: 1.14s	remaining: 1.54s
32:	learn: 1125.4545996	total: 1.15s	remaining: 1.46s
33:	learn: 1121.9075190	total: 1.16s	remaining: 1.4s
34:	learn: 1117.9240404	total: 1.17s	remaining: 1.34s
35:	learn: 1115.0330879	total: 1.18s	remaining: 1.27s
36:	learn: 1111.7880143	total: 1.19s	remaining: 1.22s
37:	learn: 1108.8171612	total: 1.24s	remaining: 1.21s
38:	learn: 1106.3250429	total: 1.29s	remaining: 1.19s
39:	learn: 1103.6018516	total: 1.36s	remaining: 1.19s
40:	learn: 1101.6109861	total: 1.41s	remaining: 1.17s
41:	learn: 1099.9748189	total: 1.56s	remaining: 1.23s
42:	learn: 1098.4088321	total: 1.58s	remaining: 1.17s
43:	learn: 1096.4106202	total: 1.59s	remaining: 1.12s
44:	learn: 1094.7960635	total: 1.59s	remaining: 1.06s
45:	learn: 1093.7801490	total: 1.6s	remaining: 1.01s
46:	learn: 1092.4083848	total: 1.61s	remaining: 958ms
47:	learn: 1091.3793672	total: 1.62s	remaining: 909ms
48:	learn: 1090.1812897	total: 1.62s	remaining: 862ms
49:	learn: 1089.2385853	total: 1.63s	remaining: 815ms
50:	learn: 1088.2519657	total: 1.64s	remaining: 770ms
51:	learn: 1087.6620006	total: 1.65s	remaining: 731ms
52:	learn: 1086.1666301	total: 1.66s	remaining: 689ms
53:	learn: 1085.3838043	total: 1.67s	remaining: 648ms
54:	learn: 1084.4051461	total: 1.69s	remaining: 615ms
55:	learn: 1083.5989425	total: 1.77s	remaining: 600ms
56:	learn: 1082.7795302	total: 1.84s	remaining: 583ms
57:	learn: 1082.2600494	total: 1.91s	remaining: 561ms
58:	learn: 1081.9948793	total: 1.92s	remaining: 521ms
59:	learn: 1081.3774665	total: 2.02s	remaining: 505ms
60:	learn: 1081.0611185	total: 2.02s	remaining: 464ms
61:	learn: 1080.6556595	total: 2.03s	remaining: 425ms
62:	learn: 1079.8252185	total: 2.04s	remaining: 388ms
63:	learn: 1078.8857460	total: 2.04s	remaining: 351ms
64:	learn: 1078.3520329	total: 2.05s	remaining: 316ms
65:	learn: 1077.7042970	total: 2.09s	remaining: 286ms
66:	learn: 1077.1566133	total: 2.13s	remaining: 254ms
67:	learn: 1076.6604947	total: 2.14s	remaining: 220ms
68:	learn: 1076.0043428	total: 2.15s	remaining: 187ms
69:	learn: 1075.4144147	total: 2.19s	remaining: 157ms
70:	learn: 1074.6647458	total: 2.27s	remaining: 128ms
71:	learn: 1074.3327366	total: 2.34s	remaining: 97.3ms
72:	learn: 1073.7943537	total: 2.4s	remaining: 65.7ms
73:	learn: 1073.4807186	total: 2.46s	remaining: 33.2ms
74:	learn: 1073.3070726	total: 2.53s	remaining: 0us
0:	learn: 1664.4837332	total: 111ms	remaining: 8.19s
1:	learn: 1625.3268363	total: 174ms	remaining: 6.34s
2:	learn: 1585.3672893	total: 344ms	remaining: 8.25s
3:	learn: 1547.6032267	total: 357ms	remaining: 6.34s
4:	learn: 1520.3247861	total: 463ms	remaining: 6.49s
5:	learn: 1487.1505379	total: 495ms	remaining: 5.7s
6:	learn: 1455.7146469	total: 665ms	remaining: 6.46s
7:	learn: 1425.4376780	total: 680ms	remaining: 5.7s
8:	learn: 1399.2079600	total: 787ms	remaining: 5.77s
9:	learn: 1374.5740531	total: 799ms	remaining: 5.2s
10:	learn: 1350.9112032	total: 873ms	remaining: 5.08s
11:	learn: 1329.7485473	total: 951ms	remaining: 4.99s
12:	learn: 1308.8565198	total: 996ms	remaining: 4.75s
13:	learn: 1290.5020073	total: 1.04s	remaining: 4.55s
14:	learn: 1275.6631155	total: 1.12s	remaining: 4.49s
15:	learn: 1258.7039100	total: 1.16s	remaining: 4.27s

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.272973 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 814
[LightGBM] [Info] Number of data points in the train set: 5454, number of used features: 39
[LightGBM] [Info] Start training from score 2149.096927
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
16:	learn: 1242.9667105	total: 1.47s	remaining: 5.03s
17:	learn: 1228.7937147	total: 1.57s	remaining: 4.97s
18:	learn: 1215.4960713	total: 1.67s	remaining: 4.92s
19:	learn: 1204.4079154	total: 1.71s	remaining: 4.71s
20:	learn: 1192.9625941	total: 1.77s	remaining: 4.55s
21:	learn: 1184.0423145	total: 1.83s	remaining: 4.42s
22:	learn: 1174.5397642	total: 1.88s	remaining: 4.25s
23:	learn: 1166.6780275	total: 1.96s	remaining: 4.17s
24:	learn: 1159.4084772	total: 2.05s	remaining: 4.09s
25:	learn: 1153.6119439	total: 2.13s	remaining: 4.02s
26:	learn: 1147.3017951	total: 2.21s	remaining: 3.92s
27:	learn: 1142.3206697	total: 2.27s	remaining: 3.82s
28:	learn: 1136.6915621	total: 2.29s	remaining: 3.63s
29:	learn: 1131.4052359	total: 2.3s	remaining: 3.45s
30:	learn: 1126.6802517	total: 2.31s	remaining: 3.28s
31:	learn: 1122.2584909	total: 2.32s	remaining: 3.12s
32:	learn: 1118.5968283	total: 2.33s	remaining: 2.96s
33:	learn: 1115.3206800	total: 2.34s	remaining: 2.82s
34:	learn: 1112.1564875	total: 2.35s	remaining: 2.68s
35:	learn: 1109.0527500	total: 2.36s	remaining: 2.55s
36:	learn: 1106.2927514	total: 2.36s	remaining: 2.43s
37:	learn: 1104.3729853	total: 2.37s	remaining: 2.31s
38:	learn: 1102.5190764	total: 2.38s	remaining: 2.2s
39:	learn: 1100.8157052	total: 2.39s	remaining: 2.09s
40:	learn: 1098.5986420	total: 2.41s	remaining: 2s
41:	learn: 1096.9086335	total: 2.41s	remaining: 1.9s
42:	learn: 1094.9990598	total: 2.42s	remaining: 1.8s
43:	learn: 1093.6085848	total: 2.43s	remaining: 1.71s
44:	learn: 1091.8554023	total: 2.44s	remaining: 1.63s
45:	learn: 1090.6905200	total: 2.45s	remaining: 1.54s
46:	learn: 1089.4701576	total: 2.46s	remaining: 1.46s
47:	learn: 1087.9367983	total: 2.47s	remaining: 1.39s
48:	learn: 1086.2534259	total: 2.47s	remaining: 1.31s
49:	learn: 1084.8574100	total: 2.48s	remaining: 1.24s
50:	learn: 1084.0730103	total: 2.49s	remaining: 1.17s
51:	learn: 1082.6361656	total: 2.5s	remaining: 1.1s
52:	learn: 1082.2923089	total: 2.51s	remaining: 1.04s
53:	learn: 1081.2647615	total: 2.52s	remaining: 978ms
54:	learn: 1080.3725098	total: 2.52s	remaining: 917ms
55:	learn: 1079.5249386	total: 2.53s	remaining: 859ms
56:	learn: 1078.6015058	total: 2.54s	remaining: 802ms
57:	learn: 1077.7499246	total: 2.54s	remaining: 746ms
58:	learn: 1076.9103530	total: 2.55s	remaining: 693ms
59:	learn: 1076.6099474	total: 2.56s	remaining: 640ms
60:	learn: 1075.9419805	total: 2.57s	remaining: 590ms
61:	learn: 1075.3390954	total: 2.58s	remaining: 540ms
62:	learn: 1074.8726691	total: 2.58s	remaining: 492ms
63:	learn: 1074.0758719	total: 2.59s	remaining: 446ms
64:	learn: 1073.6601881	total: 2.6s	remaining: 400ms
65:	learn: 1073.3828460	total: 2.61s	remaining: 356ms
66:	learn: 1072.9645788	total: 2.61s	remaining: 312ms
67:	learn: 1071.8723273	total: 2.62s	remaining: 270ms
68:	learn: 1071.4577288	total: 2.63s	remaining: 228ms
69:	learn: 1070.8477072	total: 2.63s	remaining: 188ms
70:	learn: 1070.5216378	total: 2.64s	remaining: 149ms
71:	learn: 1070.1017658	total: 2.65s	remaining: 110ms
72:	learn: 1069.6929096	total: 2.66s	remaining: 72.8ms
73:	learn: 1069.3985628	total: 2.66s	remaining: 36ms
74:	learn: 1068.9640970	total: 2.67s	remaining: 0us
0:	learn: 1658.3701449	total: 109ms	remaining: 8.07s
1:	learn: 1613.7203740	total: 129ms	remaining: 4.7s
2:	learn: 1574.4497431	total: 142ms	remaining: 3.41s
3:	learn: 1537.7226896	total: 148ms	remaining: 2.63s
4:	learn: 1503.2060769	total: 156ms	remaining: 2.18s
5:	learn: 1469.2554124	total: 172ms	remaining: 1.98s
6:	learn: 1439.9595719	total: 243ms	remaining: 2.36s
7:	learn: 1411.0029511	total: 269ms	remaining: 2.25s
8:	learn: 1385.2680849	total: 275ms	remaining: 2.02s
9:	learn: 1360.2865111	total: 341ms	remaining: 2.22s
10:	learn: 1338.1990298	total: 363ms	remaining: 2.11s
11:	learn: 1318.3286043	total: 371ms	remaining: 1.95s
12:	learn: 1298.1215639	total: 384ms	remaining: 1.83s
13:	learn: 1281.7735581	total: 391ms	remaining: 1.7s
14:	learn: 1264.6503851	total: 401ms	remaining: 1.6s
15:	learn: 1248.8651022	total: 416ms	remaining: 1.53s
16:	learn: 1234.3606562	total: 424ms	remaining: 1.45s
17:	learn: 1223.1028221	total: 431ms	remaining: 1.36s
18:	learn: 1210.6343256	total: 442ms	remaining: 1.3s
19:	learn: 1200.4410985	total: 450ms	remaining: 1.24s
20:	learn: 1190.3658436	total: 457ms	remaining: 1.18s
21:	learn: 1182.1173391	total: 467ms	remaining: 1.12s
22:	learn: 1174.2133906	total: 500ms	remaining: 1.13s
23:	learn: 1166.9690834	total: 513ms	remaining: 1.09s
24:	learn: 1159.5567345	total: 520ms	remaining: 1.04s
25:	learn: 1152.7652200	total: 528ms	remaining: 996ms
26:	learn: 1147.2242191	total: 537ms	remaining: 954ms
27:	learn: 1142.3834244	total: 543ms	remaining: 912ms
28:	learn: 1136.7102653	total: 549ms	remaining: 871ms
29:	learn: 1132.7588353	total: 557ms	remaining: 836ms
30:	learn: 1127.5734611	total: 574ms	remaining: 815ms
31:	learn: 1123.1566659	total: 592ms	remaining: 796ms
32:	learn: 1119.8923513	total: 683ms	remaining: 869ms
33:	learn: 1116.0415979	total: 751ms	remaining: 906ms
34:	learn: 1113.0987698	total: 766ms	remaining: 876ms
35:	learn: 1110.9894066	total: 931ms	remaining: 1.01s
36:	learn: 1108.1195623	total: 948ms	remaining: 973ms
37:	learn: 1104.7777804	total: 1.02s	remaining: 991ms
38:	learn: 1102.6903451	total: 1.03s	remaining: 948ms
39:	learn: 1100.1471710	total: 1.05s	remaining: 923ms
40:	learn: 1098.2305910	total: 1.17s	remaining: 970ms
41:	learn: 1096.2996952	total: 1.25s	remaining: 987ms
42:	learn: 1094.3249327	total: 1.28s	remaining: 951ms
43:	learn: 1092.5680510	total: 1.38s	remaining: 972ms
44:	learn: 1091.1405439	total: 1.4s	remaining: 937ms
45:	learn: 1089.2899967	total: 1.43s	remaining: 899ms
46:	learn: 1088.0415459	total: 1.55s	remaining: 922ms
47:	learn: 1087.1303710	total: 1.61s	remaining: 906ms
48:	learn: 1086.0707929	total: 1.72s	remaining: 912ms
49:	learn: 1084.3430664	total: 1.79s	remaining: 893ms
50:	learn: 1083.4088637	total: 1.8s	remaining: 847ms
51:	learn: 1082.4013831	total: 1.94s	remaining: 856ms
52:	learn: 1081.9610744	total: 2.04s	remaining: 849ms
53:	learn: 1081.0549581	total: 2.07s	remaining: 805ms
54:	learn: 1080.1471132	total: 2.13s	remaining: 774ms
55:	learn: 1079.4729867	total: 2.2s	remaining: 747ms
56:	learn: 1079.1136203	total: 2.28s	remaining: 720ms
57:	learn: 1078.4101584	total: 2.33s	remaining: 683ms
58:	learn: 1077.5737914	total: 2.37s	remaining: 644ms
59:	learn: 1076.6354076	total: 2.38s	remaining: 596ms
60:	learn: 1076.0168710	total: 2.42s	remaining: 556ms
61:	learn: 1075.0964519	total: 2.45s	remaining: 514ms
62:	learn: 1074.2117361	total: 2.49s	remaining: 474ms
63:	learn: 1073.4489601	total: 2.59s	remaining: 446ms
64:	learn: 1072.9688860	total: 2.66s	remaining: 409ms
65:	learn: 1072.0464718	total: 2.69s	remaining: 368ms
66:	learn: 1071.5855500	total: 2.71s	remaining: 324ms
67:	learn: 1071.2850602	total: 2.72s	remaining: 280ms
68:	learn: 1070.5680005	total: 2.73s	remaining: 237ms
69:	learn: 1069.9553064	total: 2.74s	remaining: 196ms
70:	learn: 1069.7507703	total: 2.75s	remaining: 155ms
71:	learn: 1069.4879844	total: 2.76s	remaining: 115ms
72:	learn: 1069.3173381	total: 2.76s	remaining: 75.7ms
73:	learn: 1069.0538375	total: 2.77s	remaining: 37.4ms
74:	learn: 1068.2852729	total: 2.78s	remaining: 0us
[CV] END stack__CAT__learning_rate=0.05, stack__CAT__max_depth=6, stack__CAT__n_estimators=75, stack__LGBM__learning_rate=0.05, stack__LGBM__max_depth=4, stack__LGBM__n_estimators=75, stack__XGB__learning_rate=0.3, stack__XGB__max_depth=6, stack__XGB__n_estimators=100, stack__final_estimator__max_depth=6, stack__final_estimator__n_estimators=100; total time=26.5min
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.310145 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 817
[LightGBM] [Info] Number of data points in the train set: 6819, number of used features: 39
[LightGBM] [Info] Start training from score 2193.082712
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
0:	learn: 1651.3824384	total: 47.6ms	remaining: 3.52s
1:	learn: 1611.9476176	total: 108ms	remaining: 3.96s
2:	learn: 1577.5030251	total: 188ms	remaining: 4.5s
3:	learn: 1540.0803340	total: 212ms	remaining: 3.76s
4:	learn: 1503.6249892	total: 297ms	remaining: 4.16s
5:	learn: 1474.0457312	total: 334ms	remaining: 3.84s
6:	learn: 1441.8068534	total: 374ms	remaining: 3.63s
7:	learn: 1413.9404022	total: 423ms	remaining: 3.54s
8:	learn: 1391.0040465	total: 482ms	remaining: 3.53s
9:	learn: 1365.6560178	total: 569ms	remaining: 3.7s
10:	learn: 1344.6304188	total: 609ms	remaining: 3.54s
11:	learn: 1322.8691059	total: 738ms	remaining: 3.87s
12:	learn: 1305.7018250	total: 947ms	remaining: 4.52s
13:	learn: 1286.4477484	total: 1.02s	remaining: 4.43s
14:	learn: 1268.0138173	total: 1.05s	remaining: 4.22s
15:	learn: 1254.4722370	total: 1.13s	remaining: 4.17s
16:	learn: 1240.1330154	total: 1.16s	remaining: 3.97s
17:	learn: 1226.6107207	total: 1.32s	remaining: 4.18s
18:	learn: 1215.5469807	total: 1.33s	remaining: 3.91s
19:	learn: 1204.0057183	total: 1.4s	remaining: 3.84s
20:	learn: 1194.7445432	total: 1.53s	remaining: 3.94s
21:	learn: 1186.0873024	total: 1.59s	remaining: 3.83s
22:	learn: 1176.2149208	total: 1.71s	remaining: 3.87s
23:	learn: 1166.5465377	total: 1.73s	remaining: 3.69s
24:	learn: 1158.0452467	total: 1.8s	remaining: 3.61s
25:	learn: 1150.9496547	total: 1.91s	remaining: 3.59s
26:	learn: 1144.9249738	total: 2.03s	remaining: 3.6s
27:	learn: 1138.3934746	total: 2.09s	remaining: 3.51s
28:	learn: 1132.4487795	total: 2.17s	remaining: 3.44s
29:	learn: 1127.2535185	total: 2.21s	remaining: 3.32s
30:	learn: 1121.5591362	total: 2.34s	remaining: 3.33s
31:	learn: 1116.9544792	total: 2.46s	remaining: 3.31s
32:	learn: 1112.4366625	total: 2.62s	remaining: 3.33s
33:	learn: 1109.4441441	total: 2.66s	remaining: 3.21s
34:	learn: 1105.3487203	total: 2.67s	remaining: 3.05s
35:	learn: 1102.5204461	total: 2.85s	remaining: 3.09s
36:	learn: 1099.2065858	total: 2.9s	remaining: 2.98s
37:	learn: 1096.5899543	total: 2.99s	remaining: 2.91s
38:	learn: 1094.2632817	total: 3.04s	remaining: 2.8s
39:	learn: 1092.5233629	total: 3.15s	remaining: 2.75s
40:	learn: 1089.7697745	total: 3.17s	remaining: 2.63s
41:	learn: 1087.9518857	total: 3.26s	remaining: 2.56s
42:	learn: 1086.5024147	total: 3.29s	remaining: 2.45s
43:	learn: 1085.0413361	total: 3.37s	remaining: 2.37s
44:	learn: 1083.0698624	total: 3.44s	remaining: 2.29s
45:	learn: 1080.8258849	total: 3.48s	remaining: 2.19s
46:	learn: 1079.9523783	total: 3.55s	remaining: 2.11s
47:	learn: 1078.7606612	total: 3.56s	remaining: 2s
48:	learn: 1077.7287075	total: 3.56s	remaining: 1.89s
49:	learn: 1076.5740369	total: 3.57s	remaining: 1.79s
50:	learn: 1075.1959389	total: 3.58s	remaining: 1.69s
51:	learn: 1073.7709492	total: 3.62s	remaining: 1.6s
52:	learn: 1072.5064846	total: 3.65s	remaining: 1.52s
53:	learn: 1071.9049315	total: 3.71s	remaining: 1.44s
54:	learn: 1070.7822020	total: 3.78s	remaining: 1.38s
55:	learn: 1070.0658160	total: 3.86s	remaining: 1.31s
56:	learn: 1069.2360597	total: 3.9s	remaining: 1.23s
57:	learn: 1068.2189831	total: 3.91s	remaining: 1.15s
58:	learn: 1067.5917133	total: 3.95s	remaining: 1.07s
59:	learn: 1066.8316537	total: 3.97s	remaining: 992ms
60:	learn: 1066.1170530	total: 3.98s	remaining: 913ms
61:	learn: 1065.6517235	total: 3.99s	remaining: 836ms
62:	learn: 1065.1923683	total: 3.99s	remaining: 761ms
63:	learn: 1064.5549451	total: 4s	remaining: 688ms
64:	learn: 1063.8553724	total: 4.01s	remaining: 617ms
65:	learn: 1063.0823874	total: 4.01s	remaining: 547ms
66:	learn: 1062.7080221	total: 4.02s	remaining: 480ms
67:	learn: 1062.1432787	total: 4.03s	remaining: 415ms
68:	learn: 1061.8056991	total: 4.04s	remaining: 351ms
69:	learn: 1061.6366259	total: 4.04s	remaining: 289ms
70:	learn: 1061.0134871	total: 4.05s	remaining: 228ms
71:	learn: 1060.1865955	total: 4.13s	remaining: 172ms
72:	learn: 1059.7405921	total: 4.21s	remaining: 115ms
73:	learn: 1059.4545984	total: 4.3s	remaining: 58.1ms
74:	learn: 1059.1397407	total: 4.42s	remaining: 0us
0:	learn: 1667.2458224	total: 26.1ms	remaining: 1.93s
1:	learn: 1622.3409083	total: 77.2ms	remaining: 2.82s
2:	learn: 1582.7570861	total: 99.8ms	remaining: 2.4s
3:	learn: 1544.7962534	total: 119ms	remaining: 2.11s
4:	learn: 1510.2622460	total: 138ms	remaining: 1.93s
5:	learn: 1477.5491829	total: 179ms	remaining: 2.05s
6:	learn: 1444.9359853	total: 189ms	remaining: 1.84s
7:	learn: 1416.7143580	total: 197ms	remaining: 1.65s
8:	learn: 1389.6536806	total: 204ms	remaining: 1.5s
9:	learn: 1365.5642664	total: 211ms	remaining: 1.37s
10:	learn: 1345.4704097	total: 219ms	remaining: 1.27s
11:	learn: 1326.4192447	total: 226ms	remaining: 1.19s
12:	learn: 1309.4045300	total: 233ms	remaining: 1.11s
13:	learn: 1293.0823509	total: 240ms	remaining: 1.04s
14:	learn: 1276.7834938	total: 273ms	remaining: 1.09s
15:	learn: 1260.7375556	total: 319ms	remaining: 1.18s
16:	learn: 1245.0209483	total: 1.22s	remaining: 4.17s
17:	learn: 1232.2233091	total: 1.3s	remaining: 4.12s
18:	learn: 1219.6308442	total: 1.37s	remaining: 4.04s
19:	learn: 1209.3892579	total: 1.39s	remaining: 3.82s
20:	learn: 1200.3215188	total: 1.46s	remaining: 3.76s
21:	learn: 1191.1464937	total: 1.66s	remaining: 4s
22:	learn: 1181.2933922	total: 1.71s	remaining: 3.87s
23:	learn: 1174.1387983	total: 1.95s	remaining: 4.14s
24:	learn: 1166.4624668	total: 2.03s	remaining: 4.06s
25:	learn: 1159.8183613	total: 2.05s	remaining: 3.87s
26:	learn: 1152.9949559	total: 2.12s	remaining: 3.77s
27:	learn: 1147.4086309	total: 2.19s	remaining: 3.67s
28:	learn: 1142.6664966	total: 2.21s	remaining: 3.51s
29:	learn: 1138.0475303	total: 2.29s	remaining: 3.44s
30:	learn: 1134.8362994	total: 2.35s	remaining: 3.34s
31:	learn: 1129.8554979	total: 2.41s	remaining: 3.24s
32:	learn: 1126.2693726	total: 2.48s	remaining: 3.16s
33:	learn: 1122.2133956	total: 2.52s	remaining: 3.04s
34:	learn: 1119.1332757	total: 2.6s	remaining: 2.98s
35:	learn: 1116.3797760	total: 2.65s	remaining: 2.87s
36:	learn: 1112.9881434	total: 2.67s	remaining: 2.75s
37:	learn: 1110.3794297	total: 2.74s	remaining: 2.67s
38:	learn: 1107.5736441	total: 2.8s	remaining: 2.58s
39:	learn: 1104.9671679	total: 2.92s	remaining: 2.56s
40:	learn: 1102.4258318	total: 2.97s	remaining: 2.46s
41:	learn: 1100.3295156	total: 3s	remaining: 2.35s
42:	learn: 1098.5936902	total: 3.14s	remaining: 2.34s
43:	learn: 1097.1190272	total: 3.15s	remaining: 2.22s
44:	learn: 1094.9305317	total: 3.2s	remaining: 2.14s
45:	learn: 1093.5775091	total: 3.27s	remaining: 2.06s
46:	learn: 1092.4061116	total: 3.34s	remaining: 1.99s
47:	learn: 1091.0065597	total: 3.43s	remaining: 1.93s
48:	learn: 1089.6072104	total: 3.52s	remaining: 1.87s
49:	learn: 1088.4510825	total: 3.59s	remaining: 1.79s
50:	learn: 1087.3761052	total: 3.66s	remaining: 1.72s
51:	learn: 1086.6212913	total: 3.74s	remaining: 1.65s
52:	learn: 1085.4862569	total: 3.83s	remaining: 1.59s
53:	learn: 1084.3003994	total: 4s	remaining: 1.55s
54:	learn: 1083.7229524	total: 4.03s	remaining: 1.46s
55:	learn: 1082.8182669	total: 4.08s	remaining: 1.38s
56:	learn: 1082.0621738	total: 4.12s	remaining: 1.3s
57:	learn: 1081.4600492	total: 4.18s	remaining: 1.23s
58:	learn: 1080.8064246	total: 4.25s	remaining: 1.15s
59:	learn: 1079.7927957	total: 4.32s	remaining: 1.08s
60:	learn: 1079.4515677	total: 4.37s	remaining: 1s
61:	learn: 1078.8319266	total: 4.43s	remaining: 928ms
62:	learn: 1078.6758295	total: 4.52s	remaining: 861ms
63:	learn: 1078.5190113	total: 4.53s	remaining: 778ms
64:	learn: 1078.3877144	total: 4.6s	remaining: 708ms
65:	learn: 1077.5990512	total: 4.65s	remaining: 634ms
66:	learn: 1077.2250251	total: 4.74s	remaining: 566ms
67:	learn: 1076.7235333	total: 4.81s	remaining: 495ms
68:	learn: 1075.8435405	total: 4.82s	remaining: 419ms
69:	learn: 1075.6888761	total: 4.9s	remaining: 350ms
70:	learn: 1075.3273520	total: 4.97s	remaining: 280ms
71:	learn: 1075.0751429	total: 5.03s	remaining: 209ms
72:	learn: 1074.4543730	total: 5.09s	remaining: 140ms
73:	learn: 1073.7675987	total: 5.16s	remaining: 69.8ms
74:	learn: 1073.5308131	total: 5.18s	remaining: 0us
0:	learn: 1656.4650149	total: 64.8ms	remaining: 4.79s
1:	learn: 1611.6404235	total: 170ms	remaining: 6.22s
2:	learn: 1571.4897722	total: 193ms	remaining: 4.62s
3:	learn: 1535.4339266	total: 303ms	remaining: 5.38s
4:	learn: 1499.3905821	total: 361ms	remaining: 5.05s
5:	learn: 1466.8247483	total: 467ms	remaining: 5.37s
6:	learn: 1435.6653732	total: 477ms	remaining: 4.64s
7:	learn: 1407.5773844	total: 564ms	remaining: 4.73s
8:	learn: 1380.8854545	total: 574ms	remaining: 4.21s
9:	learn: 1357.3426236	total: 758ms	remaining: 4.92s
10:	learn: 1337.5182590	total: 804ms	remaining: 4.68s
11:	learn: 1318.6659345	total: 850ms	remaining: 4.46s
12:	learn: 1299.1318892	total: 859ms	remaining: 4.1s
13:	learn: 1283.2624881	total: 865ms	remaining: 3.77s
14:	learn: 1267.3104397	total: 873ms	remaining: 3.49s
15:	learn: 1252.2546596	total: 880ms	remaining: 3.25s
16:	learn: 1236.7611360	total: 887ms	remaining: 3.03s
17:	learn: 1222.9260912	total: 896ms	remaining: 2.84s
18:	learn: 1212.3215323	total: 902ms	remaining: 2.66s
19:	learn: 1200.8409176	total: 962ms	remaining: 2.65s
20:	learn: 1190.0675654	total: 1.01s	remaining: 2.59s
21:	learn: 1179.9095402	total: 1.1s	remaining: 2.64s
22:	learn: 1172.1145109	total: 1.19s	remaining: 2.69s
23:	learn: 1163.7567241	total: 1.26s	remaining: 2.68s
24:	learn: 1156.1775172	total: 1.28s	remaining: 2.56s
25:	learn: 1148.3573601	total: 1.28s	remaining: 2.42s
26:	learn: 1142.8643490	total: 1.29s	remaining: 2.3s
27:	learn: 1137.2524544	total: 1.3s	remaining: 2.18s
28:	learn: 1131.5835812	total: 1.3s	remaining: 2.07s
29:	learn: 1127.0760279	total: 1.31s	remaining: 1.97s
30:	learn: 1123.3855675	total: 1.32s	remaining: 1.87s
31:	learn: 1119.7415763	total: 1.32s	remaining: 1.78s
32:	learn: 1115.7578494	total: 1.33s	remaining: 1.69s
33:	learn: 1112.3335599	total: 1.34s	remaining: 1.61s
34:	learn: 1108.5508034	total: 1.44s	remaining: 1.64s
35:	learn: 1105.7629420	total: 1.62s	remaining: 1.75s
36:	learn: 1103.0708890	total: 1.67s	remaining: 1.71s
37:	learn: 1099.9592190	total: 1.74s	remaining: 1.69s
38:	learn: 1097.7276683	total: 1.81s	remaining: 1.67s
39:	learn: 1095.3563688	total: 1.95s	remaining: 1.7s
40:	learn: 1093.4432319	total: 2.03s	remaining: 1.69s
41:	learn: 1091.8359398	total: 2.08s	remaining: 1.64s
42:	learn: 1090.2574924	total: 2.21s	remaining: 1.64s
43:	learn: 1088.3983227	total: 2.28s	remaining: 1.6s
44:	learn: 1086.8187684	total: 2.37s	remaining: 1.58s
45:	learn: 1085.6999151	total: 2.5s	remaining: 1.58s
46:	learn: 1084.6622422	total: 2.54s	remaining: 1.51s
47:	learn: 1083.7596000	total: 2.55s	remaining: 1.43s
48:	learn: 1082.9206919	total: 2.56s	remaining: 1.36s
49:	learn: 1082.1608774	total: 2.56s	remaining: 1.28s
50:	learn: 1081.1509906	total: 2.57s	remaining: 1.21s
51:	learn: 1080.5382851	total: 2.58s	remaining: 1.14s
52:	learn: 1078.8244384	total: 2.59s	remaining: 1.07s
53:	learn: 1077.9568115	total: 2.59s	remaining: 1.01s
54:	learn: 1077.0812751	total: 2.6s	remaining: 946ms
55:	learn: 1075.9209630	total: 2.61s	remaining: 885ms
56:	learn: 1075.2001738	total: 2.62s	remaining: 826ms
57:	learn: 1074.6591654	total: 2.62s	remaining: 769ms
58:	learn: 1073.8193655	total: 2.63s	remaining: 713ms
59:	learn: 1073.4751404	total: 2.64s	remaining: 659ms
60:	learn: 1072.7402631	total: 2.65s	remaining: 607ms
61:	learn: 1071.8742009	total: 2.65s	remaining: 556ms
62:	learn: 1071.5633009	total: 2.66s	remaining: 507ms
63:	learn: 1070.9696239	total: 2.67s	remaining: 459ms
64:	learn: 1070.0689122	total: 2.68s	remaining: 412ms
65:	learn: 1069.4352802	total: 2.68s	remaining: 366ms
66:	learn: 1069.0873484	total: 2.69s	remaining: 321ms
67:	learn: 1068.4395490	total: 2.7s	remaining: 278ms
68:	learn: 1067.8741152	total: 2.71s	remaining: 235ms
69:	learn: 1067.1065933	total: 2.71s	remaining: 194ms
70:	learn: 1066.9279912	total: 2.72s	remaining: 153ms
71:	learn: 1066.8739399	total: 2.73s	remaining: 114ms
72:	learn: 1066.6506933	total: 2.74s	remaining: 75ms
73:	learn: 1066.4382030	total: 2.74s	remaining: 37.1ms
74:	learn: 1066.0289354	total: 2.75s	remaining: 0us
[CV] END stack__CAT__learning_rate=0.05, stack__CAT__max_depth=6, stack__CAT__n_estimators=75, stack__LGBM__learning_rate=0.05, stack__LGBM__max_depth=4, stack__LGBM__n_estimators=75, stack__XGB__learning_rate=0.3, stack__XGB__max_depth=6, stack__XGB__n_estimators=100, stack__final_estimator__max_depth=6, stack__final_estimator__n_estimators=100; total time=25.6min
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.240814 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 820
[LightGBM] [Info] Number of data points in the train set: 6819, number of used features: 39
[LightGBM] [Info] Start training from score 2189.804680
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

16:	learn: 1245.5080058	total: 341ms	remaining: 1.16s
17:	learn: 1231.3092234	total: 388ms	remaining: 1.23s
18:	learn: 1219.3492285	total: 446ms	remaining: 1.31s
19:	learn: 1207.2764429	total: 474ms	remaining: 1.3s
20:	learn: 1195.9128473	total: 480ms	remaining: 1.23s
21:	learn: 1185.3968206	total: 491ms	remaining: 1.18s
22:	learn: 1176.9230164	total: 565ms	remaining: 1.28s
23:	learn: 1168.6080394	total: 629ms	remaining: 1.34s
24:	learn: 1161.1218161	total: 735ms	remaining: 1.47s
25:	learn: 1154.7988834	total: 794ms	remaining: 1.5s
26:	learn: 1149.2708418	total: 826ms	remaining: 1.47s
27:	learn: 1142.9105829	total: 847ms	remaining: 1.42s
28:	learn: 1137.0174390	total: 859ms	remaining: 1.36s
29:	learn: 1132.3226277	total: 894ms	remaining: 1.34s
30:	learn: 1128.2065928	total: 918ms	remaining: 1.3s
31:	learn: 1124.4084631	total: 927ms	remaining: 1.25s
32:	learn: 1120.2717184	total: 935ms	remaining: 1.19s
33:	learn: 1116.3586089	total: 946ms	remaining: 1.14s
34:	learn: 1112.6227234	total: 961ms	remaining: 1.1s
35:	learn: 1109.2298863	total: 967ms	remaining: 1.05s
36:	learn: 1106.3844556	total: 977ms	remaining: 1s
37:	learn: 1103.7209103	total: 983ms	remaining: 957ms
38:	learn: 1101.6899836	total: 991ms	remaining: 915ms
39:	learn: 1099.4914080	total: 1s	remaining: 877ms
40:	learn: 1097.5576418	total: 1.01s	remaining: 837ms
41:	learn: 1095.6320696	total: 1.03s	remaining: 808ms
42:	learn: 1094.1145231	total: 1.03s	remaining: 770ms
43:	learn: 1092.1325503	total: 1.04s	remaining: 733ms
44:	learn: 1090.5967845	total: 1.05s	remaining: 700ms
45:	learn: 1089.4616554	total: 1.09s	remaining: 685ms
46:	learn: 1088.2033126	total: 1.17s	remaining: 698ms
47:	learn: 1087.1355907	total: 1.18s	remaining: 664ms
48:	learn: 1086.0356206	total: 1.31s	remaining: 697ms
49:	learn: 1085.2567989	total: 1.36s	remaining: 682ms
50:	learn: 1084.1715353	total: 1.45s	remaining: 682ms
51:	learn: 1083.5021154	total: 1.5s	remaining: 663ms
52:	learn: 1082.6109813	total: 1.58s	remaining: 657ms
53:	learn: 1081.9417656	total: 1.7s	remaining: 661ms
54:	learn: 1081.0853388	total: 1.73s	remaining: 629ms
55:	learn: 1080.2419177	total: 1.79s	remaining: 608ms
56:	learn: 1079.4258099	total: 1.86s	remaining: 589ms
57:	learn: 1078.8432197	total: 1.88s	remaining: 551ms
58:	learn: 1078.1754982	total: 1.94s	remaining: 527ms
59:	learn: 1077.5502530	total: 2.06s	remaining: 516ms
60:	learn: 1076.7889936	total: 2.1s	remaining: 483ms
61:	learn: 1076.2264420	total: 2.14s	remaining: 448ms
62:	learn: 1076.0808590	total: 2.28s	remaining: 434ms
63:	learn: 1075.5647761	total: 2.3s	remaining: 395ms
64:	learn: 1075.0650772	total: 2.34s	remaining: 360ms
65:	learn: 1073.9970632	total: 2.38s	remaining: 325ms
66:	learn: 1073.5036877	total: 2.48s	remaining: 296ms
67:	learn: 1073.2638177	total: 2.52s	remaining: 259ms
68:	learn: 1072.5622211	total: 2.63s	remaining: 229ms
69:	learn: 1071.7964473	total: 2.64s	remaining: 188ms
70:	learn: 1071.0333823	total: 2.64s	remaining: 149ms
71:	learn: 1070.3166387	total: 2.66s	remaining: 111ms
72:	learn: 1069.6954019	total: 2.68s	remaining: 73.4ms
73:	learn: 1069.0385520	total: 2.69s	remaining: 36.3ms
74:	learn: 1068.3879943	total: 2.69s	remaining: 0us
0:	learn: 1676.4144872	total: 101ms	remaining: 7.48s
1:	learn: 1633.1512452	total: 190ms	remaining: 6.94s
2:	learn: 1589.9200044	total: 249ms	remaining: 5.97s
3:	learn: 1551.7635667	total: 258ms	remaining: 4.59s
4:	learn: 1519.9700312	total: 265ms	remaining: 3.7s
5:	learn: 1486.8029006	total: 271ms	remaining: 3.12s
6:	learn: 1453.6202781	total: 290ms	remaining: 2.82s
7:	learn: 1423.0099024	total: 297ms	remaining: 2.48s
8:	learn: 1396.5668116	total: 375ms	remaining: 2.75s
9:	learn: 1371.3864598	total: 413ms	remaining: 2.68s
10:	learn: 1347.6655178	total: 536ms	remaining: 3.12s
11:	learn: 1326.0406917	total: 565ms	remaining: 2.97s
12:	learn: 1305.6690502	total: 698ms	remaining: 3.33s
13:	learn: 1286.7113263	total: 715ms	remaining: 3.11s
14:	learn: 1271.2495923	total: 741ms	remaining: 2.96s
15:	learn: 1256.5398678	total: 759ms	remaining: 2.8s
16:	learn: 1243.5248597	total: 830ms	remaining: 2.83s
17:	learn: 1228.8779177	total: 988ms	remaining: 3.13s
18:	learn: 1215.3246689	total: 995ms	remaining: 2.93s
19:	learn: 1205.5306110	total: 1s	remaining: 2.76s
20:	learn: 1195.5595682	total: 1.02s	remaining: 2.63s
21:	learn: 1187.4228631	total: 1.03s	remaining: 2.47s
22:	learn: 1177.6045854	total: 1.03s	remaining: 2.33s
23:	learn: 1170.0446604	total: 1.04s	remaining: 2.21s
24:	learn: 1163.1094690	total: 1.05s	remaining: 2.1s
25:	learn: 1155.6956614	total: 1.06s	remaining: 1.99s
26:	learn: 1149.7075178	total: 1.06s	remaining: 1.89s
27:	learn: 1142.3888876	total: 1.07s	remaining: 1.8s
28:	learn: 1135.9208742	total: 1.09s	remaining: 1.73s
29:	learn: 1129.9394762	total: 1.12s	remaining: 1.68s
30:	learn: 1124.1821967	total: 1.13s	remaining: 1.6s
31:	learn: 1120.0685929	total: 1.16s	remaining: 1.56s
32:	learn: 1115.8579562	total: 1.22s	remaining: 1.55s
33:	learn: 1113.2275079	total: 1.26s	remaining: 1.53s
34:	learn: 1109.0861111	total: 1.31s	remaining: 1.5s
35:	learn: 1105.6810283	total: 1.32s	remaining: 1.43s
36:	learn: 1102.8302269	total: 1.44s	remaining: 1.48s
37:	learn: 1099.3901987	total: 1.47s	remaining: 1.43s
38:	learn: 1097.6124526	total: 1.54s	remaining: 1.42s
39:	learn: 1095.9029408	total: 1.59s	remaining: 1.39s
40:	learn: 1093.5843823	total: 1.69s	remaining: 1.41s
41:	learn: 1091.2280642	total: 1.74s	remaining: 1.36s
42:	learn: 1089.6999257	total: 1.79s	remaining: 1.33s
43:	learn: 1087.6107089	total: 1.86s	remaining: 1.31s
44:	learn: 1085.8792321	total: 1.87s	remaining: 1.25s
45:	learn: 1084.2685671	total: 1.97s	remaining: 1.24s
46:	learn: 1082.5444390	total: 2.03s	remaining: 1.21s
47:	learn: 1081.2654860	total: 2.04s	remaining: 1.15s
48:	learn: 1080.2396765	total: 2.07s	remaining: 1.1s
49:	learn: 1079.0188175	total: 2.08s	remaining: 1.04s
50:	learn: 1077.5633489	total: 2.09s	remaining: 986ms
51:	learn: 1076.5791769	total: 2.12s	remaining: 938ms
52:	learn: 1075.5375954	total: 2.13s	remaining: 884ms
53:	learn: 1074.5553950	total: 2.14s	remaining: 832ms
54:	learn: 1073.7176324	total: 2.15s	remaining: 781ms
55:	learn: 1073.4940435	total: 2.16s	remaining: 732ms
56:	learn: 1072.8754630	total: 2.16s	remaining: 683ms
57:	learn: 1072.0678820	total: 2.17s	remaining: 637ms
58:	learn: 1071.0603946	total: 2.18s	remaining: 591ms
59:	learn: 1070.6354963	total: 2.19s	remaining: 548ms
60:	learn: 1070.0069207	total: 2.2s	remaining: 506ms
61:	learn: 1068.8696750	total: 2.21s	remaining: 463ms
62:	learn: 1067.8776420	total: 2.22s	remaining: 423ms
63:	learn: 1066.9927823	total: 2.23s	remaining: 383ms
64:	learn: 1066.6798358	total: 2.24s	remaining: 344ms
65:	learn: 1065.9115270	total: 2.25s	remaining: 306ms
66:	learn: 1065.3898377	total: 2.29s	remaining: 274ms
67:	learn: 1064.8545973	total: 2.41s	remaining: 248ms
68:	learn: 1064.3195438	total: 2.48s	remaining: 216ms
69:	learn: 1063.8474950	total: 2.6s	remaining: 186ms
70:	learn: 1063.4268805	total: 2.66s	remaining: 150ms
71:	learn: 1063.1885415	total: 2.81s	remaining: 117ms
72:	learn: 1062.6053885	total: 2.88s	remaining: 78.9ms
73:	learn: 1062.2837309	total: 3s	remaining: 40.5ms
74:	learn: 1061.9717270	total: 3.05s	remaining: 0us
0:	learn: 1663.6369720	total: 136ms	remaining: 10.1s
1:	learn: 1628.7788544	total: 177ms	remaining: 6.45s
2:	learn: 1586.1688675	total: 235ms	remaining: 5.63s
3:	learn: 1548.3875864	total: 297ms	remaining: 5.27s
4:	learn: 1513.9884985	total: 395ms	remaining: 5.53s
5:	learn: 1483.9912971	total: 542ms	remaining: 6.23s
6:	learn: 1455.7543103	total: 611ms	remaining: 5.93s
7:	learn: 1427.4717878	total: 667ms	remaining: 5.59s
8:	learn: 1404.8165175	total: 730ms	remaining: 5.35s
9:	learn: 1378.2547104	total: 789ms	remaining: 5.13s
10:	learn: 1354.8636141	total: 845ms	remaining: 4.92s
11:	learn: 1332.6409772	total: 876ms	remaining: 4.6s
12:	learn: 1313.1043108	total: 997ms	remaining: 4.75s
13:	learn: 1294.6344073	total: 1.03s	remaining: 4.47s
14:	learn: 1277.0466218	total: 1.08s	remaining: 4.34s
15:	learn: 1260.8785227	total: 1.16s	remaining: 4.26s
16:	learn: 1246.1512857	total: 1.19s	remaining: 4.05s
17:	learn: 1232.5179590	total: 1.32s	remaining: 4.17s
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.241874 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 816
[LightGBM] [Info] Number of data points in the train set: 6818, number of used features: 39
[LightGBM] [Info] Start training from score 2159.816823
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
0:	learn: 1613.5032151	total: 229ms	remaining: 22.7s
1:	learn: 1530.7214629	total: 500ms	remaining: 24.5s
2:	learn: 1460.9542978	total: 558ms	remaining: 18s
3:	learn: 1398.2646625	total: 653ms	remaining: 15.7s
4:	learn: 1344.2516011	total: 733ms	remaining: 13.9s
5:	learn: 1299.2296751	total: 862ms	remaining: 13.5s
6:	learn: 1262.6201562	total: 917ms	remaining: 12.2s
7:	learn: 1231.1970155	total: 1.16s	remaining: 13.4s
8:	learn: 1204.6905465	total: 1.34s	remaining: 13.6s
9:	learn: 1180.9582451	total: 1.47s	remaining: 13.2s
10:	learn: 1161.5564185	total: 1.52s	remaining: 12.3s
11:	learn: 1146.6042246	total: 1.54s	remaining: 11.3s
12:	learn: 1132.2986008	total: 1.56s	remaining: 10.4s
13:	learn: 1119.7038031	total: 1.57s	remaining: 9.68s
14:	learn: 1110.1140520	total: 1.59s	remaining: 9.04s
15:	learn: 1101.4265715	total: 1.77s	remaining: 9.3s
16:	learn: 1095.1415991	total: 2.02s	remaining: 9.88s
17:	learn: 1088.6083388	total: 2.16s	remaining: 9.85s
18:	learn: 1082.8863211	total: 2.31s	remaining: 9.87s
19:	learn: 1077.7451002	total: 2.48s	remaining: 9.93s
20:	learn: 1073.8662425	total: 2.7s	remaining: 10.1s
21:	learn: 1069.9049113	total: 2.92s	remaining: 10.4s
22:	learn: 1067.3758544	total: 3.21s	remaining: 10.7s
23:	learn: 1065.7558818	total: 3.41s	remaining: 10.8s
24:	learn: 1062.4879357	total: 3.54s	remaining: 10.6s
25:	learn: 1060.1758805	total: 3.58s	remaining: 10.2s
26:	learn: 1057.0815155	total: 3.7s	remaining: 9.99s
27:	learn: 1054.5279914	total: 3.81s	remaining: 9.79s
28:	learn: 1052.1170537	total: 3.93s	remaining: 9.62s
29:	learn: 1050.7615278	total: 4.16s	remaining: 9.71s
30:	learn: 1048.7579892	total: 4.28s	remaining: 9.52s
31:	learn: 1048.2004336	total: 4.43s	remaining: 9.41s
32:	learn: 1047.2258394	total: 4.52s	remaining: 9.19s
33:	learn: 1046.2343705	total: 4.55s	remaining: 8.83s
34:	learn: 1044.8981778	total: 4.74s	remaining: 8.8s
35:	learn: 1044.6073147	total: 4.88s	remaining: 8.67s
36:	learn: 1043.4028494	total: 5.12s	remaining: 8.72s
37:	learn: 1042.5391014	total: 5.27s	remaining: 8.6s
38:	learn: 1041.4045164	total: 5.56s	remaining: 8.69s
39:	learn: 1040.4491295	total: 5.83s	remaining: 8.75s
40:	learn: 1039.9612067	total: 5.98s	remaining: 8.61s
41:	learn: 1039.5406029	total: 6.29s	remaining: 8.69s
42:	learn: 1039.1373802	total: 6.43s	remaining: 8.52s
43:	learn: 1038.5991481	total: 6.6s	remaining: 8.4s
44:	learn: 1038.1849093	total: 6.79s	remaining: 8.3s
45:	learn: 1037.6009143	total: 6.91s	remaining: 8.11s
46:	learn: 1037.2743430	total: 7.02s	remaining: 7.91s
47:	learn: 1036.4848236	total: 7.12s	remaining: 7.71s
48:	learn: 1036.0311564	total: 7.22s	remaining: 7.52s
49:	learn: 1035.5896848	total: 7.37s	remaining: 7.37s
50:	learn: 1035.0135192	total: 7.5s	remaining: 7.2s
51:	learn: 1034.5928270	total: 7.61s	remaining: 7.02s
52:	learn: 1033.8854883	total: 7.88s	remaining: 6.99s
53:	learn: 1033.7615225	total: 8.02s	remaining: 6.83s
54:	learn: 1033.0555934	total: 8.06s	remaining: 6.6s
55:	learn: 1032.5451608	total: 8.22s	remaining: 6.46s
56:	learn: 1032.1016192	total: 8.46s	remaining: 6.38s
57:	learn: 1031.5940730	total: 8.68s	remaining: 6.29s
58:	learn: 1031.0782843	total: 8.84s	remaining: 6.14s
59:	learn: 1030.2204719	total: 9.04s	remaining: 6.03s
60:	learn: 1029.2026553	total: 9.13s	remaining: 5.84s
61:	learn: 1028.6388728	total: 9.36s	remaining: 5.73s
62:	learn: 1028.2319761	total: 9.56s	remaining: 5.62s
63:	learn: 1027.7868020	total: 9.84s	remaining: 5.54s
64:	learn: 1027.2830850	total: 9.91s	remaining: 5.33s
65:	learn: 1026.6200950	total: 9.96s	remaining: 5.13s
66:	learn: 1026.2673034	total: 10.2s	remaining: 5.01s
67:	learn: 1024.3412336	total: 10.3s	remaining: 4.85s
68:	learn: 1024.0144198	total: 10.5s	remaining: 4.71s
69:	learn: 1023.5866819	total: 10.7s	remaining: 4.6s
70:	learn: 1023.2279131	total: 10.9s	remaining: 4.47s
71:	learn: 1022.7716194	total: 11.3s	remaining: 4.39s
72:	learn: 1022.2089056	total: 11.3s	remaining: 4.2s
73:	learn: 1021.9097143	total: 11.4s	remaining: 4.01s
74:	learn: 1021.4446329	total: 11.6s	remaining: 3.88s
75:	learn: 1020.9685930	total: 11.8s	remaining: 3.72s
76:	learn: 1020.3881224	total: 11.9s	remaining: 3.55s
77:	learn: 1019.2444454	total: 12s	remaining: 3.38s
78:	learn: 1018.9075583	total: 12.2s	remaining: 3.24s
79:	learn: 1018.1856659	total: 12.4s	remaining: 3.09s
80:	learn: 1017.7735814	total: 12.6s	remaining: 2.96s
81:	learn: 1016.5104830	total: 12.7s	remaining: 2.78s
82:	learn: 1016.0922237	total: 12.8s	remaining: 2.63s
83:	learn: 1015.8670021	total: 13.1s	remaining: 2.49s
84:	learn: 1015.5297862	total: 13.3s	remaining: 2.34s
85:	learn: 1015.1182980	total: 13.4s	remaining: 2.18s
86:	learn: 1014.7282997	total: 13.5s	remaining: 2.02s
87:	learn: 1014.2560831	total: 13.7s	remaining: 1.86s
88:	learn: 1014.0008664	total: 13.7s	remaining: 1.7s
89:	learn: 1013.5522110	total: 13.9s	remaining: 1.54s
90:	learn: 1013.0184568	total: 14s	remaining: 1.38s
91:	learn: 1012.4202789	total: 14s	remaining: 1.22s
92:	learn: 1012.0460318	total: 14.2s	remaining: 1.07s
93:	learn: 1011.4328680	total: 14.4s	remaining: 921ms
94:	learn: 1011.0364021	total: 14.6s	remaining: 771ms
95:	learn: 1010.6352629	total: 14.9s	remaining: 620ms
96:	learn: 1010.1673367	total: 15.1s	remaining: 467ms
97:	learn: 1009.6756384	total: 15.2s	remaining: 311ms
98:	learn: 1009.1456592	total: 15.3s	remaining: 155ms
99:	learn: 1008.6234121	total: 15.5s	remaining: 0us
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.245906 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 816
[LightGBM] [Info] Number of data points in the train set: 5454, number of used features: 39
[LightGBM] [Info] Start training from score 2147.784860
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.252907 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 816
[LightGBM] [Info] Number of data points in the train set: 5454, number of used features: 39
[LightGBM] [Info] Start training from score 2180.642468
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.319265 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 814
[LightGBM] [Info] Number of data points in the train set: 5454, number of used features: 39
[LightGBM] [Info] Start training from score 2149.096927
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.241178 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 814
[LightGBM] [Info] Number of data points in the train set: 5454, number of used features: 39
[LightGBM] [Info] Start training from score 2188.546493
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.253252 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 813
[LightGBM] [Info] Number of data points in the train set: 5455, number of used features: 39
[LightGBM] [Info] Start training from score 2162.504121
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.244329 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 814
[LightGBM] [Info] Number of data points in the train set: 5455, number of used features: 39
[LightGBM] [Info] Start training from score 2173.197686
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.244463 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 815
[LightGBM] [Info] Number of data points in the train set: 6818, number of used features: 39
[LightGBM] [Info] Start training from score 2183.057911
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
0:	learn: 1603.3275524	total: 149ms	remaining: 14.8s
1:	learn: 1522.2597056	total: 234ms	remaining: 11.4s
2:	learn: 1455.0879547	total: 432ms	remaining: 14s
3:	learn: 1396.8877160	total: 611ms	remaining: 14.7s
4:	learn: 1344.9262433	total: 828ms	remaining: 15.7s
5:	learn: 1298.9165393	total: 1.03s	remaining: 16.1s
6:	learn: 1260.2764952	total: 1.13s	remaining: 15s
7:	learn: 1228.3936000	total: 1.3s	remaining: 15s
8:	learn: 1201.1854387	total: 1.48s	remaining: 15s
9:	learn: 1178.0734055	total: 1.65s	remaining: 14.9s
10:	learn: 1160.2650638	total: 1.88s	remaining: 15.2s
11:	learn: 1144.2545115	total: 1.96s	remaining: 14.4s
12:	learn: 1130.9262187	total: 2.06s	remaining: 13.8s
13:	learn: 1122.1264814	total: 2.08s	remaining: 12.8s
14:	learn: 1112.5964247	total: 2.23s	remaining: 12.6s
15:	learn: 1103.5471173	total: 2.33s	remaining: 12.3s
16:	learn: 1096.0689322	total: 2.48s	remaining: 12.1s
17:	learn: 1089.7744872	total: 2.55s	remaining: 11.6s
18:	learn: 1084.6629798	total: 2.61s	remaining: 11.1s
19:	learn: 1080.4989527	total: 2.8s	remaining: 11.2s
20:	learn: 1077.2722365	total: 3.03s	remaining: 11.4s
21:	learn: 1074.1265919	total: 3.17s	remaining: 11.2s
22:	learn: 1071.2285153	total: 3.34s	remaining: 11.2s
23:	learn: 1068.7217527	total: 3.52s	remaining: 11.1s
24:	learn: 1066.5451579	total: 3.63s	remaining: 10.9s
25:	learn: 1065.0258368	total: 3.88s	remaining: 11s
26:	learn: 1063.1986775	total: 4.03s	remaining: 10.9s
27:	learn: 1061.8196798	total: 4.19s	remaining: 10.8s
28:	learn: 1059.8584926	total: 4.28s	remaining: 10.5s
29:	learn: 1058.0364176	total: 4.44s	remaining: 10.4s
30:	learn: 1056.2358891	total: 4.54s	remaining: 10.1s
31:	learn: 1055.0461786	total: 4.79s	remaining: 10.2s
32:	learn: 1054.1927177	total: 4.94s	remaining: 10s
33:	learn: 1052.9828304	total: 5.11s	remaining: 9.91s
34:	learn: 1052.1851073	total: 5.26s	remaining: 9.77s
35:	learn: 1051.4914325	total: 5.41s	remaining: 9.62s
36:	learn: 1050.2360586	total: 5.72s	remaining: 9.75s
37:	learn: 1049.4285543	total: 5.94s	remaining: 9.69s
38:	learn: 1048.2486859	total: 6.05s	remaining: 9.46s
39:	learn: 1047.1202387	total: 6.22s	remaining: 9.34s
40:	learn: 1046.6406335	total: 6.45s	remaining: 9.28s
41:	learn: 1045.6474270	total: 6.55s	remaining: 9.05s
42:	learn: 1044.8999099	total: 6.75s	remaining: 8.95s
43:	learn: 1043.5527802	total: 6.84s	remaining: 8.71s
44:	learn: 1042.4185016	total: 6.94s	remaining: 8.48s
45:	learn: 1041.4661498	total: 7.11s	remaining: 8.35s
46:	learn: 1040.7154152	total: 7.27s	remaining: 8.2s
47:	learn: 1040.2683624	total: 7.37s	remaining: 7.98s
48:	learn: 1039.6920637	total: 7.49s	remaining: 7.79s
49:	learn: 1039.0911530	total: 7.68s	remaining: 7.68s
50:	learn: 1038.6651958	total: 7.85s	remaining: 7.54s
51:	learn: 1038.3199097	total: 7.94s	remaining: 7.33s
52:	learn: 1037.3595398	total: 8.15s	remaining: 7.23s
53:	learn: 1037.1297120	total: 8.26s	remaining: 7.03s
54:	learn: 1036.6316570	total: 8.48s	remaining: 6.94s
55:	learn: 1036.0828341	total: 8.61s	remaining: 6.77s
56:	learn: 1035.5657880	total: 8.81s	remaining: 6.65s
57:	learn: 1035.3098533	total: 8.85s	remaining: 6.41s
58:	learn: 1035.1683847	total: 8.93s	remaining: 6.21s
59:	learn: 1034.9505227	total: 9.09s	remaining: 6.06s
60:	learn: 1034.6358004	total: 9.16s	remaining: 5.86s
61:	learn: 1034.1662861	total: 9.31s	remaining: 5.71s
62:	learn: 1033.5086266	total: 9.48s	remaining: 5.57s
63:	learn: 1032.7642244	total: 9.65s	remaining: 5.43s
64:	learn: 1031.9844585	total: 9.73s	remaining: 5.24s
65:	learn: 1031.6176689	total: 9.89s	remaining: 5.1s
66:	learn: 1031.3942200	total: 10s	remaining: 4.93s
67:	learn: 1030.7040731	total: 10.4s	remaining: 4.9s
68:	learn: 1030.4683664	total: 10.7s	remaining: 4.79s
69:	learn: 1030.1809159	total: 10.8s	remaining: 4.62s
70:	learn: 1029.8950898	total: 11s	remaining: 4.47s
71:	learn: 1029.1622469	total: 11.1s	remaining: 4.32s
72:	learn: 1028.8299013	total: 11.3s	remaining: 4.16s
73:	learn: 1028.2854921	total: 11.4s	remaining: 4.01s
74:	learn: 1027.9141540	total: 11.5s	remaining: 3.84s
75:	learn: 1027.6853593	total: 11.6s	remaining: 3.67s
76:	learn: 1027.2045427	total: 11.7s	remaining: 3.49s
77:	learn: 1026.9285025	total: 11.9s	remaining: 3.35s
78:	learn: 1026.6479551	total: 12s	remaining: 3.2s
79:	learn: 1026.2029063	total: 12.1s	remaining: 3.04s
80:	learn: 1025.9799584	total: 12.3s	remaining: 2.89s
81:	learn: 1025.5238620	total: 12.4s	remaining: 2.73s
82:	learn: 1025.2360885	total: 12.6s	remaining: 2.58s
83:	learn: 1024.9232711	total: 12.7s	remaining: 2.42s
84:	learn: 1024.4785117	total: 12.8s	remaining: 2.25s
85:	learn: 1023.9688780	total: 12.9s	remaining: 2.1s
86:	learn: 1023.6579611	total: 13s	remaining: 1.94s
87:	learn: 1023.2194715	total: 13.1s	remaining: 1.78s
88:	learn: 1022.0754430	total: 13.2s	remaining: 1.64s
89:	learn: 1021.6379828	total: 13.5s	remaining: 1.5s
90:	learn: 1021.2679625	total: 13.6s	remaining: 1.35s
91:	learn: 1020.5018322	total: 13.8s	remaining: 1.2s
92:	learn: 1020.1749111	total: 14s	remaining: 1.05s
93:	learn: 1019.7760990	total: 14.2s	remaining: 903ms
94:	learn: 1019.4265197	total: 14.3s	remaining: 753ms
95:	learn: 1018.9940314	total: 14.4s	remaining: 601ms
96:	learn: 1018.6174845	total: 14.6s	remaining: 450ms
97:	learn: 1018.0898836	total: 14.7s	remaining: 300ms
98:	learn: 1017.6700064	total: 14.8s	remaining: 150ms
99:	learn: 1017.1868684	total: 15.1s	remaining: 0us
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.203390 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 813
[LightGBM] [Info] Number of data points in the train set: 5454, number of used features: 39
[LightGBM] [Info] Start training from score 2171.037443
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.312952 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 813
[LightGBM] [Info] Number of data points in the train set: 5454, number of used features: 39
[LightGBM] [Info] Start training from score 2197.953391
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.363959 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 815
[LightGBM] [Info] Number of data points in the train set: 5454, number of used features: 39
[LightGBM] [Info] Start training from score 2184.956129
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.315892 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 814

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
0:	learn: 1534.8095596	total: 156ms	remaining: 15.4s
1:	learn: 1418.3105566	total: 244ms	remaining: 12s
2:	learn: 1318.2489918	total: 335ms	remaining: 10.8s
3:	learn: 1247.4796572	total: 409ms	remaining: 9.81s
4:	learn: 1193.8755311	total: 480ms	remaining: 9.12s
5:	learn: 1156.1235426	total: 492ms	remaining: 7.7s
6:	learn: 1136.0603348	total: 511ms	remaining: 6.79s
7:	learn: 1118.5715943	total: 533ms	remaining: 6.13s
8:	learn: 1106.3615486	total: 544ms	remaining: 5.5s
9:	learn: 1099.0489553	total: 569ms	remaining: 5.12s
10:	learn: 1093.3629957	total: 629ms	remaining: 5.09s
11:	learn: 1087.1217470	total: 699ms	remaining: 5.12s
12:	learn: 1083.8924077	total: 740ms	remaining: 4.95s
13:	learn: 1081.7414948	total: 814ms	remaining: 5s
14:	learn: 1079.5285132	total: 885ms	remaining: 5.02s
15:	learn: 1078.4674080	total: 977ms	remaining: 5.13s
16:	learn: 1076.8142186	total: 1s	remaining: 4.89s
17:	learn: 1074.2515067	total: 1.06s	remaining: 4.82s
18:	learn: 1070.5671615	total: 1.1s	remaining: 4.7s
19:	learn: 1069.8980351	total: 1.18s	remaining: 4.72s
20:	learn: 1068.4211798	total: 1.22s	remaining: 4.59s
21:	learn: 1067.6756983	total: 1.28s	remaining: 4.55s
22:	learn: 1066.9314003	total: 1.31s	remaining: 4.39s
23:	learn: 1066.4543600	total: 1.43s	remaining: 4.53s
24:	learn: 1065.2306260	total: 1.5s	remaining: 4.51s
25:	learn: 1064.4716585	total: 1.51s	remaining: 4.3s
26:	learn: 1063.7909780	total: 1.52s	remaining: 4.11s
27:	learn: 1063.1584074	total: 1.53s	remaining: 3.93s
28:	learn: 1062.0027321	total: 1.54s	remaining: 3.76s
29:	learn: 1061.3960778	total: 1.54s	remaining: 3.6s
30:	learn: 1060.6851478	total: 1.56s	remaining: 3.47s
31:	learn: 1059.9212762	total: 1.59s	remaining: 3.38s
32:	learn: 1059.4667191	total: 1.62s	remaining: 3.3s
33:	learn: 1058.5065687	total: 1.65s	remaining: 3.2s
34:	learn: 1057.0198097	total: 1.75s	remaining: 3.26s
35:	learn: 1056.3052817	total: 1.9s	remaining: 3.37s
36:	learn: 1055.7417741	total: 1.98s	remaining: 3.36s
37:	learn: 1055.0990186	total: 2.02s	remaining: 3.3s
38:	learn: 1054.2232760	total: 2.09s	remaining: 3.27s
39:	learn: 1053.5422170	total: 2.21s	remaining: 3.32s
40:	learn: 1052.7975053	total: 2.27s	remaining: 3.27s
41:	learn: 1052.3076826	total: 2.37s	remaining: 3.27s
42:	learn: 1051.7875201	total: 2.48s	remaining: 3.28s
43:	learn: 1051.0617023	total: 2.55s	remaining: 3.25s
44:	learn: 1050.7076550	total: 2.6s	remaining: 3.18s
45:	learn: 1050.2362239	total: 2.71s	remaining: 3.18s
46:	learn: 1049.4445119	total: 2.79s	remaining: 3.15s
47:	learn: 1048.6876307	total: 2.81s	remaining: 3.04s
48:	learn: 1047.6044922	total: 2.84s	remaining: 2.96s
49:	learn: 1046.7498142	total: 2.92s	remaining: 2.92s
50:	learn: 1046.0436641	total: 2.98s	remaining: 2.86s
51:	learn: 1045.3445313	total: 3.21s	remaining: 2.96s
52:	learn: 1044.7280429	total: 3.24s	remaining: 2.88s
53:	learn: 1044.3342864	total: 3.25s	remaining: 2.77s
54:	learn: 1043.6819857	total: 3.26s	remaining: 2.67s
55:	learn: 1043.3243194	total: 3.27s	remaining: 2.57s
56:	learn: 1042.5451793	total: 3.27s	remaining: 2.47s
57:	learn: 1042.0105938	total: 3.28s	remaining: 2.38s
58:	learn: 1041.4464457	total: 3.29s	remaining: 2.29s
59:	learn: 1040.8129241	total: 3.3s	remaining: 2.2s
60:	learn: 1040.1872123	total: 3.36s	remaining: 2.15s
61:	learn: 1039.5198194	total: 3.39s	remaining: 2.08s
62:	learn: 1038.9904954	total: 3.45s	remaining: 2.02s
63:	learn: 1038.3024300	total: 3.58s	remaining: 2.01s
64:	learn: 1037.5201500	total: 3.65s	remaining: 1.97s
65:	learn: 1036.9720714	total: 3.7s	remaining: 1.91s
66:	learn: 1036.4362869	total: 3.87s	remaining: 1.91s
67:	learn: 1035.5007017	total: 3.95s	remaining: 1.86s
68:	learn: 1034.9172458	total: 4.02s	remaining: 1.81s
69:	learn: 1034.6291564	total: 4.07s	remaining: 1.75s
70:	learn: 1033.9179514	total: 4.13s	remaining: 1.69s
71:	learn: 1033.2770625	total: 4.22s	remaining: 1.64s
72:	learn: 1032.6588825	total: 4.23s	remaining: 1.57s
73:	learn: 1032.3348973	total: 4.27s	remaining: 1.5s
74:	learn: 1031.8248118	total: 4.39s	remaining: 1.46s
75:	learn: 1031.3383184	total: 4.45s	remaining: 1.41s
76:	learn: 1030.8882296	total: 4.53s	remaining: 1.35s
77:	learn: 1030.6475518	total: 4.6s	remaining: 1.3s
78:	learn: 1029.8687386	total: 4.72s	remaining: 1.25s
79:	learn: 1029.3735232	total: 4.75s	remaining: 1.19s
80:	learn: 1028.7008647	total: 4.75s	remaining: 1.11s
81:	learn: 1028.2800269	total: 4.77s	remaining: 1.05s
82:	learn: 1027.9784524	total: 4.78s	remaining: 979ms
83:	learn: 1027.6071043	total: 4.79s	remaining: 912ms
84:	learn: 1026.8585408	total: 4.8s	remaining: 848ms
85:	learn: 1026.3100255	total: 4.83s	remaining: 786ms
86:	learn: 1025.4835083	total: 4.86s	remaining: 726ms
87:	learn: 1025.1513189	total: 4.9s	remaining: 668ms
88:	learn: 1024.7053350	total: 4.97s	remaining: 614ms
89:	learn: 1023.9245514	total: 5s	remaining: 556ms
90:	learn: 1023.6033487	total: 5.08s	remaining: 503ms
91:	learn: 1022.8624351	total: 5.16s	remaining: 449ms
92:	learn: 1022.5413643	total: 5.21s	remaining: 392ms
93:	learn: 1021.9682968	total: 5.29s	remaining: 338ms
94:	learn: 1021.7958122	total: 5.36s	remaining: 282ms
95:	learn: 1021.2785913	total: 5.44s	remaining: 227ms
96:	learn: 1020.5021050	total: 5.45s	remaining: 168ms
97:	learn: 1019.1785498	total: 5.52s	remaining: 113ms
98:	learn: 1018.8547379	total: 5.61s	remaining: 56.7ms
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
0:	learn: 1533.6847856	total: 121ms	remaining: 12s
1:	learn: 1415.1810086	total: 192ms	remaining: 9.39s
2:	learn: 1313.3111057	total: 321ms	remaining: 10.4s
3:	learn: 1247.9662972	total: 386ms	remaining: 9.25s
4:	learn: 1191.8077100	total: 462ms	remaining: 8.77s
5:	learn: 1154.6224487	total: 521ms	remaining: 8.17s
6:	learn: 1130.2191177	total: 597ms	remaining: 7.93s
7:	learn: 1111.9128187	total: 663ms	remaining: 7.62s
8:	learn: 1099.0234399	total: 727ms	remaining: 7.36s
9:	learn: 1090.3573898	total: 796ms	remaining: 7.16s
10:	learn: 1084.4333078	total: 802ms	remaining: 6.49s
11:	learn: 1080.9748972	total: 985ms	remaining: 7.22s
12:	learn: 1078.4182423	total: 997ms	remaining: 6.67s
13:	learn: 1076.2994953	total: 1.14s	remaining: 7s
14:	learn: 1072.7242082	total: 1.18s	remaining: 6.66s
15:	learn: 1070.0940384	total: 1.34s	remaining: 7.02s
16:	learn: 1068.0112668	total: 1.47s	remaining: 7.16s
17:	learn: 1066.9598009	total: 1.55s	remaining: 7.08s
18:	learn: 1065.1312170	total: 1.66s	remaining: 7.08s
19:	learn: 1063.6928903	total: 1.71s	remaining: 6.86s
20:	learn: 1062.7839845	total: 1.76s	remaining: 6.63s
21:	learn: 1062.2381117	total: 1.77s	remaining: 6.27s
22:	learn: 1061.4528082	total: 1.78s	remaining: 5.98s
23:	learn: 1060.7259190	total: 1.79s	remaining: 5.67s
24:	learn: 1060.0973812	total: 1.8s	remaining: 5.42s
25:	learn: 1059.0050316	total: 1.82s	remaining: 5.18s
26:	learn: 1058.1415699	total: 1.84s	remaining: 4.99s
27:	learn: 1057.5107380	total: 1.85s	remaining: 4.76s
28:	learn: 1055.6998136	total: 1.9s	remaining: 4.65s
29:	learn: 1054.3022196	total: 1.94s	remaining: 4.52s
30:	learn: 1053.4580675	total: 1.99s	remaining: 4.42s
31:	learn: 1052.9989728	total: 2.03s	remaining: 4.31s
32:	learn: 1052.4155548	total: 2.09s	remaining: 4.25s
33:	learn: 1051.7729923	total: 2.12s	remaining: 4.12s
34:	learn: 1050.8980920	total: 2.18s	remaining: 4.05s
35:	learn: 1050.4554983	total: 2.23s	remaining: 3.97s
36:	learn: 1050.2815534	total: 2.27s	remaining: 3.86s
37:	learn: 1049.7373164	total: 2.35s	remaining: 3.83s
38:	learn: 1049.1528684	total: 2.44s	remaining: 3.82s
39:	learn: 1048.6184167	total: 2.46s	remaining: 3.69s
40:	learn: 1048.1774946	total: 2.5s	remaining: 3.59s
41:	learn: 1047.4210679	total: 2.56s	remaining: 3.54s
42:	learn: 1046.7658663	total: 2.67s	remaining: 3.54s
43:	learn: 1046.1790188	total: 2.8s	remaining: 3.56s
44:	learn: 1045.5895402	total: 2.93s	remaining: 3.58s
45:	learn: 1045.1530174	total: 3.06s	remaining: 3.59s
46:	learn: 1044.2765769	total: 3.11s	remaining: 3.51s
47:	learn: 1043.6034989	total: 3.17s	remaining: 3.43s
48:	learn: 1042.9617258	total: 3.24s	remaining: 3.37s
49:	learn: 1042.2672130	total: 3.3s	remaining: 3.3s
50:	learn: 1041.9094800	total: 3.38s	remaining: 3.25s
51:	learn: 1041.5817985	total: 3.46s	remaining: 3.19s
52:	learn: 1041.1284928	total: 3.47s	remaining: 3.08s
53:	learn: 1040.7334387	total: 3.56s	remaining: 3.03s
54:	learn: 1040.0811353	total: 3.6s	remaining: 2.94s
55:	learn: 1039.1186448	total: 3.68s	remaining: 2.89s
56:	learn: 1038.3519096	total: 3.78s	remaining: 2.85s
57:	learn: 1037.8528744	total: 3.84s	remaining: 2.78s
58:	learn: 1037.1665425	total: 3.89s	remaining: 2.7s
59:	learn: 1036.5345483	total: 3.9s	remaining: 2.6s
60:	learn: 1035.9469633	total: 4.01s	remaining: 2.56s
61:	learn: 1035.2694046	total: 4.13s	remaining: 2.53s
62:	learn: 1034.1967182	total: 4.16s	remaining: 2.44s
63:	learn: 1033.8892001	total: 4.24s	remaining: 2.39s
64:	learn: 1033.4568072	total: 4.35s	remaining: 2.34s
65:	learn: 1032.7523631	total: 4.45s	remaining: 2.29s
66:	learn: 1032.4974071	total: 4.52s	remaining: 2.23s
67:	learn: 1031.8789075	total: 4.62s	remaining: 2.17s
68:	learn: 1031.2052956	total: 4.68s	remaining: 2.1s
69:	learn: 1030.4568846	total: 4.74s	remaining: 2.03s
70:	learn: 1029.9764503	total: 4.87s	remaining: 1.99s
71:	learn: 1029.3071277	total: 4.92s	remaining: 1.91s
72:	learn: 1028.6451732	total: 5s	remaining: 1.85s
73:	learn: 1028.1626420	total: 5.13s	remaining: 1.8s
74:	learn: 1027.6155403	total: 5.34s	remaining: 1.78s
75:	learn: 1026.8766943	total: 5.4s	remaining: 1.7s
76:	learn: 1026.6217963	total: 5.52s	remaining: 1.65s
77:	learn: 1026.2867839	total: 5.58s	remaining: 1.57s
78:	learn: 1025.7052231	total: 5.63s	remaining: 1.5s
79:	learn: 1025.0056543	total: 5.69s	remaining: 1.42s
80:	learn: 1024.4757827	total: 5.8s	remaining: 1.36s
81:	learn: 1023.4995892	total: 5.92s	remaining: 1.3s
82:	learn: 1022.5995590	total: 5.95s	remaining: 1.22s
83:	learn: 1021.8059830	total: 6s	remaining: 1.14s
84:	learn: 1021.3889864	total: 6.17s	remaining: 1.09s
85:	learn: 1020.9068902	total: 6.3s	remaining: 1.02s
86:	learn: 1020.4431113	total: 6.31s	remaining: 943ms
87:	learn: 1019.8143724	total: 6.34s	remaining: 865ms
88:	learn: 1019.2263392	total: 6.36s	remaining: 786ms
89:	learn: 1018.8998538	total: 6.41s	remaining: 712ms
90:	learn: 1018.6973911	total: 6.5s	remaining: 643ms
91:	learn: 1018.5153872	total: 6.53s	remaining: 568ms
92:	learn: 1017.8863446	total: 6.54s	remaining: 492ms
93:	learn: 1017.2412998	total: 6.56s	remaining: 419ms
94:	learn: 1016.6197176	total: 6.56s	remaining: 345ms
95:	learn: 1016.0769235	total: 6.57s	remaining: 274ms
96:	learn: 1015.5285308	total: 6.58s	remaining: 204ms
97:	learn: 1014.9538716	total: 6.59s	remaining: 135ms
98:	learn: 1014.2365480	total: 6.61s	remaining: 66.7ms

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.252838 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 816
[LightGBM] [Info] Number of data points in the train set: 5454, number of used features: 39
[LightGBM] [Info] Start training from score 2180.707534
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.216397 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 817
[LightGBM] [Info] Number of data points in the train set: 6819, number of used features: 39
[LightGBM] [Info] Start training from score 2193.082712
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
0:	learn: 1615.6194378	total: 112ms	remaining: 11s
1:	learn: 1533.1564335	total: 269ms	remaining: 13.2s
2:	learn: 1462.5267176	total: 421ms	remaining: 13.6s
3:	learn: 1404.7276500	total: 564ms	remaining: 13.5s
4:	learn: 1352.7114965	total: 684ms	remaining: 13s
5:	learn: 1310.4585814	total: 690ms	remaining: 10.8s
6:	learn: 1271.9096132	total: 739ms	remaining: 9.82s
7:	learn: 1239.4774330	total: 850ms	remaining: 9.78s
8:	learn: 1213.4975900	total: 901ms	remaining: 9.11s
9:	learn: 1192.4179608	total: 991ms	remaining: 8.92s
10:	learn: 1173.3966338	total: 1.25s	remaining: 10.1s
11:	learn: 1157.9029225	total: 1.35s	remaining: 9.9s
12:	learn: 1143.1302205	total: 1.44s	remaining: 9.61s
13:	learn: 1130.4269461	total: 1.57s	remaining: 9.65s
14:	learn: 1121.4047938	total: 1.74s	remaining: 9.88s
15:	learn: 1113.1846900	total: 2.12s	remaining: 11.2s
16:	learn: 1106.2194912	total: 2.31s	remaining: 11.3s
17:	learn: 1100.5471943	total: 2.46s	remaining: 11.2s
18:	learn: 1095.7932646	total: 2.53s	remaining: 10.8s
19:	learn: 1091.7477678	total: 2.63s	remaining: 10.5s
20:	learn: 1086.9495482	total: 2.72s	remaining: 10.2s
21:	learn: 1084.4064406	total: 2.73s	remaining: 9.69s
22:	learn: 1081.2919525	total: 2.79s	remaining: 9.33s
23:	learn: 1079.7209278	total: 2.82s	remaining: 8.92s
24:	learn: 1077.7279975	total: 2.9s	remaining: 8.71s
25:	learn: 1076.2143943	total: 2.92s	remaining: 8.31s
26:	learn: 1073.1252753	total: 3s	remaining: 8.1s
27:	learn: 1070.8107605	total: 3.02s	remaining: 7.78s
28:	learn: 1069.8348738	total: 3.05s	remaining: 7.47s
29:	learn: 1068.1394228	total: 3.14s	remaining: 7.33s
30:	learn: 1067.1723551	total: 3.32s	remaining: 7.39s
31:	learn: 1064.7806045	total: 3.46s	remaining: 7.35s
32:	learn: 1063.6005372	total: 3.57s	remaining: 7.24s
33:	learn: 1062.1442275	total: 3.78s	remaining: 7.34s
34:	learn: 1061.1123381	total: 3.89s	remaining: 7.23s
35:	learn: 1060.8299534	total: 3.91s	remaining: 6.96s
36:	learn: 1059.3080083	total: 4.08s	remaining: 6.95s
37:	learn: 1059.1046410	total: 4.25s	remaining: 6.93s
38:	learn: 1058.1186902	total: 4.32s	remaining: 6.75s
39:	learn: 1057.5666307	total: 4.54s	remaining: 6.81s
40:	learn: 1056.2778340	total: 4.7s	remaining: 6.77s
41:	learn: 1055.2551033	total: 4.83s	remaining: 6.67s
42:	learn: 1053.9562852	total: 4.86s	remaining: 6.45s
43:	learn: 1051.7538897	total: 4.96s	remaining: 6.32s
44:	learn: 1051.0213433	total: 5.13s	remaining: 6.27s
45:	learn: 1050.5200926	total: 5.38s	remaining: 6.31s
46:	learn: 1049.8565536	total: 5.61s	remaining: 6.33s
47:	learn: 1049.3206242	total: 5.85s	remaining: 6.34s
48:	learn: 1048.4080664	total: 6.12s	remaining: 6.37s
49:	learn: 1048.2691048	total: 6.35s	remaining: 6.35s
50:	learn: 1047.7774443	total: 6.57s	remaining: 6.31s
51:	learn: 1046.6650696	total: 6.67s	remaining: 6.16s
52:	learn: 1046.1980923	total: 6.9s	remaining: 6.12s
53:	learn: 1045.5291772	total: 7.04s	remaining: 6s
54:	learn: 1045.0910132	total: 7.15s	remaining: 5.85s
55:	learn: 1044.6283810	total: 7.36s	remaining: 5.79s
56:	learn: 1044.1257942	total: 7.59s	remaining: 5.73s
57:	learn: 1043.1037681	total: 7.78s	remaining: 5.63s
58:	learn: 1042.7603521	total: 7.83s	remaining: 5.44s
59:	learn: 1042.5062332	total: 7.93s	remaining: 5.29s
60:	learn: 1041.0324508	total: 8.25s	remaining: 5.28s
61:	learn: 1039.7881503	total: 8.43s	remaining: 5.16s
62:	learn: 1038.9520118	total: 8.65s	remaining: 5.08s
63:	learn: 1038.5433748	total: 8.79s	remaining: 4.95s
64:	learn: 1038.2087351	total: 8.98s	remaining: 4.84s
65:	learn: 1037.7248872	total: 9.08s	remaining: 4.68s
66:	learn: 1037.1932915	total: 9.32s	remaining: 4.59s
67:	learn: 1037.0244257	total: 9.37s	remaining: 4.41s
68:	learn: 1036.6760291	total: 9.56s	remaining: 4.3s
69:	learn: 1036.4552994	total: 9.77s	remaining: 4.19s
70:	learn: 1036.1646133	total: 9.91s	remaining: 4.05s
71:	learn: 1035.8965703	total: 10.1s	remaining: 3.93s
72:	learn: 1035.3846713	total: 10.3s	remaining: 3.79s
73:	learn: 1034.6415507	total: 10.3s	remaining: 3.63s
74:	learn: 1034.1575083	total: 10.6s	remaining: 3.53s
75:	learn: 1032.9786356	total: 10.8s	remaining: 3.4s
76:	learn: 1032.3706729	total: 10.9s	remaining: 3.27s
77:	learn: 1032.1625218	total: 11.2s	remaining: 3.15s
78:	learn: 1031.7781039	total: 11.3s	remaining: 3.01s
79:	learn: 1031.4505128	total: 11.4s	remaining: 2.86s
80:	learn: 1029.1949612	total: 11.6s	remaining: 2.72s
81:	learn: 1028.4920323	total: 11.8s	remaining: 2.59s
82:	learn: 1027.9803089	total: 12.1s	remaining: 2.48s
83:	learn: 1027.6911948	total: 12.4s	remaining: 2.35s
84:	learn: 1027.2280114	total: 12.5s	remaining: 2.21s
85:	learn: 1026.8792738	total: 12.7s	remaining: 2.07s
86:	learn: 1026.4650985	total: 12.8s	remaining: 1.92s
87:	learn: 1026.0856536	total: 12.9s	remaining: 1.76s
88:	learn: 1025.6357007	total: 13s	remaining: 1.61s
89:	learn: 1025.2161262	total: 13.2s	remaining: 1.46s
90:	learn: 1024.8876012	total: 13.4s	remaining: 1.32s
91:	learn: 1024.4493832	total: 13.4s	remaining: 1.17s
92:	learn: 1024.0321819	total: 13.7s	remaining: 1.03s
93:	learn: 1023.6046223	total: 13.9s	remaining: 885ms
94:	learn: 1023.3660238	total: 14s	remaining: 735ms
95:	learn: 1022.8451159	total: 14.3s	remaining: 595ms
96:	learn: 1022.5313695	total: 14.5s	remaining: 448ms
97:	learn: 1022.0872426	total: 14.6s	remaining: 298ms
98:	learn: 1021.7221960	total: 14.7s	remaining: 149ms
99:	learn: 1021.3085439	total: 14.9s	remaining: 0us
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.144419 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 816
[LightGBM] [Info] Number of data points in the train set: 5455, number of used features: 39
[LightGBM] [Info] Start training from score 2186.946488
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.264911 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 816
[LightGBM] [Info] Number of data points in the train set: 5455, number of used features: 39
[LightGBM] [Info] Start training from score 2195.120754
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.249205 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 815
[LightGBM] [Info] Number of data points in the train set: 5455, number of used features: 39
[LightGBM] [Info] Start training from score 2185.996669
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

18:	learn: 1221.5728491	total: 1.35s	remaining: 3.98s
19:	learn: 1209.5324384	total: 1.4s	remaining: 3.86s
20:	learn: 1199.1466821	total: 1.47s	remaining: 3.77s
21:	learn: 1190.1100632	total: 1.59s	remaining: 3.83s
22:	learn: 1180.3599087	total: 1.64s	remaining: 3.71s
23:	learn: 1171.1942596	total: 1.71s	remaining: 3.64s
24:	learn: 1163.4567843	total: 1.75s	remaining: 3.49s
25:	learn: 1156.3583359	total: 1.88s	remaining: 3.55s
26:	learn: 1150.9934785	total: 2.03s	remaining: 3.61s
27:	learn: 1144.6554955	total: 2.16s	remaining: 3.63s
28:	learn: 1139.5258091	total: 2.2s	remaining: 3.49s
29:	learn: 1134.5865682	total: 2.26s	remaining: 3.39s
30:	learn: 1129.0821526	total: 2.34s	remaining: 3.32s
31:	learn: 1124.3548768	total: 2.58s	remaining: 3.46s
32:	learn: 1120.8056830	total: 2.63s	remaining: 3.34s
33:	learn: 1117.7168994	total: 2.69s	remaining: 3.24s
34:	learn: 1113.7082620	total: 2.81s	remaining: 3.21s
35:	learn: 1110.7771171	total: 2.84s	remaining: 3.08s
36:	learn: 1108.4688525	total: 2.95s	remaining: 3.03s
37:	learn: 1106.0551572	total: 3.07s	remaining: 2.98s
38:	learn: 1103.2056839	total: 3.09s	remaining: 2.85s
39:	learn: 1100.4911382	total: 3.26s	remaining: 2.85s
40:	learn: 1097.9031308	total: 3.35s	remaining: 2.78s
41:	learn: 1096.5678022	total: 3.43s	remaining: 2.7s
42:	learn: 1095.2054236	total: 3.45s	remaining: 2.57s
43:	learn: 1093.5558851	total: 3.61s	remaining: 2.54s
44:	learn: 1092.3867262	total: 3.7s	remaining: 2.47s
45:	learn: 1090.9025291	total: 3.74s	remaining: 2.36s
46:	learn: 1089.7131853	total: 3.8s	remaining: 2.26s
47:	learn: 1088.2026239	total: 3.88s	remaining: 2.18s
48:	learn: 1087.0971362	total: 3.99s	remaining: 2.12s
49:	learn: 1086.2018216	total: 4.05s	remaining: 2.03s
50:	learn: 1084.7143043	total: 4.12s	remaining: 1.94s
51:	learn: 1083.3159389	total: 4.15s	remaining: 1.83s
52:	learn: 1082.0475758	total: 4.3s	remaining: 1.79s
53:	learn: 1081.1429465	total: 4.39s	remaining: 1.71s
54:	learn: 1079.7774910	total: 4.55s	remaining: 1.65s
55:	learn: 1079.1791919	total: 4.61s	remaining: 1.56s
56:	learn: 1078.5478178	total: 4.74s	remaining: 1.5s
57:	learn: 1077.8557152	total: 4.81s	remaining: 1.41s
58:	learn: 1076.7835899	total: 4.94s	remaining: 1.34s
59:	learn: 1076.3386911	total: 5.02s	remaining: 1.25s
60:	learn: 1075.2180141	total: 5.09s	remaining: 1.17s
61:	learn: 1074.7406511	total: 5.16s	remaining: 1.08s
62:	learn: 1074.2522975	total: 5.18s	remaining: 988ms
63:	learn: 1073.7801038	total: 5.3s	remaining: 912ms
64:	learn: 1073.2952469	total: 5.34s	remaining: 822ms
65:	learn: 1072.5126004	total: 5.45s	remaining: 744ms
66:	learn: 1072.1034239	total: 5.57s	remaining: 665ms
67:	learn: 1071.6769971	total: 5.68s	remaining: 585ms
68:	learn: 1071.4280535	total: 5.77s	remaining: 502ms
69:	learn: 1070.6909333	total: 5.82s	remaining: 416ms
70:	learn: 1070.1676979	total: 5.93s	remaining: 334ms
71:	learn: 1069.5198694	total: 6.02s	remaining: 251ms
72:	learn: 1069.2497411	total: 6.12s	remaining: 168ms
73:	learn: 1068.5550037	total: 6.14s	remaining: 82.9ms
74:	learn: 1068.3194662	total: 6.16s	remaining: 0us
0:	learn: 1660.0920633	total: 64.1ms	remaining: 4.74s
1:	learn: 1614.9573038	total: 219ms	remaining: 8.01s
2:	learn: 1574.7419880	total: 298ms	remaining: 7.16s
3:	learn: 1538.3689815	total: 338ms	remaining: 6s
4:	learn: 1503.7714093	total: 399ms	remaining: 5.58s
5:	learn: 1471.1274414	total: 551ms	remaining: 6.33s
6:	learn: 1438.7773324	total: 664ms	remaining: 6.45s
7:	learn: 1410.7381282	total: 695ms	remaining: 5.82s
8:	learn: 1384.7319387	total: 702ms	remaining: 5.14s
9:	learn: 1360.1842454	total: 708ms	remaining: 4.6s
10:	learn: 1340.3510273	total: 839ms	remaining: 4.88s
11:	learn: 1321.4010441	total: 858ms	remaining: 4.5s
12:	learn: 1301.6203097	total: 898ms	remaining: 4.28s
13:	learn: 1285.7247174	total: 979ms	remaining: 4.26s
14:	learn: 1269.6585874	total: 1.2s	remaining: 4.8s
15:	learn: 1253.4114765	total: 1.39s	remaining: 5.12s
16:	learn: 1238.5065878	total: 1.4s	remaining: 4.79s
17:	learn: 1224.5132325	total: 1.51s	remaining: 4.8s
18:	learn: 1212.6696918	total: 1.59s	remaining: 4.68s
19:	learn: 1200.7000096	total: 1.66s	remaining: 4.58s
20:	learn: 1189.3409557	total: 1.76s	remaining: 4.52s
21:	learn: 1179.8824884	total: 1.79s	remaining: 4.32s
22:	learn: 1172.1194613	total: 1.88s	remaining: 4.24s
23:	learn: 1163.5414954	total: 1.91s	remaining: 4.05s
24:	learn: 1155.9611936	total: 1.92s	remaining: 3.84s
25:	learn: 1149.4989991	total: 1.96s	remaining: 3.7s
26:	learn: 1142.6166771	total: 2.02s	remaining: 3.58s
27:	learn: 1137.2636834	total: 2.07s	remaining: 3.48s
28:	learn: 1131.8086201	total: 2.12s	remaining: 3.37s
29:	learn: 1127.2826526	total: 2.17s	remaining: 3.25s
30:	learn: 1122.3627741	total: 2.2s	remaining: 3.12s
31:	learn: 1118.6884802	total: 2.24s	remaining: 3.01s
32:	learn: 1114.6764891	total: 2.29s	remaining: 2.92s
33:	learn: 1111.2293493	total: 2.45s	remaining: 2.95s
34:	learn: 1107.5207413	total: 2.51s	remaining: 2.87s
35:	learn: 1104.7315104	total: 2.58s	remaining: 2.8s
36:	learn: 1102.3894616	total: 2.63s	remaining: 2.7s
37:	learn: 1100.4445570	total: 2.76s	remaining: 2.68s
38:	learn: 1098.2812427	total: 2.83s	remaining: 2.61s
39:	learn: 1096.7214886	total: 2.89s	remaining: 2.52s
40:	learn: 1095.2564884	total: 2.93s	remaining: 2.43s
41:	learn: 1092.7116543	total: 3.04s	remaining: 2.38s
42:	learn: 1091.1772972	total: 3.04s	remaining: 2.27s
43:	learn: 1088.7461846	total: 3.24s	remaining: 2.29s
44:	learn: 1087.0823381	total: 3.33s	remaining: 2.22s
45:	learn: 1085.3387298	total: 3.34s	remaining: 2.1s
46:	learn: 1084.0660170	total: 3.42s	remaining: 2.04s
47:	learn: 1083.1358029	total: 3.47s	remaining: 1.95s
48:	learn: 1081.5010155	total: 3.53s	remaining: 1.87s
49:	learn: 1080.7321241	total: 3.6s	remaining: 1.8s
50:	learn: 1079.7196727	total: 3.65s	remaining: 1.72s
51:	learn: 1078.8749158	total: 3.7s	remaining: 1.64s
52:	learn: 1077.5765561	total: 3.82s	remaining: 1.59s
53:	learn: 1076.5469306	total: 3.88s	remaining: 1.51s
54:	learn: 1075.6321726	total: 3.95s	remaining: 1.44s
55:	learn: 1074.8365475	total: 4.01s	remaining: 1.36s
56:	learn: 1073.8942397	total: 4.03s	remaining: 1.27s
57:	learn: 1072.9136557	total: 4.12s	remaining: 1.21s
58:	learn: 1072.6925310	total: 4.14s	remaining: 1.12s
59:	learn: 1071.8609360	total: 4.19s	remaining: 1.05s
60:	learn: 1070.8160527	total: 4.2s	remaining: 964ms
61:	learn: 1070.3847263	total: 4.25s	remaining: 892ms
62:	learn: 1069.3589303	total: 4.34s	remaining: 827ms
63:	learn: 1068.8952768	total: 4.36s	remaining: 749ms
64:	learn: 1068.3069948	total: 4.48s	remaining: 690ms
65:	learn: 1068.0764223	total: 4.61s	remaining: 629ms
66:	learn: 1067.7956685	total: 4.73s	remaining: 565ms
67:	learn: 1067.5885829	total: 4.87s	remaining: 501ms
68:	learn: 1067.3920565	total: 4.91s	remaining: 427ms
69:	learn: 1067.2332232	total: 5.02s	remaining: 359ms
70:	learn: 1066.7921962	total: 5.09s	remaining: 287ms
71:	learn: 1066.6763621	total: 5.18s	remaining: 216ms
72:	learn: 1066.3274045	total: 5.25s	remaining: 144ms
73:	learn: 1065.7408762	total: 5.3s	remaining: 71.7ms
74:	learn: 1065.5502542	total: 5.41s	remaining: 0us
[CV] END stack__CAT__learning_rate=0.05, stack__CAT__max_depth=6, stack__CAT__n_estimators=75, stack__LGBM__learning_rate=0.05, stack__LGBM__max_depth=4, stack__LGBM__n_estimators=75, stack__XGB__learning_rate=0.3, stack__XGB__max_depth=6, stack__XGB__n_estimators=100, stack__final_estimator__max_depth=6, stack__final_estimator__n_estimators=100; total time=26.2min
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.249237 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 815
[LightGBM] [Info] Number of data points in the train set: 6818, number of used features: 39
[LightGBM] [Info] Start training from score 2183.057911
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

99:	learn: 1013.6808643	total: 6.61s	remaining: 0us
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.191969 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 817
[LightGBM] [Info] Number of data points in the train set: 5455, number of used features: 39
[LightGBM] [Info] Start training from score 2184.653597
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
99:	learn: 1018.6578356	total: 5.66s	remaining: 0us
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.303768 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 816
[LightGBM] [Info] Number of data points in the train set: 5455, number of used features: 39
[LightGBM] [Info] Start training from score 2186.946488
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.249270 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 814
[LightGBM] [Info] Number of data points in the train set: 5455, number of used features: 39
[LightGBM] [Info] Start training from score 2188.145782
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.232657 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 818
[LightGBM] [Info] Number of data points in the train set: 5455, number of used features: 39
[LightGBM] [Info] Start training from score 2159.055387
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.273320 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 813
[LightGBM] [Info] Number of data points in the train set: 5455, number of used features: 39
[LightGBM] [Info] Start training from score 2175.226332
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
0:	learn: 1649.0009550	total: 200ms	remaining: 19.8s
1:	learn: 1604.6052611	total: 438ms	remaining: 21.4s
2:	learn: 1563.9929566	total: 675ms	remaining: 21.8s
3:	learn: 1526.3661382	total: 1000ms	remaining: 24s
4:	learn: 1492.2957693	total: 1.07s	remaining: 20.4s
5:	learn: 1459.5276965	total: 1.25s	remaining: 19.7s
6:	learn: 1428.3323651	total: 1.35s	remaining: 17.9s
7:	learn: 1399.4760737	total: 1.67s	remaining: 19.2s
8:	learn: 1373.3876558	total: 1.76s	remaining: 17.8s
9:	learn: 1348.5513699	total: 2s	remaining: 18s
10:	learn: 1325.3276586	total: 2.26s	remaining: 18.3s
11:	learn: 1303.4567761	total: 2.54s	remaining: 18.7s
12:	learn: 1287.3384441	total: 2.58s	remaining: 17.2s
13:	learn: 1268.5878103	total: 2.77s	remaining: 17s
14:	learn: 1251.3492914	total: 3.01s	remaining: 17.1s
15:	learn: 1238.3087331	total: 3.04s	remaining: 16s
16:	learn: 1224.2484803	total: 3.15s	remaining: 15.4s
17:	learn: 1211.1534859	total: 3.42s	remaining: 15.6s
18:	learn: 1199.0448854	total: 3.88s	remaining: 16.5s
19:	learn: 1187.9171282	total: 4.09s	remaining: 16.4s
20:	learn: 1176.9945019	total: 4.47s	remaining: 16.8s
21:	learn: 1167.5668552	total: 4.72s	remaining: 16.7s
22:	learn: 1158.6639683	total: 5.19s	remaining: 17.4s
23:	learn: 1150.1724489	total: 5.69s	remaining: 18s
24:	learn: 1142.2741916	total: 5.97s	remaining: 17.9s
25:	learn: 1135.6662715	total: 6.21s	remaining: 17.7s
26:	learn: 1128.9782435	total: 6.34s	remaining: 17.1s
27:	learn: 1122.8811339	total: 6.66s	remaining: 17.1s
28:	learn: 1117.0814682	total: 6.97s	remaining: 17.1s
29:	learn: 1112.6614566	total: 7.44s	remaining: 17.4s
30:	learn: 1107.5565920	total: 7.73s	remaining: 17.2s
31:	learn: 1102.6819800	total: 7.87s	remaining: 16.7s
32:	learn: 1098.7096611	total: 7.95s	remaining: 16.1s
33:	learn: 1094.5356282	total: 8.2s	remaining: 15.9s
34:	learn: 1091.2325494	total: 8.38s	remaining: 15.6s
35:	learn: 1087.6874570	total: 8.52s	remaining: 15.1s
36:	learn: 1084.3932609	total: 8.81s	remaining: 15s
37:	learn: 1081.8471929	total: 9.05s	remaining: 14.8s
38:	learn: 1079.2531572	total: 9.28s	remaining: 14.5s
39:	learn: 1076.8621059	total: 9.61s	remaining: 14.4s
40:	learn: 1074.5216770	total: 9.97s	remaining: 14.3s
41:	learn: 1071.9936346	total: 10.4s	remaining: 14.3s
42:	learn: 1070.3929329	total: 10.4s	remaining: 13.8s
43:	learn: 1067.4386903	total: 11s	remaining: 14s
44:	learn: 1066.2932991	total: 11.1s	remaining: 13.6s
45:	learn: 1064.1257341	total: 11.3s	remaining: 13.2s
46:	learn: 1062.4405779	total: 11.5s	remaining: 13s
47:	learn: 1060.3311810	total: 11.6s	remaining: 12.6s
48:	learn: 1058.8855825	total: 11.9s	remaining: 12.4s
49:	learn: 1057.3021643	total: 12.2s	remaining: 12.2s
50:	learn: 1056.6110266	total: 12.4s	remaining: 11.9s
51:	learn: 1055.3378536	total: 12.9s	remaining: 11.9s
52:	learn: 1054.1007605	total: 13.2s	remaining: 11.7s
53:	learn: 1053.1779890	total: 13.5s	remaining: 11.5s
54:	learn: 1052.0720928	total: 13.8s	remaining: 11.3s
55:	learn: 1050.5362521	total: 13.9s	remaining: 10.9s
56:	learn: 1049.7519673	total: 14s	remaining: 10.5s
57:	learn: 1048.5629270	total: 14.2s	remaining: 10.3s
58:	learn: 1046.7743832	total: 14.5s	remaining: 10s
59:	learn: 1046.1100577	total: 14.7s	remaining: 9.78s
60:	learn: 1045.3866238	total: 14.8s	remaining: 9.47s
61:	learn: 1044.8565388	total: 15s	remaining: 9.22s

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
0:	learn: 1507.8967725	total: 53.6ms	remaining: 5.3s
1:	learn: 1392.9568893	total: 227ms	remaining: 11.1s
2:	learn: 1301.2718329	total: 352ms	remaining: 11.4s
3:	learn: 1228.0974611	total: 361ms	remaining: 8.67s
4:	learn: 1184.7141364	total: 373ms	remaining: 7.09s
5:	learn: 1151.5446156	total: 459ms	remaining: 7.19s
6:	learn: 1123.9108545	total: 546ms	remaining: 7.25s
7:	learn: 1109.1158037	total: 623ms	remaining: 7.17s
8:	learn: 1095.1647671	total: 706ms	remaining: 7.14s
9:	learn: 1086.7914177	total: 715ms	remaining: 6.43s
10:	learn: 1078.6613776	total: 799ms	remaining: 6.46s
11:	learn: 1071.6631785	total: 880ms	remaining: 6.45s
12:	learn: 1070.1894524	total: 884ms	remaining: 5.91s
13:	learn: 1065.5598455	total: 1.02s	remaining: 6.27s
14:	learn: 1062.3943736	total: 1.06s	remaining: 5.99s
15:	learn: 1061.0879658	total: 1.09s	remaining: 5.75s
16:	learn: 1060.2094870	total: 1.13s	remaining: 5.51s
17:	learn: 1057.7976591	total: 1.29s	remaining: 5.87s
18:	learn: 1056.2784968	total: 1.41s	remaining: 6s
19:	learn: 1054.2873171	total: 1.48s	remaining: 5.9s
20:	learn: 1053.5080697	total: 1.49s	remaining: 5.59s
21:	learn: 1052.9341733	total: 1.58s	remaining: 5.61s
22:	learn: 1052.1435212	total: 1.7s	remaining: 5.68s
23:	learn: 1051.4432914	total: 1.87s	remaining: 5.93s
24:	learn: 1050.9439462	total: 2.01s	remaining: 6.02s
25:	learn: 1049.7612533	total: 2.07s	remaining: 5.89s
26:	learn: 1048.9125478	total: 2.14s	remaining: 5.79s
27:	learn: 1047.4574341	total: 2.3s	remaining: 5.92s
28:	learn: 1046.6068390	total: 2.38s	remaining: 5.84s
29:	learn: 1045.9041086	total: 2.44s	remaining: 5.69s
30:	learn: 1044.8981005	total: 2.53s	remaining: 5.63s
31:	learn: 1044.4060367	total: 2.56s	remaining: 5.45s
32:	learn: 1043.8410147	total: 2.66s	remaining: 5.4s
33:	learn: 1043.3423064	total: 2.67s	remaining: 5.19s
34:	learn: 1042.9896292	total: 2.72s	remaining: 5.06s
35:	learn: 1042.1400770	total: 2.79s	remaining: 4.96s
36:	learn: 1041.2348292	total: 2.95s	remaining: 5.02s
37:	learn: 1039.5574295	total: 3.15s	remaining: 5.14s
38:	learn: 1039.0049658	total: 3.19s	remaining: 5s
39:	learn: 1038.4703542	total: 3.24s	remaining: 4.87s
40:	learn: 1037.9623735	total: 3.35s	remaining: 4.82s
41:	learn: 1037.0593895	total: 3.37s	remaining: 4.65s
42:	learn: 1036.3202853	total: 3.52s	remaining: 4.67s
43:	learn: 1035.6452539	total: 3.58s	remaining: 4.56s
44:	learn: 1034.8697895	total: 3.63s	remaining: 4.43s
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.371960 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 816
[LightGBM] [Info] Number of data points in the train set: 5455, number of used features: 39
[LightGBM] [Info] Start training from score 2195.120754
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

45:	learn: 1034.0562651	total: 3.63s	remaining: 4.26s
46:	learn: 1033.4337595	total: 3.64s	remaining: 4.11s
47:	learn: 1032.5080270	total: 3.65s	remaining: 3.96s
48:	learn: 1032.2067638	total: 3.67s	remaining: 3.82s
49:	learn: 1031.6997628	total: 3.68s	remaining: 3.68s
50:	learn: 1031.0006228	total: 3.68s	remaining: 3.54s
51:	learn: 1030.4126873	total: 3.69s	remaining: 3.41s
52:	learn: 1029.5876561	total: 3.7s	remaining: 3.28s
53:	learn: 1028.6650968	total: 3.71s	remaining: 3.16s
54:	learn: 1028.1155266	total: 3.71s	remaining: 3.04s
55:	learn: 1027.1717314	total: 3.72s	remaining: 2.93s
56:	learn: 1026.7548047	total: 3.73s	remaining: 2.82s
57:	learn: 1025.8360844	total: 3.74s	remaining: 2.71s
58:	learn: 1025.1788675	total: 3.75s	remaining: 2.6s
59:	learn: 1024.2233536	total: 3.76s	remaining: 2.5s
60:	learn: 1023.8568723	total: 3.76s	remaining: 2.4s
61:	learn: 1023.2349795	total: 3.77s	remaining: 2.31s
62:	learn: 1022.4699589	total: 3.78s	remaining: 2.22s
63:	learn: 1021.5846524	total: 3.8s	remaining: 2.14s
64:	learn: 1020.6820655	total: 3.82s	remaining: 2.06s
65:	learn: 1020.0867405	total: 3.83s	remaining: 1.97s
66:	learn: 1019.3617313	total: 3.86s	remaining: 1.9s
67:	learn: 1018.7606209	total: 3.9s	remaining: 1.83s
68:	learn: 1018.3871535	total: 3.92s	remaining: 1.76s
69:	learn: 1017.3703531	total: 3.93s	remaining: 1.68s
70:	learn: 1016.4004180	total: 3.94s	remaining: 1.61s
71:	learn: 1015.7045536	total: 3.96s	remaining: 1.54s
72:	learn: 1015.3749313	total: 3.97s	remaining: 1.47s
73:	learn: 1014.9202015	total: 3.98s	remaining: 1.4s
74:	learn: 1014.0012166	total: 4.04s	remaining: 1.35s
75:	learn: 1013.3595777	total: 4.09s	remaining: 1.29s
76:	learn: 1012.5987817	total: 4.12s	remaining: 1.23s
77:	learn: 1011.8245418	total: 4.15s	remaining: 1.17s
78:	learn: 1011.3414734	total: 4.25s	remaining: 1.13s
79:	learn: 1010.7071839	total: 4.47s	remaining: 1.12s
80:	learn: 1010.4184629	total: 4.55s	remaining: 1.07s
81:	learn: 1009.8509482	total: 4.6s	remaining: 1.01s
82:	learn: 1009.3930901	total: 4.65s	remaining: 953ms
83:	learn: 1008.9170242	total: 4.66s	remaining: 888ms
84:	learn: 1008.6521841	total: 4.74s	remaining: 837ms
85:	learn: 1008.3412056	total: 4.79s	remaining: 779ms
86:	learn: 1008.0604360	total: 4.87s	remaining: 728ms
87:	learn: 1007.8161128	total: 4.99s	remaining: 680ms
88:	learn: 1007.5600260	total: 5.1s	remaining: 630ms
89:	learn: 1007.0104541	total: 5.16s	remaining: 573ms
90:	learn: 1006.4278716	total: 5.21s	remaining: 516ms
91:	learn: 1005.9807013	total: 5.26s	remaining: 457ms
92:	learn: 1004.7891551	total: 5.4s	remaining: 406ms
93:	learn: 1004.2128710	total: 5.48s	remaining: 350ms
94:	learn: 1003.5847998	total: 5.5s	remaining: 290ms
95:	learn: 1003.1845052	total: 5.58s	remaining: 233ms
96:	learn: 1002.9331284	total: 5.63s	remaining: 174ms
97:	learn: 1002.7097082	total: 5.73s	remaining: 117ms
98:	learn: 1001.6859461	total: 5.77s	remaining: 58.3ms
99:	learn: 1000.8966782	total: 5.89s	remaining: 0us
0:	learn: 1532.5920583	total: 105ms	remaining: 10.4s
1:	learn: 1396.3139953	total: 116ms	remaining: 5.68s
2:	learn: 1295.6827185	total: 204ms	remaining: 6.61s
3:	learn: 1228.6610675	total: 248ms	remaining: 5.96s
4:	learn: 1180.6136730	total: 306ms	remaining: 5.81s
5:	learn: 1145.7641684	total: 393ms	remaining: 6.16s
6:	learn: 1121.8182283	total: 417ms	remaining: 5.54s
7:	learn: 1104.9997357	total: 502ms	remaining: 5.78s
8:	learn: 1096.8144156	total: 548ms	remaining: 5.54s
9:	learn: 1089.6398119	total: 643ms	remaining: 5.79s
10:	learn: 1084.3442168	total: 690ms	remaining: 5.58s
11:	learn: 1079.5846384	total: 762ms	remaining: 5.59s
12:	learn: 1074.9952453	total: 823ms	remaining: 5.5s
13:	learn: 1071.9278303	total: 876ms	remaining: 5.38s
14:	learn: 1070.0488411	total: 995ms	remaining: 5.64s
15:	learn: 1069.3568934	total: 1.02s	remaining: 5.34s
16:	learn: 1067.4619809	total: 1.03s	remaining: 5.04s
17:	learn: 1065.5018136	total: 1.07s	remaining: 4.89s
18:	learn: 1063.7157802	total: 1.08s	remaining: 4.6s
19:	learn: 1061.6681244	total: 1.09s	remaining: 4.35s
20:	learn: 1059.5160879	total: 1.09s	remaining: 4.11s
21:	learn: 1058.9752734	total: 1.1s	remaining: 3.9s
22:	learn: 1057.7489050	total: 1.11s	remaining: 3.7s
23:	learn: 1057.0966335	total: 1.11s	remaining: 3.52s
24:	learn: 1055.8946718	total: 1.12s	remaining: 3.36s
25:	learn: 1053.1171599	total: 1.13s	remaining: 3.21s
26:	learn: 1052.6347627	total: 1.15s	remaining: 3.11s
27:	learn: 1052.2232575	total: 1.17s	remaining: 3.02s
28:	learn: 1051.3234734	total: 1.22s	remaining: 2.98s
29:	learn: 1050.8398856	total: 1.24s	remaining: 2.9s
30:	learn: 1048.8125516	total: 1.26s	remaining: 2.81s
31:	learn: 1048.0574706	total: 1.27s	remaining: 2.71s
32:	learn: 1046.7239625	total: 1.31s	remaining: 2.67s
33:	learn: 1046.2860959	total: 1.32s	remaining: 2.57s
34:	learn: 1045.4555503	total: 1.39s	remaining: 2.59s
35:	learn: 1044.7480204	total: 1.46s	remaining: 2.59s
36:	learn: 1043.9898009	total: 1.51s	remaining: 2.57s
37:	learn: 1043.3806390	total: 1.61s	remaining: 2.62s
38:	learn: 1042.1821477	total: 1.67s	remaining: 2.61s
39:	learn: 1041.6389453	total: 1.75s	remaining: 2.62s
40:	learn: 1040.6839889	total: 1.76s	remaining: 2.54s
41:	learn: 1039.4495354	total: 1.86s	remaining: 2.58s
42:	learn: 1038.3455880	total: 1.96s	remaining: 2.6s
43:	learn: 1037.9224874	total: 2.06s	remaining: 2.62s
44:	learn: 1037.2924204	total: 2.14s	remaining: 2.62s
45:	learn: 1036.4128804	total: 2.2s	remaining: 2.58s
46:	learn: 1035.8359883	total: 2.28s	remaining: 2.57s
47:	learn: 1035.2395983	total: 2.29s	remaining: 2.48s
48:	learn: 1034.6285528	total: 2.39s	remaining: 2.49s
49:	learn: 1034.0012806	total: 2.47s	remaining: 2.47s
50:	learn: 1033.0888183	total: 2.59s	remaining: 2.49s
51:	learn: 1032.5794399	total: 2.63s	remaining: 2.43s
52:	learn: 1031.8599282	total: 2.64s	remaining: 2.34s
53:	learn: 1031.0532072	total: 2.83s	remaining: 2.41s
54:	learn: 1030.0747411	total: 2.92s	remaining: 2.38s
55:	learn: 1029.1942982	total: 2.96s	remaining: 2.33s
56:	learn: 1028.7953532	total: 2.98s	remaining: 2.25s
57:	learn: 1028.1265935	total: 3.01s	remaining: 2.18s
58:	learn: 1027.5433767	total: 3.04s	remaining: 2.11s
59:	learn: 1026.9407381	total: 3.05s	remaining: 2.03s
60:	learn: 1026.0284189	total: 3.06s	remaining: 1.96s
61:	learn: 1025.3264537	total: 3.07s	remaining: 1.88s
62:	learn: 1024.9170645	total: 3.15s	remaining: 1.85s
63:	learn: 1024.3389484	total: 3.21s	remaining: 1.81s
64:	learn: 1023.9795323	total: 3.25s	remaining: 1.75s
65:	learn: 1023.6567036	total: 3.33s	remaining: 1.72s
66:	learn: 1023.0183655	total: 3.43s	remaining: 1.69s
67:	learn: 1022.4093697	total: 3.46s	remaining: 1.63s
68:	learn: 1021.3508956	total: 3.56s	remaining: 1.6s
69:	learn: 1020.9749703	total: 3.61s	remaining: 1.55s
70:	learn: 1020.1999200	total: 3.71s	remaining: 1.51s
71:	learn: 1019.7272139	total: 3.76s	remaining: 1.46s
72:	learn: 1019.3654888	total: 3.84s	remaining: 1.42s
73:	learn: 1018.8872799	total: 3.89s	remaining: 1.37s
74:	learn: 1018.4585776	total: 3.93s	remaining: 1.31s
75:	learn: 1017.9957953	total: 3.97s	remaining: 1.25s
76:	learn: 1016.6350090	total: 4s	remaining: 1.2s
77:	learn: 1016.2144395	total: 4.01s	remaining: 1.13s
78:	learn: 1015.7038070	total: 4.01s	remaining: 1.07s
79:	learn: 1015.0262588	total: 4.08s	remaining: 1.02s
80:	learn: 1014.5493679	total: 4.22s	remaining: 990ms
81:	learn: 1014.0572468	total: 4.25s	remaining: 933ms
82:	learn: 1013.3474321	total: 4.26s	remaining: 872ms
83:	learn: 1012.1701284	total: 4.26s	remaining: 812ms
84:	learn: 1011.4788992	total: 4.27s	remaining: 754ms
85:	learn: 1011.2077851	total: 4.29s	remaining: 698ms
86:	learn: 1010.7829805	total: 4.29s	remaining: 642ms
87:	learn: 1010.1396288	total: 4.31s	remaining: 587ms
88:	learn: 1009.6379208	total: 4.34s	remaining: 537ms
89:	learn: 1009.0835264	total: 4.41s	remaining: 490ms
90:	learn: 1008.5342195	total: 4.44s	remaining: 439ms
91:	learn: 1007.9714985	total: 4.48s	remaining: 389ms
92:	learn: 1007.5559856	total: 4.55s	remaining: 343ms
93:	learn: 1006.9304038	total: 4.58s	remaining: 293ms
94:	learn: 1005.9589629	total: 4.73s	remaining: 249ms
95:	learn: 1005.5275263	total: 4.78s	remaining: 199ms
96:	learn: 1004.2837238	total: 4.89s	remaining: 151ms
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.188222 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 820
[LightGBM] [Info] Number of data points in the train set: 6819, number of used features: 39
[LightGBM] [Info] Start training from score 2189.804680
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
0:	learn: 1620.6712381	total: 315ms	remaining: 31.2s
1:	learn: 1537.3350567	total: 507ms	remaining: 24.8s
2:	learn: 1467.0072232	total: 602ms	remaining: 19.4s
3:	learn: 1408.4473536	total: 750ms	remaining: 18s
4:	learn: 1355.7808264	total: 833ms	remaining: 15.8s
5:	learn: 1316.0747110	total: 898ms	remaining: 14.1s
6:	learn: 1274.8395678	total: 975ms	remaining: 13s
7:	learn: 1240.3420976	total: 1.21s	remaining: 13.9s
8:	learn: 1214.1923598	total: 1.3s	remaining: 13.1s
9:	learn: 1189.7311419	total: 1.44s	remaining: 12.9s
10:	learn: 1169.1778006	total: 1.51s	remaining: 12.2s
11:	learn: 1152.8907911	total: 1.6s	remaining: 11.7s
12:	learn: 1138.3570864	total: 1.78s	remaining: 11.9s
13:	learn: 1127.1010403	total: 1.93s	remaining: 11.8s
14:	learn: 1116.5172784	total: 2.06s	remaining: 11.7s
15:	learn: 1108.0095121	total: 2.15s	remaining: 11.3s
16:	learn: 1102.1596628	total: 2.34s	remaining: 11.4s
17:	learn: 1095.9940117	total: 2.49s	remaining: 11.3s
18:	learn: 1091.6488426	total: 2.8s	remaining: 12s
19:	learn: 1086.6483910	total: 2.91s	remaining: 11.7s
20:	learn: 1083.4786632	total: 3.13s	remaining: 11.8s
21:	learn: 1080.2895525	total: 3.26s	remaining: 11.6s
22:	learn: 1076.9446169	total: 3.36s	remaining: 11.3s
23:	learn: 1074.1696387	total: 3.58s	remaining: 11.3s
24:	learn: 1071.6517937	total: 3.76s	remaining: 11.3s
25:	learn: 1069.4268437	total: 3.92s	remaining: 11.2s
26:	learn: 1067.5832159	total: 3.98s	remaining: 10.8s
27:	learn: 1065.1468989	total: 4.22s	remaining: 10.9s
28:	learn: 1064.2476413	total: 4.38s	remaining: 10.7s
29:	learn: 1063.9343789	total: 4.52s	remaining: 10.6s
30:	learn: 1061.7831933	total: 4.65s	remaining: 10.3s
31:	learn: 1059.7601715	total: 4.85s	remaining: 10.3s
32:	learn: 1058.9035794	total: 4.98s	remaining: 10.1s
33:	learn: 1057.9695959	total: 5.17s	remaining: 10s
34:	learn: 1056.7766501	total: 5.3s	remaining: 9.84s
35:	learn: 1056.0992734	total: 5.4s	remaining: 9.6s
36:	learn: 1055.6707984	total: 5.48s	remaining: 9.34s
37:	learn: 1055.5075514	total: 5.57s	remaining: 9.09s
38:	learn: 1053.7669456	total: 5.62s	remaining: 8.79s
39:	learn: 1052.2347956	total: 5.72s	remaining: 8.58s
40:	learn: 1051.4066211	total: 5.8s	remaining: 8.35s
41:	learn: 1050.8211898	total: 5.89s	remaining: 8.14s
42:	learn: 1049.0852890	total: 6.03s	remaining: 7.99s
43:	learn: 1048.4038310	total: 6.11s	remaining: 7.78s
44:	learn: 1047.5275043	total: 6.21s	remaining: 7.59s
45:	learn: 1046.6674246	total: 6.34s	remaining: 7.45s
46:	learn: 1046.3307721	total: 6.46s	remaining: 7.28s
47:	learn: 1045.9310323	total: 6.54s	remaining: 7.09s
48:	learn: 1045.3092601	total: 6.57s	remaining: 6.83s
49:	learn: 1044.4164073	total: 6.62s	remaining: 6.62s
50:	learn: 1043.9249176	total: 6.7s	remaining: 6.43s
51:	learn: 1043.4797999	total: 6.81s	remaining: 6.29s
52:	learn: 1042.6361835	total: 6.94s	remaining: 6.16s
53:	learn: 1041.7188034	total: 7s	remaining: 5.96s
54:	learn: 1041.2176747	total: 7.14s	remaining: 5.84s
55:	learn: 1040.8727066	total: 7.28s	remaining: 5.72s
56:	learn: 1039.7875566	total: 7.42s	remaining: 5.6s
57:	learn: 1038.7792059	total: 7.53s	remaining: 5.45s
58:	learn: 1037.6029870	total: 7.61s	remaining: 5.29s
59:	learn: 1037.2618556	total: 7.71s	remaining: 5.14s
60:	learn: 1036.8298899	total: 7.86s	remaining: 5.03s
61:	learn: 1036.2351906	total: 7.97s	remaining: 4.89s
62:	learn: 1035.7211736	total: 8.11s	remaining: 4.76s
63:	learn: 1035.5373836	total: 8.16s	remaining: 4.59s
64:	learn: 1035.1614729	total: 8.3s	remaining: 4.47s
65:	learn: 1034.5856351	total: 8.4s	remaining: 4.33s
66:	learn: 1033.9529036	total: 8.53s	remaining: 4.2s
67:	learn: 1033.6354310	total: 8.66s	remaining: 4.07s
68:	learn: 1032.7589895	total: 8.75s	remaining: 3.93s
69:	learn: 1032.3113951	total: 8.92s	remaining: 3.82s
70:	learn: 1031.8194343	total: 9.11s	remaining: 3.72s
71:	learn: 1031.4645275	total: 9.27s	remaining: 3.6s
72:	learn: 1030.7290535	total: 9.38s	remaining: 3.47s
73:	learn: 1029.8434461	total: 9.49s	remaining: 3.34s
74:	learn: 1029.4960395	total: 9.54s	remaining: 3.18s
75:	learn: 1029.1218210	total: 9.62s	remaining: 3.04s
76:	learn: 1028.2538105	total: 9.84s	remaining: 2.94s
77:	learn: 1027.6217277	total: 9.96s	remaining: 2.81s
78:	learn: 1026.9958756	total: 10.1s	remaining: 2.69s
79:	learn: 1026.6961887	total: 10.2s	remaining: 2.56s
80:	learn: 1026.3689400	total: 10.3s	remaining: 2.43s
81:	learn: 1025.6092596	total: 10.5s	remaining: 2.3s
82:	learn: 1025.0544189	total: 10.6s	remaining: 2.16s
83:	learn: 1024.6260076	total: 10.7s	remaining: 2.03s
84:	learn: 1024.3343524	total: 10.9s	remaining: 1.92s
85:	learn: 1023.9076742	total: 11s	remaining: 1.79s
86:	learn: 1023.4430930	total: 11.1s	remaining: 1.66s
87:	learn: 1023.0959697	total: 11.3s	remaining: 1.54s
88:	learn: 1022.7394083	total: 11.3s	remaining: 1.4s
89:	learn: 1022.4070824	total: 11.5s	remaining: 1.27s
90:	learn: 1021.9754926	total: 11.6s	remaining: 1.14s
91:	learn: 1021.7048716	total: 11.7s	remaining: 1.01s
92:	learn: 1021.3675338	total: 11.8s	remaining: 891ms
93:	learn: 1020.9134730	total: 11.9s	remaining: 762ms
94:	learn: 1020.5162055	total: 12.1s	remaining: 637ms
95:	learn: 1020.1177513	total: 12.4s	remaining: 516ms
96:	learn: 1019.7949642	total: 12.6s	remaining: 389ms
97:	learn: 1019.4094670	total: 12.7s	remaining: 259ms
98:	learn: 1018.9749935	total: 12.8s	remaining: 130ms
99:	learn: 1018.5236710	total: 12.9s	remaining: 0us
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.253034 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 817
[LightGBM] [Info] Number of data points in the train set: 5455, number of used features: 39
[LightGBM] [Info] Start training from score 2184.653597
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.195991 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 815
[LightGBM] [Info] Number of data points in the train set: 5455, number of used features: 39
[LightGBM] [Info] Start training from score 2194.700891
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.313093 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 816
[LightGBM] [Info] Number of data points in the train set: 5455, number of used features: 39
[LightGBM] [Info] Start training from score 2182.058258
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.260999 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 818
[LightGBM] [Info] Number of data points in the train set: 5455, number of used features: 39
[LightGBM] [Info] Start training from score 2190.691077

97:	learn: 1003.4321333	total: 4.93s	remaining: 101ms
98:	learn: 1002.8920289	total: 4.99s	remaining: 50.4ms
99:	learn: 1002.5047654	total: 5s	remaining: 0us
0:	learn: 1532.6295875	total: 81.4ms	remaining: 8.06s
1:	learn: 1396.0752938	total: 148ms	remaining: 7.24s
2:	learn: 1296.6968683	total: 154ms	remaining: 4.98s
3:	learn: 1230.3403224	total: 160ms	remaining: 3.85s
4:	learn: 1185.7334602	total: 170ms	remaining: 3.24s
5:	learn: 1150.2782675	total: 241ms	remaining: 3.78s
6:	learn: 1125.5521071	total: 326ms	remaining: 4.33s
7:	learn: 1111.3081581	total: 385ms	remaining: 4.43s
8:	learn: 1100.6200157	total: 450ms	remaining: 4.55s
9:	learn: 1093.3825440	total: 537ms	remaining: 4.83s
10:	learn: 1088.3199705	total: 601ms	remaining: 4.86s
11:	learn: 1083.8186566	total: 727ms	remaining: 5.33s
12:	learn: 1081.1949084	total: 796ms	remaining: 5.32s
13:	learn: 1078.8291647	total: 858ms	remaining: 5.27s
14:	learn: 1076.4427484	total: 901ms	remaining: 5.1s
15:	learn: 1075.6298489	total: 918ms	remaining: 4.82s
16:	learn: 1073.8041389	total: 1.04s	remaining: 5.09s
17:	learn: 1071.6230522	total: 1.1s	remaining: 5.03s
18:	learn: 1070.7976228	total: 1.23s	remaining: 5.22s
19:	learn: 1069.5651307	total: 1.28s	remaining: 5.11s
20:	learn: 1067.5114110	total: 1.49s	remaining: 5.62s
21:	learn: 1066.2621375	total: 1.57s	remaining: 5.56s
22:	learn: 1065.5803457	total: 1.68s	remaining: 5.63s
23:	learn: 1063.5924776	total: 1.78s	remaining: 5.64s
24:	learn: 1062.8174951	total: 1.91s	remaining: 5.74s
25:	learn: 1061.8759190	total: 1.92s	remaining: 5.47s
26:	learn: 1060.5916812	total: 1.93s	remaining: 5.22s
27:	learn: 1060.2521095	total: 1.94s	remaining: 4.99s
28:	learn: 1059.2334995	total: 1.95s	remaining: 4.78s
29:	learn: 1058.3637293	total: 2.04s	remaining: 4.77s
30:	learn: 1057.8635976	total: 2.05s	remaining: 4.56s
31:	learn: 1057.2820054	total: 2.06s	remaining: 4.38s
32:	learn: 1055.0069043	total: 2.2s	remaining: 4.46s
33:	learn: 1054.0690349	total: 2.27s	remaining: 4.4s
34:	learn: 1053.4562824	total: 2.38s	remaining: 4.42s
35:	learn: 1052.5025894	total: 2.42s	remaining: 4.31s
36:	learn: 1052.0836008	total: 2.58s	remaining: 4.39s
37:	learn: 1051.8666941	total: 2.62s	remaining: 4.27s
38:	learn: 1049.7587326	total: 2.74s	remaining: 4.29s
39:	learn: 1049.1309681	total: 2.79s	remaining: 4.18s
40:	learn: 1048.7236184	total: 2.79s	remaining: 4.02s
41:	learn: 1048.3290167	total: 2.81s	remaining: 3.88s
42:	learn: 1046.7951361	total: 2.84s	remaining: 3.76s
43:	learn: 1045.9298382	total: 2.85s	remaining: 3.63s
44:	learn: 1044.9568762	total: 2.86s	remaining: 3.5s
45:	learn: 1044.2148606	total: 2.89s	remaining: 3.4s
46:	learn: 1043.1262419	total: 2.93s	remaining: 3.31s
47:	learn: 1042.3924593	total: 2.97s	remaining: 3.22s
48:	learn: 1041.6096318	total: 3s	remaining: 3.12s
49:	learn: 1040.6299169	total: 3.01s	remaining: 3.01s
50:	learn: 1039.8087114	total: 3.02s	remaining: 2.9s
51:	learn: 1039.2516943	total: 3.03s	remaining: 2.8s
52:	learn: 1038.5845320	total: 3.06s	remaining: 2.71s
53:	learn: 1037.7367721	total: 3.1s	remaining: 2.65s
54:	learn: 1037.1077860	total: 3.13s	remaining: 2.56s
55:	learn: 1036.6840532	total: 3.16s	remaining: 2.48s
56:	learn: 1035.8641690	total: 3.29s	remaining: 2.48s
57:	learn: 1035.0207687	total: 3.32s	remaining: 2.4s
58:	learn: 1034.4536796	total: 3.38s	remaining: 2.35s
59:	learn: 1033.7191504	total: 3.46s	remaining: 2.31s
60:	learn: 1033.3289527	total: 3.51s	remaining: 2.24s
61:	learn: 1032.5041842	total: 3.59s	remaining: 2.2s
62:	learn: 1032.1450682	total: 3.63s	remaining: 2.13s
63:	learn: 1031.2099949	total: 3.67s	remaining: 2.06s
64:	learn: 1030.6132408	total: 3.8s	remaining: 2.05s
65:	learn: 1029.8001109	total: 3.84s	remaining: 1.98s
66:	learn: 1029.1178323	total: 3.89s	remaining: 1.92s
67:	learn: 1028.6215792	total: 4.02s	remaining: 1.89s
68:	learn: 1028.0640260	total: 4.12s	remaining: 1.85s
69:	learn: 1027.3884503	total: 4.2s	remaining: 1.8s
70:	learn: 1026.3297647	total: 4.32s	remaining: 1.76s
71:	learn: 1025.8361529	total: 4.38s	remaining: 1.71s
72:	learn: 1025.0051745	total: 4.39s	remaining: 1.62s
73:	learn: 1024.6699968	total: 4.48s	remaining: 1.57s
74:	learn: 1023.8821601	total: 4.6s	remaining: 1.53s
75:	learn: 1023.1191770	total: 4.65s	remaining: 1.47s
76:	learn: 1022.2500453	total: 4.75s	remaining: 1.42s
77:	learn: 1021.5276179	total: 4.76s	remaining: 1.34s
78:	learn: 1021.0389507	total: 4.88s	remaining: 1.3s
79:	learn: 1020.7334997	total: 4.9s	remaining: 1.22s
80:	learn: 1020.0692136	total: 4.93s	remaining: 1.16s
81:	learn: 1019.5634522	total: 5.01s	remaining: 1.1s
82:	learn: 1019.2876931	total: 5.02s	remaining: 1.03s
83:	learn: 1018.7370450	total: 5.11s	remaining: 973ms
84:	learn: 1017.9509532	total: 5.16s	remaining: 910ms
85:	learn: 1017.2858895	total: 5.17s	remaining: 841ms
86:	learn: 1016.8617637	total: 5.23s	remaining: 782ms
87:	learn: 1016.2901859	total: 5.28s	remaining: 720ms
88:	learn: 1015.6964613	total: 5.38s	remaining: 666ms
89:	learn: 1015.1370474	total: 5.39s	remaining: 599ms
90:	learn: 1014.4042348	total: 5.49s	remaining: 543ms
91:	learn: 1014.1613557	total: 5.49s	remaining: 478ms
92:	learn: 1013.8990884	total: 5.51s	remaining: 415ms
93:	learn: 1013.4029679	total: 5.6s	remaining: 358ms
94:	learn: 1012.7210036	total: 5.66s	remaining: 298ms
95:	learn: 1011.6760928	total: 5.74s	remaining: 239ms
96:	learn: 1010.8793971	total: 5.75s	remaining: 178ms
97:	learn: 1010.4523577	total: 5.76s	remaining: 118ms
98:	learn: 1010.2107154	total: 5.84s	remaining: 59ms
99:	learn: 1009.9881914	total: 5.92s	remaining: 0us
0:	learn: 1536.3655824	total: 150ms	remaining: 14.8s
1:	learn: 1396.8460279	total: 213ms	remaining: 10.5s
2:	learn: 1293.6713360	total: 277ms	remaining: 8.96s
3:	learn: 1226.3698470	total: 295ms	remaining: 7.08s
4:	learn: 1175.0733438	total: 365ms	remaining: 6.93s
5:	learn: 1140.3404000	total: 430ms	remaining: 6.74s
6:	learn: 1120.8995642	total: 500ms	remaining: 6.64s
7:	learn: 1108.7086819	total: 609ms	remaining: 7s
8:	learn: 1095.0359976	total: 813ms	remaining: 8.22s
9:	learn: 1086.0830925	total: 910ms	remaining: 8.19s
10:	learn: 1081.3688897	total: 956ms	remaining: 7.73s
11:	learn: 1073.6810746	total: 1.01s	remaining: 7.42s
12:	learn: 1070.9441160	total: 1.15s	remaining: 7.71s
13:	learn: 1067.2212964	total: 1.33s	remaining: 8.17s
14:	learn: 1065.1030303	total: 1.38s	remaining: 7.8s
15:	learn: 1063.3496271	total: 1.38s	remaining: 7.26s
16:	learn: 1061.8200120	total: 1.4s	remaining: 6.85s
17:	learn: 1059.2351089	total: 1.43s	remaining: 6.5s
18:	learn: 1056.6561679	total: 1.45s	remaining: 6.17s
19:	learn: 1055.5938903	total: 1.49s	remaining: 5.97s
20:	learn: 1054.5145764	total: 1.59s	remaining: 5.98s
21:	learn: 1053.1407655	total: 1.66s	remaining: 5.9s
22:	learn: 1050.8869741	total: 1.72s	remaining: 5.74s
23:	learn: 1050.2034930	total: 1.78s	remaining: 5.65s
24:	learn: 1048.9669693	total: 1.83s	remaining: 5.5s
25:	learn: 1048.0471175	total: 1.87s	remaining: 5.32s
26:	learn: 1047.1373023	total: 1.94s	remaining: 5.25s
27:	learn: 1046.4445314	total: 2s	remaining: 5.16s
28:	learn: 1045.1900798	total: 2.05s	remaining: 5.01s
29:	learn: 1044.1598136	total: 2.06s	remaining: 4.8s
30:	learn: 1042.6920358	total: 2.07s	remaining: 4.6s
31:	learn: 1040.7793123	total: 2.08s	remaining: 4.41s
32:	learn: 1040.4075529	total: 2.09s	remaining: 4.25s
33:	learn: 1039.8201693	total: 2.11s	remaining: 4.09s
34:	learn: 1038.9968495	total: 2.11s	remaining: 3.92s
35:	learn: 1038.2423435	total: 2.13s	remaining: 3.78s
36:	learn: 1037.7235086	total: 2.13s	remaining: 3.63s
37:	learn: 1037.0188561	total: 2.14s	remaining: 3.5s
38:	learn: 1036.4226652	total: 2.16s	remaining: 3.37s
39:	learn: 1035.9334299	total: 2.16s	remaining: 3.25s
40:	learn: 1035.1375504	total: 2.17s	remaining: 3.13s
41:	learn: 1034.6549958	total: 2.19s	remaining: 3.02s
42:	learn: 1033.5888538	total: 2.19s	remaining: 2.91s
43:	learn: 1033.0075617	total: 2.21s	remaining: 2.81s
44:	learn: 1032.1701425	total: 2.22s	remaining: 2.72s
45:	learn: 1031.2458330	total: 2.25s	remaining: 2.64s
46:	learn: 1030.8458344	total: 2.26s	remaining: 2.55s
47:	learn: 1029.8067575	total: 2.26s	remaining: 2.45s
48:	learn: 1029.1876022	total: 2.27s	remaining: 2.37s
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
0:	learn: 1521.4246617	total: 55.2ms	remaining: 5.46s
1:	learn: 1391.1884027	total: 136ms	remaining: 6.69s
2:	learn: 1292.6306334	total: 175ms	remaining: 5.64s
3:	learn: 1218.5568500	total: 188ms	remaining: 4.51s
4:	learn: 1171.2235538	total: 195ms	remaining: 3.71s
5:	learn: 1145.6728864	total: 199ms	remaining: 3.11s
6:	learn: 1125.2517226	total: 206ms	remaining: 2.73s
7:	learn: 1105.8137432	total: 213ms	remaining: 2.45s
8:	learn: 1091.7631156	total: 220ms	remaining: 2.23s
9:	learn: 1082.5597231	total: 227ms	remaining: 2.05s
10:	learn: 1076.9820898	total: 234ms	remaining: 1.9s
11:	learn: 1071.9098635	total: 242ms	remaining: 1.77s
12:	learn: 1067.8896588	total: 250ms	remaining: 1.67s
13:	learn: 1063.8341176	total: 257ms	remaining: 1.58s
14:	learn: 1063.0419572	total: 263ms	remaining: 1.49s
15:	learn: 1059.0022313	total: 270ms	remaining: 1.42s
16:	learn: 1056.5917310	total: 276ms	remaining: 1.35s
17:	learn: 1054.8820648	total: 290ms	remaining: 1.32s
18:	learn: 1053.9100708	total: 302ms	remaining: 1.29s
19:	learn: 1051.9378627	total: 340ms	remaining: 1.36s
20:	learn: 1049.6478918	total: 396ms	remaining: 1.49s
21:	learn: 1049.1513507	total: 444ms	remaining: 1.57s
22:	learn: 1048.3675278	total: 488ms	remaining: 1.63s
23:	learn: 1047.5922665	total: 540ms	remaining: 1.71s
24:	learn: 1046.1810443	total: 587ms	remaining: 1.76s
25:	learn: 1045.2893716	total: 654ms	remaining: 1.86s
26:	learn: 1044.8784933	total: 683ms	remaining: 1.85s
27:	learn: 1044.4882317	total: 706ms	remaining: 1.81s
28:	learn: 1043.5405677	total: 720ms	remaining: 1.76s
29:	learn: 1042.6084421	total: 728ms	remaining: 1.7s
30:	learn: 1042.0042201	total: 773ms	remaining: 1.72s
31:	learn: 1040.9500607	total: 815ms	remaining: 1.73s
32:	learn: 1040.1086821	total: 838ms	remaining: 1.7s
33:	learn: 1039.2271040	total: 955ms	remaining: 1.85s
34:	learn: 1038.3821526	total: 986ms	remaining: 1.83s
35:	learn: 1037.7572244	total: 1.02s	remaining: 1.81s
36:	learn: 1037.1341437	total: 1.04s	remaining: 1.77s
37:	learn: 1036.0540616	total: 1.05s	remaining: 1.71s
38:	learn: 1035.2948132	total: 1.12s	remaining: 1.75s
39:	learn: 1034.6228409	total: 1.14s	remaining: 1.71s
40:	learn: 1034.1350218	total: 1.17s	remaining: 1.68s
41:	learn: 1033.3337259	total: 1.18s	remaining: 1.62s
42:	learn: 1032.5460130	total: 1.19s	remaining: 1.57s

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.207850 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 815
[LightGBM] [Info] Number of data points in the train set: 5455, number of used features: 39
[LightGBM] [Info] Start training from score 2194.700891
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
43:	learn: 1031.5461520	total: 1.2s	remaining: 1.52s
44:	learn: 1031.1739676	total: 1.23s	remaining: 1.5s
45:	learn: 1030.2687494	total: 1.25s	remaining: 1.47s
46:	learn: 1029.5328742	total: 1.26s	remaining: 1.42s
47:	learn: 1028.5300793	total: 1.27s	remaining: 1.37s
48:	learn: 1027.4834262	total: 1.29s	remaining: 1.34s
49:	learn: 1026.5169350	total: 1.38s	remaining: 1.38s
50:	learn: 1025.6214407	total: 1.51s	remaining: 1.45s
51:	learn: 1024.6924014	total: 1.6s	remaining: 1.47s
52:	learn: 1024.0141304	total: 1.71s	remaining: 1.52s
53:	learn: 1023.3994065	total: 1.78s	remaining: 1.51s
54:	learn: 1022.8495824	total: 1.86s	remaining: 1.52s
55:	learn: 1021.9779378	total: 1.92s	remaining: 1.5s
56:	learn: 1021.5086036	total: 2s	remaining: 1.51s
57:	learn: 1020.4230361	total: 2.08s	remaining: 1.5s
58:	learn: 1019.5976827	total: 2.08s	remaining: 1.45s
59:	learn: 1019.0814892	total: 2.21s	remaining: 1.48s
60:	learn: 1018.6492177	total: 2.28s	remaining: 1.46s
61:	learn: 1018.2623663	total: 2.29s	remaining: 1.4s
62:	learn: 1017.7066277	total: 2.42s	remaining: 1.42s
63:	learn: 1016.9848757	total: 2.45s	remaining: 1.38s
64:	learn: 1016.1858788	total: 2.49s	remaining: 1.34s
65:	learn: 1015.3638205	total: 2.56s	remaining: 1.32s
66:	learn: 1014.8296809	total: 2.61s	remaining: 1.28s
67:	learn: 1014.0112655	total: 2.62s	remaining: 1.23s
68:	learn: 1013.6240190	total: 2.71s	remaining: 1.22s
69:	learn: 1012.8715820	total: 2.79s	remaining: 1.19s
70:	learn: 1012.3221404	total: 2.85s	remaining: 1.17s
71:	learn: 1011.6904840	total: 2.95s	remaining: 1.15s
72:	learn: 1010.9342048	total: 2.98s	remaining: 1.1s
73:	learn: 1010.5950016	total: 3.05s	remaining: 1.07s
74:	learn: 1009.7577095	total: 3.06s	remaining: 1.02s
75:	learn: 1008.8519441	total: 3.2s	remaining: 1.01s
76:	learn: 1008.1751599	total: 3.21s	remaining: 959ms
77:	learn: 1007.4845196	total: 3.22s	remaining: 907ms
78:	learn: 1006.9614379	total: 3.22s	remaining: 857ms
79:	learn: 1006.1336499	total: 3.23s	remaining: 807ms
80:	learn: 1005.1530521	total: 3.23s	remaining: 759ms
81:	learn: 1004.3138261	total: 3.24s	remaining: 712ms
82:	learn: 1003.8506026	total: 3.25s	remaining: 665ms
83:	learn: 1003.6080716	total: 3.25s	remaining: 620ms
84:	learn: 1002.5848725	total: 3.26s	remaining: 576ms
85:	learn: 1001.9596141	total: 3.27s	remaining: 532ms
86:	learn: 1001.3964245	total: 3.31s	remaining: 495ms
87:	learn: 1000.7160549	total: 3.39s	remaining: 462ms
88:	learn: 1000.1164973	total: 3.42s	remaining: 423ms
89:	learn: 999.6931425	total: 3.57s	remaining: 397ms
90:	learn: 999.4154807	total: 3.64s	remaining: 360ms
91:	learn: 998.9436680	total: 3.73s	remaining: 325ms
92:	learn: 998.6948794	total: 3.81s	remaining: 286ms
93:	learn: 997.7219820	total: 3.89s	remaining: 248ms
94:	learn: 996.8538302	total: 3.91s	remaining: 206ms
95:	learn: 996.1079370	total: 3.99s	remaining: 166ms
96:	learn: 995.3328653	total: 4.06s	remaining: 125ms
97:	learn: 994.6573846	total: 4.11s	remaining: 83.9ms
98:	learn: 994.0279340	total: 4.31s	remaining: 43.6ms
99:	learn: 993.0609193	total: 4.39s	remaining: 0us
0:	learn: 1541.2763099	total: 64.6ms	remaining: 6.4s
1:	learn: 1411.5554211	total: 141ms	remaining: 6.92s
2:	learn: 1310.7921013	total: 179ms	remaining: 5.8s
3:	learn: 1239.5898021	total: 209ms	remaining: 5.01s
4:	learn: 1188.7574800	total: 328ms	remaining: 6.24s
5:	learn: 1153.4510258	total: 410ms	remaining: 6.42s
6:	learn: 1131.5483769	total: 420ms	remaining: 5.58s
7:	learn: 1112.5106211	total: 494ms	remaining: 5.68s
8:	learn: 1102.2249863	total: 542ms	remaining: 5.48s
9:	learn: 1094.8398184	total: 607ms	remaining: 5.47s
10:	learn: 1085.4115904	total: 682ms	remaining: 5.52s
11:	learn: 1080.4586264	total: 763ms	remaining: 5.59s
12:	learn: 1076.8489686	total: 780ms	remaining: 5.22s
13:	learn: 1073.8694742	total: 824ms	remaining: 5.06s
14:	learn: 1072.9076238	total: 925ms	remaining: 5.24s
15:	learn: 1071.4318201	total: 949ms	remaining: 4.98s
16:	learn: 1068.8887751	total: 1.01s	remaining: 4.93s
17:	learn: 1066.8149347	total: 1.04s	remaining: 4.74s
18:	learn: 1065.9393621	total: 1.07s	remaining: 4.58s
19:	learn: 1065.1422243	total: 1.27s	remaining: 5.07s
20:	learn: 1063.4609590	total: 1.39s	remaining: 5.21s
21:	learn: 1061.4918211	total: 1.46s	remaining: 5.16s
22:	learn: 1060.8281327	total: 1.54s	remaining: 5.14s
23:	learn: 1059.6204315	total: 1.59s	remaining: 5.03s
24:	learn: 1058.7067331	total: 1.64s	remaining: 4.91s
25:	learn: 1058.4201110	total: 1.65s	remaining: 4.69s
26:	learn: 1057.4088974	total: 1.68s	remaining: 4.53s
27:	learn: 1056.7289802	total: 1.72s	remaining: 4.41s
28:	learn: 1055.7883140	total: 1.76s	remaining: 4.32s
29:	learn: 1054.7566924	total: 1.81s	remaining: 4.22s
30:	learn: 1054.4449711	total: 1.85s	remaining: 4.11s
31:	learn: 1053.8413338	total: 1.88s	remaining: 3.98s
32:	learn: 1052.6261817	total: 1.88s	remaining: 3.83s
33:	learn: 1050.9469056	total: 1.93s	remaining: 3.74s
34:	learn: 1050.4833162	total: 2.04s	remaining: 3.78s
35:	learn: 1049.1681596	total: 2.1s	remaining: 3.74s
36:	learn: 1048.4317084	total: 2.2s	remaining: 3.75s
37:	learn: 1047.8811840	total: 2.21s	remaining: 3.61s
38:	learn: 1047.3619449	total: 2.24s	remaining: 3.5s
39:	learn: 1046.8034298	total: 2.27s	remaining: 3.4s
40:	learn: 1045.8589631	total: 2.28s	remaining: 3.29s
41:	learn: 1045.1389955	total: 2.29s	remaining: 3.17s
42:	learn: 1044.2292542	total: 2.37s	remaining: 3.14s
43:	learn: 1043.3638841	total: 2.38s	remaining: 3.02s
44:	learn: 1042.6088012	total: 2.38s	remaining: 2.91s
45:	learn: 1041.4245398	total: 2.41s	remaining: 2.83s
46:	learn: 1040.5934909	total: 2.46s	remaining: 2.77s
47:	learn: 1039.9755512	total: 2.49s	remaining: 2.7s
48:	learn: 1039.0942375	total: 2.5s	remaining: 2.6s
49:	learn: 1038.2212087	total: 2.52s	remaining: 2.52s
50:	learn: 1037.4157192	total: 2.54s	remaining: 2.44s
51:	learn: 1036.5947030	total: 2.61s	remaining: 2.41s
52:	learn: 1035.8153344	total: 2.64s	remaining: 2.34s
53:	learn: 1035.1269042	total: 2.68s	remaining: 2.29s
54:	learn: 1034.3140282	total: 2.73s	remaining: 2.23s
55:	learn: 1033.3997739	total: 2.76s	remaining: 2.17s
56:	learn: 1032.7446519	total: 2.88s	remaining: 2.17s
57:	learn: 1032.2062013	total: 2.92s	remaining: 2.12s
58:	learn: 1031.2902404	total: 3.01s	remaining: 2.09s
59:	learn: 1030.6549924	total: 3.07s	remaining: 2.04s
60:	learn: 1029.7941058	total: 3.13s	remaining: 2s
61:	learn: 1028.7945403	total: 3.17s	remaining: 1.94s
62:	learn: 1028.1895808	total: 3.22s	remaining: 1.89s
63:	learn: 1027.8156334	total: 3.24s	remaining: 1.82s
64:	learn: 1027.1386136	total: 3.32s	remaining: 1.79s
65:	learn: 1026.2364647	total: 3.39s	remaining: 1.75s
66:	learn: 1025.5782645	total: 3.42s	remaining: 1.69s
67:	learn: 1025.2253138	total: 3.47s	remaining: 1.63s
68:	learn: 1024.7189858	total: 3.53s	remaining: 1.58s
69:	learn: 1023.8508115	total: 3.54s	remaining: 1.52s
70:	learn: 1023.1851927	total: 3.58s	remaining: 1.46s
71:	learn: 1022.7643766	total: 3.68s	remaining: 1.43s
72:	learn: 1022.4074908	total: 3.73s	remaining: 1.38s
73:	learn: 1021.8991236	total: 3.76s	remaining: 1.32s
74:	learn: 1021.3152591	total: 3.82s	remaining: 1.27s
75:	learn: 1020.4180687	total: 3.87s	remaining: 1.22s
76:	learn: 1020.0868527	total: 3.93s	remaining: 1.17s
77:	learn: 1019.2519091	total: 3.96s	remaining: 1.12s
78:	learn: 1018.7723805	total: 4.08s	remaining: 1.08s
79:	learn: 1018.0858420	total: 4.15s	remaining: 1.04s
80:	learn: 1016.9537758	total: 4.18s	remaining: 980ms
81:	learn: 1016.4443435	total: 4.29s	remaining: 941ms
82:	learn: 1015.8566476	total: 4.33s	remaining: 886ms
83:	learn: 1014.8749969	total: 4.38s	remaining: 835ms
84:	learn: 1014.3170602	total: 4.48s	remaining: 791ms
85:	learn: 1013.9859446	total: 4.5s	remaining: 732ms
86:	learn: 1013.5508753	total: 4.51s	remaining: 673ms
87:	learn: 1013.2724016	total: 4.52s	remaining: 617ms
88:	learn: 1012.8222443	total: 4.54s	remaining: 561ms
89:	learn: 1012.3487167	total: 4.61s	remaining: 512ms
90:	learn: 1011.8286616	total: 4.67s	remaining: 462ms
91:	learn: 1011.3233479	total: 4.68s	remaining: 407ms
92:	learn: 1010.5350519	total: 4.69s	remaining: 353ms
93:	learn: 1009.7769217	total: 4.7s	remaining: 300ms
94:	learn: 1009.5192149	total: 4.71s	remaining: 248ms

49:	learn: 1028.7111678	total: 2.29s	remaining: 2.29s
50:	learn: 1028.2568621	total: 2.31s	remaining: 2.22s
51:	learn: 1027.3329031	total: 2.32s	remaining: 2.14s
52:	learn: 1026.4536479	total: 2.36s	remaining: 2.1s
53:	learn: 1025.6190399	total: 2.47s	remaining: 2.1s
54:	learn: 1024.6825100	total: 2.48s	remaining: 2.03s
55:	learn: 1024.2372465	total: 2.49s	remaining: 1.96s
56:	learn: 1023.8425249	total: 2.5s	remaining: 1.89s
57:	learn: 1023.0587087	total: 2.52s	remaining: 1.82s
58:	learn: 1021.9130620	total: 2.52s	remaining: 1.75s
59:	learn: 1021.1798432	total: 2.53s	remaining: 1.69s
60:	learn: 1020.5321072	total: 2.54s	remaining: 1.62s
61:	learn: 1019.3334004	total: 2.54s	remaining: 1.56s
62:	learn: 1018.7962338	total: 2.55s	remaining: 1.5s
63:	learn: 1018.4518397	total: 2.61s	remaining: 1.47s
64:	learn: 1018.1429631	total: 2.7s	remaining: 1.45s
65:	learn: 1017.0703697	total: 2.77s	remaining: 1.42s
66:	learn: 1016.3882772	total: 2.81s	remaining: 1.38s
67:	learn: 1015.5056990	total: 2.89s	remaining: 1.36s
68:	learn: 1014.8743457	total: 2.93s	remaining: 1.32s
69:	learn: 1014.5447018	total: 2.96s	remaining: 1.27s
70:	learn: 1014.2396379	total: 2.98s	remaining: 1.22s
71:	learn: 1013.5826554	total: 3s	remaining: 1.17s
72:	learn: 1013.3175926	total: 3.05s	remaining: 1.13s
73:	learn: 1013.0404256	total: 3.15s	remaining: 1.11s
74:	learn: 1012.1585798	total: 3.23s	remaining: 1.07s
75:	learn: 1011.3544534	total: 3.29s	remaining: 1.04s
76:	learn: 1011.0996133	total: 3.52s	remaining: 1.05s
77:	learn: 1010.5282148	total: 3.59s	remaining: 1.01s
78:	learn: 1010.0585149	total: 3.62s	remaining: 962ms
79:	learn: 1009.8208171	total: 3.71s	remaining: 928ms
80:	learn: 1009.0783289	total: 3.8s	remaining: 892ms
81:	learn: 1008.7030920	total: 3.81s	remaining: 836ms
82:	learn: 1008.2144641	total: 3.96s	remaining: 811ms
83:	learn: 1007.6248918	total: 4.01s	remaining: 764ms
84:	learn: 1007.1330840	total: 4.08s	remaining: 720ms
85:	learn: 1006.4739548	total: 4.21s	remaining: 686ms
86:	learn: 1005.9496685	total: 4.28s	remaining: 639ms
87:	learn: 1004.9690890	total: 4.37s	remaining: 596ms
88:	learn: 1004.5316022	total: 4.49s	remaining: 555ms
89:	learn: 1004.2872792	total: 4.62s	remaining: 513ms
90:	learn: 1004.0914229	total: 4.72s	remaining: 467ms
91:	learn: 1003.5163155	total: 4.79s	remaining: 416ms
92:	learn: 1003.1269733	total: 4.85s	remaining: 365ms
93:	learn: 1002.8797643	total: 4.92s	remaining: 314ms
94:	learn: 1002.3029642	total: 5.16s	remaining: 271ms
95:	learn: 1002.0863780	total: 5.21s	remaining: 217ms
96:	learn: 1001.8486139	total: 5.28s	remaining: 163ms
97:	learn: 1001.1406708	total: 5.33s	remaining: 109ms
98:	learn: 1000.7812134	total: 5.41s	remaining: 54.7ms
99:	learn: 1000.4031355	total: 5.48s	remaining: 0us
0:	learn: 1517.4150898	total: 34.6ms	remaining: 3.42s
1:	learn: 1393.7299831	total: 100ms	remaining: 4.9s
2:	learn: 1294.0681850	total: 145ms	remaining: 4.69s
3:	learn: 1227.2824695	total: 192ms	remaining: 4.6s
4:	learn: 1177.7836405	total: 334ms	remaining: 6.34s
5:	learn: 1150.1292680	total: 416ms	remaining: 6.51s
6:	learn: 1124.1836635	total: 445ms	remaining: 5.91s
7:	learn: 1109.3466352	total: 453ms	remaining: 5.21s
8:	learn: 1098.8611104	total: 461ms	remaining: 4.66s
9:	learn: 1090.1377278	total: 472ms	remaining: 4.25s
10:	learn: 1084.5447238	total: 482ms	remaining: 3.9s
11:	learn: 1080.7307689	total: 488ms	remaining: 3.58s
12:	learn: 1077.5624957	total: 495ms	remaining: 3.31s
13:	learn: 1074.0875205	total: 502ms	remaining: 3.08s
14:	learn: 1071.5091285	total: 509ms	remaining: 2.88s
15:	learn: 1069.4012825	total: 513ms	remaining: 2.69s
16:	learn: 1068.3511858	total: 520ms	remaining: 2.54s
17:	learn: 1067.4513842	total: 526ms	remaining: 2.4s
18:	learn: 1066.5644027	total: 532ms	remaining: 2.27s
19:	learn: 1065.4905202	total: 540ms	remaining: 2.16s
20:	learn: 1064.3400103	total: 553ms	remaining: 2.08s
21:	learn: 1062.5637882	total: 563ms	remaining: 1.99s
22:	learn: 1061.6313423	total: 590ms	remaining: 1.98s
23:	learn: 1060.6785849	total: 615ms	remaining: 1.95s
24:	learn: 1059.2535316	total: 628ms	remaining: 1.88s
25:	learn: 1058.5426966	total: 636ms	remaining: 1.81s
26:	learn: 1057.6335949	total: 642ms	remaining: 1.74s
27:	learn: 1055.1307151	total: 649ms	remaining: 1.67s
28:	learn: 1054.0545148	total: 656ms	remaining: 1.61s
29:	learn: 1053.4892165	total: 663ms	remaining: 1.55s
30:	learn: 1052.4331043	total: 670ms	remaining: 1.49s
31:	learn: 1051.8294234	total: 677ms	remaining: 1.44s
32:	learn: 1050.9451962	total: 685ms	remaining: 1.39s
33:	learn: 1050.1937956	total: 692ms	remaining: 1.34s
34:	learn: 1049.5553373	total: 698ms	remaining: 1.3s
35:	learn: 1048.9648770	total: 704ms	remaining: 1.25s
36:	learn: 1047.5525650	total: 710ms	remaining: 1.21s
37:	learn: 1045.7849618	total: 717ms	remaining: 1.17s
38:	learn: 1044.8398541	total: 724ms	remaining: 1.13s
39:	learn: 1044.3477109	total: 780ms	remaining: 1.17s
40:	learn: 1043.7581559	total: 822ms	remaining: 1.18s
41:	learn: 1042.8029559	total: 873ms	remaining: 1.2s
42:	learn: 1041.6188537	total: 920ms	remaining: 1.22s
43:	learn: 1041.0625787	total: 974ms	remaining: 1.24s
44:	learn: 1040.4742015	total: 1.03s	remaining: 1.26s
45:	learn: 1039.0829870	total: 1.05s	remaining: 1.23s
46:	learn: 1038.1303700	total: 1.11s	remaining: 1.26s
47:	learn: 1036.7079819	total: 1.21s	remaining: 1.31s
48:	learn: 1036.0202562	total: 1.27s	remaining: 1.33s
49:	learn: 1035.3592700	total: 1.35s	remaining: 1.35s
50:	learn: 1034.6426777	total: 1.4s	remaining: 1.35s
51:	learn: 1033.8138578	total: 1.45s	remaining: 1.34s
52:	learn: 1033.0012690	total: 1.49s	remaining: 1.32s
53:	learn: 1032.3159038	total: 1.54s	remaining: 1.31s
54:	learn: 1031.6502733	total: 1.6s	remaining: 1.31s
55:	learn: 1030.8244461	total: 1.63s	remaining: 1.28s
56:	learn: 1030.0682263	total: 1.64s	remaining: 1.24s
57:	learn: 1029.5184037	total: 1.74s	remaining: 1.26s
58:	learn: 1028.8723073	total: 1.97s	remaining: 1.37s
59:	learn: 1027.9517217	total: 2.06s	remaining: 1.37s
60:	learn: 1027.4234865	total: 2.13s	remaining: 1.36s
61:	learn: 1026.9097988	total: 2.17s	remaining: 1.33s
62:	learn: 1026.5125020	total: 2.19s	remaining: 1.28s
63:	learn: 1025.9423382	total: 2.28s	remaining: 1.28s
64:	learn: 1025.6070172	total: 2.31s	remaining: 1.24s
65:	learn: 1024.6545189	total: 2.42s	remaining: 1.25s
66:	learn: 1024.3816356	total: 2.46s	remaining: 1.21s
67:	learn: 1023.6928877	total: 2.52s	remaining: 1.18s
68:	learn: 1023.1496687	total: 2.6s	remaining: 1.17s
69:	learn: 1022.1345994	total: 2.81s	remaining: 1.21s
70:	learn: 1021.4308524	total: 2.88s	remaining: 1.17s
71:	learn: 1021.1815906	total: 2.93s	remaining: 1.14s
72:	learn: 1020.7183368	total: 2.97s	remaining: 1.1s
73:	learn: 1020.4273011	total: 3.07s	remaining: 1.08s
74:	learn: 1020.1586403	total: 3.14s	remaining: 1.05s
75:	learn: 1019.6222832	total: 3.15s	remaining: 994ms
76:	learn: 1019.0062431	total: 3.26s	remaining: 974ms
77:	learn: 1018.5475329	total: 3.35s	remaining: 947ms
78:	learn: 1018.1784115	total: 3.38s	remaining: 899ms
79:	learn: 1017.5184859	total: 3.4s	remaining: 849ms
80:	learn: 1016.9118762	total: 3.41s	remaining: 799ms
81:	learn: 1014.9980679	total: 3.42s	remaining: 752ms
82:	learn: 1014.1560266	total: 3.43s	remaining: 703ms
83:	learn: 1013.7247940	total: 3.45s	remaining: 658ms
84:	learn: 1013.3178271	total: 3.52s	remaining: 621ms
85:	learn: 1012.2224058	total: 3.56s	remaining: 580ms
86:	learn: 1011.9318389	total: 3.62s	remaining: 542ms
87:	learn: 1011.3626715	total: 3.68s	remaining: 502ms
88:	learn: 1010.7122507	total: 3.71s	remaining: 459ms
89:	learn: 1009.4641405	total: 3.82s	remaining: 425ms
90:	learn: 1009.0557683	total: 3.95s	remaining: 390ms
91:	learn: 1008.6986556	total: 4.02s	remaining: 350ms
92:	learn: 1007.8792433	total: 4.06s	remaining: 306ms
93:	learn: 1007.0971607	total: 4.16s	remaining: 265ms
94:	learn: 1006.8449709	total: 4.21s	remaining: 222ms
95:	learn: 1006.5889427	total: 4.25s	remaining: 177ms
96:	learn: 1006.3603193	total: 4.34s	remaining: 134ms
97:	learn: 1005.8981956	total: 4.39s	remaining: 89.5ms
98:	learn: 1005.0419303	total: 4.42s	remaining: 44.6ms
99:	learn: 1004.5931305	total: 4.47s	remaining: 0us
95:	learn: 1008.5965729	total: 4.72s	remaining: 197ms
96:	learn: 1008.2051347	total: 4.73s	remaining: 146ms
97:	learn: 1007.4244781	total: 4.74s	remaining: 96.7ms
98:	learn: 1007.1502306	total: 4.75s	remaining: 47.9ms
99:	learn: 1006.6934242	total: 4.79s	remaining: 0us
0:	learn: 1532.6413875	total: 86.5ms	remaining: 8.56s
1:	learn: 1400.5105448	total: 150ms	remaining: 7.36s
2:	learn: 1301.2366127	total: 233ms	remaining: 7.54s
3:	learn: 1234.7069632	total: 316ms	remaining: 7.58s
4:	learn: 1184.8305786	total: 362ms	remaining: 6.88s
5:	learn: 1148.7379037	total: 372ms	remaining: 5.83s
6:	learn: 1125.9400925	total: 505ms	remaining: 6.71s
7:	learn: 1105.7836950	total: 610ms	remaining: 7.02s
8:	learn: 1095.6609436	total: 698ms	remaining: 7.06s
9:	learn: 1087.5881205	total: 813ms	remaining: 7.32s
10:	learn: 1081.1832016	total: 836ms	remaining: 6.76s
11:	learn: 1073.7474382	total: 890ms	remaining: 6.53s
12:	learn: 1069.2510379	total: 934ms	remaining: 6.25s
13:	learn: 1065.5910111	total: 1.03s	remaining: 6.34s
14:	learn: 1064.1931739	total: 1.15s	remaining: 6.51s
15:	learn: 1063.4598527	total: 1.25s	remaining: 6.54s
16:	learn: 1061.1765677	total: 1.31s	remaining: 6.38s
17:	learn: 1060.1879304	total: 1.32s	remaining: 6.01s
18:	learn: 1059.1926427	total: 1.37s	remaining: 5.83s
19:	learn: 1058.0379321	total: 1.54s	remaining: 6.14s
20:	learn: 1056.6009309	total: 1.63s	remaining: 6.13s
21:	learn: 1055.9524980	total: 1.64s	remaining: 5.81s
22:	learn: 1055.1447377	total: 1.76s	remaining: 5.89s
23:	learn: 1053.3277275	total: 1.86s	remaining: 5.88s
24:	learn: 1052.0803030	total: 1.9s	remaining: 5.7s
25:	learn: 1050.2962086	total: 2s	remaining: 5.69s
26:	learn: 1048.7906555	total: 2.03s	remaining: 5.49s
27:	learn: 1047.9269868	total: 2.06s	remaining: 5.29s
28:	learn: 1046.4964584	total: 2.06s	remaining: 5.06s
29:	learn: 1045.4583057	total: 2.1s	remaining: 4.9s
30:	learn: 1044.5270088	total: 2.23s	remaining: 4.97s
31:	learn: 1044.0106419	total: 2.26s	remaining: 4.8s
32:	learn: 1043.3874547	total: 2.27s	remaining: 4.62s
33:	learn: 1042.4902206	total: 2.28s	remaining: 4.43s
34:	learn: 1042.3384238	total: 2.44s	remaining: 4.53s
35:	learn: 1041.8268560	total: 2.51s	remaining: 4.46s
36:	learn: 1040.8724038	total: 2.58s	remaining: 4.4s
37:	learn: 1039.6383635	total: 2.7s	remaining: 4.41s
38:	learn: 1039.1373669	total: 2.77s	remaining: 4.34s
39:	learn: 1038.4541268	total: 2.82s	remaining: 4.23s
40:	learn: 1037.0147993	total: 2.87s	remaining: 4.12s
41:	learn: 1036.5189720	total: 2.91s	remaining: 4.02s
42:	learn: 1035.3385644	total: 3s	remaining: 3.98s
43:	learn: 1034.5689716	total: 3.08s	remaining: 3.91s
44:	learn: 1033.8798448	total: 3.24s	remaining: 3.96s
45:	learn: 1033.4652764	total: 3.28s	remaining: 3.85s
46:	learn: 1032.5515275	total: 3.35s	remaining: 3.78s
47:	learn: 1031.9707036	total: 3.44s	remaining: 3.73s
48:	learn: 1031.1420648	total: 3.51s	remaining: 3.65s
49:	learn: 1030.1199429	total: 3.58s	remaining: 3.58s
50:	learn: 1028.9843077	total: 3.62s	remaining: 3.48s
51:	learn: 1027.2700548	total: 3.71s	remaining: 3.42s
52:	learn: 1026.2708799	total: 3.79s	remaining: 3.36s
53:	learn: 1025.6723573	total: 3.81s	remaining: 3.25s
54:	learn: 1025.1255577	total: 3.83s	remaining: 3.13s
55:	learn: 1024.2724749	total: 3.9s	remaining: 3.06s
56:	learn: 1023.4135850	total: 3.91s	remaining: 2.95s
57:	learn: 1022.6593005	total: 3.92s	remaining: 2.83s
58:	learn: 1022.1631737	total: 3.96s	remaining: 2.75s
59:	learn: 1021.5302098	total: 4s	remaining: 2.66s
60:	learn: 1021.0217023	total: 4.04s	remaining: 2.58s
61:	learn: 1020.2220173	total: 4.12s	remaining: 2.53s
62:	learn: 1019.7749605	total: 4.21s	remaining: 2.47s
63:	learn: 1019.2067006	total: 4.3s	remaining: 2.42s
64:	learn: 1018.8652057	total: 4.34s	remaining: 2.34s
65:	learn: 1018.3113048	total: 4.36s	remaining: 2.25s
66:	learn: 1017.9663220	total: 4.41s	remaining: 2.17s
67:	learn: 1017.1258117	total: 4.48s	remaining: 2.11s
68:	learn: 1016.6678751	total: 4.5s	remaining: 2.02s
69:	learn: 1015.8395695	total: 4.5s	remaining: 1.93s
70:	learn: 1015.3133826	total: 4.51s	remaining: 1.84s
71:	learn: 1014.6770877	total: 4.51s	remaining: 1.75s
72:	learn: 1014.0840215	total: 4.52s	remaining: 1.67s
73:	learn: 1013.7723104	total: 4.53s	remaining: 1.59s
74:	learn: 1012.8562482	total: 4.53s	remaining: 1.51s
75:	learn: 1012.0855087	total: 4.55s	remaining: 1.44s
76:	learn: 1011.3782622	total: 4.55s	remaining: 1.36s
77:	learn: 1010.4728319	total: 4.56s	remaining: 1.29s
78:	learn: 1010.1746794	total: 4.57s	remaining: 1.21s
79:	learn: 1009.1764690	total: 4.58s	remaining: 1.14s
80:	learn: 1008.3757652	total: 4.64s	remaining: 1.09s
81:	learn: 1007.9175347	total: 4.72s	remaining: 1.04s
82:	learn: 1007.4607580	total: 4.77s	remaining: 977ms
83:	learn: 1007.0042979	total: 4.81s	remaining: 916ms
84:	learn: 1006.5098715	total: 4.9s	remaining: 865ms
85:	learn: 1006.0862687	total: 4.95s	remaining: 806ms
86:	learn: 1005.0128134	total: 5.03s	remaining: 752ms
87:	learn: 1004.1372615	total: 5.06s	remaining: 690ms
88:	learn: 1003.1985090	total: 5.13s	remaining: 634ms
89:	learn: 1002.1930191	total: 5.17s	remaining: 575ms
90:	learn: 1001.3405222	total: 5.34s	remaining: 528ms
91:	learn: 1000.8715394	total: 5.4s	remaining: 469ms
92:	learn: 1000.3405568	total: 5.49s	remaining: 413ms
93:	learn: 999.8781634	total: 5.5s	remaining: 351ms
94:	learn: 999.0917559	total: 5.57s	remaining: 293ms
95:	learn: 998.8018906	total: 5.62s	remaining: 234ms
96:	learn: 998.2368871	total: 5.75s	remaining: 178ms
97:	learn: 997.6928028	total: 5.78s	remaining: 118ms
98:	learn: 996.5785136	total: 5.87s	remaining: 59.3ms
99:	learn: 995.6937992	total: 5.94s	remaining: 0us
0:	learn: 1530.5488104	total: 33.9ms	remaining: 3.35s
1:	learn: 1393.7179700	total: 54.6ms	remaining: 2.67s
2:	learn: 1315.1328656	total: 94.6ms	remaining: 3.06s
3:	learn: 1244.8432064	total: 143ms	remaining: 3.44s
4:	learn: 1193.8964314	total: 221ms	remaining: 4.2s
5:	learn: 1157.8691816	total: 271ms	remaining: 4.25s
6:	learn: 1134.1743898	total: 320ms	remaining: 4.25s
7:	learn: 1113.3625155	total: 390ms	remaining: 4.48s
8:	learn: 1099.9284666	total: 527ms	remaining: 5.33s
9:	learn: 1092.8064677	total: 604ms	remaining: 5.44s
10:	learn: 1085.6029056	total: 682ms	remaining: 5.52s
11:	learn: 1079.5908899	total: 745ms	remaining: 5.46s
12:	learn: 1075.6884662	total: 804ms	remaining: 5.38s
13:	learn: 1071.8630757	total: 845ms	remaining: 5.19s
14:	learn: 1068.5445572	total: 897ms	remaining: 5.08s
15:	learn: 1065.9471581	total: 994ms	remaining: 5.22s
16:	learn: 1065.1119001	total: 1.02s	remaining: 4.98s
17:	learn: 1063.4384441	total: 1.14s	remaining: 5.21s
18:	learn: 1060.0036451	total: 1.23s	remaining: 5.25s
19:	learn: 1057.1183785	total: 1.26s	remaining: 5.05s
20:	learn: 1056.4770761	total: 1.27s	remaining: 4.77s
21:	learn: 1055.4425727	total: 1.27s	remaining: 4.52s
22:	learn: 1053.5259034	total: 1.28s	remaining: 4.29s
23:	learn: 1053.1062300	total: 1.29s	remaining: 4.08s
24:	learn: 1052.5889623	total: 1.3s	remaining: 3.91s
25:	learn: 1051.4611698	total: 1.31s	remaining: 3.73s
26:	learn: 1050.2720929	total: 1.33s	remaining: 3.59s
27:	learn: 1048.8902613	total: 1.35s	remaining: 3.47s
28:	learn: 1048.3995436	total: 1.36s	remaining: 3.34s
29:	learn: 1047.5981089	total: 1.41s	remaining: 3.28s
30:	learn: 1046.6307122	total: 1.44s	remaining: 3.21s
31:	learn: 1045.4576049	total: 1.48s	remaining: 3.15s
32:	learn: 1044.7302773	total: 1.49s	remaining: 3.03s
33:	learn: 1044.4414160	total: 1.59s	remaining: 3.09s
34:	learn: 1043.8808633	total: 1.64s	remaining: 3.05s
35:	learn: 1042.8452394	total: 1.71s	remaining: 3.04s
36:	learn: 1041.6695353	total: 1.84s	remaining: 3.13s
37:	learn: 1041.0752648	total: 1.86s	remaining: 3.04s
38:	learn: 1040.5947462	total: 1.94s	remaining: 3.04s
39:	learn: 1039.5855782	total: 2.02s	remaining: 3.02s
40:	learn: 1039.2031735	total: 2.12s	remaining: 3.05s
41:	learn: 1038.8191436	total: 2.21s	remaining: 3.06s
42:	learn: 1038.2178587	total: 2.23s	remaining: 2.96s
43:	learn: 1037.4793110	total: 2.28s	remaining: 2.9s
44:	learn: 1036.8772131	total: 2.38s	remaining: 2.91s
45:	learn: 1035.9969509	total: 2.41s	remaining: 2.83s
46:	learn: 1035.0035395	total: 2.46s	remaining: 2.78s

47:	learn: 1033.9250333	total: 2.5s	remaining: 2.71s
48:	learn: 1033.3689911	total: 2.6s	remaining: 2.71s
49:	learn: 1032.5722174	total: 2.65s	remaining: 2.65s
50:	learn: 1031.8271252	total: 2.66s	remaining: 2.56s
51:	learn: 1030.8706885	total: 2.68s	remaining: 2.47s
52:	learn: 1030.1672070	total: 2.69s	remaining: 2.39s
53:	learn: 1029.6995209	total: 2.7s	remaining: 2.3s
54:	learn: 1028.4709647	total: 2.72s	remaining: 2.22s
55:	learn: 1027.7264779	total: 2.73s	remaining: 2.14s
56:	learn: 1027.0510484	total: 2.8s	remaining: 2.11s
57:	learn: 1026.1535495	total: 2.82s	remaining: 2.04s
58:	learn: 1025.4407464	total: 2.89s	remaining: 2.01s
59:	learn: 1025.0176795	total: 2.91s	remaining: 1.94s
60:	learn: 1024.4125734	total: 2.92s	remaining: 1.86s
61:	learn: 1024.0513209	total: 2.92s	remaining: 1.79s
62:	learn: 1023.5125339	total: 2.93s	remaining: 1.72s
63:	learn: 1022.9021218	total: 2.94s	remaining: 1.65s
64:	learn: 1022.5586916	total: 2.99s	remaining: 1.61s
65:	learn: 1021.8178034	total: 2.99s	remaining: 1.54s
66:	learn: 1020.9597366	total: 3.01s	remaining: 1.48s
67:	learn: 1020.6616765	total: 3.04s	remaining: 1.43s
68:	learn: 1019.8926471	total: 3.19s	remaining: 1.43s
69:	learn: 1019.1781056	total: 3.27s	remaining: 1.4s
70:	learn: 1018.5664342	total: 3.44s	remaining: 1.4s
71:	learn: 1017.5368997	total: 3.52s	remaining: 1.37s
72:	learn: 1016.5125798	total: 3.55s	remaining: 1.31s
73:	learn: 1015.2697851	total: 3.56s	remaining: 1.25s
74:	learn: 1014.2866206	total: 3.57s	remaining: 1.19s
75:	learn: 1013.4483862	total: 3.58s	remaining: 1.13s
76:	learn: 1012.8100587	total: 3.58s	remaining: 1.07s
77:	learn: 1012.5205884	total: 3.59s	remaining: 1.01s
78:	learn: 1011.5715843	total: 3.6s	remaining: 956ms
79:	learn: 1010.9869124	total: 3.63s	remaining: 908ms
80:	learn: 1010.3360958	total: 3.64s	remaining: 855ms
81:	learn: 1009.5153139	total: 3.66s	remaining: 804ms
82:	learn: 1008.7885386	total: 3.69s	remaining: 756ms
83:	learn: 1008.0393876	total: 3.72s	remaining: 709ms
84:	learn: 1006.9924089	total: 3.77s	remaining: 665ms
85:	learn: 1006.6291903	total: 3.85s	remaining: 626ms
86:	learn: 1005.9775101	total: 3.9s	remaining: 583ms
87:	learn: 1005.4756543	total: 3.98s	remaining: 542ms
88:	learn: 1004.6749011	total: 3.99s	remaining: 493ms
89:	learn: 1004.2210398	total: 3.99s	remaining: 444ms
90:	learn: 1003.7239778	total: 4.05s	remaining: 401ms
91:	learn: 1003.4706379	total: 4.07s	remaining: 354ms
92:	learn: 1003.2046706	total: 4.18s	remaining: 315ms
93:	learn: 1002.2824434	total: 4.23s	remaining: 270ms
94:	learn: 1001.5372505	total: 4.3s	remaining: 226ms
95:	learn: 1001.0073596	total: 4.37s	remaining: 182ms
96:	learn: 1000.2681994	total: 4.41s	remaining: 136ms
97:	learn: 999.4980737	total: 4.49s	remaining: 91.6ms
98:	learn: 998.9738064	total: 4.6s	remaining: 46.4ms
99:	learn: 998.1295723	total: 4.68s	remaining: 0us
0:	learn: 1523.9581740	total: 236ms	remaining: 23.4s
1:	learn: 1386.5778514	total: 426ms	remaining: 20.9s
2:	learn: 1307.3557000	total: 431ms	remaining: 13.9s
3:	learn: 1238.5778130	total: 670ms	remaining: 16.1s
4:	learn: 1187.8452403	total: 799ms	remaining: 15.2s
5:	learn: 1153.0428728	total: 926ms	remaining: 14.5s
6:	learn: 1128.9544637	total: 1.32s	remaining: 17.6s
7:	learn: 1108.9210946	total: 1.41s	remaining: 16.2s
8:	learn: 1094.6250343	total: 1.69s	remaining: 17.1s
9:	learn: 1088.4458095	total: 1.91s	remaining: 17.2s
10:	learn: 1081.3920037	total: 2.03s	remaining: 16.4s
11:	learn: 1076.1284833	total: 2.15s	remaining: 15.7s
12:	learn: 1072.1241077	total: 2.23s	remaining: 15s
13:	learn: 1068.6907261	total: 2.42s	remaining: 14.9s
14:	learn: 1066.2581068	total: 2.66s	remaining: 15.1s
15:	learn: 1063.6322008	total: 2.88s	remaining: 15.1s
16:	learn: 1062.6980355	total: 3.15s	remaining: 15.4s
17:	learn: 1061.2084424	total: 3.42s	remaining: 15.6s
18:	learn: 1058.4736623	total: 3.64s	remaining: 15.5s
19:	learn: 1056.7000252	total: 3.71s	remaining: 14.8s
20:	learn: 1055.8857280	total: 3.93s	remaining: 14.8s
21:	learn: 1055.0617147	total: 4.21s	remaining: 14.9s
22:	learn: 1053.4623026	total: 4.48s	remaining: 15s
23:	learn: 1052.8569264	total: 4.65s	remaining: 14.7s
24:	learn: 1052.0695430	total: 4.97s	remaining: 14.9s
25:	learn: 1051.1275164	total: 5.16s	remaining: 14.7s
26:	learn: 1050.0573676	total: 5.31s	remaining: 14.4s
27:	learn: 1049.6717846	total: 5.33s	remaining: 13.7s
28:	learn: 1048.9300431	total: 5.35s	remaining: 13.1s
29:	learn: 1048.1168275	total: 5.46s	remaining: 12.7s
30:	learn: 1047.6655301	total: 5.54s	remaining: 12.3s
31:	learn: 1046.1247359	total: 5.7s	remaining: 12.1s
32:	learn: 1045.5238165	total: 5.76s	remaining: 11.7s
33:	learn: 1045.1075714	total: 5.97s	remaining: 11.6s
34:	learn: 1044.4965906	total: 6.1s	remaining: 11.3s
35:	learn: 1042.6607031	total: 6.28s	remaining: 11.2s
36:	learn: 1040.5070814	total: 6.49s	remaining: 11s
37:	learn: 1039.7230681	total: 6.57s	remaining: 10.7s
38:	learn: 1039.1665933	total: 6.62s	remaining: 10.3s
39:	learn: 1038.1464825	total: 6.89s	remaining: 10.3s
40:	learn: 1037.6145379	total: 6.98s	remaining: 10s
41:	learn: 1036.6992978	total: 6.99s	remaining: 9.66s
42:	learn: 1036.0922335	total: 7.01s	remaining: 9.29s
43:	learn: 1035.2880771	total: 7.13s	remaining: 9.08s
44:	learn: 1034.4691046	total: 7.31s	remaining: 8.94s
45:	learn: 1033.5713464	total: 7.44s	remaining: 8.73s
46:	learn: 1032.8620467	total: 7.53s	remaining: 8.49s
47:	learn: 1032.2906804	total: 7.61s	remaining: 8.24s
48:	learn: 1031.7700753	total: 7.72s	remaining: 8.04s
49:	learn: 1030.9146939	total: 7.96s	remaining: 7.96s
50:	learn: 1030.2967911	total: 8.14s	remaining: 7.82s
51:	learn: 1029.4387469	total: 8.42s	remaining: 7.77s
52:	learn: 1028.4953837	total: 8.59s	remaining: 7.61s
53:	learn: 1027.6647925	total: 8.72s	remaining: 7.43s
54:	learn: 1027.1308118	total: 8.81s	remaining: 7.21s
55:	learn: 1026.3913806	total: 8.94s	remaining: 7.03s
56:	learn: 1025.6217939	total: 9.16s	remaining: 6.91s
57:	learn: 1025.0298943	total: 9.36s	remaining: 6.78s
58:	learn: 1024.1328731	total: 9.52s	remaining: 6.62s
59:	learn: 1023.7039069	total: 9.66s	remaining: 6.44s
60:	learn: 1022.5621168	total: 9.91s	remaining: 6.34s
61:	learn: 1021.4801586	total: 10.1s	remaining: 6.16s
62:	learn: 1021.1251895	total: 10.2s	remaining: 5.99s
63:	learn: 1020.4570207	total: 10.3s	remaining: 5.79s
64:	learn: 1019.8942956	total: 10.5s	remaining: 5.66s
65:	learn: 1019.2845794	total: 10.7s	remaining: 5.5s
66:	learn: 1018.2603445	total: 10.8s	remaining: 5.33s
67:	learn: 1017.8556168	total: 11s	remaining: 5.16s
68:	learn: 1017.1543470	total: 11.3s	remaining: 5.09s
69:	learn: 1016.5809774	total: 11.5s	remaining: 4.94s
70:	learn: 1015.9857944	total: 11.7s	remaining: 4.77s
71:	learn: 1015.2593633	total: 11.9s	remaining: 4.63s
72:	learn: 1014.7670737	total: 12.1s	remaining: 4.48s
73:	learn: 1014.2899193	total: 12.3s	remaining: 4.32s
74:	learn: 1013.5748700	total: 12.4s	remaining: 4.14s
75:	learn: 1013.2096081	total: 12.7s	remaining: 4.02s
76:	learn: 1012.8556297	total: 12.8s	remaining: 3.83s
77:	learn: 1012.4237098	total: 13.1s	remaining: 3.68s
78:	learn: 1011.9026540	total: 13.2s	remaining: 3.5s
79:	learn: 1011.5928348	total: 13.3s	remaining: 3.32s
80:	learn: 1011.1369903	total: 13.4s	remaining: 3.15s
81:	learn: 1010.8334356	total: 13.7s	remaining: 3.01s
82:	learn: 1010.5841105	total: 13.9s	remaining: 2.84s
83:	learn: 1009.5222446	total: 14s	remaining: 2.67s
84:	learn: 1008.6309859	total: 14.1s	remaining: 2.49s
85:	learn: 1007.8248219	total: 14.3s	remaining: 2.33s
86:	learn: 1007.5829327	total: 14.4s	remaining: 2.16s
87:	learn: 1006.5767938	total: 14.7s	remaining: 2s
88:	learn: 1005.7281177	total: 14.8s	remaining: 1.83s
89:	learn: 1005.3333325	total: 15s	remaining: 1.66s
90:	learn: 1004.7247450	total: 15.1s	remaining: 1.49s
91:	learn: 1003.9171307	total: 15.3s	remaining: 1.33s
92:	learn: 1003.0928022	total: 15.4s	remaining: 1.16s
93:	learn: 1001.9860131	total: 15.6s	remaining: 993ms
94:	learn: 1001.3375690	total: 15.8s	remaining: 829ms
95:	learn: 1001.0391087	total: 15.9s	remaining: 662ms
96:	learn: 1000.6982958	total: 16.1s	remaining: 498ms
97:	learn: 1000.0761840	total: 16.2s	remaining: 331ms
98:	learn: 999.4554860	total: 16.4s	remaining: 165ms

KeyboardInterrupt:

In [ ]:
gcv.best_score_,gcv.best_params_

In [11]:
test

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type
0,FDW58,20.750,Low Fat,0.007565,Snack Foods,107.8622,OUT049,1999,Medium,Tier 1,Supermarket Type1
1,FDW14,8.300,reg,0.038428,Dairy,87.3198,OUT017,2007,NaN,Tier 2,Supermarket Type1
2,NCN55,14.600,Low Fat,0.099575,Others,241.7538,OUT010,1998,NaN,Tier 3,Grocery Store
3,FDQ58,7.315,Low Fat,0.015388,Snack Foods,155.0340,OUT017,2007,NaN,Tier 2,Supermarket Type1
4,FDY38,NaN,Regular,0.118599,Dairy,234.2300,OUT027,1985,Medium,Tier 3,Supermarket Type3
...,...,...,...,...,...,...,...,...,...,...,...
5676,FDB58,10.500,Regular,0.013496,Snack Foods,141.3154,OUT046,1997,Small,Tier 1,Supermarket Type1
5677,FDD47,7.600,Regular,0.142991,Starchy Foods,169.1448,OUT018,2009,Medium,Tier 3,Supermarket Type2
5678,NCO17,10.000,Low Fat,0.073529,Health and Hygiene,118.7440,OUT045,2002,NaN,Tier 2,Supermarket Type1
5679,FDJ26,15.300,Regular,0.000000,Canned,214.6218,OUT017,2007,NaN,Tier 2,Supermarket Type1
5680,FDU37,9.500,Regular,0.104720,Canned,79.7960,OUT045,2002,NaN,Tier 2,Supermarket Type1

In [12]:
bm = gcv.best_estimator_
y_pred = bm.predict(test)
y_pred

array([1648.2816, 1438.0696,  679.7606, ..., 1929.1388, 3639.1345,
       1291.0635], dtype=float32)

In [15]:
submission = pd.read_csv("sample_submission_8RXa3c6.csv")
submission["Item_Outlet_Sales"] = y_pred

In [16]:
submission.to_csv("AnalyticsVidhyaSubmission.csv", index = False)