In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.cluster.hierarchy import linkage,dendrogram
from sklearn.preprocessing import StandardScaler
import warnings
from sklearn.cluster import AgglomerativeClustering, KMeans
from sklearn.decomposition import PCA
from sklearn.metrics import silhouette_score
from tqdm import tqdm
import os
os.chdir("/home/pgcp-ai/MachineLearning/Cases/Recency Frequency Monetary/")

In [2]:
rfm = pd.read_csv('rfm_data_customer.csv', index_col = 0)
rfm

             revenue most_recent_visit  number_of_orders  recency_days
customer_id
22086            777        2006-05-14                 9           232
2290            1555        2006-09-08                16           115
26377            336        2006-11-19                 5            43
24650           1189        2006-10-29                12            64
12883           1229        2006-12-09                12            23
...              ...               ...               ...           ...
3249             998        2006-12-01                10            31
6686             771        2006-06-28                 8           187
16418           1016        2006-07-31                 9           154
9117             678        2006-06-20                 7           195
19184           1519        2006-09-10                13           113

[39999 rows x 4 columns]

In [3]:
X = rfm[["recency_days", "number_of_orders", "revenue"]]
X

             recency_days  number_of_orders  revenue
customer_id
22086                 232                 9      777
2290                  115                16     1555
26377                  43                 5      336
24650                  64                12     1189
12883                  23                12     1229
...                   ...               ...      ...
3249                   31                10      998
6686                  187                 8      771
16418                 154                 9     1016
9117                  195                 7      678
19184                 113                13     1519

[39999 rows x 3 columns]

In [4]:
X.isna().sum()

recency_days        0
number_of_orders    0
revenue             0
dtype: int64

In [5]:
ss = StandardScaler().set_output(transform='pandas')
X_scaled = ss.fit_transform(X)

In [6]:
# link='average'
# mergings = linkage(X_scaled,method=link)
# dendrogram(mergings,labels=list(X_scaled.index))
# plt.title(link+" Linkage")
# plt.show()

In [7]:
# scores = []
# no_of_clusters = np.arange(2,7)
# for n in no_of_clusters:
#     agg = AgglomerativeClustering(n_clusters=n)
#     agg.fit(X_scaled)
#     score = silhouette_score(X_scaled,agg.labels_)
#     scores.append([n,score])
# df_scores = pd.DataFrame(scores,columns=['No. of Clusters','Silhouette Score'])    
# df_scores.sort_values('Silhouette Score',ascending=False)

In [8]:
scores = []
no_of_clusters = [2,3,4,5,6]

for n in no_of_clusters:
    clust = KMeans(n_clusters = n, random_state = 26)
    clust.fit(X_scaled)
    score = silhouette_score(X_scaled, clust.labels_)
    scores.append([n, score])
    
df_scores = pd.DataFrame(scores, columns = ["Number of Clusters", "Silhouette Score"])
df_scores.sort_values('Silhouette Score', ascending = False)

/home/pgcp-ai/.local/lib/python3.8/site-packages/sklearn/cluster/_kmeans.py:1416: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)
/home/pgcp-ai/.local/lib/python3.8/site-packages/sklearn/cluster/_kmeans.py:1416: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)
/home/pgcp-ai/.local/lib/python3.8/site-packages/sklearn/cluster/_kmeans.py:1416: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)
/home/pgcp-ai/.local/lib/python3.8/site-packages/sklearn/cluster/_kmeans.py:1416: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)
/home/pgcp-ai/.local/lib/python3.8/site-packages/sklearn/cluster/_kmeans.py:1416: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)

   Number of Clusters  Silhouette Score
1                   3          0.370478
0                   2          0.361901
3                   5          0.325342
2                   4          0.322711
4                   6          0.288967

In [12]:
df = X.copy()
km = KMeans(n_clusters = 3, random_state = 26)
km.fit(X_scaled)
df['Cluster'] = km.labels_
df.groupby('Cluster').mean()

/home/pgcp-ai/.local/lib/python3.8/site-packages/sklearn/cluster/_kmeans.py:1416: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)

         recency_days  number_of_orders      revenue
Cluster
0          135.581563          8.260367   752.807239
1          415.074989          7.344709   691.559946
2          133.264177         12.941800  1284.899355