In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler, OneHotEncoder, LabelEncoder
from sklearn.compose import ColumnTransformer, make_column_selector
from xgboost import XGBClassifier
from catboost import CatBoostClassifier
from lightgbm import LGBMClassifier
from sklearn.pipeline import Pipeline
from sklearn.decomposition import PCA
from sklearn.model_selection import StratifiedKFold,GridSearchCV
from sklearn.ensemble import BaggingRegressor,RandomForestRegressor
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression, ElasticNet
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import r2_score, accuracy_score, log_loss
import warnings
from tqdm import tqdm
import os
os.chdir('/home/pgcp-ai/MachineLearning/Datasets/IrrigationNeed/')

/home/pgcp-ai/.local/lib/python3.8/site-packages/xgboost/core.py:265: FutureWarning: Your system has an old version of glibc (< 2.28). We will stop supporting Linux distros with glibc older than 2.28 after **May 31, 2025**. Please upgrade to a recent Linux distro (with glibc 2.28+) to use future versions of XGBoost.
Note: You have installed the 'manylinux2014' variant of XGBoost. Certain features such as GPU algorithms or federated learning are not available. To use these features, please upgrade to a recent Linux distro with glibc 2.28+, and install the 'manylinux_2_28' variant.
  warnings.warn(

In [2]:
irrigation_data = pd.read_csv("train.csv", index_col = 0)
irrigation_data

,Soil_Type,Soil_pH,Soil_Moisture,Organic_Carbon,Electrical_Conductivity,Temperature_C,Humidity,Rainfall_mm,Sunlight_Hours,Wind_Speed_kmh,Crop_Type,Crop_Growth_Stage,Season,Irrigation_Type,Water_Source,Field_Area_hectare,Mulching_Used,Previous_Irrigation_mm,Region,Irrigation_Need
id,,,,,,,,,,,,,,,,,,,,
0,Loamy,4.92,32.58,1.01,3.05,15.01,50.61,725.99,5.90,16.79,Sugarcane,Sowing,Zaid,Drip,Rainwater,0.82,No,112.16,East,Low
1,Clay,7.08,56.61,0.44,2.00,22.92,67.86,985.66,6.98,3.39,Wheat,Vegetative,Kharif,Rainfed,River,5.27,Yes,47.16,South,Low
2,Clay,5.69,27.71,0.81,2.83,26.97,92.22,2201.70,6.05,3.85,Rice,Vegetative,Kharif,Sprinkler,Reservoir,8.24,Yes,110.38,North,Low
3,Sandy,5.65,13.32,1.33,0.87,13.32,61.57,1357.33,9.12,2.31,Wheat,Flowering,Kharif,Canal,River,8.32,Yes,53.85,South,Medium
4,Clay,7.96,59.14,0.38,0.96,20.22,91.11,1538.20,6.95,13.94,Wheat,Sowing,Rabi,Canal,River,7.37,No,93.19,South,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
629995,Clay,6.54,13.45,1.15,1.86,26.65,26.86,1041.33,10.62,18.85,Rice,Sowing,Kharif,Sprinkler,River,4.35,No,118.36,South,Medium
629996,Clay,7.03,54.49,0.96,2.35,36.99,88.00,1419.57,9.93,17.99,Sugarcane,Vegetative,Kharif,Drip,Groundwater,12.97,Yes,40.75,Central,Medium
629997,Clay,6.52,11.98,0.93,0.38,37.82,70.98,88.45,8.19,17.25,Potato,Vegetative,Zaid,Canal,Reservoir,13.58,Yes,2.62,South,High
629998,Clay,5.93,42.86,0.33,3.39,34.99,94.58,2433.92,9.88,5.00,Sugarcane,Vegetative,Zaid,Sprinkler,Groundwater,0.79,Yes,90.00,East,Low
629999,Loamy,7.02,35.36,1.19,0.46,26.92,64.33,1269.55,7.91,2.72,Maize,Harvest,Kharif,Drip,Reservoir,3.80,No,112.93,West,Low

In [3]:
ohe = OneHotEncoder(sparse_output=False, drop='first', handle_unknown='ignore')
transformer = ColumnTransformer(transformers=[('ohe', ohe, make_column_selector(dtype_include=object))], remainder='passthrough', verbose_feature_names_out=False).set_output(transform = 'pandas')

In [4]:
irrigation_data.isna().sum().sum()

0

In [5]:
X,y = irrigation_data.drop('Irrigation_Need',axis=1), irrigation_data['Irrigation_Need']

In [6]:
le = LabelEncoder()
ss = StandardScaler()
xgb = XGBClassifier(random_state=26)
pca = PCA()
y = le.fit_transform(y)

In [7]:
pipe = Pipeline([('OHE',transformer),('SS',ss),('PCA',pca),('XGB',xgb)])
# pipe.get_params()

In [8]:
params = {"XGB__max_depth" : [2, 3, 4, 5], "XGB__learning_rate" : np.linspace(0.05, 0.7, 5), "XGB__n_estimators" : [10, 25,50,75]}
folds = StratifiedKFold(n_splits = 5, shuffle = True, random_state = 26)

gcv = GridSearchCV(estimator = pipe, cv = folds, param_grid = params, n_jobs = -1, verbose = 3, scoring='balanced_accuracy')
gcv.fit(X, y)

Fitting 5 folds for each of 80 candidates, totalling 400 fits

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=26, shuffle=True),
             estimator=Pipeline(steps=[('OHE',
                                        ColumnTransformer(remainder='passthrough',
                                                          transformers=[('ohe',
                                                                         OneHotEncoder(drop='first',
                                                                                       handle_unknown='ignore',
                                                                                       sparse_output=False),
                                                                         <sklearn.compose._column_transformer.make_column_selector object at 0x7ffa9442aac0>)],
                                                          verbose_feature_names_out=...
                                                      max_leaves=None,
                                                      min_child_weight=None,
                                                      missing=nan,
                                                      monotone_constraints=None,
                                                      multi_strategy=None,
                                                      n_estimators=None,
                                                      n_jobs=None,
                                                      num_parallel_tree=None,
                                                      random_state=26, ...))]),
             n_jobs=-1,
             param_grid={'XGB__learning_rate': array([0.05  , 0.2125, 0.375 , 0.5375, 0.7   ]),
                         'XGB__max_depth': [2, 3, 4, 5],
                         'XGB__n_estimators': [10, 25, 50, 75]},
             scoring='balanced_accuracy', verbose=3)

In [11]:
gcv.best_estimator_, gcv.best_score_

(Pipeline(steps=[('OHE',
                  ColumnTransformer(remainder='passthrough',
                                    transformers=[('ohe',
                                                   OneHotEncoder(drop='first',
                                                                 handle_unknown='ignore',
                                                                 sparse_output=False),
                                                   <sklearn.compose._column_transformer.make_column_selector object at 0x7ffafb919b50>)],
                                    verbose_feature_names_out=False)),
                 ('SS', StandardScaler()), ('PCA', PCA()),
                 ('XGB',
                  XGBClassifier(base_score=None,...
                                feature_types=None, gamma=None, grow_policy=None,
                                importance_type=None,
                                interaction_constraints=None, learning_rate=0.7,
                                max_bin=None, max_cat_threshold=None,
                                max_cat_to_onehot=None, max_delta_step=None,
                                max_depth=5, max_leaves=None,
                                min_child_weight=None, missing=nan,
                                monotone_constraints=None, multi_strategy=None,
                                n_estimators=75, n_jobs=None,
                                num_parallel_tree=None,
                                objective='multi:softprob', ...))]),
 0.8415240547393253)

[CV 1/5] END XGB__learning_rate=0.05, XGB__max_depth=2, XGB__n_estimators=75;, score=0.556 total time=  38.7s
[CV 2/5] END XGB__learning_rate=0.05, XGB__max_depth=3, XGB__n_estimators=75;, score=0.594 total time=  43.7s
[CV 4/5] END XGB__learning_rate=0.05, XGB__max_depth=4, XGB__n_estimators=75;, score=0.635 total time=  47.1s
[CV 5/5] END XGB__learning_rate=0.05, XGB__max_depth=5, XGB__n_estimators=75;, score=0.667 total time=  54.7s
[CV 1/5] END XGB__learning_rate=0.21249999999999997, XGB__max_depth=3, XGB__n_estimators=50;, score=0.673 total time=  32.9s
[CV 2/5] END XGB__learning_rate=0.21249999999999997, XGB__max_depth=4, XGB__n_estimators=25;, score=0.653 total time=  24.4s
[CV 1/5] END XGB__learning_rate=0.21249999999999997, XGB__max_depth=5, XGB__n_estimators=10;, score=0.641 total time=  19.5s
[CV 2/5] END XGB__learning_rate=0.21249999999999997, XGB__max_depth=5, XGB__n_estimators=25;, score=0.686 total time=  26.5s
[CV 2/5] END XGB__learning_rate=0.37499999999999994, XGB__max_depth=2, XGB__n_estimators=10;, score=0.557 total time=  16.3s
[CV 3/5] END XGB__learning_rate=0.37499999999999994, XGB__max_depth=2, XGB__n_estimators=25;, score=0.622 total time=  23.1s
[CV 1/5] END XGB__learning_rate=0.37499999999999994, XGB__max_depth=3, XGB__n_estimators=10;, score=0.599 total time=  18.0s
[CV 3/5] END XGB__learning_rate=0.37499999999999994, XGB__max_depth=3, XGB__n_estimators=50;, score=0.725 total time=  32.1s
[CV 4/5] END XGB__learning_rate=0.37499999999999994, XGB__max_depth=4, XGB__n_estimators=25;, score=0.704 total time=  25.2s
[CV 4/5] END XGB__learning_rate=0.37499999999999994, XGB__max_depth=5, XGB__n_estimators=10;, score=0.668 total time=  17.7s
[CV 4/5] END XGB__learning_rate=0.37499999999999994, XGB__max_depth=5, XGB__n_estimators=50;, score=0.794 total time=  39.5s
[CV 4/5] END XGB__learning_rate=0.5375, XGB__max_depth=2, XGB__n_estimators=50;, score=0.698 total time=  30.7s
[CV 4/5] END XGB__learning_rate=0.5375, XGB__max_depth=3, XGB__n_estimators=25;, score=0.690 total time=  22.6s
[CV 3/5] END XGB__learning_rate=0.5375, XGB__max_depth=4, XGB__n_estimators=10;, score=0.657 total time=  18.0s
[CV 3/5] END XGB__learning_rate=0.5375, XGB__max_depth=4, XGB__n_estimators=50;, score=0.788 total time=  37.0s
[CV 5/5] END XGB__learning_rate=0.5375, XGB__max_depth=5, XGB__n_estimators=25;, score=0.768 total time=  29.1s
[CV 1/5] END XGB__learning_rate=0.7, XGB__max_depth=2, XGB__n_estimators=25;, score=0.671 total time=  21.0s
[CV 2/5] END XGB__learning_rate=0.7, XGB__max_depth=2, XGB__n_estimators=75;, score=0.745 total time=  38.1s
[CV 2/5] END XGB__learning_rate=0.7, XGB__max_depth=3, XGB__n_estimators=75;, score=0.800 total time=  42.2s
[CV 4/5] END XGB__learning_rate=0.7, XGB__max_depth=4, XGB__n_estimators=75;, score=0.825 total time=  46.1s

/home/pgcp-ai/.local/lib/python3.8/site-packages/xgboost/core.py:265: FutureWarning: Your system has an old version of glibc (< 2.28). We will stop supporting Linux distros with glibc older than 2.28 after **May 31, 2025**. Please upgrade to a recent Linux distro (with glibc 2.28+) to use future versions of XGBoost.
Note: You have installed the 'manylinux2014' variant of XGBoost. Certain features such as GPU algorithms or federated learning are not available. To use these features, please upgrade to a recent Linux distro with glibc 2.28+, and install the 'manylinux_2_28' variant.
  warnings.warn(

[CV 4/5] END XGB__learning_rate=0.05, XGB__max_depth=2, XGB__n_estimators=25;, score=0.519 total time=  22.8s
[CV 4/5] END XGB__learning_rate=0.05, XGB__max_depth=3, XGB__n_estimators=10;, score=0.529 total time=  18.3s
[CV 5/5] END XGB__learning_rate=0.05, XGB__max_depth=3, XGB__n_estimators=50;, score=0.584 total time=  32.4s
[CV 4/5] END XGB__learning_rate=0.05, XGB__max_depth=4, XGB__n_estimators=50;, score=0.618 total time=  35.8s
[CV 5/5] END XGB__learning_rate=0.05, XGB__max_depth=5, XGB__n_estimators=25;, score=0.633 total time=  26.7s
[CV 4/5] END XGB__learning_rate=0.21249999999999997, XGB__max_depth=2, XGB__n_estimators=10;, score=0.538 total time=  16.6s
[CV 3/5] END XGB__learning_rate=0.21249999999999997, XGB__max_depth=2, XGB__n_estimators=50;, score=0.628 total time=  29.7s
[CV 5/5] END XGB__learning_rate=0.21249999999999997, XGB__max_depth=3, XGB__n_estimators=10;, score=0.574 total time=  18.5s
[CV 3/5] END XGB__learning_rate=0.21249999999999997, XGB__max_depth=3, XGB__n_estimators=75;, score=0.702 total time=  42.0s
[CV 5/5] END XGB__learning_rate=0.21249999999999997, XGB__max_depth=4, XGB__n_estimators=75;, score=0.749 total time=  49.2s
[CV 1/5] END XGB__learning_rate=0.37499999999999994, XGB__max_depth=2, XGB__n_estimators=25;, score=0.625 total time=  23.0s
[CV 2/5] END XGB__learning_rate=0.37499999999999994, XGB__max_depth=2, XGB__n_estimators=75;, score=0.704 total time=  37.0s
[CV 2/5] END XGB__learning_rate=0.37499999999999994, XGB__max_depth=3, XGB__n_estimators=75;, score=0.756 total time=  42.0s
[CV 4/5] END XGB__learning_rate=0.37499999999999994, XGB__max_depth=4, XGB__n_estimators=75;, score=0.797 total time=  48.5s
[CV 1/5] END XGB__learning_rate=0.5375, XGB__max_depth=2, XGB__n_estimators=10;, score=0.596 total time=  16.1s
[CV 3/5] END XGB__learning_rate=0.5375, XGB__max_depth=2, XGB__n_estimators=25;, score=0.651 total time=  21.8s
[CV 5/5] END XGB__learning_rate=0.5375, XGB__max_depth=2, XGB__n_estimators=75;, score=0.733 total time=  37.4s
[CV 1/5] END XGB__learning_rate=0.5375, XGB__max_depth=4, XGB__n_estimators=25;, score=0.746 total time=  26.0s
[CV 2/5] END XGB__learning_rate=0.5375, XGB__max_depth=4, XGB__n_estimators=75;, score=0.813 total time=  47.1s
[CV 4/5] END XGB__learning_rate=0.5375, XGB__max_depth=5, XGB__n_estimators=75;, score=0.834 total time=  52.2s
[CV 5/5] END XGB__learning_rate=0.7, XGB__max_depth=3, XGB__n_estimators=10;, score=0.650 total time=  17.9s
[CV 3/5] END XGB__learning_rate=0.7, XGB__max_depth=3, XGB__n_estimators=75;, score=0.802 total time=  42.8s
[CV 5/5] END XGB__learning_rate=0.7, XGB__max_depth=4, XGB__n_estimators=75;, score=0.829 total time=  46.1s

/home/pgcp-ai/.local/lib/python3.8/site-packages/xgboost/core.py:265: FutureWarning: Your system has an old version of glibc (< 2.28). We will stop supporting Linux distros with glibc older than 2.28 after **May 31, 2025**. Please upgrade to a recent Linux distro (with glibc 2.28+) to use future versions of XGBoost.
Note: You have installed the 'manylinux2014' variant of XGBoost. Certain features such as GPU algorithms or federated learning are not available. To use these features, please upgrade to a recent Linux distro with glibc 2.28+, and install the 'manylinux_2_28' variant.
  warnings.warn(

[CV 4/5] END XGB__learning_rate=0.05, XGB__max_depth=2, XGB__n_estimators=50;, score=0.538 total time=  29.6s
[CV 3/5] END XGB__learning_rate=0.05, XGB__max_depth=3, XGB__n_estimators=25;, score=0.563 total time=  23.9s
[CV 5/5] END XGB__learning_rate=0.05, XGB__max_depth=4, XGB__n_estimators=10;, score=0.569 total time=  19.1s
[CV 1/5] END XGB__learning_rate=0.05, XGB__max_depth=4, XGB__n_estimators=75;, score=0.632 total time=  49.1s
[CV 3/5] END XGB__learning_rate=0.05, XGB__max_depth=5, XGB__n_estimators=75;, score=0.661 total time=  56.8s
[CV 4/5] END XGB__learning_rate=0.21249999999999997, XGB__max_depth=3, XGB__n_estimators=10;, score=0.581 total time=  16.0s
[CV 1/5] END XGB__learning_rate=0.21249999999999997, XGB__max_depth=3, XGB__n_estimators=75;, score=0.710 total time=  42.1s
[CV 3/5] END XGB__learning_rate=0.21249999999999997, XGB__max_depth=4, XGB__n_estimators=75;, score=0.744 total time=  48.9s
[CV 5/5] END XGB__learning_rate=0.21249999999999997, XGB__max_depth=5, XGB__n_estimators=75;, score=0.784 total time=  55.4s
[CV 1/5] END XGB__learning_rate=0.37499999999999994, XGB__max_depth=3, XGB__n_estimators=50;, score=0.726 total time=  33.1s
[CV 2/5] END XGB__learning_rate=0.37499999999999994, XGB__max_depth=4, XGB__n_estimators=25;, score=0.702 total time=  24.8s
[CV 1/5] END XGB__learning_rate=0.37499999999999994, XGB__max_depth=5, XGB__n_estimators=10;, score=0.665 total time=  18.0s
[CV 4/5] END XGB__learning_rate=0.37499999999999994, XGB__max_depth=5, XGB__n_estimators=25;, score=0.736 total time=  27.8s
[CV 1/5] END XGB__learning_rate=0.5375, XGB__max_depth=2, XGB__n_estimators=25;, score=0.657 total time=  24.6s
[CV 2/5] END XGB__learning_rate=0.5375, XGB__max_depth=2, XGB__n_estimators=75;, score=0.728 total time=  37.9s
[CV 3/5] END XGB__learning_rate=0.5375, XGB__max_depth=3, XGB__n_estimators=75;, score=0.784 total time=  42.2s
[CV 5/5] END XGB__learning_rate=0.5375, XGB__max_depth=4, XGB__n_estimators=75;, score=0.815 total time=  47.0s
[CV 3/5] END XGB__learning_rate=0.7, XGB__max_depth=2, XGB__n_estimators=10;, score=0.603 total time=  16.3s
[CV 4/5] END XGB__learning_rate=0.7, XGB__max_depth=2, XGB__n_estimators=25;, score=0.676 total time=  23.0s
[CV 2/5] END XGB__learning_rate=0.7, XGB__max_depth=3, XGB__n_estimators=10;, score=0.644 total time=  18.0s
[CV 3/5] END XGB__learning_rate=0.7, XGB__max_depth=3, XGB__n_estimators=50;, score=0.779 total time=  32.2s
[CV 1/5] END XGB__learning_rate=0.7, XGB__max_depth=4, XGB__n_estimators=50;, score=0.808 total time=  37.1s
[CV 4/5] END XGB__learning_rate=0.7, XGB__max_depth=5, XGB__n_estimators=25;, score=0.788 total time=  25.8s

/home/pgcp-ai/.local/lib/python3.8/site-packages/xgboost/core.py:265: FutureWarning: Your system has an old version of glibc (< 2.28). We will stop supporting Linux distros with glibc older than 2.28 after **May 31, 2025**. Please upgrade to a recent Linux distro (with glibc 2.28+) to use future versions of XGBoost.
Note: You have installed the 'manylinux2014' variant of XGBoost. Certain features such as GPU algorithms or federated learning are not available. To use these features, please upgrade to a recent Linux distro with glibc 2.28+, and install the 'manylinux_2_28' variant.
  warnings.warn(
/home/pgcp-ai/.local/lib/python3.8/site-packages/xgboost/core.py:265: FutureWarning: Your system has an old version of glibc (< 2.28). We will stop supporting Linux distros with glibc older than 2.28 after **May 31, 2025**. Please upgrade to a recent Linux distro (with glibc 2.28+) to use future versions of XGBoost.
Note: You have installed the 'manylinux2014' variant of XGBoost. Certain features such as GPU algorithms or federated learning are not available. To use these features, please upgrade to a recent Linux distro with glibc 2.28+, and install the 'manylinux_2_28' variant.
  warnings.warn(
/home/pgcp-ai/.local/lib/python3.8/site-packages/xgboost/core.py:265: FutureWarning: Your system has an old version of glibc (< 2.28). We will stop supporting Linux distros with glibc older than 2.28 after **May 31, 2025**. Please upgrade to a recent Linux distro (with glibc 2.28+) to use future versions of XGBoost.
Note: You have installed the 'manylinux2014' variant of XGBoost. Certain features such as GPU algorithms or federated learning are not available. To use these features, please upgrade to a recent Linux distro with glibc 2.28+, and install the 'manylinux_2_28' variant.
  warnings.warn(

[CV 5/5] END XGB__learning_rate=0.05, XGB__max_depth=2, XGB__n_estimators=25;, score=0.508 total time=  23.8s
[CV 1/5] END XGB__learning_rate=0.05, XGB__max_depth=3, XGB__n_estimators=25;, score=0.557 total time=  23.3s
[CV 3/5] END XGB__learning_rate=0.05, XGB__max_depth=3, XGB__n_estimators=75;, score=0.595 total time=  44.4s
[CV 2/5] END XGB__learning_rate=0.05, XGB__max_depth=5, XGB__n_estimators=10;, score=0.620 total time=  19.5s
[CV 2/5] END XGB__learning_rate=0.05, XGB__max_depth=5, XGB__n_estimators=50;, score=0.646 total time=  40.3s
[CV 4/5] END XGB__learning_rate=0.21249999999999997, XGB__max_depth=2, XGB__n_estimators=25;, score=0.586 total time=  21.9s
[CV 1/5] END XGB__learning_rate=0.21249999999999997, XGB__max_depth=3, XGB__n_estimators=10;, score=0.574 total time=  17.7s
[CV 3/5] END XGB__learning_rate=0.21249999999999997, XGB__max_depth=3, XGB__n_estimators=50;, score=0.667 total time=  32.4s
[CV 4/5] END XGB__learning_rate=0.21249999999999997, XGB__max_depth=4, XGB__n_estimators=25;, score=0.652 total time=  24.5s
[CV 3/5] END XGB__learning_rate=0.21249999999999997, XGB__max_depth=5, XGB__n_estimators=10;, score=0.636 total time=  19.7s
[CV 5/5] END XGB__learning_rate=0.21249999999999997, XGB__max_depth=5, XGB__n_estimators=50;, score=0.749 total time=  40.6s
[CV 1/5] END XGB__learning_rate=0.37499999999999994, XGB__max_depth=2, XGB__n_estimators=75;, score=0.704 total time=  39.4s
[CV 5/5] END XGB__learning_rate=0.37499999999999994, XGB__max_depth=3, XGB__n_estimators=50;, score=0.727 total time=  31.8s
[CV 3/5] END XGB__learning_rate=0.37499999999999994, XGB__max_depth=4, XGB__n_estimators=50;, score=0.759 total time=  36.4s
[CV 1/5] END XGB__learning_rate=0.37499999999999994, XGB__max_depth=5, XGB__n_estimators=50;, score=0.796 total time=  40.2s
[CV 2/5] END XGB__learning_rate=0.5375, XGB__max_depth=2, XGB__n_estimators=25;, score=0.658 total time=  21.6s
[CV 4/5] END XGB__learning_rate=0.5375, XGB__max_depth=2, XGB__n_estimators=75;, score=0.729 total time=  37.6s
[CV 5/5] END XGB__learning_rate=0.5375, XGB__max_depth=4, XGB__n_estimators=10;, score=0.659 total time=  18.3s
[CV 1/5] END XGB__learning_rate=0.5375, XGB__max_depth=4, XGB__n_estimators=75;, score=0.817 total time=  49.0s
[CV 3/5] END XGB__learning_rate=0.5375, XGB__max_depth=5, XGB__n_estimators=75;, score=0.835 total time=  53.1s
[CV 4/5] END XGB__learning_rate=0.7, XGB__max_depth=3, XGB__n_estimators=10;, score=0.646 total time=  16.5s
[CV 5/5] END XGB__learning_rate=0.7, XGB__max_depth=3, XGB__n_estimators=50;, score=0.775 total time=  32.0s
[CV 2/5] END XGB__learning_rate=0.7, XGB__max_depth=4, XGB__n_estimators=50;, score=0.809 total time=  36.1s
[CV 2/5] END XGB__learning_rate=0.7, XGB__max_depth=5, XGB__n_estimators=25;, score=0.789 total time=  28.2s
[CV 2/5] END XGB__learning_rate=0.05, XGB__max_depth=2, XGB__n_estimators=50;, score=0.536 total time=  30.2s
[CV 5/5] END XGB__learning_rate=0.05, XGB__max_depth=3, XGB__n_estimators=25;, score=0.556 total time=  22.2s
[CV 4/5] END XGB__learning_rate=0.05, XGB__max_depth=4, XGB__n_estimators=10;, score=0.576 total time=  19.4s
[CV 5/5] END XGB__learning_rate=0.05, XGB__max_depth=4, XGB__n_estimators=50;, score=0.619 total time=  37.6s
[CV 3/5] END XGB__learning_rate=0.05, XGB__max_depth=5, XGB__n_estimators=50;, score=0.644 total time=  41.3s
[CV 4/5] END XGB__learning_rate=0.21249999999999997, XGB__max_depth=2, XGB__n_estimators=50;, score=0.628 total time=  29.5s
[CV 1/5] END XGB__learning_rate=0.21249999999999997, XGB__max_depth=3, XGB__n_estimators=25;, score=0.619 total time=  24.6s
[CV 1/5] END XGB__learning_rate=0.21249999999999997, XGB__max_depth=4, XGB__n_estimators=10;, score=0.610 total time=  19.4s
[CV 3/5] END XGB__learning_rate=0.21249999999999997, XGB__max_depth=4, XGB__n_estimators=50;, score=0.708 total time=  36.7s
[CV 4/5] END XGB__learning_rate=0.21249999999999997, XGB__max_depth=5, XGB__n_estimators=25;, score=0.687 total time=  26.7s
[CV 3/5] END XGB__learning_rate=0.37499999999999994, XGB__max_depth=2, XGB__n_estimators=10;, score=0.574 total time=  16.7s
[CV 3/5] END XGB__learning_rate=0.37499999999999994, XGB__max_depth=2, XGB__n_estimators=50;, score=0.673 total time=  30.6s
[CV 2/5] END XGB__learning_rate=0.37499999999999994, XGB__max_depth=3, XGB__n_estimators=25;, score=0.664 total time=  22.8s
[CV 1/5] END XGB__learning_rate=0.37499999999999994, XGB__max_depth=4, XGB__n_estimators=10;, score=0.633 total time=  17.1s
[CV 5/5] END XGB__learning_rate=0.37499999999999994, XGB__max_depth=4, XGB__n_estimators=25;, score=0.703 total time=  25.7s
[CV 1/5] END XGB__learning_rate=0.37499999999999994, XGB__max_depth=5, XGB__n_estimators=25;, score=0.745 total time=  28.7s
[CV 3/5] END XGB__learning_rate=0.37499999999999994, XGB__max_depth=5, XGB__n_estimators=75;, score=0.818 total time=  53.6s
[CV 5/5] END XGB__learning_rate=0.5375, XGB__max_depth=3, XGB__n_estimators=10;, score=0.631 total time=  16.6s
[CV 1/5] END XGB__learning_rate=0.5375, XGB__max_depth=3, XGB__n_estimators=75;, score=0.785 total time=  43.7s
[CV 4/5] END XGB__learning_rate=0.5375, XGB__max_depth=4, XGB__n_estimators=75;, score=0.814 total time=  47.7s
[CV 1/5] END XGB__learning_rate=0.7, XGB__max_depth=2, XGB__n_estimators=10;, score=0.603 total time=  16.2s
[CV 2/5] END XGB__learning_rate=0.7, XGB__max_depth=2, XGB__n_estimators=25;, score=0.667 total time=  21.7s
[CV 4/5] END XGB__learning_rate=0.7, XGB__max_depth=2, XGB__n_estimators=75;, score=0.746 total time=  37.2s
[CV 4/5] END XGB__learning_rate=0.7, XGB__max_depth=4, XGB__n_estimators=10;, score=0.678 total time=  17.0s
[CV 3/5] END XGB__learning_rate=0.7, XGB__max_depth=4, XGB__n_estimators=50;, score=0.810 total time=  36.1s
[CV 3/5] END XGB__learning_rate=0.7, XGB__max_depth=5, XGB__n_estimators=25;, score=0.782 total time=  28.0s
[CV 2/5] END XGB__learning_rate=0.05, XGB__max_depth=2, XGB__n_estimators=10;, score=0.514 total time=  15.8s
[CV 3/5] END XGB__learning_rate=0.05, XGB__max_depth=2, XGB__n_estimators=75;, score=0.554 total time=  38.4s
[CV 5/5] END XGB__learning_rate=0.05, XGB__max_depth=3, XGB__n_estimators=75;, score=0.601 total time=  43.0s
[CV 4/5] END XGB__learning_rate=0.05, XGB__max_depth=5, XGB__n_estimators=10;, score=0.605 total time=  21.0s
[CV 5/5] END XGB__learning_rate=0.05, XGB__max_depth=5, XGB__n_estimators=50;, score=0.651 total time=  40.1s
[CV 5/5] END XGB__learning_rate=0.21249999999999997, XGB__max_depth=2, XGB__n_estimators=50;, score=0.631 total time=  29.9s
[CV 5/5] END XGB__learning_rate=0.21249999999999997, XGB__max_depth=3, XGB__n_estimators=25;, score=0.624 total time=  24.7s
[CV 5/5] END XGB__learning_rate=0.21249999999999997, XGB__max_depth=4, XGB__n_estimators=10;, score=0.613 total time=  19.6s
[CV 1/5] END XGB__learning_rate=0.21249999999999997, XGB__max_depth=4, XGB__n_estimators=75;, score=0.751 total time=  48.8s
[CV 3/5] END XGB__learning_rate=0.21249999999999997, XGB__max_depth=5, XGB__n_estimators=75;, score=0.782 total time=  55.5s
[CV 4/5] END XGB__learning_rate=0.37499999999999994, XGB__max_depth=3, XGB__n_estimators=10;, score=0.605 total time=  16.9s
[CV 1/5] END XGB__learning_rate=0.37499999999999994, XGB__max_depth=3, XGB__n_estimators=75;, score=0.759 total time=  42.5s
[CV 3/5] END XGB__learning_rate=0.37499999999999994, XGB__max_depth=4, XGB__n_estimators=75;, score=0.789 total time=  48.1s
[CV 5/5] END XGB__learning_rate=0.37499999999999994, XGB__max_depth=5, XGB__n_estimators=75;, score=0.821 total time=  51.8s
[CV 2/5] END XGB__learning_rate=0.5375, XGB__max_depth=3, XGB__n_estimators=25;, score=0.695 total time=  22.3s
[CV 5/5] END XGB__learning_rate=0.5375, XGB__max_depth=3, XGB__n_estimators=75;, score=0.781 total time=  42.9s
[CV 4/5] END XGB__learning_rate=0.5375, XGB__max_depth=5, XGB__n_estimators=10;, score=0.687 total time=  18.6s
[CV 5/5] END XGB__learning_rate=0.5375, XGB__max_depth=5, XGB__n_estimators=50;, score=0.819 total time=  39.5s
[CV 1/5] END XGB__learning_rate=0.7, XGB__max_depth=2, XGB__n_estimators=75;, score=0.754 total time=  38.0s
[CV 4/5] END XGB__learning_rate=0.7, XGB__max_depth=3, XGB__n_estimators=50;, score=0.775 total time=  33.2s
[CV 5/5] END XGB__learning_rate=0.7, XGB__max_depth=4, XGB__n_estimators=50;, score=0.811 total time=  35.8s
[CV 5/5] END XGB__learning_rate=0.7, XGB__max_depth=5, XGB__n_estimators=25;, score=0.787 total time=  27.9s

/home/pgcp-ai/.local/lib/python3.8/site-packages/xgboost/core.py:265: FutureWarning: Your system has an old version of glibc (< 2.28). We will stop supporting Linux distros with glibc older than 2.28 after **May 31, 2025**. Please upgrade to a recent Linux distro (with glibc 2.28+) to use future versions of XGBoost.
Note: You have installed the 'manylinux2014' variant of XGBoost. Certain features such as GPU algorithms or federated learning are not available. To use these features, please upgrade to a recent Linux distro with glibc 2.28+, and install the 'manylinux_2_28' variant.
  warnings.warn(

[CV 4/5] END XGB__learning_rate=0.05, XGB__max_depth=2, XGB__n_estimators=10;, score=0.514 total time=  16.6s
[CV 5/5] END XGB__learning_rate=0.05, XGB__max_depth=2, XGB__n_estimators=75;, score=0.554 total time=  39.0s
[CV 2/5] END XGB__learning_rate=0.05, XGB__max_depth=4, XGB__n_estimators=10;, score=0.580 total time=  17.5s
[CV 2/5] END XGB__learning_rate=0.05, XGB__max_depth=4, XGB__n_estimators=50;, score=0.614 total time=  36.0s
[CV 2/5] END XGB__learning_rate=0.05, XGB__max_depth=5, XGB__n_estimators=25;, score=0.625 total time=  26.6s
[CV 1/5] END XGB__learning_rate=0.21249999999999997, XGB__max_depth=2, XGB__n_estimators=10;, score=0.530 total time=  16.2s
[CV 2/5] END XGB__learning_rate=0.21249999999999997, XGB__max_depth=2, XGB__n_estimators=25;, score=0.575 total time=  21.6s
[CV 4/5] END XGB__learning_rate=0.21249999999999997, XGB__max_depth=2, XGB__n_estimators=75;, score=0.659 total time=  38.4s
[CV 3/5] END XGB__learning_rate=0.21249999999999997, XGB__max_depth=4, XGB__n_estimators=10;, score=0.608 total time=  17.6s
[CV 1/5] END XGB__learning_rate=0.21249999999999997, XGB__max_depth=4, XGB__n_estimators=50;, score=0.714 total time=  37.8s
[CV 5/5] END XGB__learning_rate=0.21249999999999997, XGB__max_depth=5, XGB__n_estimators=25;, score=0.693 total time=  26.5s
[CV 4/5] END XGB__learning_rate=0.37499999999999994, XGB__max_depth=2, XGB__n_estimators=10;, score=0.565 total time=  16.1s
[CV 2/5] END XGB__learning_rate=0.37499999999999994, XGB__max_depth=2, XGB__n_estimators=50;, score=0.677 total time=  30.4s
[CV 1/5] END XGB__learning_rate=0.37499999999999994, XGB__max_depth=3, XGB__n_estimators=25;, score=0.666 total time=  23.3s
[CV 5/5] END XGB__learning_rate=0.37499999999999994, XGB__max_depth=3, XGB__n_estimators=75;, score=0.760 total time=  43.4s
[CV 5/5] END XGB__learning_rate=0.37499999999999994, XGB__max_depth=5, XGB__n_estimators=10;, score=0.670 total time=  20.2s
[CV 1/5] END XGB__learning_rate=0.37499999999999994, XGB__max_depth=5, XGB__n_estimators=75;, score=0.820 total time=  52.6s
[CV 3/5] END XGB__learning_rate=0.5375, XGB__max_depth=2, XGB__n_estimators=75;, score=0.730 total time=  38.2s
[CV 1/5] END XGB__learning_rate=0.5375, XGB__max_depth=4, XGB__n_estimators=10;, score=0.661 total time=  19.4s
[CV 5/5] END XGB__learning_rate=0.5375, XGB__max_depth=4, XGB__n_estimators=50;, score=0.792 total time=  36.6s
[CV 2/5] END XGB__learning_rate=0.5375, XGB__max_depth=5, XGB__n_estimators=50;, score=0.816 total time=  40.9s
[CV 1/5] END XGB__learning_rate=0.7, XGB__max_depth=2, XGB__n_estimators=50;, score=0.726 total time=  29.1s
[CV 1/5] END XGB__learning_rate=0.7, XGB__max_depth=3, XGB__n_estimators=25;, score=0.722 total time=  22.7s
[CV 5/5] END XGB__learning_rate=0.7, XGB__max_depth=3, XGB__n_estimators=75;, score=0.803 total time=  42.4s
[CV 3/5] END XGB__learning_rate=0.7, XGB__max_depth=5, XGB__n_estimators=10;, score=0.705 total time=  18.5s
[CV 4/5] END XGB__learning_rate=0.7, XGB__max_depth=5, XGB__n_estimators=50;, score=0.826 total time=  33.1s
[CV 1/5] END XGB__learning_rate=0.05, XGB__max_depth=2, XGB__n_estimators=50;, score=0.539 total time=  30.2s
[CV 2/5] END XGB__learning_rate=0.05, XGB__max_depth=3, XGB__n_estimators=25;, score=0.555 total time=  24.1s
[CV 3/5] END XGB__learning_rate=0.05, XGB__max_depth=4, XGB__n_estimators=10;, score=0.567 total time=  17.2s
[CV 3/5] END XGB__learning_rate=0.05, XGB__max_depth=4, XGB__n_estimators=50;, score=0.612 total time=  36.8s
[CV 4/5] END XGB__learning_rate=0.05, XGB__max_depth=5, XGB__n_estimators=25;, score=0.626 total time=  27.7s
[CV 5/5] END XGB__learning_rate=0.21249999999999997, XGB__max_depth=2, XGB__n_estimators=10;, score=0.529 total time=  16.0s
[CV 1/5] END XGB__learning_rate=0.21249999999999997, XGB__max_depth=2, XGB__n_estimators=50;, score=0.625 total time=  31.2s
[CV 2/5] END XGB__learning_rate=0.21249999999999997, XGB__max_depth=3, XGB__n_estimators=25;, score=0.618 total time=  23.8s
[CV 5/5] END XGB__learning_rate=0.21249999999999997, XGB__max_depth=3, XGB__n_estimators=75;, score=0.710 total time=  42.5s
[CV 5/5] END XGB__learning_rate=0.21249999999999997, XGB__max_depth=5, XGB__n_estimators=10;, score=0.644 total time=  18.2s
[CV 4/5] END XGB__learning_rate=0.21249999999999997, XGB__max_depth=5, XGB__n_estimators=50;, score=0.747 total time=  40.9s
[CV 5/5] END XGB__learning_rate=0.37499999999999994, XGB__max_depth=2, XGB__n_estimators=50;, score=0.679 total time=  30.0s
[CV 3/5] END XGB__learning_rate=0.37499999999999994, XGB__max_depth=3, XGB__n_estimators=25;, score=0.660 total time=  23.0s
[CV 2/5] END XGB__learning_rate=0.37499999999999994, XGB__max_depth=4, XGB__n_estimators=10;, score=0.633 total time=  17.2s
[CV 1/5] END XGB__learning_rate=0.37499999999999994, XGB__max_depth=4, XGB__n_estimators=50;, score=0.764 total time=  37.3s
[CV 5/5] END XGB__learning_rate=0.37499999999999994, XGB__max_depth=5, XGB__n_estimators=25;, score=0.738 total time=  26.8s
[CV 4/5] END XGB__learning_rate=0.5375, XGB__max_depth=2, XGB__n_estimators=10;, score=0.590 total time=  16.2s
[CV 3/5] END XGB__learning_rate=0.5375, XGB__max_depth=2, XGB__n_estimators=50;, score=0.701 total time=  31.9s
[CV 1/5] END XGB__learning_rate=0.5375, XGB__max_depth=3, XGB__n_estimators=50;, score=0.757 total time=  33.5s
[CV 2/5] END XGB__learning_rate=0.5375, XGB__max_depth=4, XGB__n_estimators=25;, score=0.734 total time=  24.7s
[CV 1/5] END XGB__learning_rate=0.5375, XGB__max_depth=5, XGB__n_estimators=10;, score=0.694 total time=  18.2s
[CV 3/5] END XGB__learning_rate=0.5375, XGB__max_depth=5, XGB__n_estimators=25;, score=0.767 total time=  28.1s
[CV 5/5] END XGB__learning_rate=0.7, XGB__max_depth=2, XGB__n_estimators=10;, score=0.599 total time=  15.9s
[CV 5/5] END XGB__learning_rate=0.7, XGB__max_depth=2, XGB__n_estimators=50;, score=0.728 total time=  31.5s
[CV 5/5] END XGB__learning_rate=0.7, XGB__max_depth=3, XGB__n_estimators=25;, score=0.724 total time=  22.4s
[CV 3/5] END XGB__learning_rate=0.7, XGB__max_depth=4, XGB__n_estimators=10;, score=0.676 total time=  17.6s
[CV 4/5] END XGB__learning_rate=0.7, XGB__max_depth=4, XGB__n_estimators=50;, score=0.805 total time=  36.9s
[CV 2/5] END XGB__learning_rate=0.7, XGB__max_depth=5, XGB__n_estimators=50;, score=0.825 total time=  34.6s

/home/pgcp-ai/.local/lib/python3.8/site-packages/xgboost/core.py:265: FutureWarning: Your system has an old version of glibc (< 2.28). We will stop supporting Linux distros with glibc older than 2.28 after **May 31, 2025**. Please upgrade to a recent Linux distro (with glibc 2.28+) to use future versions of XGBoost.
Note: You have installed the 'manylinux2014' variant of XGBoost. Certain features such as GPU algorithms or federated learning are not available. To use these features, please upgrade to a recent Linux distro with glibc 2.28+, and install the 'manylinux_2_28' variant.
  warnings.warn(
/home/pgcp-ai/.local/lib/python3.8/site-packages/xgboost/core.py:265: FutureWarning: Your system has an old version of glibc (< 2.28). We will stop supporting Linux distros with glibc older than 2.28 after **May 31, 2025**. Please upgrade to a recent Linux distro (with glibc 2.28+) to use future versions of XGBoost.
Note: You have installed the 'manylinux2014' variant of XGBoost. Certain features such as GPU algorithms or federated learning are not available. To use these features, please upgrade to a recent Linux distro with glibc 2.28+, and install the 'manylinux_2_28' variant.
  warnings.warn(

[CV 3/5] END XGB__learning_rate=0.05, XGB__max_depth=2, XGB__n_estimators=25;, score=0.508 total time=  24.0s
[CV 5/5] END XGB__learning_rate=0.05, XGB__max_depth=3, XGB__n_estimators=10;, score=0.525 total time=  18.2s
[CV 1/5] END XGB__learning_rate=0.05, XGB__max_depth=3, XGB__n_estimators=75;, score=0.598 total time=  43.0s
[CV 3/5] END XGB__learning_rate=0.05, XGB__max_depth=4, XGB__n_estimators=75;, score=0.627 total time=  49.4s
[CV 2/5] END XGB__learning_rate=0.21249999999999997, XGB__max_depth=2, XGB__n_estimators=10;, score=0.532 total time=  18.3s
[CV 5/5] END XGB__learning_rate=0.21249999999999997, XGB__max_depth=2, XGB__n_estimators=25;, score=0.585 total time=  21.3s
[CV 2/5] END XGB__learning_rate=0.21249999999999997, XGB__max_depth=3, XGB__n_estimators=10;, score=0.578 total time=  16.9s
[CV 2/5] END XGB__learning_rate=0.21249999999999997, XGB__max_depth=3, XGB__n_estimators=50;, score=0.670 total time=  32.2s
[CV 3/5] END XGB__learning_rate=0.21249999999999997, XGB__max_depth=4, XGB__n_estimators=25;, score=0.655 total time=  25.2s
[CV 2/5] END XGB__learning_rate=0.21249999999999997, XGB__max_depth=5, XGB__n_estimators=10;, score=0.639 total time=  17.8s
[CV 3/5] END XGB__learning_rate=0.21249999999999997, XGB__max_depth=5, XGB__n_estimators=50;, score=0.741 total time=  41.1s
[CV 5/5] END XGB__learning_rate=0.37499999999999994, XGB__max_depth=2, XGB__n_estimators=25;, score=0.621 total time=  21.6s
[CV 5/5] END XGB__learning_rate=0.37499999999999994, XGB__max_depth=2, XGB__n_estimators=75;, score=0.707 total time=  37.4s
[CV 1/5] END XGB__learning_rate=0.37499999999999994, XGB__max_depth=4, XGB__n_estimators=25;, score=0.703 total time=  24.0s
[CV 2/5] END XGB__learning_rate=0.37499999999999994, XGB__max_depth=4, XGB__n_estimators=75;, score=0.794 total time=  46.5s
[CV 4/5] END XGB__learning_rate=0.37499999999999994, XGB__max_depth=5, XGB__n_estimators=75;, score=0.817 total time=  51.5s
[CV 4/5] END XGB__learning_rate=0.5375, XGB__max_depth=3, XGB__n_estimators=10;, score=0.629 total time=  17.7s
[CV 2/5] END XGB__learning_rate=0.5375, XGB__max_depth=3, XGB__n_estimators=75;, score=0.785 total time=  42.0s
[CV 3/5] END XGB__learning_rate=0.5375, XGB__max_depth=4, XGB__n_estimators=75;, score=0.813 total time=  48.3s
[CV 5/5] END XGB__learning_rate=0.5375, XGB__max_depth=5, XGB__n_estimators=75;, score=0.838 total time=  53.3s
[CV 1/5] END XGB__learning_rate=0.7, XGB__max_depth=3, XGB__n_estimators=50;, score=0.775 total time=  33.1s
[CV 2/5] END XGB__learning_rate=0.7, XGB__max_depth=4, XGB__n_estimators=25;, score=0.759 total time=  23.8s
[CV 1/5] END XGB__learning_rate=0.7, XGB__max_depth=5, XGB__n_estimators=10;, score=0.715 total time=  19.2s
[CV 1/5] END XGB__learning_rate=0.7, XGB__max_depth=5, XGB__n_estimators=50;, score=0.829 total time=  35.1s

/home/pgcp-ai/.local/lib/python3.8/site-packages/xgboost/core.py:265: FutureWarning: Your system has an old version of glibc (< 2.28). We will stop supporting Linux distros with glibc older than 2.28 after **May 31, 2025**. Please upgrade to a recent Linux distro (with glibc 2.28+) to use future versions of XGBoost.
Note: You have installed the 'manylinux2014' variant of XGBoost. Certain features such as GPU algorithms or federated learning are not available. To use these features, please upgrade to a recent Linux distro with glibc 2.28+, and install the 'manylinux_2_28' variant.
  warnings.warn(

[CV 1/5] END XGB__learning_rate=0.05, XGB__max_depth=2, XGB__n_estimators=10;, score=0.513 total time=  15.7s
[CV 2/5] END XGB__learning_rate=0.05, XGB__max_depth=2, XGB__n_estimators=75;, score=0.555 total time=  38.4s
[CV 4/5] END XGB__learning_rate=0.05, XGB__max_depth=3, XGB__n_estimators=75;, score=0.601 total time=  43.5s
[CV 3/5] END XGB__learning_rate=0.05, XGB__max_depth=5, XGB__n_estimators=10;, score=0.614 total time=  20.4s
[CV 4/5] END XGB__learning_rate=0.05, XGB__max_depth=5, XGB__n_estimators=50;, score=0.646 total time=  41.2s
[CV 1/5] END XGB__learning_rate=0.21249999999999997, XGB__max_depth=2, XGB__n_estimators=75;, score=0.662 total time=  38.4s
[CV 4/5] END XGB__learning_rate=0.21249999999999997, XGB__max_depth=3, XGB__n_estimators=50;, score=0.672 total time=  31.9s
[CV 5/5] END XGB__learning_rate=0.21249999999999997, XGB__max_depth=4, XGB__n_estimators=25;, score=0.661 total time=  25.7s
[CV 1/5] END XGB__learning_rate=0.21249999999999997, XGB__max_depth=5, XGB__n_estimators=25;, score=0.688 total time=  26.6s
[CV 2/5] END XGB__learning_rate=0.21249999999999997, XGB__max_depth=5, XGB__n_estimators=75;, score=0.779 total time=  54.3s
[CV 3/5] END XGB__learning_rate=0.37499999999999994, XGB__max_depth=3, XGB__n_estimators=10;, score=0.602 total time=  16.7s
[CV 4/5] END XGB__learning_rate=0.37499999999999994, XGB__max_depth=3, XGB__n_estimators=50;, score=0.721 total time=  31.7s
[CV 2/5] END XGB__learning_rate=0.37499999999999994, XGB__max_depth=4, XGB__n_estimators=50;, score=0.762 total time=  36.4s
[CV 3/5] END XGB__learning_rate=0.37499999999999994, XGB__max_depth=5, XGB__n_estimators=25;, score=0.730 total time=  28.0s
[CV 5/5] END XGB__learning_rate=0.5375, XGB__max_depth=2, XGB__n_estimators=10;, score=0.594 total time=  18.1s
[CV 1/5] END XGB__learning_rate=0.5375, XGB__max_depth=2, XGB__n_estimators=75;, score=0.733 total time=  38.4s
[CV 4/5] END XGB__learning_rate=0.5375, XGB__max_depth=3, XGB__n_estimators=50;, score=0.753 total time=  31.3s
[CV 4/5] END XGB__learning_rate=0.5375, XGB__max_depth=4, XGB__n_estimators=25;, score=0.733 total time=  24.7s
[CV 5/5] END XGB__learning_rate=0.5375, XGB__max_depth=5, XGB__n_estimators=10;, score=0.690 total time=  18.4s
[CV 1/5] END XGB__learning_rate=0.5375, XGB__max_depth=5, XGB__n_estimators=75;, score=0.835 total time=  52.4s
[CV 3/5] END XGB__learning_rate=0.7, XGB__max_depth=2, XGB__n_estimators=75;, score=0.744 total time=  36.7s
[CV 4/5] END XGB__learning_rate=0.7, XGB__max_depth=3, XGB__n_estimators=75;, score=0.798 total time=  41.5s
[CV 2/5] END XGB__learning_rate=0.7, XGB__max_depth=5, XGB__n_estimators=10;, score=0.706 total time=  18.7s
[CV 3/5] END XGB__learning_rate=0.7, XGB__max_depth=5, XGB__n_estimators=50;, score=0.824 total time=  38.0s

/home/pgcp-ai/.local/lib/python3.8/site-packages/xgboost/core.py:265: FutureWarning: Your system has an old version of glibc (< 2.28). We will stop supporting Linux distros with glibc older than 2.28 after **May 31, 2025**. Please upgrade to a recent Linux distro (with glibc 2.28+) to use future versions of XGBoost.
Note: You have installed the 'manylinux2014' variant of XGBoost. Certain features such as GPU algorithms or federated learning are not available. To use these features, please upgrade to a recent Linux distro with glibc 2.28+, and install the 'manylinux_2_28' variant.
  warnings.warn(

[CV 5/5] END XGB__learning_rate=0.05, XGB__max_depth=2, XGB__n_estimators=10;, score=0.491 total time=  16.7s
[CV 1/5] END XGB__learning_rate=0.05, XGB__max_depth=3, XGB__n_estimators=10;, score=0.525 total time=  16.8s
[CV 4/5] END XGB__learning_rate=0.05, XGB__max_depth=3, XGB__n_estimators=25;, score=0.563 total time=  24.0s
[CV 1/5] END XGB__learning_rate=0.05, XGB__max_depth=4, XGB__n_estimators=25;, score=0.593 total time=  24.5s
[CV 2/5] END XGB__learning_rate=0.05, XGB__max_depth=4, XGB__n_estimators=75;, score=0.631 total time=  47.9s
[CV 4/5] END XGB__learning_rate=0.05, XGB__max_depth=5, XGB__n_estimators=75;, score=0.665 total time=  55.8s
[CV 3/5] END XGB__learning_rate=0.21249999999999997, XGB__max_depth=3, XGB__n_estimators=25;, score=0.617 total time=  22.8s
[CV 4/5] END XGB__learning_rate=0.21249999999999997, XGB__max_depth=3, XGB__n_estimators=75;, score=0.708 total time=  41.8s
[CV 4/5] END XGB__learning_rate=0.21249999999999997, XGB__max_depth=5, XGB__n_estimators=10;, score=0.641 total time=  19.4s
[CV 1/5] END XGB__learning_rate=0.21249999999999997, XGB__max_depth=5, XGB__n_estimators=75;, score=0.785 total time=  53.5s
[CV 3/5] END XGB__learning_rate=0.37499999999999994, XGB__max_depth=2, XGB__n_estimators=75;, score=0.702 total time=  36.6s
[CV 4/5] END XGB__learning_rate=0.37499999999999994, XGB__max_depth=3, XGB__n_estimators=75;, score=0.754 total time=  42.6s
[CV 2/5] END XGB__learning_rate=0.37499999999999994, XGB__max_depth=5, XGB__n_estimators=10;, score=0.663 total time=  18.1s
[CV 2/5] END XGB__learning_rate=0.37499999999999994, XGB__max_depth=5, XGB__n_estimators=50;, score=0.792 total time=  41.8s
[CV 5/5] END XGB__learning_rate=0.5375, XGB__max_depth=2, XGB__n_estimators=25;, score=0.658 total time=  23.3s
[CV 2/5] END XGB__learning_rate=0.5375, XGB__max_depth=3, XGB__n_estimators=10;, score=0.622 total time=  16.5s
[CV 3/5] END XGB__learning_rate=0.5375, XGB__max_depth=3, XGB__n_estimators=50;, score=0.753 total time=  34.0s
[CV 2/5] END XGB__learning_rate=0.5375, XGB__max_depth=4, XGB__n_estimators=50;, score=0.789 total time=  37.7s
[CV 1/5] END XGB__learning_rate=0.5375, XGB__max_depth=5, XGB__n_estimators=50;, score=0.815 total time=  40.6s
[CV 3/5] END XGB__learning_rate=0.7, XGB__max_depth=2, XGB__n_estimators=25;, score=0.670 total time=  22.9s
[CV 1/5] END XGB__learning_rate=0.7, XGB__max_depth=3, XGB__n_estimators=10;, score=0.647 total time=  16.7s
[CV 2/5] END XGB__learning_rate=0.7, XGB__max_depth=3, XGB__n_estimators=50;, score=0.780 total time=  31.6s
[CV 3/5] END XGB__learning_rate=0.7, XGB__max_depth=4, XGB__n_estimators=25;, score=0.754 total time=  24.9s
[CV 4/5] END XGB__learning_rate=0.7, XGB__max_depth=5, XGB__n_estimators=10;, score=0.712 total time=  18.0s
[CV 5/5] END XGB__learning_rate=0.7, XGB__max_depth=5, XGB__n_estimators=50;, score=0.829 total time=  37.0s

/home/pgcp-ai/.local/lib/python3.8/site-packages/xgboost/core.py:265: FutureWarning: Your system has an old version of glibc (< 2.28). We will stop supporting Linux distros with glibc older than 2.28 after **May 31, 2025**. Please upgrade to a recent Linux distro (with glibc 2.28+) to use future versions of XGBoost.
Note: You have installed the 'manylinux2014' variant of XGBoost. Certain features such as GPU algorithms or federated learning are not available. To use these features, please upgrade to a recent Linux distro with glibc 2.28+, and install the 'manylinux_2_28' variant.
  warnings.warn(

[CV 3/5] END XGB__learning_rate=0.05, XGB__max_depth=2, XGB__n_estimators=10;, score=0.501 total time=  16.1s
[CV 4/5] END XGB__learning_rate=0.05, XGB__max_depth=2, XGB__n_estimators=75;, score=0.557 total time=  38.0s
[CV 1/5] END XGB__learning_rate=0.05, XGB__max_depth=4, XGB__n_estimators=10;, score=0.570 total time=  17.5s
[CV 5/5] END XGB__learning_rate=0.05, XGB__max_depth=4, XGB__n_estimators=25;, score=0.595 total time=  25.1s
[CV 5/5] END XGB__learning_rate=0.05, XGB__max_depth=5, XGB__n_estimators=10;, score=0.618 total time=  21.1s
[CV 1/5] END XGB__learning_rate=0.05, XGB__max_depth=5, XGB__n_estimators=75;, score=0.663 total time=  55.0s
[CV 3/5] END XGB__learning_rate=0.21249999999999997, XGB__max_depth=2, XGB__n_estimators=75;, score=0.659 total time=  38.1s
[CV 2/5] END XGB__learning_rate=0.21249999999999997, XGB__max_depth=4, XGB__n_estimators=10;, score=0.611 total time=  19.2s
[CV 5/5] END XGB__learning_rate=0.21249999999999997, XGB__max_depth=4, XGB__n_estimators=50;, score=0.715 total time=  36.6s
[CV 2/5] END XGB__learning_rate=0.21249999999999997, XGB__max_depth=5, XGB__n_estimators=50;, score=0.746 total time=  42.2s
[CV 1/5] END XGB__learning_rate=0.37499999999999994, XGB__max_depth=2, XGB__n_estimators=50;, score=0.677 total time=  30.4s
[CV 5/5] END XGB__learning_rate=0.37499999999999994, XGB__max_depth=3, XGB__n_estimators=10;, score=0.606 total time=  17.1s
[CV 3/5] END XGB__learning_rate=0.37499999999999994, XGB__max_depth=3, XGB__n_estimators=75;, score=0.760 total time=  42.8s
[CV 5/5] END XGB__learning_rate=0.37499999999999994, XGB__max_depth=4, XGB__n_estimators=75;, score=0.795 total time=  47.1s
[CV 3/5] END XGB__learning_rate=0.5375, XGB__max_depth=2, XGB__n_estimators=10;, score=0.589 total time=  16.4s
[CV 2/5] END XGB__learning_rate=0.5375, XGB__max_depth=2, XGB__n_estimators=50;, score=0.705 total time=  30.5s
[CV 1/5] END XGB__learning_rate=0.5375, XGB__max_depth=3, XGB__n_estimators=25;, score=0.699 total time=  22.8s
[CV 4/5] END XGB__learning_rate=0.5375, XGB__max_depth=3, XGB__n_estimators=75;, score=0.777 total time=  41.9s
[CV 3/5] END XGB__learning_rate=0.5375, XGB__max_depth=5, XGB__n_estimators=10;, score=0.680 total time=  19.1s
[CV 4/5] END XGB__learning_rate=0.5375, XGB__max_depth=5, XGB__n_estimators=50;, score=0.816 total time=  39.3s
[CV 4/5] END XGB__learning_rate=0.7, XGB__max_depth=2, XGB__n_estimators=50;, score=0.721 total time=  29.7s
[CV 3/5] END XGB__learning_rate=0.7, XGB__max_depth=3, XGB__n_estimators=25;, score=0.722 total time=  23.4s
[CV 1/5] END XGB__learning_rate=0.7, XGB__max_depth=4, XGB__n_estimators=10;, score=0.674 total time=  17.5s
[CV 4/5] END XGB__learning_rate=0.7, XGB__max_depth=4, XGB__n_estimators=25;, score=0.756 total time=  24.7s
[CV 5/5] END XGB__learning_rate=0.7, XGB__max_depth=5, XGB__n_estimators=10;, score=0.713 total time=  17.8s
[CV 1/5] END XGB__learning_rate=0.7, XGB__max_depth=5, XGB__n_estimators=75;, score=0.843 total time=  43.1s

/home/pgcp-ai/.local/lib/python3.8/site-packages/xgboost/core.py:265: FutureWarning: Your system has an old version of glibc (< 2.28). We will stop supporting Linux distros with glibc older than 2.28 after **May 31, 2025**. Please upgrade to a recent Linux distro (with glibc 2.28+) to use future versions of XGBoost.
Note: You have installed the 'manylinux2014' variant of XGBoost. Certain features such as GPU algorithms or federated learning are not available. To use these features, please upgrade to a recent Linux distro with glibc 2.28+, and install the 'manylinux_2_28' variant.
  warnings.warn(

[CV 2/5] END XGB__learning_rate=0.05, XGB__max_depth=2, XGB__n_estimators=25;, score=0.520 total time=  21.2s
[CV 2/5] END XGB__learning_rate=0.05, XGB__max_depth=3, XGB__n_estimators=10;, score=0.530 total time=  16.5s
[CV 3/5] END XGB__learning_rate=0.05, XGB__max_depth=3, XGB__n_estimators=50;, score=0.583 total time=  32.2s
[CV 4/5] END XGB__learning_rate=0.05, XGB__max_depth=4, XGB__n_estimators=25;, score=0.591 total time=  26.3s
[CV 1/5] END XGB__learning_rate=0.05, XGB__max_depth=5, XGB__n_estimators=25;, score=0.623 total time=  28.3s
[CV 2/5] END XGB__learning_rate=0.05, XGB__max_depth=5, XGB__n_estimators=75;, score=0.662 total time=  54.6s
[CV 3/5] END XGB__learning_rate=0.21249999999999997, XGB__max_depth=3, XGB__n_estimators=10;, score=0.577 total time=  16.6s
[CV 5/5] END XGB__learning_rate=0.21249999999999997, XGB__max_depth=3, XGB__n_estimators=50;, score=0.675 total time=  32.8s
[CV 2/5] END XGB__learning_rate=0.21249999999999997, XGB__max_depth=4, XGB__n_estimators=50;, score=0.708 total time=  37.1s
[CV 3/5] END XGB__learning_rate=0.21249999999999997, XGB__max_depth=5, XGB__n_estimators=25;, score=0.682 total time=  27.6s
[CV 5/5] END XGB__learning_rate=0.37499999999999994, XGB__max_depth=2, XGB__n_estimators=10;, score=0.557 total time=  16.1s
[CV 4/5] END XGB__learning_rate=0.37499999999999994, XGB__max_depth=2, XGB__n_estimators=50;, score=0.670 total time=  31.0s
[CV 4/5] END XGB__learning_rate=0.37499999999999994, XGB__max_depth=3, XGB__n_estimators=25;, score=0.661 total time=  23.4s
[CV 4/5] END XGB__learning_rate=0.37499999999999994, XGB__max_depth=4, XGB__n_estimators=10;, score=0.636 total time=  19.4s
[CV 5/5] END XGB__learning_rate=0.37499999999999994, XGB__max_depth=4, XGB__n_estimators=50;, score=0.760 total time=  36.4s
[CV 3/5] END XGB__learning_rate=0.37499999999999994, XGB__max_depth=5, XGB__n_estimators=50;, score=0.790 total time=  41.7s
[CV 1/5] END XGB__learning_rate=0.5375, XGB__max_depth=2, XGB__n_estimators=50;, score=0.704 total time=  32.2s
[CV 5/5] END XGB__learning_rate=0.5375, XGB__max_depth=3, XGB__n_estimators=25;, score=0.702 total time=  23.0s
[CV 4/5] END XGB__learning_rate=0.5375, XGB__max_depth=4, XGB__n_estimators=10;, score=0.655 total time=  18.0s
[CV 4/5] END XGB__learning_rate=0.5375, XGB__max_depth=4, XGB__n_estimators=50;, score=0.791 total time=  36.0s
[CV 4/5] END XGB__learning_rate=0.5375, XGB__max_depth=5, XGB__n_estimators=25;, score=0.770 total time=  26.4s
[CV 4/5] END XGB__learning_rate=0.7, XGB__max_depth=2, XGB__n_estimators=10;, score=0.604 total time=  16.7s
[CV 3/5] END XGB__learning_rate=0.7, XGB__max_depth=2, XGB__n_estimators=50;, score=0.715 total time=  29.3s
[CV 2/5] END XGB__learning_rate=0.7, XGB__max_depth=3, XGB__n_estimators=25;, score=0.723 total time=  24.2s
[CV 2/5] END XGB__learning_rate=0.7, XGB__max_depth=4, XGB__n_estimators=10;, score=0.678 total time=  17.4s
[CV 5/5] END XGB__learning_rate=0.7, XGB__max_depth=4, XGB__n_estimators=25;, score=0.765 total time=  24.5s
[CV 1/5] END XGB__learning_rate=0.7, XGB__max_depth=5, XGB__n_estimators=25;, score=0.789 total time=  27.4s
[CV 3/5] END XGB__learning_rate=0.7, XGB__max_depth=5, XGB__n_estimators=75;, score=0.840 total time=  35.0s

/home/pgcp-ai/.local/lib/python3.8/site-packages/xgboost/core.py:265: FutureWarning: Your system has an old version of glibc (< 2.28). We will stop supporting Linux distros with glibc older than 2.28 after **May 31, 2025**. Please upgrade to a recent Linux distro (with glibc 2.28+) to use future versions of XGBoost.
Note: You have installed the 'manylinux2014' variant of XGBoost. Certain features such as GPU algorithms or federated learning are not available. To use these features, please upgrade to a recent Linux distro with glibc 2.28+, and install the 'manylinux_2_28' variant.
  warnings.warn(
/home/pgcp-ai/.local/lib/python3.8/site-packages/xgboost/core.py:265: FutureWarning: Your system has an old version of glibc (< 2.28). We will stop supporting Linux distros with glibc older than 2.28 after **May 31, 2025**. Please upgrade to a recent Linux distro (with glibc 2.28+) to use future versions of XGBoost.
Note: You have installed the 'manylinux2014' variant of XGBoost. Certain features such as GPU algorithms or federated learning are not available. To use these features, please upgrade to a recent Linux distro with glibc 2.28+, and install the 'manylinux_2_28' variant.
  warnings.warn(

[CV 3/5] END XGB__learning_rate=0.05, XGB__max_depth=2, XGB__n_estimators=50;, score=0.530 total time=  30.8s
[CV 1/5] END XGB__learning_rate=0.05, XGB__max_depth=3, XGB__n_estimators=50;, score=0.582 total time=  33.2s
[CV 3/5] END XGB__learning_rate=0.05, XGB__max_depth=4, XGB__n_estimators=25;, score=0.589 total time=  24.2s
[CV 5/5] END XGB__learning_rate=0.05, XGB__max_depth=4, XGB__n_estimators=75;, score=0.635 total time=  49.1s
[CV 1/5] END XGB__learning_rate=0.21249999999999997, XGB__max_depth=2, XGB__n_estimators=25;, score=0.578 total time=  22.0s
[CV 2/5] END XGB__learning_rate=0.21249999999999997, XGB__max_depth=2, XGB__n_estimators=75;, score=0.656 total time=  37.7s
[CV 2/5] END XGB__learning_rate=0.21249999999999997, XGB__max_depth=3, XGB__n_estimators=75;, score=0.704 total time=  41.6s
[CV 4/5] END XGB__learning_rate=0.21249999999999997, XGB__max_depth=4, XGB__n_estimators=75;, score=0.751 total time=  47.2s
[CV 1/5] END XGB__learning_rate=0.37499999999999994, XGB__max_depth=2, XGB__n_estimators=10;, score=0.567 total time=  16.4s
[CV 2/5] END XGB__learning_rate=0.37499999999999994, XGB__max_depth=2, XGB__n_estimators=25;, score=0.619 total time=  21.4s
[CV 4/5] END XGB__learning_rate=0.37499999999999994, XGB__max_depth=2, XGB__n_estimators=75;, score=0.701 total time=  37.8s
[CV 3/5] END XGB__learning_rate=0.37499999999999994, XGB__max_depth=4, XGB__n_estimators=10;, score=0.630 total time=  18.4s
[CV 4/5] END XGB__learning_rate=0.37499999999999994, XGB__max_depth=4, XGB__n_estimators=50;, score=0.769 total time=  34.9s
[CV 2/5] END XGB__learning_rate=0.37499999999999994, XGB__max_depth=5, XGB__n_estimators=25;, score=0.731 total time=  27.3s
[CV 2/5] END XGB__learning_rate=0.5375, XGB__max_depth=2, XGB__n_estimators=10;, score=0.583 total time=  16.3s
[CV 4/5] END XGB__learning_rate=0.5375, XGB__max_depth=2, XGB__n_estimators=25;, score=0.649 total time=  21.8s
[CV 1/5] END XGB__learning_rate=0.5375, XGB__max_depth=3, XGB__n_estimators=10;, score=0.628 total time=  16.5s
[CV 2/5] END XGB__learning_rate=0.5375, XGB__max_depth=3, XGB__n_estimators=50;, score=0.757 total time=  32.5s
[CV 3/5] END XGB__learning_rate=0.5375, XGB__max_depth=4, XGB__n_estimators=25;, score=0.734 total time=  24.1s
[CV 2/5] END XGB__learning_rate=0.5375, XGB__max_depth=5, XGB__n_estimators=10;, score=0.688 total time=  18.3s
[CV 3/5] END XGB__learning_rate=0.5375, XGB__max_depth=5, XGB__n_estimators=50;, score=0.815 total time=  40.5s
[CV 2/5] END XGB__learning_rate=0.7, XGB__max_depth=2, XGB__n_estimators=50;, score=0.717 total time=  32.7s
[CV 4/5] END XGB__learning_rate=0.7, XGB__max_depth=3, XGB__n_estimators=25;, score=0.722 total time=  23.2s
[CV 5/5] END XGB__learning_rate=0.7, XGB__max_depth=4, XGB__n_estimators=10;, score=0.681 total time=  17.0s
[CV 1/5] END XGB__learning_rate=0.7, XGB__max_depth=4, XGB__n_estimators=75;, score=0.826 total time=  48.4s
[CV 2/5] END XGB__learning_rate=0.7, XGB__max_depth=5, XGB__n_estimators=75;, score=0.842 total time=  38.3s
[CV 5/5] END XGB__learning_rate=0.05, XGB__max_depth=2, XGB__n_estimators=50;, score=0.532 total time=  29.9s
[CV 2/5] END XGB__learning_rate=0.05, XGB__max_depth=3, XGB__n_estimators=50;, score=0.580 total time=  32.5s
[CV 2/5] END XGB__learning_rate=0.05, XGB__max_depth=4, XGB__n_estimators=25;, score=0.590 total time=  24.8s
[CV 1/5] END XGB__learning_rate=0.05, XGB__max_depth=5, XGB__n_estimators=10;, score=0.608 total time=  19.7s
[CV 1/5] END XGB__learning_rate=0.05, XGB__max_depth=5, XGB__n_estimators=50;, score=0.644 total time=  40.3s
[CV 3/5] END XGB__learning_rate=0.21249999999999997, XGB__max_depth=2, XGB__n_estimators=25;, score=0.575 total time=  21.1s
[CV 5/5] END XGB__learning_rate=0.21249999999999997, XGB__max_depth=2, XGB__n_estimators=75;, score=0.665 total time=  38.4s
[CV 1/5] END XGB__learning_rate=0.21249999999999997, XGB__max_depth=4, XGB__n_estimators=25;, score=0.655 total time=  27.3s
[CV 2/5] END XGB__learning_rate=0.21249999999999997, XGB__max_depth=4, XGB__n_estimators=75;, score=0.748 total time=  49.0s
[CV 4/5] END XGB__learning_rate=0.21249999999999997, XGB__max_depth=5, XGB__n_estimators=75;, score=0.780 total time=  55.6s
[CV 5/5] END XGB__learning_rate=0.37499999999999994, XGB__max_depth=3, XGB__n_estimators=25;, score=0.663 total time=  23.1s
[CV 5/5] END XGB__learning_rate=0.37499999999999994, XGB__max_depth=4, XGB__n_estimators=10;, score=0.635 total time=  19.6s
[CV 1/5] END XGB__learning_rate=0.37499999999999994, XGB__max_depth=4, XGB__n_estimators=75;, score=0.795 total time=  48.0s
[CV 2/5] END XGB__learning_rate=0.37499999999999994, XGB__max_depth=5, XGB__n_estimators=75;, score=0.816 total time=  53.6s
[CV 3/5] END XGB__learning_rate=0.5375, XGB__max_depth=3, XGB__n_estimators=10;, score=0.620 total time=  18.1s
[CV 5/5] END XGB__learning_rate=0.5375, XGB__max_depth=3, XGB__n_estimators=50;, score=0.754 total time=  31.6s
[CV 1/5] END XGB__learning_rate=0.5375, XGB__max_depth=4, XGB__n_estimators=50;, score=0.794 total time=  35.3s
[CV 2/5] END XGB__learning_rate=0.5375, XGB__max_depth=5, XGB__n_estimators=25;, score=0.761 total time=  25.9s
[CV 2/5] END XGB__learning_rate=0.7, XGB__max_depth=2, XGB__n_estimators=10;, score=0.603 total time=  17.2s
[CV 5/5] END XGB__learning_rate=0.7, XGB__max_depth=2, XGB__n_estimators=25;, score=0.673 total time=  21.4s
[CV 5/5] END XGB__learning_rate=0.7, XGB__max_depth=2, XGB__n_estimators=75;, score=0.754 total time=  38.9s
[CV 1/5] END XGB__learning_rate=0.7, XGB__max_depth=4, XGB__n_estimators=25;, score=0.757 total time=  24.9s
[CV 3/5] END XGB__learning_rate=0.7, XGB__max_depth=4, XGB__n_estimators=75;, score=0.828 total time=  46.5s
[CV 4/5] END XGB__learning_rate=0.7, XGB__max_depth=5, XGB__n_estimators=75;, score=0.842 total time=  31.3s

/home/pgcp-ai/.local/lib/python3.8/site-packages/xgboost/core.py:265: FutureWarning: Your system has an old version of glibc (< 2.28). We will stop supporting Linux distros with glibc older than 2.28 after **May 31, 2025**. Please upgrade to a recent Linux distro (with glibc 2.28+) to use future versions of XGBoost.
Note: You have installed the 'manylinux2014' variant of XGBoost. Certain features such as GPU algorithms or federated learning are not available. To use these features, please upgrade to a recent Linux distro with glibc 2.28+, and install the 'manylinux_2_28' variant.
  warnings.warn(

[CV 1/5] END XGB__learning_rate=0.05, XGB__max_depth=2, XGB__n_estimators=25;, score=0.514 total time=  22.7s
[CV 3/5] END XGB__learning_rate=0.05, XGB__max_depth=3, XGB__n_estimators=10;, score=0.523 total time=  16.5s
[CV 4/5] END XGB__learning_rate=0.05, XGB__max_depth=3, XGB__n_estimators=50;, score=0.585 total time=  32.3s
[CV 1/5] END XGB__learning_rate=0.05, XGB__max_depth=4, XGB__n_estimators=50;, score=0.616 total time=  37.3s
[CV 3/5] END XGB__learning_rate=0.05, XGB__max_depth=5, XGB__n_estimators=25;, score=0.623 total time=  27.0s
[CV 3/5] END XGB__learning_rate=0.21249999999999997, XGB__max_depth=2, XGB__n_estimators=10;, score=0.529 total time=  18.3s
[CV 2/5] END XGB__learning_rate=0.21249999999999997, XGB__max_depth=2, XGB__n_estimators=50;, score=0.623 total time=  31.3s
[CV 4/5] END XGB__learning_rate=0.21249999999999997, XGB__max_depth=3, XGB__n_estimators=25;, score=0.622 total time=  24.7s
[CV 4/5] END XGB__learning_rate=0.21249999999999997, XGB__max_depth=4, XGB__n_estimators=10;, score=0.609 total time=  18.1s
[CV 4/5] END XGB__learning_rate=0.21249999999999997, XGB__max_depth=4, XGB__n_estimators=50;, score=0.711 total time=  36.4s
[CV 1/5] END XGB__learning_rate=0.21249999999999997, XGB__max_depth=5, XGB__n_estimators=50;, score=0.749 total time=  41.5s
[CV 4/5] END XGB__learning_rate=0.37499999999999994, XGB__max_depth=2, XGB__n_estimators=25;, score=0.619 total time=  23.5s
[CV 2/5] END XGB__learning_rate=0.37499999999999994, XGB__max_depth=3, XGB__n_estimators=10;, score=0.598 total time=  16.6s
[CV 2/5] END XGB__learning_rate=0.37499999999999994, XGB__max_depth=3, XGB__n_estimators=50;, score=0.723 total time=  32.4s
[CV 3/5] END XGB__learning_rate=0.37499999999999994, XGB__max_depth=4, XGB__n_estimators=25;, score=0.697 total time=  24.5s
[CV 3/5] END XGB__learning_rate=0.37499999999999994, XGB__max_depth=5, XGB__n_estimators=10;, score=0.663 total time=  19.4s
[CV 5/5] END XGB__learning_rate=0.37499999999999994, XGB__max_depth=5, XGB__n_estimators=50;, score=0.796 total time=  40.0s
[CV 5/5] END XGB__learning_rate=0.5375, XGB__max_depth=2, XGB__n_estimators=50;, score=0.706 total time=  29.9s
[CV 3/5] END XGB__learning_rate=0.5375, XGB__max_depth=3, XGB__n_estimators=25;, score=0.691 total time=  22.9s
[CV 2/5] END XGB__learning_rate=0.5375, XGB__max_depth=4, XGB__n_estimators=10;, score=0.650 total time=  17.5s
[CV 5/5] END XGB__learning_rate=0.5375, XGB__max_depth=4, XGB__n_estimators=25;, score=0.736 total time=  25.2s
[CV 1/5] END XGB__learning_rate=0.5375, XGB__max_depth=5, XGB__n_estimators=25;, score=0.772 total time=  25.8s
[CV 2/5] END XGB__learning_rate=0.5375, XGB__max_depth=5, XGB__n_estimators=75;, score=0.833 total time=  53.2s
[CV 3/5] END XGB__learning_rate=0.7, XGB__max_depth=3, XGB__n_estimators=10;, score=0.636 total time=  17.2s
[CV 1/5] END XGB__learning_rate=0.7, XGB__max_depth=3, XGB__n_estimators=75;, score=0.800 total time=  42.3s
[CV 2/5] END XGB__learning_rate=0.7, XGB__max_depth=4, XGB__n_estimators=75;, score=0.826 total time=  48.2s
[CV 5/5] END XGB__learning_rate=0.7, XGB__max_depth=5, XGB__n_estimators=75;, score=0.842 total time=  31.9s

/home/pgcp-ai/.local/lib/python3.8/site-packages/xgboost/core.py:265: FutureWarning: Your system has an old version of glibc (< 2.28). We will stop supporting Linux distros with glibc older than 2.28 after **May 31, 2025**. Please upgrade to a recent Linux distro (with glibc 2.28+) to use future versions of XGBoost.
Note: You have installed the 'manylinux2014' variant of XGBoost. Certain features such as GPU algorithms or federated learning are not available. To use these features, please upgrade to a recent Linux distro with glibc 2.28+, and install the 'manylinux_2_28' variant.
  warnings.warn(

In [9]:
tst = pd.read_csv("test.csv", index_col = 0)
tst

,Soil_Type,Soil_pH,Soil_Moisture,Organic_Carbon,Electrical_Conductivity,Temperature_C,Humidity,Rainfall_mm,Sunlight_Hours,Wind_Speed_kmh,Crop_Type,Crop_Growth_Stage,Season,Irrigation_Type,Water_Source,Field_Area_hectare,Mulching_Used,Previous_Irrigation_mm,Region
id,,,,,,,,,,,,,,,,,,,
630000,Silt,6.36,26.19,0.59,2.81,17.83,30.24,1533.38,5.40,3.00,Maize,Sowing,Rabi,Canal,River,13.59,Yes,47.48,West
630001,Clay,5.87,9.88,1.18,3.26,21.18,78.07,576.05,7.22,15.88,Cotton,Sowing,Rabi,Drip,Reservoir,6.12,Yes,56.43,South
630002,Sandy,6.22,26.55,0.96,0.85,26.87,60.35,545.30,9.43,2.63,Wheat,Sowing,Kharif,Sprinkler,Reservoir,3.11,Yes,20.00,East
630003,Clay,7.68,53.58,0.83,0.55,41.74,36.05,1211.03,6.69,1.86,Maize,Harvest,Rabi,Canal,Groundwater,2.27,No,102.99,North
630004,Loamy,5.23,59.02,0.54,2.11,41.08,52.47,1321.91,4.11,5.71,Cotton,Sowing,Kharif,Canal,Groundwater,12.39,Yes,13.33,Central
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
899995,Sandy,5.63,51.90,0.68,2.58,33.27,72.09,2326.61,7.09,10.02,Potato,Vegetative,Rabi,Rainfed,River,2.93,Yes,43.49,East
899996,Loamy,7.84,45.16,0.85,1.04,27.55,45.16,2322.37,5.15,5.62,Wheat,Vegetative,Rabi,Canal,Groundwater,11.23,Yes,92.03,West
899997,Loamy,7.83,11.02,1.56,1.90,23.39,64.87,996.72,10.44,9.98,Maize,Vegetative,Zaid,Sprinkler,Groundwater,2.88,Yes,34.02,East
899998,Silt,7.12,10.18,1.32,2.65,41.09,58.04,1130.71,5.11,1.46,Rice,Harvest,Kharif,Rainfed,River,5.71,Yes,3.92,East
899999,Clay,6.61,24.96,1.41,3.41,35.15,61.30,1270.60,9.69,9.93,Maize,Sowing,Zaid,Drip,Reservoir,4.01,No,108.20,South

In [10]:
tst_ohe = transformer.transform(tst)

NotFittedError: This ColumnTransformer instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.

In [ ]:
tst_ss = ss.transform(tst_ohe)
tst_ss

In [ ]:
tst["Irrigation_Need"] = le.inverse_transform(bm.predict(tst_ss))
tst

In [ ]:
submit = pd.read_csv("sample_submission.csv")
submit

In [ ]:
submit["Irrigation_Need"] = le.inverse_transform(bm.predict(tst_ss))
submit

In [ ]:
submit.to_csv("KaggleSubmissionXGB.csv", index = False)