In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression, Lasso, Ridge, ElasticNet
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
import os
os.chdir('/home/pgcp-ai/MachineLearning/Datasets')

In [2]:
df = pd.read_csv('Concrete_Data.csv')
df

,Cement,Blast,Fly,Water,Superplasticizer,Coarse,Fine,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30
...,...,...,...,...,...,...,...,...,...
1025,276.4,116.0,90.3,179.6,8.9,870.1,768.3,28,44.28
1026,322.2,0.0,115.6,196.0,10.4,817.9,813.4,28,31.18
1027,148.5,139.4,108.6,192.7,6.1,892.4,780.0,28,23.70
1028,159.1,186.7,0.0,175.6,11.3,989.6,788.9,28,32.77
1029,260.9,100.5,78.3,200.6,8.6,864.5,761.5,28,32.40

In [3]:
X = df.drop('Strength', axis = 1)
y = df['Strength']

In [4]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=26)

In [5]:
lr = LinearRegression()
lr.fit(X_train, y_train)

LinearRegression()

In [6]:
y_pred = lr.predict(X_test)
r2_score(y_test, y_pred)

0.61814647284644

In [7]:
alpha_values = np.linspace(0.01, 10)
dict_alpha = dict()
for i in alpha_values:
    lasso = Lasso(alpha = i)
    lasso.fit(X_train, y_train)
    y_pred_lasso = lasso.predict(X_test)
    dict_alpha[i] = r2_score(y_test, y_pred_lasso)
    
lasso_df = pd.DataFrame(dict_alpha.items(), columns = ['Alpha', 'Score'])
lasso_df.sort_values('Score', ascending = False).iloc[0]

Alpha    2.456531
Score    0.619195
Name: 12, dtype: float64

In [8]:
alpha_values = np.linspace(0.01, 10)
dict_alpha = dict()
for i in alpha_values:
    ridge = Ridge(alpha = i)
    ridge.fit(X_train, y_train)
    y_pred_ridge = ridge.predict(X_test)
    dict_alpha[i] = r2_score(y_test, y_pred_ridge)
    
ridge_df = pd.DataFrame(dict_alpha.items(), columns = ['Alpha', 'Score'])
ridge_df.sort_values('Score', ascending = False).iloc[0]

Alpha    10.000000
Score     0.618152
Name: 49, dtype: float64

In [12]:
alpha_values = np.linspace(0.01, 10)
l1_ratios = np.linspace(0,1)
dict_alpha = dict()
scores = []
for i,j in zip(alpha_values,l1_ratios):
    el = ElasticNet(alpha = i,l1_ratio=j)
    el.fit(X_train, y_train)
    y_pred_ElasticNet = el.predict(X_test)
    dict_alpha[i] = r2_score(y_test, y_pred_ElasticNet)
    scores.append([i,j, r2_score(y_test, y_pred_ElasticNet)])
# ElasticNet_df = pd.DataFrame(dict_alpha.items(), columns = ['Alpha', 'Score'])
# ElasticNet_df.sort_values('Score', ascending = False)

df1 = pd.DataFrame(scores, columns = ['Alpha', 'L1 Ratio', 'Score'])
df1.sort_values('Score', ascending = False).iloc[0]

/home/pgcp-ai/.local/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.711e+04, tolerance: 1.899e+01 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(

Alpha       4.291429
L1 Ratio    0.428571
Score       0.619324
Name: 21, dtype: float64

In [11]:
tst = pd.read_csv("testConcrete.csv")
tst

    Cement  Blast  Fly  Water  Superplasticizer  Coarse  Fine  Age
0      495    120    0    155                 5     866   884   75
1      262    129    0    271                 2     808   787  174
2      201     48    1    215                 5     807   839  113
3      329    141    0    286                 1     881   823  229
4      354     14    0    129                 2     839   847  210
5      150     23   23    114                 4     883   638   36
6      480     64    0    292                 3     896   776  180
7      393     49   82    132                 1     887   830  271
8      284     63    1    138                 1     804   725   44
9      206     38    0    103                 2     818   719  191
10     247     64   26    175                 2     822   898  183
11     223    102    0    110                 2     808   854  270
12     457     89    0    289                 3     829   865  190
13     125     93    0    200                 5     893   671  113

In [13]:
el = ElasticNet(alpha = 5, l1_ratio=0.263158)
el.fit(X,y)

ElasticNet(alpha=5, l1_ratio=0.263158)

In [14]:
tst['predicted'] = el.predict(tst)
tst

    Cement  Blast  Fly  Water  Superplasticizer  Coarse  Fine  Age  predicted
0      495    120    0    155                 5     866   884   75  69.422232
1      262    129    0    271                 2     808   787  174  30.541413
2      201     48    1    215                 5     807   839  113  19.542512
3      329    141    0    286                 1     881   823  229  44.603082
4      354     14    0    129                 2     839   847  210  60.427137
5      150     23   23    114                 4     883   638   36  19.549537
6      480     64    0    292                 3     896   776  180  47.742368
7      393     49   82    132                 1     887   830  271  82.354604
8      284     63    1    138                 1     804   725   44  34.162597
9      206     38    0    103                 2     818   719  191  45.433335
10     247     64   26    175                 2     822   898  183  44.538800
11     223    102    0    110                 2     808   854  270  63.802756
12     457     89    0    289                 3     829   865  190  49.884783
13     125     93    0    200                 5     893   671  113  15.980987