In [ ]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression, Lasso
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import PolynomialFeatures
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
import os
os.chdir('/home/pgcp-ai/MachineLearning/Datasets')

In [ ]:
boston = pd.read_csv("Boston.csv")
X = boston.drop('medv', axis = 1)
y = boston['medv']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state=26)

In [ ]:
lasso = Lasso()

In [ ]:
alpha_values = np.linspace(0.01, 10)
dict_alpha = dict()
for i in alpha_values:
    lasso = Lasso(alpha = i)
    lasso.fit(X_train, y_train)
    y_pred_lasso = lasso.predict(X_test)
    dict_alpha[i] = r2_score(y_test, y_pred_lasso)

lasso_df = pd.DataFrame(dict_alpha.items(), columns = ['Alpha', 'Score'])
lasso_df.sort_values('Score', ascending = False)

        Alpha     Score
0    0.010000  0.747510
1    0.213878  0.744048
2    0.417755  0.743577
3    0.621633  0.737104
4    0.825510  0.724496
5    1.029388  0.705791
6    1.233265  0.680991
7    1.437143  0.664337
8    1.641020  0.652380
9    1.844898  0.638679
10   2.048776  0.628369
11   2.252653  0.620726
12   2.456531  0.612351
13   2.660408  0.603309
14   2.864286  0.593586
15   3.068163  0.583192
16   3.272041  0.574998
17   3.475918  0.567333
18   3.679796  0.565394
19   3.883673  0.564115
20   4.087551  0.562771
21   4.291429  0.561366
22   4.495306  0.559906
23   4.699184  0.558390
24   4.903061  0.556818
25   5.106939  0.555191
26   5.310816  0.553509
27   5.514694  0.551771
28   5.718571  0.549978
29   5.922449  0.548129
30   6.126327  0.546225
31   6.330204  0.544266
32   6.534082  0.542251
33   6.737959  0.540181
34   6.941837  0.538056
35   7.145714  0.535895
36   7.349592  0.533659
37   7.553469  0.531367
38   7.757347  0.529020
39   7.961224  0.526618
40   8.165102  0.525041
41   8.368980  0.524011
42   8.572857  0.522955
43   8.776735  0.521878
44   8.980612  0.520777
45   9.184490  0.519652
46   9.388367  0.518504
47   9.592245  0.517332
48   9.796122  0.516136
49  10.000000  0.514917

In [ ]:
concrete_df = pd.read_csv('/home/pgcp-ai/Datasets/Concrete_Data.csv')
concrete_df

,Cement,Blast,Fly,Water,Superplasticizer,Coarse,Fine,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30
...,...,...,...,...,...,...,...,...,...
1025,276.4,116.0,90.3,179.6,8.9,870.1,768.3,28,44.28
1026,322.2,0.0,115.6,196.0,10.4,817.9,813.4,28,31.18
1027,148.5,139.4,108.6,192.7,6.1,892.4,780.0,28,23.70
1028,159.1,186.7,0.0,175.6,11.3,989.6,788.9,28,32.77
1029,260.9,100.5,78.3,200.6,8.6,864.5,761.5,28,32.40

In [ ]:
X = concrete_df.drop('Strength', axis = 1)
y = concrete_df['Strength']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state=26)

In [ ]:
lasso = Lasso()

In [ ]:
alpha_values = np.linspace(0.01, 10)
dict_alpha = dict()
for i in alpha_values:
    lasso = Lasso(alpha = i)
    lasso.fit(X_train, y_train)
    y_pred_lasso = lasso.predict(X_test)
    dict_alpha[i] = r2_score(y_test, y_pred_lasso)

lasso_df = pd.DataFrame(dict_alpha.items(), columns = ['Alpha', 'Score'])
lasso_df.sort_values('Score', ascending = False)

        Alpha     Score
12   2.456531  0.619195
11   2.252653  0.619193
13   2.660408  0.619183
10   2.048776  0.619174
14   2.864286  0.619155
9    1.844898  0.619141
15   3.068163  0.619112
8    1.641020  0.619093
16   3.272041  0.619054
7    1.437143  0.619029
17   3.475918  0.618980
6    1.233265  0.618950
18   3.679796  0.618891
5    1.029388  0.618856
19   3.883673  0.618787
4    0.825510  0.618746
20   4.087551  0.618668
3    0.621633  0.618621
21   4.291429  0.618533
2    0.417755  0.618481
22   4.495306  0.618383
1    0.213878  0.618326
23   4.699184  0.618217
0    0.010000  0.618155
24   4.903061  0.618037
25   5.106939  0.617841
26   5.310816  0.617649
27   5.514694  0.617598
28   5.718571  0.617545
29   5.922449  0.617491
30   6.126327  0.617433
31   6.330204  0.617377
32   6.534082  0.617319
33   6.737959  0.617260
34   6.941837  0.617200
35   7.145714  0.617139
36   7.349592  0.617077
37   7.553469  0.617011
38   7.757347  0.616947
39   7.961224  0.616881
40   8.165102  0.616814
41   8.368980  0.616746
42   8.572857  0.616677
43   8.776735  0.616607
44   8.980612  0.616532
45   9.184490  0.616460
46   9.388367  0.616386
47   9.592245  0.616311
48   9.796122  0.616235
49  10.000000  0.616158